Repository netlify/build, pull requests merged in 2020-06, with the labels that each got.

#1395 Fix errors with a `type` property
  packages/build/src/error/build.js
  packages/build/src/plugins/ipc.js
  packages/build/tests/error/build/fixtures/exception_props/plugin.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
Labels: type: bug

#1389 Fix `package` starting with `/`
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/load/fixtures/local_absolute/manifest.yml
  packages/build/tests/plugins/load/fixtures/local_absolute/netlify.toml
  packages/build/tests/plugins/load/fixtures/local_absolute/plugin.js
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/load/tests.js
Labels: type: bug

#1386 Send build logs URL for debugging
  packages/build/src/error/monitor/location.js
  packages/build/src/error/monitor/report.js
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/error/monitor/tests.js
Labels: type: chore

#1400 Fix `spawn node ENOENT`
  packages/build/src/telemetry/track.js
Labels: type: bug

#1388 Improve the error message for missing dependencies in Netlify Functions
  packages/build/src/plugins_core/functions/error.js
  packages/build/src/plugins_core/functions/plugin.js
  packages/build/tests/install/functions/fixtures/mispelled_dep/functions/test.js
  packages/build/tests/install/functions/fixtures/mispelled_dep/netlify.toml
  packages/build/tests/install/functions/snapshots/tests.js.md
  packages/build/tests/install/functions/snapshots/tests.js.snap
  packages/build/tests/install/functions/tests.js
Labels: type: feature

#1387 Improve debugging error message normalization
  packages/build/src/error/monitor/normalize.js
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
Labels: type: chore

#1399 Simplify code related to npm install
  packages/build/src/install/main.js
Labels: type: chore

#1398 Simplify code related to automatic installs
  packages/build/src/install/main.js
  packages/build/src/install/missing.js
Labels: type: chore

#1397 Improve plugin automatic installation
  .gitignore
  packages/build/src/install/main.js
  packages/build/src/install/missing.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/install/missing/fixtures/already_installed/.netlify/plugins/node_modules/netlify-plugin-test/index.js
  packages/build/tests/install/missing/fixtures/already_installed/.netlify/plugins/node_modules/netlify-plugin-test/manifest.yml
  packages/build/tests/install/missing/fixtures/already_installed/.netlify/plugins/package.json
  packages/build/tests/install/missing/fixtures/already_installed/netlify.toml
  packages/build/tests/install/missing/snapshots/tests.js.md
  packages/build/tests/install/missing/snapshots/tests.js.snap
  packages/build/tests/install/missing/tests.js
Labels: type: bug

#1403 Fix performance issue
  packages/build/src/telemetry/track.js
Labels: type: bug

#1405 Fix Bugsnag grouping
  packages/build/src/error/monitor/normalize.js
Labels: type: chore

#1410 Remove some dead code
  packages/build/src/plugins/child/utils.js
  packages/build/tests/error/build/fixtures/cancel_compat/manifest.yml
  packages/build/tests/error/build/fixtures/cancel_compat/netlify.toml
  packages/build/tests/error/build/fixtures/cancel_compat/plugin.js
  packages/build/tests/error/build/fixtures/fail_build_compat/manifest.yml
  packages/build/tests/error/build/fixtures/fail_build_compat/netlify.toml
  packages/build/tests/error/build/fixtures/fail_build_compat/plugin.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/build/tests.js
  packages/config/src/path.js
  packages/config/src/validate/helpers.js
  packages/config/src/validate/validations.js
  packages/config/tests/parse/fixtures/yml/netlify.yml
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/parse/tests.js
  packages/config/tests/validate/fixtures/build_lifecycle/netlify.toml
  packages/config/tests/validate/fixtures/plugins_config_renamed/netlify.toml
  packages/config/tests/validate/fixtures/plugins_type_renamed/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: chore

#1409 Handle circular references in errors
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/plugins/child/error.js
  packages/build/tests/error/build/fixtures/exception_circular/manifest.yml
  packages/build/tests/error/build/fixtures/exception_circular/netlify.toml
  packages/build/tests/error/build/fixtures/exception_circular/plugin.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/build/tests.js
Labels: type: bug

#1408 Improve validation of `plugins[*].package`
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/validate/validations.js
  packages/config/tests/validate/fixtures/plugins_package_scheme/netlify.toml
  packages/config/tests/validate/fixtures/plugins_package_version/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: bug

#1412 Improve error handling of invalid local plugin paths
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/load/fixtures/local_invalid/netlify.toml
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/load/tests.js
Labels: type: bug

#1413 Improve normalization of Bugsnag errors
  packages/build/src/error/monitor/normalize.js
Labels: type: chore

#1415 Remove some unused tests related to installations
  packages/build/tests/install/functions/fixtures/npm/functions/package-lock.json
  packages/build/tests/install/functions/fixtures/npm/functions/package.json
  packages/build/tests/install/functions/fixtures/npm/functions/test.js
  packages/build/tests/install/functions/fixtures/npm/netlify.toml
  packages/build/tests/install/functions/fixtures/npm_ci_no_lock/functions/package.json
  packages/build/tests/install/functions/fixtures/npm_ci_no_lock/functions/test.js
  packages/build/tests/install/functions/fixtures/npm_ci_no_lock/netlify.toml
  packages/build/tests/install/functions/fixtures/npm_lock/functions/package-lock.json
  packages/build/tests/install/functions/fixtures/npm_lock/functions/package.json
  packages/build/tests/install/functions/fixtures/npm_lock/functions/test.js
  packages/build/tests/install/functions/fixtures/npm_lock/netlify.toml
  packages/build/tests/install/functions/fixtures/yarn/functions/package.json
  packages/build/tests/install/functions/fixtures/yarn/functions/test.js
  packages/build/tests/install/functions/fixtures/yarn/functions/yarn.lock
  packages/build/tests/install/functions/fixtures/yarn/netlify.toml
  packages/build/tests/install/functions/fixtures/yarn_ci/functions/package.json
  packages/build/tests/install/functions/fixtures/yarn_ci/functions/test.js
  packages/build/tests/install/functions/fixtures/yarn_ci/functions/yarn.lock
  packages/build/tests/install/functions/fixtures/yarn_ci/netlify.toml
  packages/build/tests/install/functions/snapshots/tests.js.md
  packages/build/tests/install/functions/snapshots/tests.js.snap
  packages/build/tests/install/functions/tests.js
  packages/build/tests/install/local/fixtures/npm/netlify.toml
  packages/build/tests/install/local/fixtures/npm/plugin/main.js
  packages/build/tests/install/local/fixtures/npm/plugin/manifest.yml
  packages/build/tests/install/local/fixtures/npm/plugin/package-lock.json
  packages/build/tests/install/local/fixtures/npm/plugin/package.json
  packages/build/tests/install/local/fixtures/npm_ci_no_lock/netlify.toml
  packages/build/tests/install/local/fixtures/npm_ci_no_lock/plugin/main.js
  packages/build/tests/install/local/fixtures/npm_ci_no_lock/plugin/manifest.yml
  packages/build/tests/install/local/fixtures/npm_ci_no_lock/plugin/package.json
  packages/build/tests/install/local/fixtures/npm_lock/netlify.toml
  packages/build/tests/install/local/fixtures/npm_lock/plugin/main.js
  packages/build/tests/install/local/fixtures/npm_lock/plugin/manifest.yml
  packages/build/tests/install/local/fixtures/npm_lock/plugin/package-lock.json
  packages/build/tests/install/local/fixtures/npm_lock/plugin/package.json
  packages/build/tests/install/local/fixtures/yarn/netlify.toml
  packages/build/tests/install/local/fixtures/yarn/plugin/main.js
  packages/build/tests/install/local/fixtures/yarn/plugin/manifest.yml
  packages/build/tests/install/local/fixtures/yarn/plugin/package.json
  packages/build/tests/install/local/fixtures/yarn/plugin/yarn.lock
  packages/build/tests/install/local/fixtures/yarn_ci/netlify.toml
  packages/build/tests/install/local/fixtures/yarn_ci/plugin/main.js
  packages/build/tests/install/local/fixtures/yarn_ci/plugin/manifest.yml
  packages/build/tests/install/local/fixtures/yarn_ci/plugin/package.json
  packages/build/tests/install/local/fixtures/yarn_ci/plugin/yarn.lock
  packages/build/tests/install/local/snapshots/tests.js.md
  packages/build/tests/install/local/snapshots/tests.js.snap
  packages/build/tests/install/local/tests.js
Labels: type: chore

#1414 Remove process warnings debugging
  packages/build/src/core/main.js
  packages/build/src/error/process.js
  packages/build/tests/error/process/fixtures/process/netlify.toml
  packages/build/tests/error/process/snapshots/tests.js.md
  packages/build/tests/error/process/snapshots/tests.js.snap
  packages/build/tests/error/process/tests.js
Labels: type: chore

#1417 Remove dead code
  packages/build/tests/plugins/normalize/fixtures/lifecycle_name/netlify.toml
Labels: test, type: chore

#1416 Improve speed of installation-related tests
  packages/build/tests/install/functions/tests.js
  packages/build/tests/install/local/tests.js
  packages/build/tests/install/missing/tests.js
Labels: test, type: chore

#1418 Improve Bugsnag start logic
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/error/monitor/start.js
Labels: type: bug

#1419 Improve `@netlify/build` return value
  packages/build/src/core/bin.js
  packages/build/src/core/main.js
Labels: type: chore

#1420 Make `flags` object optional
  packages/build/src/core/main.js
Labels: type: chore

#1421 Refactor how CLI flags are passed in tests
  packages/build/tests/helpers/common.js
Labels: test, type: chore

#1422 Add `deployId` flag
  packages/build/src/core/bin.js
  packages/build/src/core/config.js
  packages/build/src/core/constants.js
  packages/build/src/core/main.js
  packages/build/src/env/main.js
  packages/build/src/error/cancel.js
  packages/build/src/log/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/options.js
  packages/build/src/status/report.js
  packages/build/tests/core/cli/snapshots/tests.js.md
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/error/build/tests.js
  packages/build/tests/error/monitor/tests.js
  packages/build/tests/status/helpers/run.js
  packages/build/tests/status/report/tests.js
Labels: test, type: chore

#1423 Add `debug` flag
  packages/build/src/core/bin.js
  packages/build/src/core/config.js
  packages/build/src/log/main.js
  packages/build/tests/helpers/common.js
  packages/build/tests/helpers/main.js
Labels: type: chore

#1424 Add `--bugsnag-key` CLI flag
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/error/monitor/start.js
  packages/build/src/log/main.js
  packages/build/tests/error/monitor/tests.js
Labels: type: chore

#1426 Add `testOpts.errorMonitor` flag
  packages/build/src/core/bin.js
  packages/build/src/core/commands.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/error/monitor/report.js
  packages/build/src/log/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/options.js
  packages/build/src/status/report.js
  packages/build/tests/error/monitor/tests.js
Labels: test, type: chore

#1427 Add `testOpts.oldCliLogs` flag
  packages/build/src/core/main.js
  packages/build/src/log/old_version.js
  packages/build/tests/log/old_version/tests.js
Labels: type: chore

#1428 Add `testOpts.apiClient` flag
  packages/build/src/plugins/child/api.js
  packages/build/src/plugins/child/load.js
  packages/build/tests/plugins/api/tests.js
Labels: test, type: chore

#1429 Add `testOpts.buildImagePluginsDir` flag
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/core/flags/tests.js
  packages/build/tests/plugins/load/tests.js
Labels: test, type: chore

#1430 Add `testOpts.cachePath` flag
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/cache/plugin.js
  packages/build/src/plugins_core/main.js
  packages/build/tests/cache/main/tests.js
  packages/build/tests/helpers/main.js
Labels: test, type: chore

#1431 Add `testOpts.sendStatus` flag
  packages/build/src/status/report.js
  packages/build/tests/status/helpers/run.js
Labels: test, type: chore

#1432 Add `telemetry` flag
  ava.config.js
  packages/build/src/core/bin.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/log/main.js
  packages/build/src/telemetry/complete.js
  packages/build/src/telemetry/track.js
  packages/build/tests/core/cli/snapshots/tests.js.md
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/core/telemetry/tests.js
  packages/build/tests/helpers/main.js
Labels: test, type: chore

#1433 Add `testOpts.telemetryOrigin` flag
  packages/build/src/core/main.js
  packages/build/src/telemetry/complete.js
  packages/build/src/telemetry/request.js
  packages/build/src/telemetry/track.js
  packages/build/tests/core/telemetry/tests.js
Labels: test, type: chore

#1434 Improve error handling of `@netlify/config`
  packages/config/src/bin/main.js
Labels: type: bug

#1435 Use `path-type` dependency in `@netlify/config`
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/files.js
  packages/config/src/options/main.js
  packages/config/src/utils/dir-exists.js
Labels: type: chore

#1436 Remove code related to validation warnings in `@netlify/config`
  packages/config/src/validate/main.js
  packages/config/src/validate/validations.js
Labels: type: chore

#1437 Improve environment variables usage in `@netlify/config`
  packages/config/src/main.js
  packages/config/src/options/branch.js
  packages/config/src/options/main.js
Labels: test, type: chore

#1438 Improve retrieval of the current directory in the `cache` utility
  packages/cache-utils/src/list.js
  packages/cache-utils/src/path.js
Labels: type: bug

#1441 Remove unused `api` client
  packages/build/package.json
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/plugins/child/api.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/validate.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/manifest/validate.js
  packages/build/src/plugins/options.js
  packages/build/tests/manifest/validate/fixtures/scopes_array/manifest.yml
  packages/build/tests/manifest/validate/fixtures/scopes_array/netlify.toml
  packages/build/tests/manifest/validate/fixtures/scopes_array/plugin.js
  packages/build/tests/manifest/validate/fixtures/scopes_invalid/manifest.yml
  packages/build/tests/manifest/validate/fixtures/scopes_invalid/netlify.toml
  packages/build/tests/manifest/validate/fixtures/scopes_invalid/plugin.js
  packages/build/tests/manifest/validate/snapshots/tests.js.md
  packages/build/tests/manifest/validate/snapshots/tests.js.snap
  packages/build/tests/manifest/validate/tests.js
  packages/build/tests/plugins/api/fixtures/api_call/manifest.yml
  packages/build/tests/plugins/api/fixtures/api_call/netlify.toml
  packages/build/tests/plugins/api/fixtures/api_call/plugin.js
  packages/build/tests/plugins/api/fixtures/default_scopes/manifest.yml
  packages/build/tests/plugins/api/fixtures/default_scopes/netlify.toml
  packages/build/tests/plugins/api/fixtures/default_scopes/plugin.js
  packages/build/tests/plugins/api/fixtures/feature_flag/manifest.yml
  packages/build/tests/plugins/api/fixtures/feature_flag/netlify.toml
  packages/build/tests/plugins/api/fixtures/feature_flag/plugin.js
  packages/build/tests/plugins/api/fixtures/no_token/manifest.yml
  packages/build/tests/plugins/api/fixtures/no_token/netlify.toml
  packages/build/tests/plugins/api/fixtures/no_token/plugin.js
  packages/build/tests/plugins/api/fixtures/site_id/netlify.toml
  packages/build/tests/plugins/api/fixtures/star_scopes/manifest.yml
  packages/build/tests/plugins/api/fixtures/star_scopes/netlify.toml
  packages/build/tests/plugins/api/fixtures/star_scopes/plugin.js
  packages/build/tests/plugins/api/fixtures/token/netlify.toml
  packages/build/tests/plugins/api/fixtures/wrong_scopes/manifest.yml
  packages/build/tests/plugins/api/fixtures/wrong_scopes/netlify.toml
  packages/build/tests/plugins/api/fixtures/wrong_scopes/plugin.js
  packages/build/tests/plugins/api/snapshots/tests.js.md
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/api/tests.js
Labels: type: chore

#1442 Fix codecov script
  scripts/coverage.sh
Labels: type: chore

#1443 Simplify `git` utils
  packages/build/src/core/main.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/child/utils.js
  packages/build/src/plugins/load.js
  packages/build/tests/plugins/utils/fixtures/git_no_root_delayed/manifest.yml
  packages/build/tests/plugins/utils/fixtures/git_no_root_delayed/netlify.toml
  packages/build/tests/plugins/utils/fixtures/git_no_root_delayed/plugin.js
  packages/build/tests/plugins/utils/snapshots/tests.js.md
  packages/build/tests/plugins/utils/snapshots/tests.js.snap
  packages/build/tests/plugins/utils/tests.js
  packages/git-utils/src/commits.js
  packages/git-utils/src/diff.js
  packages/git-utils/src/exec.js
  packages/git-utils/src/main.js
  packages/git-utils/src/refs.js
  packages/git-utils/src/stats.js
  packages/git-utils/tests/main.js
Labels: type: chore

#1444 Lazy load `utils`
  packages/build/src/plugins/child/lazy.js
  packages/build/src/plugins/child/status.js
  packages/build/src/plugins/child/utils.js
  packages/build/tests/plugins/utils/fixtures/defined/manifest.yml
  packages/build/tests/plugins/utils/fixtures/defined/netlify.toml
  packages/build/tests/plugins/utils/fixtures/defined/node_modules/@netlify/git-utils/index.js
  packages/build/tests/plugins/utils/fixtures/defined/package.json
  packages/build/tests/plugins/utils/fixtures/defined/plugin.js
  packages/build/tests/plugins/utils/fixtures/error/manifest.yml
  packages/build/tests/plugins/utils/fixtures/error/netlify.toml
  packages/build/tests/plugins/utils/fixtures/error/node_modules/@netlify/git-utils/index.js
  packages/build/tests/plugins/utils/fixtures/error/package.json
  packages/build/tests/plugins/utils/fixtures/error/plugin.js
  packages/build/tests/plugins/utils/fixtures/function_async/manifest.yml
  packages/build/tests/plugins/utils/fixtures/function_async/netlify.toml
  packages/build/tests/plugins/utils/fixtures/function_async/node_modules/@netlify/git-utils/index.js
  packages/build/tests/plugins/utils/fixtures/function_async/package.json
  packages/build/tests/plugins/utils/fixtures/function_async/plugin.js
  packages/build/tests/plugins/utils/fixtures/keys/manifest.yml
  packages/build/tests/plugins/utils/fixtures/keys/netlify.toml
  packages/build/tests/plugins/utils/fixtures/keys/plugin.js
  packages/build/tests/plugins/utils/snapshots/tests.js.md
  packages/build/tests/plugins/utils/snapshots/tests.js.snap
  packages/build/tests/plugins/utils/tests.js
Labels: test, type: chore

#1445 Remove dead code `--features`
  packages/build/src/core/bin.js
  packages/build/tests/core/cli/snapshots/tests.js.md
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/core/cli/tests.js
Labels: type: chore

#1446 Improve colors support
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/core/bin.js
  packages/build/src/core/main.js
  packages/build/src/env/main.js
  packages/build/src/log/colors.js
  packages/build/src/plugins/child/error.js
  packages/build/tests/helpers/common.js
Labels: type: chore

#1447 Simplify some code
  packages/build/src/env/changes.js
Labels: type: chore

#1448 Improve stack trace cleanup
  packages/build/src/error/parse/clean_stack.js
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.snap
  packages/build/tests/manifest/validate/snapshots/tests.js.md
  packages/build/tests/manifest/validate/snapshots/tests.js.snap
Labels: type: feature

#1449 Fix tests randomly failing
  packages/build/src/core/commands.js
  packages/build/src/log/stream.js
Labels: type: bug

#1450 Fix error message with Node 8
  packages/build/src/plugins/manifest/load.js
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.snap
Labels: type: bug

#1451 Fix tests in Node 8
  packages/build/src/plugins_core/functions/error.js
  packages/build/tests/helpers/normalize.js
  packages/build/tests/install/functions/snapshots/tests.js.md
  packages/build/tests/install/functions/snapshots/tests.js.snap
  packages/build/tests/install/local/snapshots/tests.js.md
  packages/build/tests/install/local/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
Labels: type: bug

#1452 Refactor some code related to the `PRINT` environment variable
  packages/build/tests/helpers/common.js
Labels: type: chore

#1453 Remove test timeout
  packages/build/tests/helpers/common.js
Labels: type: chore

#1454 Use `failed` instead of `exitCode`
  packages/build/tests/core/cli/tests.js
  packages/build/tests/helpers/common.js
Labels: type: chore

#1455 Combine stdout and stderr in tests
  packages/build/tests/core/cli/tests.js
  packages/build/tests/core/config/tests.js
  packages/build/tests/error/clean_stack/tests.js
  packages/build/tests/error/log/snapshots/tests.js.md
  packages/build/tests/error/log/snapshots/tests.js.snap
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/error/monitor/tests.js
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/helpers/common.js
  packages/build/tests/log/colors/tests.js
  packages/build/tests/log/old_version/snapshots/tests.js.md
  packages/build/tests/log/old_version/snapshots/tests.js.snap
  packages/build/tests/plugins/run/snapshots/tests.js.md
  packages/build/tests/plugins/run/snapshots/tests.js.snap
  packages/build/tests/status/report/snapshots/tests.js.md
  packages/build/tests/status/report/snapshots/tests.js.snap
  packages/config/tests/base/tests.js
  packages/config/tests/cli/tests.js
  packages/config/tests/load/tests.js
Labels: test, type: chore

#1456 Refactor `--node-path` tests
  packages/build/tests/plugins/node_version/tests.js
Labels: type: chore

#1457 Refactor how `utils.cache` is tested
  packages/build/src/core/config.js
  packages/build/src/core/constants.js
  packages/cache-utils/src/dir.js
  packages/cache-utils/tests/dir.js
Labels: type: chore

#1458 Refactor some code in `@netlify/config`
  packages/config/src/api/client.js
  packages/config/src/main.js
Labels: type: chore

#1459 Refactor `siteId` in `@netlify/config`
  packages/config/src/main.js
Labels: type: chore

#1460 Refactor default values of `@netlify/config`
  packages/config/src/main.js
  packages/config/src/options/main.js
Labels: type: chore

#1461 Fix failing test in Node 8
  packages/build/tests/error/build/fixtures/exception_circular/plugin.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
Labels: type: bug

#1462 Refactor how default flags are assigned
  packages/build/src/core/config.js
Labels: type: chore

#1463 Remove `getJsonOpt()` test helper
  packages/build/tests/core/build_command/tests.js
  packages/build/tests/core/config/tests.js
  packages/build/tests/error/monitor/tests.js
  packages/build/tests/error/stack/tests.js
  packages/build/tests/helpers/common.js
  packages/build/tests/plugins/load/tests.js
  packages/config/tests/base/tests.js
  packages/config/tests/helpers/main.js
  packages/config/tests/load/tests.js
Labels: type: chore

#1465 Add `opts.env` to `@netlify/config`
  packages/config/src/api/client.js
  packages/config/src/options/branch.js
  packages/config/src/options/main.js
  packages/config/tests/context/tests.js
  packages/config/tests/helpers/main.js
Labels: type: chore

#1466 Add `env` option to `@netlify/build`
  packages/build/src/core/config.js
Labels: type: chore

#1467 Add `buffer` option
  packages/build/src/core/bin.js
  packages/build/src/core/commands.js
  packages/build/src/core/config.js
  packages/build/src/core/dry.js
  packages/build/src/core/main.js
  packages/build/src/error/monitor/print.js
  packages/build/src/error/monitor/report.js
  packages/build/src/error/monitor/start.js
  packages/build/src/install/local.js
  packages/build/src/install/missing.js
  packages/build/src/log/logger.js
  packages/build/src/log/main.js
  packages/build/src/log/stream.js
  packages/build/src/log/timer.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/src/plugins/spawn.js
  packages/build/src/status/report.js
  packages/build/tests/error/log/snapshots/tests.js.md
  packages/build/tests/error/log/snapshots/tests.js.snap
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/helpers/main.js
  packages/build/tests/log/old_version/snapshots/tests.js.md
  packages/build/tests/log/old_version/snapshots/tests.js.snap
  packages/build/tests/plugins/run/snapshots/tests.js.md
  packages/build/tests/plugins/run/snapshots/tests.js.snap
  packages/build/tests/status/report/snapshots/tests.js.md
  packages/build/tests/status/report/snapshots/tests.js.snap
Labels: type: chore

#1469 Remove `path-key`
  packages/build/package.json
  packages/build/tests/helpers/main.js
Labels: type: chore

#1470 Add some comments
  packages/build/tests/helpers/main.js
  packages/config/tests/helpers/main.js
Labels: type: chore

#1468 Use objects when passing flags in tests
  packages/build/tests/cache/main/tests.js
  packages/build/tests/core/build_command/tests.js
  packages/build/tests/core/cli/tests.js
  packages/build/tests/core/config/tests.js
  packages/build/tests/core/dry/tests.js
  packages/build/tests/core/flags/tests.js
  packages/build/tests/core/telemetry/tests.js
  packages/build/tests/env/git/tests.js
  packages/build/tests/env/main/tests.js
  packages/build/tests/error/build/tests.js
  packages/build/tests/error/monitor/tests.js
  packages/build/tests/error/stack/tests.js
  packages/build/tests/helpers/common.js
  packages/build/tests/helpers/main.js
  packages/build/tests/install/functions/tests.js
  packages/build/tests/install/local/tests.js
  packages/build/tests/install/missing/tests.js
  packages/build/tests/log/colors/tests.js
  packages/build/tests/log/old_version/tests.js
  packages/build/tests/plugins/constants/tests.js
  packages/build/tests/plugins/load/tests.js
  packages/build/tests/plugins/node_version/tests.js
  packages/build/tests/status/helpers/run.js
  packages/build/tests/status/report/tests.js
  packages/config/tests/api/tests.js
  packages/config/tests/base/tests.js
  packages/config/tests/cli/tests.js
  packages/config/tests/context/tests.js
  packages/config/tests/cwd/tests.js
  packages/config/tests/helpers/main.js
  packages/config/tests/load/tests.js
  packages/config/tests/parse/tests.js
  packages/config/tests/validate/tests.js
Labels: test, type: chore

#1471 Refactor test helpers
  packages/build/tests/helpers/main.js
  packages/config/tests/helpers/main.js
Labels: test, type: chore

#1472 Run tests using the programmatic main functions
  packages/build/tests/core/build_command/tests.js
  packages/build/tests/core/cli/tests.js
  packages/build/tests/core/config/tests.js
  packages/build/tests/core/dry/tests.js
  packages/build/tests/error/monitor/tests.js
  packages/build/tests/error/stack/tests.js
  packages/build/tests/helpers/common.js
  packages/build/tests/helpers/main.js
  packages/build/tests/log/colors/tests.js
  packages/build/tests/log/old_version/tests.js
  packages/build/tests/plugins/load/tests.js
  packages/build/tests/status/helpers/run.js
  packages/config/src/bin/main.js
  packages/config/tests/base/tests.js
  packages/config/tests/cli/tests.js
  packages/config/tests/helpers/main.js
  packages/config/tests/load/tests.js
Labels: type: chore

#1473 Fix colors in tests
  packages/build/tests/helpers/common.js
Labels: type: chore

#1475 Re-enable some tests
  packages/build/tests/core/tests.js
  packages/build/tests/env/tests.js
  packages/build/tests/error/tests.js
  packages/build/tests/plugins/tests.js
  packages/config/tests/parse/tests.js
  packages/git-utils/tests/main.js
Labels: type: chore

#1476 Print `testOpts` in logs
  packages/build/src/log/main.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/helpers/normalize.js
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: type: chore

#1477 Print `deployId` in logs
  packages/build/src/log/main.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: type: chore

#1479 Fix failing test
  packages/build/tests/error/fixtures/early_exit/plugin.js
  packages/build/tests/error/fixtures/early_exit/plugin_slow.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
Labels: type: chore

#1480 Refactor IPC logic
  packages/build/src/plugins/ipc.js
Labels: type: chore

#1481 Fix test randomly failing
  packages/build/src/plugins/ipc.js
Labels: type: bug

#1482 Test in Node 14 instead of Node 13
  .github/workflows/workflow.yml
Labels: test, type: chore

#1483 Re-add `path-key`
  packages/build/package.json
  packages/build/tests/helpers/main.js
Labels: type: chore

#1484 Fix randomly failing test
  packages/build/tests/error/tests.js
Labels: type: chore

#1486 Fix test failing on Node 8
  packages/build/tests/error/fixtures/early_exit/plugin_slow.js
Labels: type: chore

#1485 Improve test performance
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/tests/core/tests.js
Labels: type: chore

#1488 Fix some tests failing on Windows
  packages/build/tests/helpers/main.js
Labels: test, type: chore

#1487 Fix some tests on Windows
  packages/run-utils/tests/main.js
Labels: test, type: chore

#1489 Fix tests using Yarn
  packages/build/tests/install/tests.js
Labels: test, type: chore

#1491 Remove dead code (core cache plugin)
  packages/build/src/core/config.js
  packages/build/src/core/constants.js
  packages/build/src/log/main.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/cache/manifest.yml
  packages/build/src/plugins_core/cache/plugin.js
  packages/build/src/plugins_core/main.js
  packages/build/tests/core/fixtures/cache_plugin/index.js
  packages/build/tests/core/fixtures/cache_plugin/manifest.yml
  packages/build/tests/core/fixtures/ci/netlify.toml
  packages/build/tests/core/fixtures/local/netlify.toml
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: type: chore

#1490 Fix randomly failing test
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/tests/error/fixtures/early_exit/plugin_slow.js
  packages/build/tests/error/tests.js
Labels: test, type: chore

#1492 Simplify some tests
  packages/build/tests/install/tests.js
Labels: test, type: chore

#1493 Simplify some test
  packages/build/tests/log/tests.js
Labels: test, type: chore

#1494 Small refactor of test helper
  packages/build/tests/helpers/common.js
  packages/build/tests/helpers/main.js
Labels: type: chore

#1497 Fix error monitoring tests
  packages/build/src/error/monitor/print.js
  packages/build/src/error/monitor/report.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
Labels: test, type: chore

#1496 Update documentation of the test helpers
  packages/build/tests/README.md
  packages/build/tests/helpers/common.js
Labels: test, type: chore

#1504 Remove dead code
  packages/build/src/plugins/child/run.js
Labels: type: chore

#1501 Add `utils.functions.list()`
  packages/build/src/plugins/child/utils.js
  packages/functions-utils/README.md
  packages/functions-utils/package-lock.json
  packages/functions-utils/package.json
  packages/functions-utils/src/main.js
  packages/functions-utils/tests/fixtures/list/empty/.gitkeep
  packages/functions-utils/tests/fixtures/list/one/index.js
  packages/functions-utils/tests/fixtures/list/test
  packages/functions-utils/tests/fixtures/list/test.go
  packages/functions-utils/tests/fixtures/list/test.js
  packages/functions-utils/tests/fixtures/list/test.zip
  packages/functions-utils/tests/fixtures/list/two/two.js
  packages/functions-utils/tests/main.js
Labels: type: feature

#1502 Fix functions directory validation
  packages/build/src/plugins_core/functions/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: bug

#1503 Improve build logs of Functions bundling
  packages/build/src/log/logger.js
  packages/build/src/log/main.js
  packages/build/src/plugins_core/functions/plugin.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: feat/build-plugins, feat/builds, type: feature

#1507 Allow `text` and `title` to be empty strings in `utils.status.show()`
  packages/build/src/plugins/child/status.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/status/tests.js
Labels: type: bug

#1506 Add --functionsDistDir flag
  packages/build/src/core/bin.js
  packages/build/src/core/config.js
  packages/build/src/core/constants.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/config/tests/cli/snapshots/tests.js.snap
Labels: type: feature

#1519 Add support for `SITE_NAME`
  packages/build/src/env/metadata.js
  packages/build/src/error/monitor/location.js
  packages/build/tests/error/tests.js
Labels: type: chore

#1516 Simplify colors logic
  packages/build/src/core/bin.js
  packages/build/src/log/colors.js
  packages/build/src/plugins/child/main.js
  packages/build/tests/log/tests.js
Labels: type: chore

#1517 Refactor how flags are hidden
  packages/build/src/log/main.js
Labels: type: chore

#1515 Do not print warnings when automatically installing plugins choosen f…
  packages/build/src/install/missing.js
  packages/build/tests/install/fixtures/empty/.gitkeep
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/install/tests.js
Labels: type: bug

#1518 Add `--build-image-plugins-dir` CLI flag
  packages/build/src/core/bin.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/install/missing.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/install/tests.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: chore

#1520 Do not print `--buildImagePluginsDir` CLI flag in production
  packages/build/src/log/main.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
Labels: type: chore

#1521 Fix executing local binaries
  packages/build/src/plugins/options.js
  packages/build/src/plugins/spawn.js
  packages/build/tests/plugins/fixtures/build_image_bin/netlify.toml
  packages/build/tests/plugins/fixtures/build_image_cache_bin/node_modules/.bin/testbin
  packages/build/tests/plugins/fixtures/build_image_cache_bin/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/fixtures/build_image_cache_bin/node_modules/netlify-plugin-test/manifest.yml
  packages/build/tests/plugins/fixtures/build_image_cache_bin/node_modules/netlify-plugin-test/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: bug

#1523 Redact API token in build error logs
  packages/build/src/error/api.js
  packages/build/tests/error/fixtures/api_token_redact/manifest.yml
  packages/build/tests/error/fixtures/api_token_redact/netlify.toml
  packages/build/tests/error/fixtures/api_token_redact/plugin.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/error/tests.js
Labels: type: security

#1525 Fix test that randomly fails
  packages/build/tests/core/tests.js
Labels: type: bug

#1528 Add a newline in an error message
  packages/build/src/plugins_core/functions/error.js
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
Labels: type: chore

#1527 Improve Bugsnag error grouping
  packages/build/src/error/monitor/normalize.js
Labels: type: chore

#1524 Do not log that core plugins are loading
  packages/build/src/log/main.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.snap
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: feat/build-plugins, feat/builds, type: feature

#1526 Improve error message when inputs are invalid
  packages/build/src/error/monitor/normalize.js
  packages/build/src/plugins/manifest/check.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/manifest/fixtures/unknown_none/manifest.yml
  packages/build/tests/manifest/fixtures/unknown_none/netlify.toml
  packages/build/tests/manifest/fixtures/unknown_none/plugin.js
  packages/build/tests/manifest/fixtures/unknown_some/manifest.yml
  packages/build/tests/manifest/fixtures/unknown_some/netlify.toml
  packages/build/tests/manifest/fixtures/unknown_some/plugin.js
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/manifest/tests.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: feat/build-plugins, feat/builds, type: feature

#1533 Do not pass Bugnag key to build commands and plugins
  packages/build/src/env/main.js
  packages/build/tests/env/fixtures/bugsnag_key/index.js
  packages/build/tests/env/fixtures/bugsnag_key/netlify.toml
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/env/tests.js
Labels: type: bug

#1552 Fix error message when Netlify Function is missing a local file
  packages/build/src/plugins_core/functions/error.js
  packages/build/tests/install/fixtures/local_dep/functions/index.js
  packages/build/tests/install/fixtures/local_dep/functions/package.json
  packages/build/tests/install/fixtures/local_dep/netlify.toml
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/install/tests.js
Labels: type: bug

#1550 Fix config case normalization
  packages/config/src/case.js
  packages/config/src/context.js
  packages/config/src/main.js
  packages/config/src/normalize.js
  packages/config/src/validate/main.js
  packages/config/src/validate/validations.js
  packages/config/tests/normalize/fixtures/props_case_context/base_test_branch/.gitkeep
  packages/config/tests/normalize/fixtures/props_case_context/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
Labels: type: bug

#1549 Refactor variable names of `packageJson`
  packages/build/src/core/commands.js
  packages/build/src/core/main.js
  packages/build/src/error/monitor/print.js
  packages/build/src/error/monitor/report.js
  packages/build/src/error/parse/plugin.js
  packages/build/src/log/main.js
  packages/build/src/log/old_version.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/check.js
  packages/build/src/plugins/manifest/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/node_version.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/spawn.js
  packages/build/src/status/add.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
Labels: type: chore

#1546 Fix empty strings in `build.environment`
  packages/build/src/env/main.js
  packages/build/tests/env/fixtures/empty_string/index.js
  packages/build/tests/env/fixtures/empty_string/netlify.toml
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/env/tests.js
Labels: type: bug

#1544 Do not fail when `cwd` does not exist but was passed as option to `@netlify/config`
  packages/config/src/options/main.js
Labels: type: bug

#1543 Improve error message on invalid `cwd` in `git` utils
  packages/git-utils/package-lock.json
  packages/git-utils/package.json
  packages/git-utils/src/exec.js
  packages/git-utils/src/main.js
  packages/git-utils/tests/main.js
Labels: type: bug

#1541 Fix `utils.cache.list()` failing if `cwd` does not exist
  packages/cache-utils/src/list.js
  packages/cache-utils/src/path.js
  packages/cache-utils/src/utils/cwd.js
  packages/cache-utils/tests/list.js
Labels: type: bug

#1547 Add warnings when using create-react-app with CI=true
  packages/build/src/core/commands.js
  packages/build/src/core/main.js
  packages/build/src/log/main.js
  packages/build/src/plugins/options.js
  packages/build/src/utils/package.js
  packages/build/tests/env/fixtures/create_react_app/index.js
  packages/build/tests/env/fixtures/create_react_app/netlify.toml
  packages/build/tests/env/fixtures/create_react_app/package.json
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/env/tests.js
Labels: type: bug

#1542 Fix invalid `cwd` in `cache` utility
  packages/cache-utils/src/path.js
  packages/cache-utils/tests/path.js
Labels: type: bug

#1553 Add `cwd` option to `utils.cache.*`
  packages/cache-utils/README.md
  packages/cache-utils/src/list.js
  packages/cache-utils/src/main.js
  packages/cache-utils/src/path.js
  packages/cache-utils/src/utils/cwd.js
  packages/cache-utils/tests/list.js
  packages/cache-utils/tests/path.js
Labels: type: chore

#1556 Improve logging of CLI flags
  packages/build/src/log/main.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: chore

#1555 Improve debug mode
  packages/build/src/log/cleanup.js
  packages/build/src/log/main.js
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
Labels: type: chore

#1557 Add debug mode to `@netlify/config`
  packages/config/src/log/options.js
  packages/config/src/options/main.js
  packages/config/tests/log/fixtures/empty/netlify.toml
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/log/tests.js
Labels: type: chore

#1558 Print more CLI flags in debug mode
  packages/build/src/core/config.js
  packages/build/src/log/main.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: chore

#1559 Move config cleanup logic from `@netlify/build` to `@netlify/config`
  packages/build/src/log/main.js
  packages/config/src/log/cleanup.js
  packages/config/src/main.js
Labels: type: chore

#1560 Print `defaultConfig` in debug mode with `@netlify/config`
  packages/config/src/log/cleanup.js
  packages/config/src/log/options.js
  packages/config/src/main.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
Labels: type: chore

#1561 Print `@netlify/config` result in debugging
  packages/config/src/log/options.js
  packages/config/src/main.js
  packages/config/tests/log/fixtures/empty/netlify.toml
  packages/config/tests/log/fixtures/simple/netlify.toml
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/log/tests.js
Labels: type: chore

#1562 Refactor `@netlify/config` debugging
  packages/config/src/log/cleanup.js
  packages/config/src/log/main.js
  packages/config/src/log/options.js
  packages/config/src/log/remove.js
  packages/config/src/main.js
  packages/config/src/options/main.js
Labels: type: chore

#1563 Add `utils.functions.listAll()`
  packages/build/src/plugins/child/utils.js
  packages/functions-utils/README.md
  packages/functions-utils/src/main.js
  packages/functions-utils/tests/main.js
Labels: type: chore

#1568 Add more documentation about --debug `@netlify/config` flag
  packages/config/src/bin/flags.js
Labels: type: chore

#1566 Fix newline problem in `@netlify/config`
  packages/config/src/log/main.js
Labels: type: bug

#1565 Do not print `cachedConfig` and `defaultConfig` CLI flag
  packages/build/src/log/main.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: security

#1569 Allow debug mode to be abled from the UI settings
  packages/config/src/options/main.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/log/tests.js
Labels: type: chore

#1567 Do not print `@netlify/config` CLI flags twice
  packages/config/src/log/main.js
Labels: type: chore

#1570 Move log logic of `@netlify/config`
  packages/config/src/log/logger.js
  packages/config/src/log/main.js
Labels: type: chore

#1571 Use YAML when logging in `@netlify/config`
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/log/logger.js
  packages/config/src/log/serialize.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
Labels: type: chore

#1572 Improve `@netlify/config` debugging titles
  packages/config/src/log/main.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
Labels: type: chore

#1574 Improve headers of debug logs for `@netlify/config`
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/log/logger.js
  packages/config/src/log/main.js
  packages/config/src/log/theme.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
Labels: type: chore

#1576 Downgrade chalk
  packages/config/package-lock.json
  packages/config/package.json
Labels: type: bug

#1575 Add `buffer` option to `@netlify/config`
  packages/config/src/bin/flags.js
  packages/config/src/log/logger.js
  packages/config/src/log/main.js
  packages/config/src/main.js
  packages/config/src/options/main.js
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/helpers/main.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/log/tests.js
Labels: type: chore

#1573 Fix `utils.cache.list()` crashing builds
  packages/cache-utils/README.md
  packages/cache-utils/src/list.js
  packages/cache-utils/tests/list.js
Labels: type: bug

#1577 Rename some logged titles
  packages/config/src/log/main.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
Labels: type: chore

#1578 Fix logging of `build.command`
  packages/build/src/core/commands.js
  packages/build/src/core/dry.js
  packages/build/src/core/main.js
  packages/build/src/error/parse/location.js
  packages/build/src/log/description.js
  packages/build/src/log/main.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/log/fixtures/empty/.gitkeep
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/log/tests.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/config/src/context.js
  packages/config/src/default_config.js
  packages/config/src/log/cleanup.js
  packages/config/src/normalize.js
  packages/config/src/origin.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/fixtures/command_origin_config/netlify.toml
  packages/config/tests/normalize/fixtures/command_origin_context/netlify.toml
  packages/config/tests/normalize/fixtures/empty/.gitkeep
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
Labels: type: bug

#1582 Add `NETLIFY_SITE_ID` environment variable support
  packages/config/src/options/main.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/api/tests.js
Labels: type: chore

#1581 Fix `base` directory used in CLI
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/config/src/main.js
  packages/config/src/options/base.js
  packages/config/src/options/main.js
  packages/config/tests/cwd/fixtures/build_base_override/netlify.toml
  packages/config/tests/cwd/fixtures/build_base_override/subdir/netlify.toml
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/cwd/tests.js
Labels: type: bug

#1584 Rename file
  packages/config/src/main.js
  packages/config/src/merge.js
Labels: type: chore

#1585 Move `defaultConfig` logic to its own file
  packages/config/src/default.js
  packages/config/src/main.js
Labels: type: chore
