Repository netlify/build, pull requests merged in 2020-11, with the labels that each got.

#2024 Add new `name` property in `functions-utils` `README.md`
  packages/functions-utils/README.md
Labels: documentation, type: feature

#2026 Add `eslint-plugin-promise`
  .eslintrc.js
  packages/build/src/plugins/ipc.js
Labels: type: chore

#2027 Add `eslint-plugin-import`
  .eslintrc.js
  packages/build/src/error/handle.js
  packages/build/src/plugins/child/logic.js
  packages/build/tests/plugins/tests.js
Labels: type: chore

#2034 Add `--fail` flag to `curl` for Codecov
  scripts/coverage.sh
Labels: type: chore

#2035 Use new `eslint-config-node`
  .eslintrc.js
  package-lock.json
  package.json
Labels: type: chore

#2037 Improve mock HTTP server
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/tests/core/tests.js
  packages/build/tests/env/tests.js
  packages/build/tests/error/tests.js
  packages/build/tests/helpers/server.js
  packages/build/tests/status/tests.js
  packages/config/tests/api/tests.js
Labels: type: chore

#2041 github tools: fix fossa workflow file
  .github/workflows/fossa.yml
Labels: type: chore

#2038 Simplify tests related to telemetry
  packages/build/tests/core/tests.js
Labels: test, type: chore

#2039 Simplify tests related to build cancellation
  packages/build/tests/error/tests.js
Labels: test, type: chore

#2045 Upgrade `eslint-config-node`
  .github/workflows/workflow.yml
  package.json
  scripts/coverage.sh
Labels: type: chore

#2047 Small refactoring
  packages/config/src/files.js
Labels: type: chore

#2048 Improve handling of default value for `edge-handlers` directory
  packages/build/src/core/constants.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/config/src/files.js
  packages/config/tests/normalize/fixtures/default_handlers_defined/edge-handlers/.gitkeep
  packages/config/tests/normalize/fixtures/default_handlers_defined/netlify.toml
  packages/config/tests/normalize/fixtures/default_handlers_not_defined/edge-handlers/.gitkeep
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
Labels: type: feature

#2049 Add default directory for Functions
  packages/config/src/files.js
  packages/config/tests/normalize/fixtures/default_functions_defined/netlify-automatic-functions/.gitkeep
  packages/config/tests/normalize/fixtures/default_functions_defined/netlify.toml
  packages/config/tests/normalize/fixtures/default_functions_not_defined/netlify-automatic-functions/.gitkeep
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
Labels: type: feature

#2052 Fix missing Edge handlers directory behavior
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/main.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: bug

#2053 Update `constants.FUNCTIONS_SRC` if the default functions directory is created dynamically
  packages/build/src/commands/constants.js
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/main.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/load.js
  packages/build/tests/plugins/fixtures/edge_handlers_src_dynamic/manifest.yml
  packages/build/tests/plugins/fixtures/edge_handlers_src_dynamic/netlify.toml
  packages/build/tests/plugins/fixtures/edge_handlers_src_dynamic/plugin.js
  packages/build/tests/plugins/fixtures/edge_handlers_src_dynamic_ignore/manifest.yml
  packages/build/tests/plugins/fixtures/edge_handlers_src_dynamic_ignore/netlify.toml
  packages/build/tests/plugins/fixtures/edge_handlers_src_dynamic_ignore/plugin.js
  packages/build/tests/plugins/fixtures/edge_handlers_src_dynamic_ignore/test/dummy
  packages/build/tests/plugins/fixtures/functions_src_dynamic/manifest.yml
  packages/build/tests/plugins/fixtures/functions_src_dynamic/netlify.toml
  packages/build/tests/plugins/fixtures/functions_src_dynamic/plugin.js
  packages/build/tests/plugins/fixtures/functions_src_dynamic_ignore/manifest.yml
  packages/build/tests/plugins/fixtures/functions_src_dynamic_ignore/netlify.toml
  packages/build/tests/plugins/fixtures/functions_src_dynamic_ignore/plugin.js
  packages/build/tests/plugins/fixtures/functions_src_dynamic_ignore/test/dummy
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2054 Refactor `commandsCount`
  packages/build/src/commands/get.js
  packages/build/src/core/dry.js
  packages/build/src/core/main.js
Labels: type: feature

#2057 Refactor IPC errors
  packages/build/src/commands/error.js
  packages/build/src/commands/plugin.js
  packages/build/src/error/build.js
  packages/build/src/plugins/ipc.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/spawn.js
  packages/build/src/status/load_error.js
Labels: type: feature

#2059 Add the concept of core commands
  packages/build/src/commands/core_command.js
  packages/build/src/commands/error.js
  packages/build/src/commands/get.js
  packages/build/src/commands/return.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/main.js
  packages/build/src/error/parse/location.js
  packages/build/src/error/type.js
  packages/build/src/log/description.js
  packages/build/src/log/messages/commands.js
  packages/build/src/log/messages/core_commands.js
  packages/build/src/log/messages/dry.js
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins_core/functions/error.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/src/plugins_core/functions/manifest.yml
  packages/build/src/plugins_core/main.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/plugins/fixtures/core_override/netlify.toml
  packages/build/tests/plugins/fixtures/functions_twice/functions/.gitkeep
  packages/build/tests/plugins/fixtures/functions_twice/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2055 Bundle Functions/Edge handlers if a directory is created during build
  packages/build/src/commands/get.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/dry.js
  packages/build/src/core/main.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/plugins/fixtures/functions_src_dynamic_bundle/manifest.yml
  packages/build/tests/plugins/fixtures/functions_src_dynamic_bundle/netlify.toml
  packages/build/tests/plugins/fixtures/functions_src_dynamic_bundle/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2063 Fix variable name typo
  packages/build/src/commands/return.js
  packages/build/src/commands/run_command.js
  packages/build/tests/status/fixtures/core_command_error/functions/function.js
  packages/build/tests/status/fixtures/core_command_error/netlify.toml
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/status/tests.js
Labels: type: feature

#2062 Make build logs headers prettier
  packages/build/src/log/header.js
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: type: feature

#2066 Fix empty version in build logs
  packages/build/src/log/messages/plugins.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
Labels: type: bug

#2065 Improve error message when `manifest.yml` is missing
  packages/build/src/plugins/manifest/load.js
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
Labels: type: chore

#2064 Fix error handling of Functions bundling errors
  packages/build/src/plugins_core/functions/error.js
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/plugins/fixtures/functions_package_json_invalid/functions/test.js
  packages/build/tests/plugins/fixtures/functions_package_json_invalid/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: type: bug

#2070 Improve renovate config
  renovate.json5
Labels: type: chore

#2074 Fix error reporting when a plugin is missing a `manifest.yml`
  packages/build/src/plugins/manifest/load.js
  packages/build/src/plugins/manifest/path.js
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
Labels: type: bug

#2079 Add `supports-color` to `renovate.json5`
  renovate.json5
Labels: type: chore

#2082 chore: git ignore .vscode
  .gitignore
Labels: type: chore

#2081 fix(config): return empty object on undefined site id
  packages/config/src/api/site_info.js
Labels: type: bug

#2076 Fetch the `plugins.json` in builds
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/core/feature_flags.js
  packages/build/src/core/main.js
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/list.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/helpers/main.js
  packages/build/tests/helpers/normalize.js
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: type: feature
