Repository netlify/build, pull requests merged in 2020-08, with the labels that each got.

#1725 Revert deploy server client implementation and --buildbotServerSocket CLI flag
  packages/build/src/buildbot_client/main.js
  packages/build/src/commands/run.js
  packages/build/src/core/bin.js
  packages/build/src/core/main.js
  packages/build/src/error/parse/location.js
  packages/build/src/error/type.js
Labels: type: chore

#1728 Rename the monitoring tag name of Build plugins
  packages/build/src/commands/run.js
  packages/build/tests/time/tests.js
Labels: feat/speedy-builds, type: feature

#1729 Rename `metricName` to `tag`
  packages/build/src/commands/run.js
  packages/build/src/time/main.js
  packages/build/src/time/report.js
  packages/build/tests/time/tests.js
Labels: feat/speedy-builds, type: feature

#1730 Add test for the `build.command` duration monitoring
  packages/build/tests/time/fixtures/plugin/netlify.toml
  packages/build/tests/time/tests.js
Labels: feat/speedy-builds, type: feature

#1732 Refactor timings tests
  packages/build/tests/time/tests.js
Labels: feat/speedy-builds, type: feature

#1736 Do not log `timersFile` in production
  packages/build/src/log/main.js
Labels: type: bug

#1735 Simplify `README`
  README.md
  package-lock.json
  package.json
Labels: documentation, type: chore

#1742 Add more metrics for plugins
  packages/build/src/time/aggregate.js
  packages/build/src/time/report.js
  packages/build/tests/time/fixtures/plugin/netlify.toml
  packages/build/tests/time/fixtures/plugin/one/index.js
  packages/build/tests/time/fixtures/plugin/one/manifest.yml
  packages/build/tests/time/fixtures/plugin/two/index.js
  packages/build/tests/time/fixtures/plugin/two/manifest.yml
  packages/build/tests/time/tests.js
Labels: type: feature

#1737 Improve packages `package.json`
  package.json
  packages/build/package.json
  packages/cache-utils/package.json
  packages/config/package.json
  packages/functions-utils/package.json
  packages/git-utils/package.json
  packages/run-utils/package.json
Labels: type: chore

#1745 Add `statsd` parent tags
  packages/build/src/commands/run.js
  packages/build/src/time/aggregate.js
  packages/build/src/time/main.js
Labels: feat/speedy-builds, type: feature

#1746 Rename `tag` internal variable to `stageTag`
  packages/build/src/time/aggregate.js
  packages/build/src/time/main.js
  packages/build/src/time/report.js
  packages/build/tests/time/tests.js
Labels: feat/speedy-builds, type: feature

#1747 Rename all statsd `stage` tags
  packages/build/src/commands/run.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/spawn.js
  packages/build/src/time/aggregate.js
  packages/build/src/time/main.js
  packages/build/tests/time/tests.js
Labels: feat/speedy-builds, type: feature

#1749 Replace `total` duration measurement by `others`
  packages/build/src/core/main.js
  packages/build/src/time/aggregate.js
  packages/build/src/time/main.js
  packages/build/tests/time/tests.js
Labels: feat/speedy-builds, type: feature

#1750 Improve performance monitoring rounding
  packages/build/src/commands/run.js
  packages/build/src/core/main.js
  packages/build/src/log/main.js
  packages/build/src/telemetry/complete.js
  packages/build/src/time/aggregate.js
  packages/build/src/time/main.js
  packages/build/src/time/measure.js
  packages/build/src/time/report.js
  packages/build/tests/time/tests.js
Labels: feat/speedy-builds, type: feature

#1753 Improve constants path normalization
  packages/build/src/core/constants.js
Labels: feat/build-plugins, type: feature

#1752 Pass `constants.NETLIFY_API_TOKEN` to core plugins
  packages/build/src/core/config.js
  packages/build/src/core/constants.js
  packages/build/src/core/main.js
  packages/build/src/plugins/load.js
  packages/build/tests/plugins/fixtures/netlify_api_token/manifest.yml
  packages/build/tests/plugins/fixtures/netlify_api_token/netlify.toml
  packages/build/tests/plugins/fixtures/netlify_api_token/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/config/README.md
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/bin/main.js
  packages/config/src/main.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/api/tests.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
Labels: feat/build-plugins, type: feature

#1751 Send information directly to statsd
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/core/bin.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/log/main.js
  packages/build/src/time/main.js
  packages/build/src/time/report.js
  packages/build/tests/helpers/temp.js
  packages/build/tests/helpers/udp_server.js
  packages/build/tests/time/snapshots/tests.js.md
  packages/build/tests/time/snapshots/tests.js.snap
  packages/build/tests/time/tests.js
Labels: feat/speedy-builds, type: feature

#1754 Add `--framework` CLI flag
  packages/build/src/core/bin.js
  packages/build/src/core/main.js
  packages/build/src/log/main.js
  packages/build/src/time/report.js
  packages/build/tests/time/snapshots/tests.js.md
  packages/build/tests/time/snapshots/tests.js.snap
  packages/build/tests/time/tests.js
Labels: feat/speedy-builds, type: feature

#1755 Refactor core plugins logic
  packages/build/src/install/local.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/main.js
Labels: project:edge-handlers-support, type: feature

#1765 chore(deps): ignore major updates breaking node 8 support
  renovate.json5
Labels: type: chore

#1771 Log `baseRelDir` in debug mode
  packages/config/src/default.js
  packages/config/src/log/cleanup.js
  packages/config/src/log/main.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
Labels: type: chore

#1769 Fix error message on missing Netlify Function dependency
  packages/build/src/plugins_core/functions/error.js
Labels: type: bug

#1770 Fix `publish` and `functions` directory resolution in monorepos with Netlify CLI
  packages/config/src/options/base.js
  packages/config/src/options/main.js
  packages/config/tests/api/fixtures/build_base_override/netlify.toml
  packages/config/tests/api/fixtures/build_base_override/subdir/netlify.toml
  packages/config/tests/api/fixtures/build_base_override/subdir/publish/.gitkeep
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/api/tests.js
Labels: type: bug

#1772 Fix cache utility bug
  packages/cache-utils/package.json
  packages/cache-utils/src/manifest.js
Labels: type: bug

#1773 Show full stack trace in debug mode
  packages/build/src/commands/error.js
  packages/build/src/commands/run.js
  packages/build/src/core/main.js
  packages/build/src/error/handle.js
  packages/build/src/error/parse/clean_stack.js
  packages/build/src/error/parse/parse.js
  packages/build/src/error/parse/serialize_log.js
  packages/build/src/error/parse/serialize_status.js
  packages/build/src/error/parse/stack.js
  packages/build/src/log/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/options.js
  packages/build/src/status/add.js
  packages/build/src/status/report.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/error/tests.js
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: type: chore

#1774 Improve documentation of error handling
  packages/build/src/commands/run.js
Labels: type: chore

#1775 Remove `create-react-app` warning
  packages/build/src/commands/build_command.js
  packages/build/src/log/main.js
  packages/build/tests/env/fixtures/create_react_app/index.js
  packages/build/tests/env/fixtures/create_react_app/netlify.toml
  packages/build/tests/env/fixtures/create_react_app/package.json
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/env/tests.js
Labels: type: chore

#1776 Add `eslint-plugin-fp`
  .eslintrc.json
  package-lock.json
  package.json
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/env/changes.js
  packages/build/src/error/build.js
  packages/build/src/error/monitor/report.js
  packages/build/src/log/colors.js
  packages/build/src/log/logger.js
  packages/build/src/log/old_version.js
  packages/build/src/plugins/child/lazy.js
  packages/build/tests/error/fixtures/early_exit/plugin_slow.js
  packages/build/tests/helpers/server.js
  packages/build/tests/plugins/fixtures/error_argument/plugin.js
  packages/config/src/log/logger.js
  packages/config/src/validate/example.js
  packages/functions-utils/package-lock.json
  packages/functions-utils/package.json
  packages/functions-utils/tests/main.js
  packages/run-utils/src/main.js
Labels: type: chore

#1784 Add `os-name` to list of dependencies not to upgrade
  renovate.json5
Labels: type: chore

#1785 Remove `babel-eslint`
  .eslintrc.json
  package-lock.json
  package.json
Labels: type: chore

#1786 Lint ESLint comments
  .eslintrc.json
  package-lock.json
  package.json
  packages/build/src/plugins/child/error.js
  packages/build/tests/install/fixtures/already/plugin/main.js
  packages/build/tests/install/fixtures/dir/functions/function/index.js
  packages/build/tests/install/fixtures/functions_error/functions/index.js
  packages/build/tests/install/fixtures/functions_npm/functions/index.js
  packages/build/tests/install/fixtures/functions_yarn/functions/index.js
  packages/build/tests/install/fixtures/functions_yarn_ci/functions/index.js
  packages/build/tests/install/fixtures/local_dep/functions/index.js
  packages/build/tests/install/fixtures/local_missing/plugin/main.js
  packages/build/tests/install/fixtures/mispelled_dep/functions/index.js
  packages/build/tests/install/fixtures/no_package/plugin/main.js
  packages/build/tests/install/fixtures/npm/plugin/main.js
  packages/build/tests/install/fixtures/optional/functions/index.js
  packages/build/tests/install/fixtures/yarn/plugin/main.js
  packages/build/tests/install/fixtures/yarn_ci/plugin/main.js
Labels: type: chore
