Repository netlify/build, pull requests merged in 2020-05, with the labels that each got.

#1217 Improve `npm install` error handling
  packages/build/src/error/monitor/normalize.js
  packages/build/src/error/monitor/report.js
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
Labels: type: feature

#1171 Deprecate `netlify.yml` and `netlify.json`
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/parse/main.js
  packages/config/src/parse/parsers.js
  packages/config/src/utils/toml.js
  packages/config/src/validate/example.js
  packages/config/tests/parse/fixtures/non_convertible_yaml/netlify.yml
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/parse/tests.js
  packages/config/tests/validate/fixtures/colors/netlify.yml
  packages/config/tests/validate/tests.js
Labels: type: feature

#1226 Improve error handling grouping
  packages/build/src/error/monitor/normalize.js
Labels: type: feature

#1227 Improve grouping of monitored errors
  packages/build/src/error/monitor/normalize.js
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
Labels: type: chore

#1229 Print `netlify.toml` instead of creating one when user has a `netlify.yml`
  packages/config/src/parse/main.js
  packages/config/src/parse/parsers.js
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/parse/tests.js
Labels: type: chore

#1230 Fix automatic package installation uncaught exception
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/install/missing.js
  packages/build/src/plugins/options.js
  packages/build/src/utils/resolve.js
Labels: type: bug

#1237 Fix `toml.parse()` returning an object with `null` prototype
  packages/config/src/parse/parsers.js
Labels: type: chore

#1234 Fix handling non-error instances
  packages/build/src/error/serialize.js
Labels: type: bug

#1176 Document that `process.env` can be modified in plugins
  README.md
Labels: documentation, type: feature

#1084 Improve documentation for `utils.build`
  README.md
Labels: documentation, type: feature

#1246 Use color theme in all parts of the codebase
  packages/build/src/log/logger.js
Labels: type: chore

#1242 Do not allow overridding core plugins
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/main.js
  packages/build/tests/plugins/load/fixtures/core_override/netlify.toml
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/load/tests.js
Labels: type: chore

#1241 Separate Functions auto-installation plugin from Functions bundling plugin
  packages/build/src/plugins_core/functions/plugin.js
  packages/build/src/plugins_core/functions_install/manifest.yml
  packages/build/src/plugins_core/functions_install/plugin.js
  packages/build/src/plugins_core/main.js
  packages/build/tests/core/dry/snapshots/tests.js.md
  packages/build/tests/core/dry/snapshots/tests.js.snap
  packages/build/tests/core/flags/snapshots/tests.js.md
  packages/build/tests/core/flags/snapshots/tests.js.snap
  packages/build/tests/install/functions/fixtures/dir/netlify.toml
  packages/build/tests/install/functions/fixtures/node_modules/netlify.toml
  packages/build/tests/install/functions/fixtures/npm_ci_lock/netlify.toml
  packages/build/tests/install/functions/fixtures/npm_ci_no_lock/netlify.toml
  packages/build/tests/install/functions/fixtures/npm_lock/netlify.toml
  packages/build/tests/install/functions/fixtures/yarn_ci_lock/netlify.toml
  packages/build/tests/install/functions/fixtures/yarn_lock/netlify.toml
  packages/build/tests/install/functions/snapshots/tests.js.md
  packages/build/tests/install/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/snapshots/tests.js.md
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/utils/snapshots/tests.js.md
  packages/build/tests/plugins/utils/snapshots/tests.js.snap
Labels: type: feature

#1243 Add deprecation warning for Functions automatic installs
  packages/build/src/install/functions.js
  packages/build/src/log/logger.js
  packages/build/src/log/main.js
  packages/build/src/log/theme.js
  packages/build/src/plugins/options.js
  packages/build/tests/install/functions/fixtures/warning/functions/package-lock.json
  packages/build/tests/install/functions/fixtures/warning/functions/package.json
  packages/build/tests/install/functions/fixtures/warning/functions/test.js
  packages/build/tests/install/functions/fixtures/warning/netlify.toml
  packages/build/tests/install/functions/snapshots/tests.js.md
  packages/build/tests/install/functions/snapshots/tests.js.snap
  packages/build/tests/install/functions/tests.js
Labels: type: feature

#1244 Allow core plugins to be optional
  packages/build/src/plugins/options.js
Labels: type: chore

#1105 Add documentation about asynchronous code
  README.md
Labels: documentation, type: feature

#1150 Update `@netlify/config` `README`
  packages/config/README.md
Labels: documentation, type: feature

#1253 Report `groupingHash` to Bugsnag
  packages/build/src/error/monitor/print.js
  packages/build/src/error/monitor/report.js
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
Labels: type: chore

#1251 Use custom cache folder with Yarn
  packages/build/src/install/main.js
Labels: type: bug

#1258 Rename error `context` to `group`
  packages/build/src/error/monitor/report.js
  packages/build/src/error/type.js
Labels: type: chore

#1260 Rename `ID` to `Name` in build logs
  packages/build/src/error/plugin.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/install/local/snapshots/tests.js.md
  packages/build/tests/install/local/snapshots/tests.js.snap
  packages/build/tests/install/missing/snapshots/tests.js.md
  packages/build/tests/install/missing/snapshots/tests.js.snap
  packages/build/tests/manifest/check/snapshots/tests.js.md
  packages/build/tests/manifest/check/snapshots/tests.js.snap
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.snap
  packages/build/tests/manifest/validate/snapshots/tests.js.md
  packages/build/tests/manifest/validate/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.md
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/handlers/snapshots/tests.js.md
  packages/build/tests/plugins/handlers/snapshots/tests.js.snap
  packages/build/tests/plugins/utils/snapshots/tests.js.md
  packages/build/tests/plugins/utils/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.md
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
Labels: type: feature

#1259 Refactor error serialization
  packages/build/src/error/location.js
  packages/build/src/error/parse.js
  packages/build/src/error/plugin.js
  packages/build/src/error/properties.js
  packages/build/src/error/serialize.js
  packages/build/src/error/serialize_log.js
  packages/build/src/error/stack.js
  packages/build/src/log/main.js
Labels: type: chore

#1257 Simplify error context
  packages/build/src/error/monitor/report.js
  packages/build/src/error/type.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/install/local/snapshots/tests.js.md
  packages/build/tests/install/local/snapshots/tests.js.snap
  packages/build/tests/log/old_version/snapshots/tests.js.md
  packages/build/tests/log/old_version/snapshots/tests.js.snap
  packages/build/tests/manifest/check/snapshots/tests.js.md
  packages/build/tests/manifest/check/snapshots/tests.js.snap
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.md
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
Labels: type: feature

#1262 Rename `header` to `title`
  packages/build/src/error/monitor/report.js
  packages/build/src/error/parse.js
  packages/build/src/error/serialize_log.js
  packages/build/src/error/type.js
  packages/build/src/log/main.js
Labels: type: chore

#1263 Small refactoring of `getTypeInfo()`
  packages/build/src/error/cancel.js
  packages/build/src/error/monitor/report.js
  packages/build/src/error/parse.js
  packages/build/src/error/type.js
Labels: type: chore

#1254 Improve plugins orchestration
  packages/build/src/core/commands.js
  packages/build/src/core/main.js
  packages/build/src/error/cancel.js
  packages/build/src/error/type.js
  packages/build/src/log/main.js
  packages/build/tests/plugins/handlers/fixtures/end_fail_plugin/netlify.toml
  packages/build/tests/plugins/handlers/fixtures/end_fail_plugin/plugin.js
  packages/build/tests/plugins/handlers/fixtures/error_fail_plugin/netlify.toml
  packages/build/tests/plugins/handlers/fixtures/error_fail_plugin/plugin.js
  packages/build/tests/plugins/handlers/fixtures/success_fail_plugin/netlify.toml
  packages/build/tests/plugins/handlers/fixtures/success_fail_plugin/plugin.js
  packages/build/tests/plugins/handlers/snapshots/tests.js.md
  packages/build/tests/plugins/handlers/snapshots/tests.js.snap
  packages/build/tests/plugins/handlers/tests.js
  packages/build/tests/plugins/run/fixtures/env_changes_on_error/netlify.toml
  packages/build/tests/plugins/run/fixtures/env_changes_on_error/plugin.js
  packages/build/tests/plugins/run/snapshots/tests.js.md
  packages/build/tests/plugins/run/snapshots/tests.js.snap
  packages/build/tests/plugins/run/tests.js
Labels: type: feature

#1264 Add `utils.status.show()`
  packages/build/src/core/commands.js
  packages/build/src/core/status.js
  packages/build/src/error/type.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/child/status.js
  packages/build/src/plugins/child/utils.js
  packages/build/tests/plugins/handlers/snapshots/tests.js.snap
  packages/build/tests/plugins/utils/snapshots/tests.js.md
  packages/build/tests/plugins/utils/snapshots/tests.js.snap
Labels: type: feature

#1267 Move error parsing files together
  packages/build/src/error/parse/clean_stack.js
  packages/build/src/error/parse/location.js
  packages/build/src/error/parse/parse.js
  packages/build/src/error/parse/plugin.js
  packages/build/src/error/parse/properties.js
  packages/build/src/error/parse/serialize_log.js
  packages/build/src/error/parse/stack.js
  packages/build/src/error/type.js
  packages/build/src/log/main.js
Labels: type: chore

#1266 Validate arguments of `utils.status.show()`
  packages/build/src/plugins/child/status.js
  packages/build/tests/plugins/status/fixtures/main/netlify.toml
  packages/build/tests/plugins/status/fixtures/main/plugin.js
  packages/build/tests/plugins/status/snapshots/tests.js.md
  packages/build/tests/plugins/status/snapshots/tests.js.snap
  packages/build/tests/plugins/status/tests.js
Labels: type: feature

#1268 Add tests covering interaction of `onError` and `cancelBuild()`
  packages/build/src/core/commands.js
  packages/build/tests/plugins/handlers/fixtures/end_cancel_build/netlify.toml
  packages/build/tests/plugins/handlers/fixtures/end_cancel_build/plugin.js
  packages/build/tests/plugins/handlers/fixtures/error_cancel_build/netlify.toml
  packages/build/tests/plugins/handlers/fixtures/error_cancel_build/plugin.js
  packages/build/tests/plugins/handlers/fixtures/success_cancel_build/netlify.toml
  packages/build/tests/plugins/handlers/fixtures/success_cancel_build/plugin.js
  packages/build/tests/plugins/handlers/snapshots/tests.js.md
  packages/build/tests/plugins/handlers/snapshots/tests.js.snap
  packages/build/tests/plugins/handlers/tests.js
Labels: test, type: chore

#1269 Fix statuses validation
  packages/build/src/plugins/child/status.js
  packages/build/tests/plugins/status/snapshots/tests.js.md
  packages/build/tests/plugins/status/snapshots/tests.js.snap
  packages/build/tests/plugins/status/tests.js
Labels: type: bug

#1270 Log success statuses in CLI builds
  packages/build/src/core/main.js
  packages/build/src/core/status.js
  packages/build/src/log/main.js
  packages/build/tests/plugins/status/fixtures/print/four.js
  packages/build/tests/plugins/status/fixtures/print/netlify.toml
  packages/build/tests/plugins/status/fixtures/print/one.js
  packages/build/tests/plugins/status/fixtures/print/three.js
  packages/build/tests/plugins/status/fixtures/print/two.js
  packages/build/tests/plugins/status/snapshots/tests.js.md
  packages/build/tests/plugins/status/snapshots/tests.js.snap
  packages/build/tests/plugins/status/tests.js
Labels: type: feature

#1272 Use a brighter color for deprecation warning
  packages/build/src/log/main.js
Labels: type: feature

#1271 Add error statuses
  packages/build/src/core/commands.js
  packages/build/src/core/main.js
  packages/build/src/error/cancel.js
  packages/build/src/error/parse/parse.js
  packages/build/src/error/parse/properties.js
  packages/build/src/error/parse/serialize_log.js
  packages/build/src/error/parse/serialize_status.js
  packages/build/src/error/type.js
Labels: type: feature

#1273 Do not allow overriding an error status with a success status
  packages/build/src/core/status.js
  packages/build/tests/plugins/status/fixtures/error_status_override/netlify.toml
  packages/build/tests/plugins/status/fixtures/error_status_override/plugin.js
  packages/build/tests/plugins/status/snapshots/tests.js.md
  packages/build/tests/plugins/status/snapshots/tests.js.snap
  packages/build/tests/plugins/status/tests.js
Labels: type: feature

#1275 Assign a default status for plugins that do not use `utils.status.show()`
  packages/build/src/core/commands.js
  packages/build/src/core/status.js
  packages/build/tests/plugins/status/fixtures/error_status_error_override/netlify.toml
  packages/build/tests/plugins/status/fixtures/error_status_error_override/plugin.js
  packages/build/tests/plugins/status/fixtures/error_status_override/plugin.js
  packages/build/tests/plugins/status/fixtures/implicit_one/netlify.toml
  packages/build/tests/plugins/status/fixtures/implicit_one/plugin.js
  packages/build/tests/plugins/status/fixtures/implicit_onend/netlify.toml
  packages/build/tests/plugins/status/fixtures/implicit_onend/plugin.js
  packages/build/tests/plugins/status/fixtures/implicit_several/netlify.toml
  packages/build/tests/plugins/status/fixtures/implicit_several/plugin.js
  packages/build/tests/plugins/status/fixtures/no_implicit/netlify.toml
  packages/build/tests/plugins/status/fixtures/no_implicit/plugin.js
  packages/build/tests/plugins/status/fixtures/no_implicit_none/netlify.toml
  packages/build/tests/plugins/status/fixtures/no_implicit_none/plugin.js
  packages/build/tests/plugins/status/fixtures/no_implicit_onerror/netlify.toml
  packages/build/tests/plugins/status/fixtures/no_implicit_onerror/plugin.js
  packages/build/tests/plugins/status/fixtures/success_status_override/netlify.toml
  packages/build/tests/plugins/status/fixtures/success_status_override/plugin.js
  packages/build/tests/plugins/status/snapshots/tests.js.md
  packages/build/tests/plugins/status/snapshots/tests.js.snap
  packages/build/tests/plugins/status/tests.js
Labels: type: feature

#1276 Improve API mocking test helper
  packages/build/tests/core/telemetry/snapshots/tests.js.md
  packages/build/tests/core/telemetry/snapshots/tests.js.snap
  packages/build/tests/core/telemetry/tests.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/build/tests.js
  packages/build/tests/helpers/server.js
Labels: test, type: chore

#1277 Send statuses to the API
  packages/build/src/core/main.js
  packages/build/src/core/status.js
  packages/build/tests/plugins/status/fixtures/error_cancel_build/netlify.toml
  packages/build/tests/plugins/status/fixtures/error_cancel_build/plugin.js
  packages/build/tests/plugins/status/fixtures/error_fail_build/netlify.toml
  packages/build/tests/plugins/status/fixtures/error_fail_build/plugin.js
  packages/build/tests/plugins/status/fixtures/error_fail_plugin/netlify.toml
  packages/build/tests/plugins/status/fixtures/error_fail_plugin/plugin.js
  packages/build/tests/plugins/status/fixtures/error_properties/netlify.toml
  packages/build/tests/plugins/status/fixtures/error_properties/plugin.js
  packages/build/tests/plugins/status/fixtures/no_implicit_incomplete/netlify.toml
  packages/build/tests/plugins/status/fixtures/no_implicit_incomplete/one.js
  packages/build/tests/plugins/status/fixtures/no_implicit_incomplete/two.js
  packages/build/tests/plugins/status/snapshots/tests.js.md
  packages/build/tests/plugins/status/snapshots/tests.js.snap
  packages/build/tests/plugins/status/tests.js
Labels: type: feature

#1283 Improve logs related to plugins load
  packages/build/src/log/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/spawn.js
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/install/local/snapshots/tests.js.md
  packages/build/tests/install/local/snapshots/tests.js.snap
  packages/build/tests/install/missing/snapshots/tests.js.md
  packages/build/tests/install/missing/snapshots/tests.js.snap
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.md
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/status/snapshots/tests.js.md
  packages/build/tests/plugins/status/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.md
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
Labels: type: feature

#1286 Report plugin load errors as statuses
  packages/build/src/core/main.js
  packages/build/src/core/status.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/options.js
  packages/build/tests/plugins/status/fixtures/error_inputs_validation/manifest.yml
  packages/build/tests/plugins/status/fixtures/error_inputs_validation/netlify.toml
  packages/build/tests/plugins/status/fixtures/error_inputs_validation/plugin.js
  packages/build/tests/plugins/status/fixtures/error_load_uncaught/netlify.toml
  packages/build/tests/plugins/status/fixtures/error_load_uncaught/plugin.js
  packages/build/tests/plugins/status/fixtures/error_plugin_shape/netlify.toml
  packages/build/tests/plugins/status/fixtures/error_plugin_shape/plugin.js
  packages/build/tests/plugins/status/snapshots/tests.js.md
  packages/build/tests/plugins/status/snapshots/tests.js.snap
  packages/build/tests/plugins/status/tests.js
Labels: type: feature

#1287 Strip ANSI sequences from statuses
  packages/build/src/core/status.js
  packages/build/tests/plugins/status/fixtures/colors/netlify.toml
  packages/build/tests/plugins/status/fixtures/colors/plugin.js
  packages/build/tests/plugins/status/snapshots/tests.js.md
  packages/build/tests/plugins/status/snapshots/tests.js.snap
  packages/build/tests/plugins/status/tests.js
Labels: type: feature

#1288 Split statuses code into several files
  packages/build/src/core/commands.js
  packages/build/src/core/main.js
  packages/build/src/core/status.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/status/add.js
  packages/build/src/status/colors.js
  packages/build/src/status/report.js
Labels: type: chore

#1289 Split tests into several files
  packages/build/tests/plugins/status/snapshots/tests.js.md
  packages/build/tests/plugins/status/snapshots/tests.js.snap
  packages/build/tests/plugins/status/tests.js
  packages/build/tests/status/add/fixtures/error_status_error_override/netlify.toml
  packages/build/tests/status/add/fixtures/error_status_error_override/plugin.js
  packages/build/tests/status/add/fixtures/error_status_override/netlify.toml
  packages/build/tests/status/add/fixtures/error_status_override/plugin.js
  packages/build/tests/status/add/fixtures/implicit_one/netlify.toml
  packages/build/tests/status/add/fixtures/implicit_one/plugin.js
  packages/build/tests/status/add/fixtures/implicit_onend/netlify.toml
  packages/build/tests/status/add/fixtures/implicit_onend/plugin.js
  packages/build/tests/status/add/fixtures/implicit_several/netlify.toml
  packages/build/tests/status/add/fixtures/implicit_several/plugin.js
  packages/build/tests/status/add/fixtures/no_implicit/netlify.toml
  packages/build/tests/status/add/fixtures/no_implicit/plugin.js
  packages/build/tests/status/add/fixtures/no_implicit_incomplete/netlify.toml
  packages/build/tests/status/add/fixtures/no_implicit_incomplete/one.js
  packages/build/tests/status/add/fixtures/no_implicit_incomplete/two.js
  packages/build/tests/status/add/fixtures/no_implicit_none/netlify.toml
  packages/build/tests/status/add/fixtures/no_implicit_none/plugin.js
  packages/build/tests/status/add/fixtures/no_implicit_onerror/netlify.toml
  packages/build/tests/status/add/fixtures/no_implicit_onerror/plugin.js
  packages/build/tests/status/add/fixtures/success_status_override/netlify.toml
  packages/build/tests/status/add/fixtures/success_status_override/plugin.js
  packages/build/tests/status/add/snapshots/tests.js.md
  packages/build/tests/status/add/snapshots/tests.js.snap
  packages/build/tests/status/add/tests.js
  packages/build/tests/status/helpers/run.js
  packages/build/tests/status/report/fixtures/colors/netlify.toml
  packages/build/tests/status/report/fixtures/colors/plugin.js
  packages/build/tests/status/report/fixtures/error_cancel_build/netlify.toml
  packages/build/tests/status/report/fixtures/error_cancel_build/plugin.js
  packages/build/tests/status/report/fixtures/error_fail_build/netlify.toml
  packages/build/tests/status/report/fixtures/error_fail_build/plugin.js
  packages/build/tests/status/report/fixtures/error_fail_plugin/netlify.toml
  packages/build/tests/status/report/fixtures/error_fail_plugin/plugin.js
  packages/build/tests/status/report/fixtures/error_inputs_validation/manifest.yml
  packages/build/tests/status/report/fixtures/error_inputs_validation/netlify.toml
  packages/build/tests/status/report/fixtures/error_inputs_validation/plugin.js
  packages/build/tests/status/report/fixtures/error_load_uncaught/netlify.toml
  packages/build/tests/status/report/fixtures/error_load_uncaught/plugin.js
  packages/build/tests/status/report/fixtures/error_plugin_shape/netlify.toml
  packages/build/tests/status/report/fixtures/error_plugin_shape/plugin.js
  packages/build/tests/status/report/fixtures/error_properties/netlify.toml
  packages/build/tests/status/report/fixtures/error_properties/plugin.js
  packages/build/tests/status/report/fixtures/print/four.js
  packages/build/tests/status/report/fixtures/print/netlify.toml
  packages/build/tests/status/report/fixtures/print/one.js
  packages/build/tests/status/report/fixtures/print/three.js
  packages/build/tests/status/report/fixtures/print/two.js
  packages/build/tests/status/report/snapshots/tests.js.md
  packages/build/tests/status/report/snapshots/tests.js.snap
  packages/build/tests/status/report/tests.js
  packages/build/tests/status/utils/fixtures/main/netlify.toml
  packages/build/tests/status/utils/fixtures/main/plugin.js
  packages/build/tests/status/utils/snapshots/tests.js.md
  packages/build/tests/status/utils/snapshots/tests.js.snap
  packages/build/tests/status/utils/tests.js
Labels: test, type: chore

#1282 Use the plugins cached in the `build-image`
  packages/build/package.json
  packages/build/src/install/missing.js
  packages/build/src/log/main.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/package.js
  packages/build/src/plugins/resolve.js
  packages/build/src/plugins_core/main.js
  packages/build/src/utils/resolve.js
  packages/build/tests/plugins/load/fixtures/build_image/netlify.toml
  packages/build/tests/plugins/load/fixtures/build_image/package.json
  packages/build/tests/plugins/load/fixtures/build_image_cache/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/load/fixtures/build_image_cache/node_modules/netlify-plugin-test/package.json
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/load/tests.js
Labels: type: feature

#1291 Add `pluginOption.loadedFrom`
  packages/build/src/core/commands.js
  packages/build/src/error/monitor/report.js
  packages/build/src/error/parse/location.js
  packages/build/src/install/local.js
  packages/build/src/log/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/check.js
  packages/build/src/plugins/manifest/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/src/plugins/spawn.js
  packages/build/src/plugins_core/main.js
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
Labels: type: feature

#1293 Small refactoring extracting a function
  packages/build/src/plugins/options.js
Labels: type: chore

#1292 Improve performance of plugins automatic installation
  .gitignore
  packages/build/package.json
  packages/build/src/install/missing.js
  packages/build/src/log/logger.js
  packages/build/src/log/main.js
  packages/build/src/log/theme.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/install/missing/fixtures/already_installed/.netlify/plugins/node_modules/netlify-plugin-test/index.js
  packages/build/tests/install/missing/fixtures/already_installed/.netlify/plugins/package.json
  packages/build/tests/install/missing/fixtures/already_installed/netlify.toml
  packages/build/tests/install/missing/fixtures/installed_already/netlify.toml
  packages/build/tests/install/missing/fixtures/installed_already/node_modules/isobject/LICENSE
  packages/build/tests/install/missing/fixtures/installed_already/node_modules/isobject/README.md
  packages/build/tests/install/missing/fixtures/installed_already/node_modules/isobject/index.cjs.js
  packages/build/tests/install/missing/fixtures/installed_already/node_modules/isobject/index.d.ts
  packages/build/tests/install/missing/fixtures/installed_already/node_modules/isobject/index.js
  packages/build/tests/install/missing/fixtures/installed_already/node_modules/isobject/package.json
  packages/build/tests/install/missing/fixtures/installed_already/package-lock.json
  packages/build/tests/install/missing/fixtures/installed_already/package.json
  packages/build/tests/install/missing/fixtures/main/netlify.toml
  packages/build/tests/install/missing/fixtures/npm_ci_lock/netlify.toml
  packages/build/tests/install/missing/fixtures/npm_ci_lock/package-lock.json
  packages/build/tests/install/missing/fixtures/npm_ci_lock/package.json
  packages/build/tests/install/missing/fixtures/npm_ci_no_lock/netlify.toml
  packages/build/tests/install/missing/fixtures/npm_ci_no_lock/package.json
  packages/build/tests/install/missing/fixtures/npm_lock/netlify.toml
  packages/build/tests/install/missing/fixtures/npm_lock/package-lock.json
  packages/build/tests/install/missing/fixtures/npm_lock/package.json
  packages/build/tests/install/missing/fixtures/yarn_ci_lock/netlify.toml
  packages/build/tests/install/missing/fixtures/yarn_ci_lock/package.json
  packages/build/tests/install/missing/fixtures/yarn_ci_lock/yarn.lock
  packages/build/tests/install/missing/fixtures/yarn_lock/netlify.toml
  packages/build/tests/install/missing/fixtures/yarn_lock/package.json
  packages/build/tests/install/missing/fixtures/yarn_lock/yarn.lock
  packages/build/tests/install/missing/fixtures/yarn_lock_workspaces/netlify.toml
  packages/build/tests/install/missing/fixtures/yarn_lock_workspaces/one/.gitempty
  packages/build/tests/install/missing/fixtures/yarn_lock_workspaces/package.json
  packages/build/tests/install/missing/fixtures/yarn_lock_workspaces/yarn.lock
  packages/build/tests/install/missing/snapshots/tests.js.md
  packages/build/tests/install/missing/snapshots/tests.js.snap
  packages/build/tests/install/missing/tests.js
Labels: type: feature

#1296 Fix automatic installation crashing
  packages/build/src/install/main.js
Labels: type: bug

#1297 Simplify some code related to `loadedFrom`
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
Labels: type: chore

#1299 Improve plugins Node.js versioning
  packages/build/src/core/main.js
  packages/build/src/plugins/spawn.js
  packages/build/tests/core/flags/fixtures/build_command/netlify.toml
  packages/build/tests/core/flags/fixtures/build_image/netlify.toml
  packages/build/tests/core/flags/fixtures/build_image/package.json
  packages/build/tests/core/flags/fixtures/build_image_cache/node_modules/netlify-plugin-test/index.js
  packages/build/tests/core/flags/fixtures/build_image_cache/node_modules/netlify-plugin-test/package.json
  packages/build/tests/core/flags/fixtures/core/functions/test.js
  packages/build/tests/core/flags/fixtures/core/netlify.toml
  packages/build/tests/core/flags/fixtures/local/netlify.toml
  packages/build/tests/core/flags/fixtures/local/plugin.js
  packages/build/tests/core/flags/fixtures/package/netlify.toml
  packages/build/tests/core/flags/fixtures/package/node_modules/netlify-plugin-test/index.js
  packages/build/tests/core/flags/fixtures/package/node_modules/netlify-plugin-test/package.json
  packages/build/tests/core/flags/fixtures/package/package.json
  packages/build/tests/core/flags/snapshots/tests.js.md
  packages/build/tests/core/flags/snapshots/tests.js.snap
  packages/build/tests/core/flags/tests.js
Labels: type: feature

#1304 Improve Node.js version validation
  packages/build/src/error/type.js
  packages/build/src/plugins/node_version.js
  packages/build/src/plugins/spawn.js
  packages/build/tests/plugins/node_version/fixtures/empty/netlify.toml
  packages/build/tests/plugins/node_version/fixtures/engines/netlify.toml
  packages/build/tests/plugins/node_version/fixtures/engines/package.json
  packages/build/tests/plugins/node_version/fixtures/engines/plugin.js
  packages/build/tests/plugins/node_version/fixtures/simple/netlify.toml
  packages/build/tests/plugins/node_version/fixtures/simple/plugin.js
  packages/build/tests/plugins/node_version/snapshots/tests.js.md
  packages/build/tests/plugins/node_version/snapshots/tests.js.snap
  packages/build/tests/plugins/node_version/tests.js
Labels: type: feature

#1305 Fix missing `onInit`
  packages/build/tests/error/plugin_load/fixtures/full/node_modules/netlify-plugin-test/index.js
  packages/build/tests/error/plugin_load/fixtures/partial/node_modules/netlify-plugin-test/index.js
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/install/missing/fixtures/already_installed/.netlify/plugins/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/load/fixtures/basedir/base/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/load/fixtures/build_image_cache/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/load/fixtures/module/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/load/fixtures/ui/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/load/snapshots/tests.js.snap
Labels: type: chore

#1306 Fix `Cannot read property 'replace' of undefined`
  packages/build/src/error/monitor/report.js
Labels: type: bug

#1307 Make local plugin installation an opt-in
  packages/build/src/core/main.js
  packages/build/src/install/local.js
  packages/build/src/log/main.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/main.js
  packages/build/tests/install/local/fixtures/already/netlify.toml
  packages/build/tests/install/local/fixtures/error/netlify.toml
  packages/build/tests/install/local/fixtures/no_package/netlify.toml
  packages/build/tests/install/local/fixtures/no_root_package/netlify.toml
  packages/build/tests/install/local/fixtures/npm_ci_lock/netlify.toml
  packages/build/tests/install/local/fixtures/npm_ci_no_lock/netlify.toml
  packages/build/tests/install/local/fixtures/npm_lock/netlify.toml
  packages/build/tests/install/local/fixtures/yarn_ci_lock/netlify.toml
  packages/build/tests/install/local/fixtures/yarn_lock/netlify.toml
  packages/build/tests/install/local/snapshots/tests.js.md
  packages/build/tests/install/local/snapshots/tests.js.snap
Labels: type: feature

#1311 Improve `util.inspect()` depth when logging error properties
  packages/build/src/error/parse/properties.js
Labels: type: bug

#1313 Fix `build.command` error handling
  packages/build/src/core/commands.js
  packages/build/tests/status/report/fixtures/error_build_command/netlify.toml
  packages/build/tests/status/report/snapshots/tests.js.md
  packages/build/tests/status/report/snapshots/tests.js.snap
  packages/build/tests/status/report/tests.js
Labels: type: bug

#1310 Refactor `plugin.origin`
  packages/config/src/default_config.js
  packages/config/src/normalize/main.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: bug

#1308 Improve logs when automatically installing plugins
  packages/build/src/log/main.js
  packages/build/tests/install/missing/snapshots/tests.js.md
  packages/build/tests/install/missing/snapshots/tests.js.snap
Labels: type: feature

#1309 Temporarily disable warning on automatic plugin installation
  packages/build/src/plugins/resolve.js
  packages/build/tests/install/missing/snapshots/tests.js.md
  packages/build/tests/install/missing/snapshots/tests.js.snap
Labels: type: chore

#1314 Rename `Name` to `Package` in build logs
  packages/build/src/error/parse/plugin.js
  packages/build/tests/core/build_command/snapshots/tests.js.snap
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/core/config/snapshots/tests.js.snap
  packages/build/tests/core/dry/snapshots/tests.js.snap
  packages/build/tests/core/flags/snapshots/tests.js.snap
  packages/build/tests/env/git/snapshots/tests.js.snap
  packages/build/tests/env/main/snapshots/tests.js.snap
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/install/local/snapshots/tests.js.md
  packages/build/tests/install/local/snapshots/tests.js.snap
  packages/build/tests/manifest/check/snapshots/tests.js.md
  packages/build/tests/manifest/check/snapshots/tests.js.snap
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.snap
  packages/build/tests/manifest/validate/snapshots/tests.js.md
  packages/build/tests/manifest/validate/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.md
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/handlers/snapshots/tests.js.md
  packages/build/tests/plugins/handlers/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/node_version/snapshots/tests.js.snap
  packages/build/tests/plugins/run/snapshots/tests.js.md
  packages/build/tests/plugins/run/snapshots/tests.js.snap
  packages/build/tests/plugins/utils/snapshots/tests.js.md
  packages/build/tests/plugins/utils/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.md
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/status/add/snapshots/tests.js.md
  packages/build/tests/status/add/snapshots/tests.js.snap
  packages/build/tests/status/report/snapshots/tests.js.md
  packages/build/tests/status/report/snapshots/tests.js.snap
  packages/build/tests/status/utils/snapshots/tests.js.md
  packages/build/tests/status/utils/snapshots/tests.js.snap
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature

#1315 Fix `resolve`
  packages/build/src/plugins/resolve.js
  packages/build/src/utils/resolve.js
Labels: type: bug

#1318 Report `BUILD_ID` to Bugsnag
  packages/build/src/error/monitor/report.js
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/error/monitor/tests.js
Labels: type: feature

#1319 Send plugin homepage to Bugsnag
  packages/build/src/error/monitor/print.js
  packages/build/src/error/monitor/report.js
  packages/build/src/error/parse/plugin.js
  packages/build/tests/error/monitor/fixtures/plugin_homepage/netlify.toml
  packages/build/tests/error/monitor/fixtures/plugin_homepage/package.json
  packages/build/tests/error/monitor/fixtures/plugin_homepage/plugin.js
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/error/monitor/tests.js
Labels: type: feature

#1320 Improve how plugins origin is reported and logged
  packages/build/src/core/commands.js
  packages/build/src/error/parse/location.js
  packages/build/src/log/description.js
  packages/build/src/log/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/check.js
  packages/build/src/plugins/manifest/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/options.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/monitor/fixtures/plugin_origin/netlify.toml
  packages/build/tests/error/monitor/fixtures/plugin_origin/plugin.js
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/error/monitor/tests.js
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/install/local/snapshots/tests.js.md
  packages/build/tests/install/local/snapshots/tests.js.snap
  packages/build/tests/manifest/check/snapshots/tests.js.md
  packages/build/tests/manifest/check/snapshots/tests.js.snap
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.snap
  packages/build/tests/manifest/validate/snapshots/tests.js.md
  packages/build/tests/manifest/validate/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.md
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/handlers/snapshots/tests.js.md
  packages/build/tests/plugins/handlers/snapshots/tests.js.snap
  packages/build/tests/plugins/run/snapshots/tests.js.md
  packages/build/tests/plugins/run/snapshots/tests.js.snap
  packages/build/tests/plugins/utils/snapshots/tests.js.md
  packages/build/tests/plugins/utils/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.md
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/status/add/snapshots/tests.js.md
  packages/build/tests/status/add/snapshots/tests.js.snap
  packages/build/tests/status/report/snapshots/tests.js.md
  packages/build/tests/status/report/snapshots/tests.js.snap
  packages/build/tests/status/utils/snapshots/tests.js.md
  packages/build/tests/status/utils/snapshots/tests.js.snap
Labels: type: feature

#1321 Fix test fixture using `onInit()`
  packages/build/tests/error/monitor/fixtures/plugin_homepage/plugin.js
Labels: type: chore

#1322 Print configuration on build errors
  packages/build/src/core/commands.js
  packages/build/src/core/main.js
  packages/build/src/error/parse/parse.js
  packages/build/src/error/parse/serialize_log.js
  packages/build/src/log/main.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/install/local/snapshots/tests.js.md
  packages/build/tests/install/local/snapshots/tests.js.snap
  packages/build/tests/log/old_version/snapshots/tests.js.md
  packages/build/tests/log/old_version/snapshots/tests.js.snap
  packages/build/tests/manifest/check/snapshots/tests.js.md
  packages/build/tests/manifest/check/snapshots/tests.js.snap
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.snap
  packages/build/tests/manifest/validate/snapshots/tests.js.md
  packages/build/tests/manifest/validate/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.md
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/handlers/snapshots/tests.js.md
  packages/build/tests/plugins/handlers/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/node_version/snapshots/tests.js.md
  packages/build/tests/plugins/node_version/snapshots/tests.js.snap
  packages/build/tests/plugins/run/snapshots/tests.js.md
  packages/build/tests/plugins/run/snapshots/tests.js.snap
  packages/build/tests/plugins/utils/snapshots/tests.js.md
  packages/build/tests/plugins/utils/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.md
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/status/add/snapshots/tests.js.md
  packages/build/tests/status/add/snapshots/tests.js.snap
  packages/build/tests/status/report/snapshots/tests.js.md
  packages/build/tests/status/report/snapshots/tests.js.snap
  packages/build/tests/status/utils/snapshots/tests.js.md
  packages/build/tests/status/utils/snapshots/tests.js.snap
Labels: type: feature

#1323 Improve reporting of plugins `package.json`
  packages/build/src/error/monitor/print.js
  packages/build/src/error/monitor/report.js
  packages/build/src/error/parse/plugin.js
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
Labels: type: feature

#1326 Send some metadata for debugging
  packages/build/src/core/main.js
  packages/build/src/env/metadata.js
  packages/build/src/error/monitor/print.js
  packages/build/src/error/monitor/report.js
  packages/build/src/error/parse/parse.js
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
Labels: type: feature

#1327 Rename `config` variable to `netlifyConfig`
  packages/build/src/log/main.js
Labels: type: chore

#1332 Fix `canceled_build` typo
  packages/build/src/error/type.js
  packages/build/tests/status/report/snapshots/tests.js.md
  packages/build/tests/status/report/snapshots/tests.js.snap
Labels: type: bug

#1346 Remove `plugins[*].type`
  packages/config/src/normalize/main.js
  packages/config/src/validate/validations.js
  packages/config/tests/normalize/fixtures/type/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: chore

#1349 Remove `plugins[*].id`
  packages/config/src/validate/validations.js
  packages/config/tests/validate/fixtures/plugins_id_compat/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: chore

#1348 Remove `plugins[*].enabled`
  packages/config/src/validate/validations.js
  packages/config/tests/validate/fixtures/plugins_enabled/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: chore

#1347 Remove `plugins[*].config`
  packages/config/src/normalize/main.js
  packages/config/src/validate/validations.js
  packages/config/tests/normalize/fixtures/config/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: chore

#1345 Remove `build.lifecycle`
  packages/config/src/main.js
  packages/config/src/normalize.js
  packages/config/src/normalize/lifecycle.js
  packages/config/src/validate/validations.js
  packages/config/tests/normalize/fixtures/command_lifecycle/netlify.toml
  packages/config/tests/normalize/fixtures/lifecycle/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: chore

#1344 Remove `netlify.yml`
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/main.js
  packages/config/src/parse.js
  packages/config/src/parse/parsers.js
  packages/config/src/path.js
  packages/config/tests/load/fixtures/several/netlify.toml
  packages/config/tests/load/fixtures/several/netlify.yaml
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
  packages/config/tests/parse/fixtures/advanced_yaml/netlify.yml
  packages/config/tests/parse/fixtures/invalid/netlify.invalid
  packages/config/tests/parse/fixtures/json/netlify.json
  packages/config/tests/parse/fixtures/non_convertible_yaml/netlify.yml
  packages/config/tests/parse/fixtures/yaml/netlify.yaml
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/parse/tests.js
  packages/config/tests/validate/fixtures/colors/netlify.yml
  packages/config/tests/validate/tests.js
Labels: type: chore

#1340 Remove deprecated `fail()` and `cancel()`
  packages/build/src/plugins/child/utils.js
  packages/build/src/plugins/error.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
Labels: type: chore

#1341 Remove plugin properties `name`, `config` and `inputs`
  packages/build/src/plugins/child/validate.js
  packages/build/src/plugins/error.js
  packages/build/tests/plugins/validate/fixtures/backward_compat_config/netlify.toml
  packages/build/tests/plugins/validate/fixtures/backward_compat_config/plugin.js
  packages/build/tests/plugins/validate/fixtures/backward_compat_inputs/netlify.toml
  packages/build/tests/plugins/validate/fixtures/backward_compat_inputs/plugin.js
  packages/build/tests/plugins/validate/fixtures/backward_compat_name/netlify.toml
  packages/build/tests/plugins/validate/fixtures/backward_compat_name/plugin.js
  packages/build/tests/plugins/validate/snapshots/tests.js.md
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/tests.js
Labels: type: chore

#1338 Remove `pluginConfig` and `config`
  packages/build/src/core/constants.js
  packages/build/src/plugins/child/run.js
  packages/build/tests/plugins/constants/fixtures/build_dir/plugin.js
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/tests.js
  packages/build/tests/plugins/run/fixtures/inputs_plugin_config/netlify.toml
  packages/build/tests/plugins/run/fixtures/inputs_plugin_config/plugin.js
  packages/build/tests/plugins/run/snapshots/tests.js.md
  packages/build/tests/plugins/run/snapshots/tests.js.snap
  packages/build/tests/plugins/run/tests.js
Labels: type: chore

#1339 Remove deprecated event handlers
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/normalize.js
  packages/build/src/plugins/child/validate.js
  packages/build/src/plugins/events.js
  packages/build/tests/plugins/normalize/snapshots/tests.js.md
  packages/build/tests/plugins/normalize/snapshots/tests.js.snap
Labels: type: chore

#1337 Add stack to plugin validation errors
  packages/build/src/error/type.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.snap
  packages/build/tests/manifest/validate/snapshots/tests.js.md
  packages/build/tests/manifest/validate/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/normalize/snapshots/tests.js.md
  packages/build/tests/plugins/normalize/snapshots/tests.js.snap
  packages/build/tests/plugins/run/snapshots/tests.js.md
  packages/build/tests/plugins/run/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.md
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/status/report/snapshots/tests.js.md
  packages/build/tests/status/report/snapshots/tests.js.snap
  packages/build/tests/status/utils/snapshots/tests.js.md
  packages/build/tests/status/utils/snapshots/tests.js.snap
Labels: type: feature

#1351 Make Functions automatic install an opt-in
  packages/build/src/install/functions.js
  packages/build/src/log/main.js
  packages/build/tests/install/functions/snapshots/tests.js.md
  packages/build/tests/install/functions/snapshots/tests.js.snap
  packages/build/tests/install/functions/tests.js
Labels: type: chore

#1350 Make local plugin automatic installations an opt-in
  packages/build/src/install/local.js
  packages/build/src/log/main.js
  packages/build/tests/install/local/fixtures/missing/netlify.toml
  packages/build/tests/install/local/fixtures/missing/plugin/main.js
  packages/build/tests/install/local/fixtures/missing/plugin/node_modules/math-avg/index.js
  packages/build/tests/install/local/fixtures/missing/plugin/node_modules/math-avg/license
  packages/build/tests/install/local/fixtures/missing/plugin/node_modules/math-avg/package.json
  packages/build/tests/install/local/fixtures/missing/plugin/node_modules/math-avg/readme.md
  packages/build/tests/install/local/fixtures/missing/plugin/package-lock.json
  packages/build/tests/install/local/fixtures/missing/plugin/package.json
  packages/build/tests/install/local/snapshots/tests.js.md
  packages/build/tests/install/local/snapshots/tests.js.snap
  packages/build/tests/install/local/tests.js
Labels: type: chore

#1342 Add test for plugin `inputs`
  packages/build/tests/plugins/run/fixtures/inputs/manifest.yml
  packages/build/tests/plugins/run/fixtures/inputs/netlify.toml
  packages/build/tests/plugins/run/fixtures/inputs/plugin.js
  packages/build/tests/plugins/run/snapshots/tests.js.md
  packages/build/tests/plugins/run/snapshots/tests.js.snap
  packages/build/tests/plugins/run/tests.js
Labels: test, type: chore

#1335 Improve logging of `cancelBuild()`
  packages/build/src/error/cancel.js
  packages/build/src/log/main.js
Labels: type: feature

#1334 Fix error normalization
  packages/build/src/error/parse/parse.js
Labels: type: bug

#1328 Do not report plugin `package.json` twice on build errors
  packages/build/src/error/monitor/report.js
Labels: type: bug

#1354 Do not print resolved config in logs when build is canceled
  packages/build/src/log/main.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/plugins/handlers/snapshots/tests.js.md
  packages/build/tests/plugins/handlers/snapshots/tests.js.snap
  packages/build/tests/status/report/snapshots/tests.js.md
  packages/build/tests/status/report/snapshots/tests.js.snap
Labels: type: bug

#1355 Simplify code related to error logging
  packages/build/src/core/commands.js
  packages/build/src/log/main.js
Labels: type: chore

#1261 Add documentation for `utils.status.show()`
  README.md
Labels: documentation, type: feature

#1329 Improve documentation of local plugins
  README.md
Labels: documentation, type: feature

#1330 Improve documentation of constants
  README.md
Labels: documentation, type: feature

#1357 Add documentation about utilities
  README.md
Labels: documentation, type: feature

#1358 Add more documentation about the `netlify build` CLI command
  README.md
Labels: documentation, type: feature

#1359 Improve the speed of local plugin automatic installation
  packages/build/src/install/local.js
Labels: type: feature

#1356 Improve API error handling
  packages/build/src/core/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/options.js
  packages/build/src/status/report.js
  packages/build/tests/status/helpers/run.js
  packages/build/tests/status/report/fixtures/simple/manifest.yml
  packages/build/tests/status/report/fixtures/simple/netlify.toml
  packages/build/tests/status/report/fixtures/simple/plugin.js
  packages/build/tests/status/report/snapshots/tests.js.md
  packages/build/tests/status/report/snapshots/tests.js.snap
  packages/build/tests/status/report/tests.js
Labels: type: bug

#1360 Refactor `@netlify/config` validation
  packages/config/src/default_config.js
  packages/config/src/main.js
  packages/config/src/validate/context.js
  packages/config/src/validate/main.js
  packages/config/src/validate/validations.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: chore

#1364 Add `constants.NETLIFY_BUILD_VERSION`
  README.md
  packages/build/src/core/constants.js
  packages/build/tests/plugins/constants/fixtures/netlify_build_version/manifest.yml
  packages/build/tests/plugins/constants/fixtures/netlify_build_version/netlify.toml
  packages/build/tests/plugins/constants/fixtures/netlify_build_version/plugin.js
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/tests.js
Labels: type: feature

#1361 Improve documentation of `utils`
  README.md
Labels: documentation, type: feature

#1365 Refactor `@netlify/config` validation
  packages/config/src/main.js
  packages/config/src/validate/main.js
  packages/config/src/validate/validations.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: chore

#1367 Do not log environment variables when builds fail
  packages/build/src/log/main.js
  packages/build/tests/error/log/fixtures/log_secret/manifest.yml
  packages/build/tests/error/log/fixtures/log_secret/netlify.toml
  packages/build/tests/error/log/fixtures/log_secret/plugin.js
  packages/build/tests/error/log/snapshots/tests.js.md
  packages/build/tests/error/log/snapshots/tests.js.snap
  packages/build/tests/error/log/tests.js
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.snap
Labels: type: security

#1368 Allow capitalized configuration properties
  packages/config/src/normalize.js
  packages/config/tests/normalize/fixtures/props_case/base/.gitkeep
  packages/config/tests/normalize/fixtures/props_case/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
Labels: type: bug

#1352 Finish removing `plugins[*].type`
  packages/config/src/validate/validations.js
Labels: type: chore

#1371 Fix typo in `utils.status.show()`
  README.md
Labels: documentation, type: bug

#1370 Add default value for `packages[*].inputs`
  packages/build/src/log/main.js
  packages/build/src/plugins/options.js
  packages/build/tests/cache/main/snapshots/tests.js.md
  packages/build/tests/cache/main/snapshots/tests.js.snap
  packages/build/tests/core/dry/snapshots/tests.js.md
  packages/build/tests/core/dry/snapshots/tests.js.snap
  packages/build/tests/core/flags/snapshots/tests.js.md
  packages/build/tests/core/flags/snapshots/tests.js.snap
  packages/build/tests/env/git/snapshots/tests.js.md
  packages/build/tests/env/git/snapshots/tests.js.snap
  packages/build/tests/env/main/snapshots/tests.js.md
  packages/build/tests/env/main/snapshots/tests.js.snap
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/monitor/snapshots/tests.js.md
  packages/build/tests/error/monitor/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/install/functions/snapshots/tests.js.md
  packages/build/tests/install/functions/snapshots/tests.js.snap
  packages/build/tests/install/local/snapshots/tests.js.md
  packages/build/tests/install/local/snapshots/tests.js.snap
  packages/build/tests/install/missing/snapshots/tests.js.md
  packages/build/tests/install/missing/snapshots/tests.js.snap
  packages/build/tests/manifest/check/snapshots/tests.js.md
  packages/build/tests/manifest/check/snapshots/tests.js.snap
  packages/build/tests/manifest/validate/snapshots/tests.js.md
  packages/build/tests/manifest/validate/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.md
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/handlers/snapshots/tests.js.md
  packages/build/tests/plugins/handlers/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/node_version/snapshots/tests.js.md
  packages/build/tests/plugins/node_version/snapshots/tests.js.snap
  packages/build/tests/plugins/normalize/snapshots/tests.js.md
  packages/build/tests/plugins/normalize/snapshots/tests.js.snap
  packages/build/tests/plugins/run/snapshots/tests.js.md
  packages/build/tests/plugins/run/snapshots/tests.js.snap
  packages/build/tests/plugins/utils/snapshots/tests.js.md
  packages/build/tests/plugins/utils/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.md
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/status/add/snapshots/tests.js.md
  packages/build/tests/status/add/snapshots/tests.js.snap
  packages/build/tests/status/report/snapshots/tests.js.md
  packages/build/tests/status/report/snapshots/tests.js.snap
  packages/build/tests/status/utils/snapshots/tests.js.md
  packages/build/tests/status/utils/snapshots/tests.js.snap
  packages/config/src/normalize.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: chore

#1372 Remove error related to Functions automatic install
  packages/build/src/install/functions.js
  packages/build/src/plugins/options.js
  packages/build/tests/install/functions/fixtures/warning/functions/package-lock.json
  packages/build/tests/install/functions/fixtures/warning/functions/package.json
  packages/build/tests/install/functions/fixtures/warning/functions/test.js
  packages/build/tests/install/functions/fixtures/warning/netlify.toml
  packages/build/tests/install/functions/snapshots/tests.js.md
  packages/build/tests/install/functions/snapshots/tests.js.snap
  packages/build/tests/install/functions/tests.js
Labels: type: bug

#1374 Fix optional automatic Functions install
  packages/build/src/plugins_core/main.js
  packages/build/tests/core/dry/snapshots/tests.js.md
  packages/build/tests/core/dry/snapshots/tests.js.snap
  packages/build/tests/core/flags/snapshots/tests.js.md
  packages/build/tests/core/flags/snapshots/tests.js.snap
  packages/build/tests/install/functions/fixtures/optional/functions/package-lock.json
  packages/build/tests/install/functions/fixtures/optional/functions/package.json
  packages/build/tests/install/functions/fixtures/optional/functions/test.js
  packages/build/tests/install/functions/fixtures/optional/netlify.toml
  packages/build/tests/install/functions/snapshots/tests.js.md
  packages/build/tests/install/functions/snapshots/tests.js.snap
  packages/build/tests/install/functions/tests.js
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/snapshots/tests.js.md
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/utils/snapshots/tests.js.md
  packages/build/tests/plugins/utils/snapshots/tests.js.snap
Labels: type: bug

#1375 we're stable now! 🔥
  README.md
Labels: documentation, type: chore

#1377 Fix loading local plugins directories
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/load/fixtures/local_dir/netlify.toml
  packages/build/tests/plugins/load/fixtures/local_dir/plugin/index.js
  packages/build/tests/plugins/load/fixtures/local_dir/plugin/manifest.yml
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/load/tests.js
Labels: type: bug

#1380 Refactor `plugin.origin`
  packages/config/src/default_config.js
  packages/config/src/normalize.js
Labels: type: chore

#1381 Fix wrong usage of `process.exit()`
  packages/build/src/core/bin.js
  packages/config/src/bin/main.js
  packages/config/tests/cli/fixtures/big/.gitkeep
  packages/config/tests/cli/tests.js
Labels: type: bug

#1382 Fix plugins merging
  packages/config/src/default_config.js
  packages/config/tests/load/fixtures/plugins_merge/netlify.toml
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
Labels: type: bug

#1376 Improve `functions` property validation
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/plugins_core/functions/plugin.js
  packages/build/tests/plugins/functions/fixtures/regular_file/functions/test.js
  packages/build/tests/plugins/functions/fixtures/regular_file/netlify.toml
  packages/build/tests/plugins/functions/snapshots/tests.js.md
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/tests.js
Labels: type: feature

#1383 Validate duplicate plugins
  packages/config/src/default_config.js
  packages/config/tests/validate/fixtures/plugins_duplicate/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: bug
