Repository netlify/build, pull requests merged in 2020-12, with the labels that each got.

#2084 Improve error message when plugin package is wrong
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/manifest/path.js
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
Labels: type: chore

#2088 Rename `addLatestDependencies()`
  packages/build/src/install/main.js
  packages/build/src/install/missing.js
Labels: type: feature

#2089 Move `logPluginsList()`
  packages/build/src/plugins/list.js
  packages/build/src/plugins/resolve.js
Labels: type: chore

#2090 Move `autoPluginsDir` logic
  packages/build/src/install/missing.js
  packages/build/src/plugins/resolve.js
Labels: type: feature

#2093 Remove dead code related to `plugins.json` fetch
  packages/build/src/log/messages/plugins.js
Labels: type: feature

#2092 Remove `pluginsList` feature flag
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins/list.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2094 Add `tryResolvePath()`
  packages/build/src/plugins/resolve.js
  packages/build/src/utils/resolve.js
Labels: type: feature

#2095 Small refactoring of `loadedFrom` attribute
  packages/build/src/plugins/resolve.js
Labels: type: feature

#2091 Refactor local plugins installation
  packages/build/src/plugins/resolve.js
Labels: type: feature

#2096 Improve comments related to plugins installation
  packages/build/src/install/missing.js
  packages/build/src/log/messages/install.js
  packages/build/src/plugins/resolve.js
Labels: type: feature

#2097 Fix warning related to config-only plugins
  packages/build/src/install/missing.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
Labels: type: feature

#2098 Add `expectedVersion` to plugins
  packages/build/src/install/missing.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2099 Add HTTP request timeout when fetching the plugins list
  packages/build/src/plugins/list.js
Labels: type: feature

#2101 Fix bug with `require.resolve()`
  packages/build/src/utils/resolve.js
Labels: type: bug

#2110 Improve warning logs
  packages/build/src/log/messages/install.js
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
Labels: type: feature

#2109 Fix `resolve` bug
  packages/build/src/utils/resolve.js
Labels: type: bug

#2111 Add support for `manifest.yaml`
  packages/build/src/plugins/manifest/path.js
  packages/build/tests/manifest/fixtures/manifest_yaml/manifest.yaml
  packages/build/tests/manifest/fixtures/manifest_yaml/netlify.toml
  packages/build/tests/manifest/fixtures/manifest_yaml/plugin.js
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/manifest/tests.js
Labels: type: feature

#2102 Improve how plugins are installed
  .gitignore
  packages/build/src/core/feature_flags.js
  packages/build/src/install/main.js
  packages/build/src/install/missing.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/list.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/helpers/normalize.js
  packages/build/tests/plugins/fixtures/invalid_package/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_cache/.netlify/plugins/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/plugins_cache/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/plugins_cache/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/plugins_cache/.netlify/plugins/package.json
  packages/build/tests/plugins/fixtures/plugins_cache/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_cache/package.json
  packages/build/tests/plugins/fixtures/plugins_cache_bin/.netlify/plugins/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/plugins_cache_bin/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/plugins_cache_bin/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/plugins_cache_bin/.netlify/plugins/package.json
  packages/build/tests/plugins/fixtures/plugins_cache_bin/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_cache_bin/package.json
  packages/build/tests/plugins/fixtures/plugins_cache_local/.netlify/plugins/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/plugins_cache_local/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/plugins_cache_local/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/plugins_cache_local/.netlify/plugins/package.json
  packages/build/tests/plugins/fixtures/plugins_cache_local/manifest.yml
  packages/build/tests/plugins/fixtures/plugins_cache_local/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_cache_local/package.json
  packages/build/tests/plugins/fixtures/plugins_cache_local/plugin.js
  packages/build/tests/plugins/fixtures/plugins_cache_outdated/.netlify/plugins-old/node_modules/netlify-plugin-contextual-env-old/index.js
  packages/build/tests/plugins/fixtures/plugins_cache_outdated/.netlify/plugins-old/node_modules/netlify-plugin-contextual-env-old/manifest.yml
  packages/build/tests/plugins/fixtures/plugins_cache_outdated/.netlify/plugins-old/node_modules/netlify-plugin-contextual-env-old/package.json
  packages/build/tests/plugins/fixtures/plugins_cache_outdated/.netlify/plugins-old/package.json
  packages/build/tests/plugins/fixtures/plugins_cache_outdated/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_cache_outdated/package.json
  packages/build/tests/plugins/fixtures/plugins_cache_site_deps/.netlify/plugins/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/plugins_cache_site_deps/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/plugins_cache_site_deps/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/plugins_cache_site_deps/.netlify/plugins/package.json
  packages/build/tests/plugins/fixtures/plugins_cache_site_deps/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_cache_site_deps/package.json
  packages/build/tests/plugins/fixtures/valid_package/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2121 Improve normalization regular expression
  packages/build/tests/helpers/normalize.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: chore

#2119 Fix bug with `.netlify` being a regular file
  packages/build/src/install/missing.js
  packages/build/src/log/messages/install.js
  packages/build/tests/plugins/fixtures/plugins_cache_regular_file/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_cache_regular_file/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: bug

#2115 Remove old unused plugins installation flow
  packages/build/src/core/feature_flags.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/install/missing.js
  packages/build/src/log/messages/config.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/core/fixtures/build_image/netlify.toml
  packages/build/tests/core/fixtures/build_image/package.json
  packages/build/tests/core/fixtures/build_image_cache/node_modules/netlify-plugin-test/index.js
  packages/build/tests/core/fixtures/build_image_cache/node_modules/netlify-plugin-test/manifest.yml
  packages/build/tests/core/fixtures/build_image_cache/node_modules/netlify-plugin-test/package.json
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/install/tests.js
  packages/build/tests/plugins/fixtures/build_image/netlify.toml
  packages/build/tests/plugins/fixtures/build_image/package.json
  packages/build/tests/plugins/fixtures/build_image_bin/netlify.toml
  packages/build/tests/plugins/fixtures/build_image_cache/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/fixtures/build_image_cache/node_modules/netlify-plugin-test/manifest.yml
  packages/build/tests/plugins/fixtures/build_image_cache/node_modules/netlify-plugin-test/package.json
  packages/build/tests/plugins/fixtures/build_image_cache_bin/node_modules/.bin/testbin
  packages/build/tests/plugins/fixtures/build_image_cache_bin/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/fixtures/build_image_cache_bin/node_modules/netlify-plugin-test/manifest.yml
  packages/build/tests/plugins/fixtures/build_image_cache_bin/node_modules/netlify-plugin-test/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: Blocked, type: feature

#2130 Fail on plugins that are neither in `plugins.json` nor `package.json`
  packages/build/src/install/missing.js
  packages/build/src/log/messages/install.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/error/fixtures/dependencies/functions/test.js
  packages/build/tests/error/fixtures/dependencies/netlify.toml
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/helpers/normalize.js
  packages/build/tests/install/fixtures/already_installed/netlify.toml
  packages/build/tests/install/fixtures/empty/.gitkeep
  packages/build/tests/install/fixtures/missing/netlify.toml
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/install/tests.js
  packages/build/tests/plugins/fixtures/module_base/base/netlify.toml
  packages/build/tests/plugins/fixtures/module_base/base/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/fixtures/module_base/base/node_modules/netlify-plugin-test/manifest.yml
  packages/build/tests/plugins/fixtures/module_base/base/node_modules/netlify-plugin-test/package.json
  packages/build/tests/plugins/fixtures/module_base/base/package.json
  packages/build/tests/plugins/fixtures/module_base/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2139 chore: add commit linting
  commitlint.config.js
  package-lock.json
  package.json
Labels: type: chore

#2150 Fix a randomly failing test
  packages/build/tests/error/tests.js
Labels: type: chore
