Repository netlify/build, pull requests merged in 2020-09, with the labels that each got.

#1788 Refactor events filtering
  packages/build/src/commands/get.js
  packages/build/src/commands/run.js
  packages/build/src/core/dry.js
  packages/build/src/status/add.js
Labels: type: feature

#1789 Improve error handling of `onError`, `onSuccess` and `onEnd`
  packages/build/src/commands/error.js
  packages/build/src/commands/get.js
  packages/build/src/commands/run.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/child/utils.js
  packages/build/tests/error/fixtures/cancel_post_deploy/manifest.yml
  packages/build/tests/error/fixtures/cancel_post_deploy/netlify.toml
  packages/build/tests/error/fixtures/cancel_post_deploy/plugin.js
  packages/build/tests/error/fixtures/fail_build_post_deploy/manifest.yml
  packages/build/tests/error/fixtures/fail_build_post_deploy/netlify.toml
  packages/build/tests/error/fixtures/fail_build_post_deploy/plugin.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/error/tests.js
  packages/build/tests/plugins/fixtures/end_fail/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/status/tests.js
Labels: type: feature

#1791 Refactor logging utility
  packages/build/src/log/logger.js
Labels: type: chore

#1792 Print warning when calling `failBuild()` or `cancelBuild()` after deploy
  packages/build/src/log/logger.js
  packages/build/src/log/main.js
  packages/build/src/plugins/child/utils.js
  packages/build/src/plugins/error.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
Labels: type: feature

#1793 Add a feature flag to post-deploy error handling
  packages/build/src/commands/get.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: epic/bp2/on-success, type: feature

#1798 Improve post-deploy warning message
  packages/build/src/log/main.js
Labels: epic/bp2/on-success, type: feature

#1799 Refactor error information parsing
  packages/build/src/error/monitor/report.js
  packages/build/src/error/parse/parse.js
Labels: epic/bp2/on-success, type: feature

#1800 Improve handling of invalid errors
  packages/build/src/error/info.js
Labels: epic/bp2/on-success, type: feature

#1801 Refactor build error parsing
  packages/build/src/commands/error.js
Labels: epic/bp2/on-success, type: feature

#1757 Add edge handlers core plugin
  .eslintrc.json
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/main.js
  packages/build/tests/plugins/fixtures/handlers_custom_dir/custom-edge-handlers/test.js
  packages/build/tests/plugins/fixtures/handlers_custom_dir/netlify.toml
  packages/build/tests/plugins/fixtures/handlers_simple/edge-handlers/data.json
  packages/build/tests/plugins/fixtures/handlers_simple/edge-handlers/test.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: project:edge-handlers-support, type: feature

#1797 Improve core plugins execution order
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/functions/plugin.js
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: epic/bp2/on-success, type: feature

#1802 Improve error information parsing
  packages/build/src/commands/error.js
  packages/build/src/error/parse/parse.js
  packages/build/src/error/parse/serialize_log.js
  packages/build/src/error/parse/serialize_status.js
  packages/build/src/log/main.js
  packages/build/src/status/add.js
Labels: epic/bp2/on-success, type: feature

#1803 Add `error.severity: none`
  packages/build/src/error/cancel.js
  packages/build/src/error/monitor/report.js
  packages/build/src/error/parse/parse.js
  packages/build/src/error/parse/serialize_log.js
  packages/build/src/error/parse/stack.js
  packages/build/src/error/type.js
  packages/build/src/log/main.js
Labels: epic/bp2/on-success, type: feature

#1804 Add more exit codes
  packages/build/src/core/bin.js
  packages/build/src/core/main.js
  packages/build/src/error/handle.js
  packages/build/tests/core/fixtures/cancel/manifest.yml
  packages/build/tests/core/fixtures/cancel/netlify.toml
  packages/build/tests/core/fixtures/cancel/plugin.js
  packages/build/tests/core/fixtures/plugin_error/manifest.yml
  packages/build/tests/core/fixtures/plugin_error/netlify.toml
  packages/build/tests/core/fixtures/plugin_error/plugin.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/helpers/common.js
Labels: epic/bp2/on-success, type: feature

#1812 Add `yargs` to `renovate.json5`
  renovate.json5
Labels: type: chore

#1813 Fix wrong programmatic `success` return value
  packages/build/src/core/bin.js
  packages/build/src/core/main.js
  packages/build/src/core/severity.js
  packages/build/tests/core/tests.js
  packages/build/tests/helpers/main.js
Labels: type: bug

#1814 Fix exit code of build cancellation
  packages/build/src/core/main.js
  packages/build/src/core/severity.js
  packages/build/src/error/type.js
  packages/build/tests/core/tests.js
Labels: type: feature

#1820 Fix `token` returned by `@netlify/config`
  packages/config/src/main.js
  packages/config/tests/load/tests.js
Labels: project:edge-handlers-support, type: bug

#1823 Add `--feature-flags` CLI flag
  packages/build/src/core/bin.js
  packages/build/src/core/feature_flags.js
  packages/build/src/core/flags.js
  packages/build/src/log/main.js
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: type: feature

#1828 Add `build.edge_handlers` configuration property
  packages/config/README.md
  packages/config/src/case.js
  packages/config/src/files.js
  packages/config/src/log/cleanup.js
  packages/config/src/options/base.js
  packages/config/src/validate/validations.js
  packages/config/tests/base/fixtures/prop_config/base/netlify.toml
  packages/config/tests/base/fixtures/prop_config/netlify.toml
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/base/tests.js
  packages/config/tests/normalize/fixtures/props_case/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/validate/fixtures/build_edge_handlers_parent/netlify.toml
  packages/config/tests/validate/fixtures/build_edge_handlers_string/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: project:edge-handlers-support, type: feature

#1829 Add `constants.EDGE_HANDLERS_SRC`
  packages/build/src/core/constants.js
  packages/build/src/plugins_core/main.js
  packages/build/tests/plugins/fixtures/edge_handlers_src_default/edge-handlers/.gitkeep
  packages/build/tests/plugins/fixtures/edge_handlers_src_default/manifest.yml
  packages/build/tests/plugins/fixtures/edge_handlers_src_default/netlify.toml
  packages/build/tests/plugins/fixtures/edge_handlers_src_default/plugin.js
  packages/build/tests/plugins/fixtures/edge_handlers_src_missing/manifest.yml
  packages/build/tests/plugins/fixtures/edge_handlers_src_missing/netlify.toml
  packages/build/tests/plugins/fixtures/edge_handlers_src_missing/plugin.js
  packages/build/tests/plugins/fixtures/edge_handlers_src_relative/custom-edge-handlers/.gitkeep
  packages/build/tests/plugins/fixtures/edge_handlers_src_relative/manifest.yml
  packages/build/tests/plugins/fixtures/edge_handlers_src_relative/netlify.toml
  packages/build/tests/plugins/fixtures/edge_handlers_src_relative/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: project:edge-handlers-support, type: feature

#1827 Fix `npm install` errors severity
  packages/build/src/error/type.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
Labels: type: bug

#1825 Improve logging when Netlify Functions directory is invalid
  packages/build/src/plugins_core/functions/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: bug

#1826 Improve core plugins error handling
  packages/build/src/commands/error.js
  packages/build/src/commands/plugin.js
  packages/build/src/error/type.js
  packages/build/tests/install/snapshots/tests.js.snap
Labels: epic/bp2/on-success, type: feature

#1824 Add `postDeployErrors` feature flag
  packages/build/src/commands/error.js
  packages/build/src/commands/get.js
  packages/build/src/commands/run.js
  packages/build/src/core/feature_flags.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/child/utils.js
  packages/build/src/plugins/load.js
Labels: epic/bp2/on-success, type: feature

#1839 Add code complexity linting
  .eslintrc.json
  packages/build/src/commands/run.js
  packages/build/src/core/bin.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/core/normalize_flags.js
  packages/build/src/log/main.js
  packages/build/src/plugins/child/status.js
  packages/build/src/plugins/resolve.js
  packages/config/src/main.js
Labels: type: chore

#1840 Split big file into several files
  packages/build/src/commands/return.js
  packages/build/src/commands/run.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/main.js
Labels: type: chore

#1841 Break down big log file
  packages/build/src/commands/build_command.js
  packages/build/src/commands/return.js
  packages/build/src/commands/run_command.js
  packages/build/src/core/config.js
  packages/build/src/core/dry.js
  packages/build/src/core/main.js
  packages/build/src/core/normalize_flags.js
  packages/build/src/error/handle.js
  packages/build/src/install/functions.js
  packages/build/src/install/local.js
  packages/build/src/install/missing.js
  packages/build/src/log/header_func.js
  packages/build/src/log/main.js
  packages/build/src/log/messages/commands.js
  packages/build/src/log/messages/config.js
  packages/build/src/log/messages/core.js
  packages/build/src/log/messages/dry.js
  packages/build/src/log/messages/install.js
  packages/build/src/log/messages/plugins.js
  packages/build/src/log/messages/status.js
  packages/build/src/plugins/error.js
  packages/build/src/plugins/spawn.js
  packages/build/src/plugins_core/functions/plugin.js
  packages/build/src/status/report.js
Labels: type: chore

#1843 Do not include core plugins twice
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/src/plugins_core/functions_install/index.js
  packages/build/src/plugins_core/main.js
  packages/build/tests/plugins/fixtures/functions_twice/functions/.gitkeep
  packages/build/tests/plugins/fixtures/functions_twice/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: project:edge-handlers-support, type: feature

#1844 Fix typo in copy
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: bug

#1845 Fix `constants.EDGE_HANDLERS_SRC` behavior
  packages/build/src/core/constants.js
  packages/build/tests/plugins/fixtures/edge_handlers_src_auto/edge-handlers/.gitkeep
  packages/build/tests/plugins/fixtures/edge_handlers_src_auto/manifest.yml
  packages/build/tests/plugins/fixtures/edge_handlers_src_auto/netlify.toml
  packages/build/tests/plugins/fixtures/edge_handlers_src_auto/plugin.js
  packages/build/tests/plugins/fixtures/edge_handlers_src_missing/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: project:edge-handlers-support, type: feature

#1846 Split a function into smaller functions
  packages/build/src/plugins/child/status.js
Labels: type: chore

#1847 Small refactoring to decrease cyclomatic complexity
  packages/build/src/plugins/resolve.js
Labels: type: chore

#1848 Refactor a function to make it smaller
  packages/config/src/main.js
Labels: type: chore

#1849 Upgrade Edge handlers plugin
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/main.js
  packages/build/tests/plugins/fixtures/handlers_custom_dir/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: project:edge-handlers-support, type: feature

#1850 Remove dead code
  packages/build/src/plugins/child/validate.js
  packages/build/src/plugins/error.js
  packages/build/tests/plugins/fixtures/backward_compat_name/manifest.yml
  packages/build/tests/plugins/fixtures/backward_compat_name/netlify.toml
  packages/build/tests/plugins/fixtures/backward_compat_name/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: chore

#1852 Fix telemetry crash when required programmatically
  packages/build/src/core/normalize_flags.js
  packages/build/tests/core/tests.js
Labels: type: bug

#1851 Simplify telemetry
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/telemetry/complete.js
  packages/build/src/telemetry/track.js
Labels: type: bug

#1854 Try to fix statsd test
  packages/build/tests/time/tests.js
Labels: type: bug

#1855 Fix `yarn` when there is a space in the home directory
  packages/build/src/install/main.js
Labels: type: bug

#1856 Fix Windows support on some tests
  packages/build/tests/helpers/normalize.js
Labels: type: bug

#1857 Add documentation about file paths
  packages/config/docs/file_paths.md
Labels: documentation, type: chore

#1806 Run deploy as an onPostBuild event using a new core plugin
  packages/build/src/core/constants.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/deploy/buildbot_client.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/src/plugins_core/deploy/manifest.yml
  packages/build/src/plugins_core/main.js
Labels: type: feature

#1858 Enable tests for Edge handlers on Windows
  packages/build/tests/plugins/tests.js
Labels: test, type: chore

#1861 Add `--feature-flags=eventsOrder`
  packages/build/src/core/feature_flags.js
  packages/build/src/core/main.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/logic.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: epic/bp2/on-success, type: feature

#1862 Add `require-await` ESLint rule
  .eslintrc.json
  packages/build/src/core/main.js
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/ipc.js
  packages/build/src/plugins/node_version.js
  packages/build/src/plugins/spawn.js
  packages/build/tests/error/fixtures/cancel/plugin.js
  packages/build/tests/error/fixtures/cancel_error_option/plugin.js
  packages/build/tests/error/fixtures/cancel_post_deploy/plugin.js
  packages/build/tests/error/fixtures/exception/plugin.js
  packages/build/tests/error/fixtures/exception_array/plugin.js
  packages/build/tests/error/fixtures/exception_circular/plugin.js
  packages/build/tests/error/fixtures/exception_props/plugin.js
  packages/build/tests/error/fixtures/exception_string/plugin.js
  packages/build/tests/error/fixtures/fail_build/plugin.js
  packages/build/tests/error/fixtures/fail_build_error_option/plugin.js
  packages/build/tests/error/fixtures/fail_build_post_deploy/plugin.js
  packages/build/tests/error/fixtures/plugin_exit/plugin.js
  packages/build/tests/error/fixtures/unhandled_promise/plugin.js
  packages/build/tests/helpers/common.js
  packages/build/tests/plugins/fixtures/cache/plugin.js
  packages/cache-utils/tests/save_restore.js
  packages/functions-utils/tests/helpers/main.js
Labels: type: chore

#1859 Simplify error handling of deploy core plugin
  packages/build/src/plugins_core/deploy/buildbot_client.js
Labels: epic/bp2/on-success, type: feature

#1860 Use `--feature-flags=triggerDeploy`
  packages/build/src/core/feature_flags.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/main.js
Labels: epic/bp2/on-success, type: feature

#1865 Add deploy message
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins_core/deploy/index.js
Labels: epic/bp2/on-success, type: feature

#1870 Fix core deploy event
  packages/build/src/plugins_core/deploy/index.js
Labels: epic/bp2/on-success, type: feature

#1867 Improve error handling when buildbot socket closes
  packages/build/src/plugins_core/deploy/buildbot_client.js
Labels: epic/bp2/on-success, type: feature

#1866 Improve error handling of the buildbot socket
  packages/build/src/plugins_core/deploy/buildbot_client.js
  packages/build/src/utils/errors.js
Labels: epic/bp2/on-success, type: feature

#1868 Add `--testOpts.buildbotServerSocketTimeout` CLI flag
  packages/build/src/core/constants.js
  packages/build/src/core/main.js
  packages/build/src/plugins_core/deploy/buildbot_client.js
  packages/build/src/plugins_core/deploy/index.js
Labels: epic/bp2/on-success, type: feature

#1877 Add `del` to Node 8 dependencies
  renovate.json5
Labels: type: chore

#1869 Add tests for the deploy core plugin
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/tests/helpers/tcp_server.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: epic/bp2/on-success, test, type: feature

#1881 Fix Deploy core plugins on Node <14
  packages/build/src/plugins_core/deploy/buildbot_client.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: epic/bp2/on-success, type: feature

#1882 Fix test failing on Node 8
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: epic/bp2/on-success, type: feature

#1885 Rename some functions
  packages/build/src/commands/get.js
  packages/build/src/commands/run_command.js
  packages/build/src/core/dry.js
  packages/build/src/status/add.js
Labels: epic/bp2/on-success, type: feature

#1884 Improve `onError` semantics
  packages/build/src/commands/run_command.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: epic/bp2/on-success, type: feature

#1883 Add support for `--buildbotServerSocket` on Windows
  packages/build/package.json
  packages/build/src/plugins_core/deploy/buildbot_client.js
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/helpers/normalize.js
  packages/build/tests/helpers/tcp_server.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: project:edge-handlers-support, type: feature

#1886 Fix test titles
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: epic/bp2/on-success, type: feature

#1887 Remove `runCorePluginsLast` feature flag
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/logic.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/options.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: epic/bp2/on-success, type: feature

#1890 Expose `constants.NETLIFY_API_TOKEN`
  packages/build/src/plugins/load.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: epic/bp2/on-success, type: feature

#1889 Print a warning on lingering processes
  packages/build/src/core/lingering.js
  packages/build/src/core/main.js
  packages/build/src/log/messages/core.js
  packages/build/src/log/theme.js
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/fixtures/lingering/forever.js
  packages/build/tests/core/fixtures/lingering/manifest.yml
  packages/build/tests/core/fixtures/lingering/netlify.toml
  packages/build/tests/core/fixtures/lingering/plugin.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/helpers/main.js
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: epic/bp2/on-success, type: feature

#1891 Improve core deploy plugin log message
  packages/build/src/log/messages/plugins.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: epic/bp2/on-success, type: feature

#1892 Move core plugin-specific information
  packages/build/src/commands/plugin.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/load.js
Labels: epic/bp2/on-success, type: feature

#1893 Do not wait for post-processing for most builds
  packages/build/src/commands/get.js
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/main.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins_core/deploy/buildbot_client.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/tests/plugins/fixtures/end/manifest.yml
  packages/build/tests/plugins/fixtures/end/netlify.toml
  packages/build/tests/plugins/fixtures/end/plugin.js
  packages/build/tests/plugins/fixtures/success/manifest.yml
  packages/build/tests/plugins/fixtures/success/netlify.toml
  packages/build/tests/plugins/fixtures/success/plugin.js
  packages/build/tests/plugins/tests.js
Labels: epic/bp2/on-success, type: feature
