Repository netlify/build, pull requests merged in 2020-07, with the labels that each got.

#1602 Fix plugin load error handling
  packages/build/src/core/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/manifest/main.js
  packages/build/src/plugins/options.js
  packages/build/src/status/add.js
  packages/build/src/status/report.js
  packages/build/tests/status/fixtures/error_plugin_load/netlify.toml
  packages/build/tests/status/fixtures/error_plugin_load/one/index.js
  packages/build/tests/status/fixtures/error_plugin_load/one/manifest.yml
  packages/build/tests/status/fixtures/error_plugin_load/two/index.js
  packages/build/tests/status/fixtures/error_plugin_load/two/manifest.yml
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/status/tests.js
Labels: type: bug

#1604 Move some lines of code
  packages/build/src/core/main.js
Labels: type: chore

#1603 Improve JSDoc comments
  packages/build/src/core/bin.js
  packages/build/src/core/main.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
Labels: type: chore

#1605 Move some configuration logic between files
  packages/build/src/core/config.js
  packages/build/src/core/main.js
Labels: type: chore

#1607 Move some lines of code at the start of builds
  packages/build/src/core/main.js
Labels: type: chore

#1610 Move lines of code related to configuration logging
  packages/build/src/core/config.js
Labels: type: chore

#1609 Move some variables
  packages/build/src/core/config.js
  packages/build/src/core/main.js
Labels: type: chore

#1611 Move logic to retrieve `constants`
  packages/build/src/core/config.js
  packages/build/src/core/main.js
Labels: type: chore

#1606 Split a file into two
  packages/build/src/core/config.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
Labels: type: chore

#1612 Move `package.json` retrieval
  packages/build/src/core/commands.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
Labels: type: chore

#1616 Improve error message normalization
  packages/build/src/error/monitor/normalize.js
Labels: type: bug

#1615 Move build error handling logic to its own function
  packages/build/src/core/main.js
Labels: type: chore

#1613 Move one line of code related to CLI warnings
  packages/build/src/core/main.js
Labels: type: chore

#1614 Split a function into two functions
  packages/build/src/core/main.js
Labels: type: chore

#1617 Move a function
  packages/build/src/core/config.js
Labels: type: chore

#1618 Move `cancelBuild` logic
  packages/build/src/core/commands.js
  packages/build/src/core/main.js
  packages/build/src/error/cancel.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
Labels: type: chore

#1626 Add comment on CLI entry point
  packages/build/src/core/bin.js
Labels: type: chore

#1625 Fix `commandsCount` used in analytics
  packages/build/src/core/main.js
Labels: type: bug

#1619 Move `childEnv`-related logic
  packages/build/src/core/commands.js
  packages/build/src/core/main.js
  packages/build/src/error/monitor/report.js
  packages/build/src/error/parse/parse.js
  packages/build/src/status/report.js
Labels: type: chore

#1620 Move `netlifyConfig`-related logic
  packages/build/src/core/main.js
  packages/build/src/error/parse/parse.js
  packages/build/src/error/parse/serialize_log.js
  packages/build/src/log/main.js
Labels: type: chore

#1622 Log build error before reporting it
  packages/build/src/core/main.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
Labels: type: chore

#1624 Move logic related to plugin statuses reporting
  packages/build/src/core/commands.js
  packages/build/src/core/main.js
  packages/build/src/status/add.js
Labels: type: chore

#1621 Move CLI warning on build failures
  packages/build/src/core/commands.js
  packages/build/src/core/main.js
  packages/build/src/log/main.js
  packages/build/src/status/report.js
Labels: type: chore

#1623 Consolidate build error handling
  packages/build/src/core/commands.js
  packages/build/src/core/main.js
  packages/build/src/error/handle.js
  packages/build/src/status/report.js
  packages/build/tests/error/snapshots/tests.js.snap
Labels: type: chore

#1627 Split a big file into smaller files
  packages/build/src/commands/build_command.js
  packages/build/src/commands/error.js
  packages/build/src/commands/get.js
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run.js
  packages/build/src/core/commands.js
  packages/build/src/core/dry.js
  packages/build/src/core/main.js
Labels: type: chore

#1628 Split a test directory into two smaller directories
  packages/build/tests/commands/fixtures/bash/netlify.toml
  packages/build/tests/commands/fixtures/global_bin/netlify.toml
  packages/build/tests/commands/fixtures/invalid_package_json/package.json
  packages/build/tests/commands/fixtures/local_bin/netlify.toml
  packages/build/tests/commands/fixtures/none/.gitkeep
  packages/build/tests/commands/fixtures/pwd/file.js
  packages/build/tests/commands/fixtures/pwd/netlify.toml
  packages/build/tests/commands/fixtures/shell/netlify.toml
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/commands/tests.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: type: chore

#1629 Revert `onSuccess` error handling behavior
  packages/build/src/commands/error.js
  packages/build/src/commands/run.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: chore

#1630 Add documentation about release process
  CONTRIBUTING.md
Labels: type: chore

#1632 Fix tests randomly failing
  packages/build/src/error/monitor/start.js
  packages/build/tests/error/tests.js
Labels: type: chore

#1631 Fix Codecov CI failing
  scripts/coverage.sh
Labels: type: bug

#1637 Remove logos from `README`
  packages/cache-utils/README.md
  packages/functions-utils/README.md
  packages/git-utils/README.md
  packages/run-utils/README.md
Labels: type: chore

#1641 Fix `npm link` shown in local plugin errors
  packages/build/src/error/parse/plugin.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: type: bug

#1644 Upgrade `cpy`
  packages/cache-utils/package-lock.json
  packages/cache-utils/package.json
  packages/functions-utils/package-lock.json
  packages/functions-utils/package.json
Labels: type: chore

#1643 Upgrade `moize`
  packages/git-utils/package-lock.json
  packages/git-utils/package.json
Labels: type: chore

#1642 Upgrade `semver`
  packages/run-utils/package-lock.json
  packages/run-utils/package.json
Labels: type: chore

#1651 Update `renovate.json`
  renovate.json
Labels: type: chore

#1684 Fix linting of lock files with Renovate
  package.json
Labels: type: chore

#1686 --buildbotServerSocket CLI flag
  packages/build/src/core/bin.js
  packages/build/src/core/main.js
Labels: type: feature

#1655 Refactor some test helper
  packages/build/tests/helpers/temp.js
Labels: feat/builds, type: feature

#1654 Refactor duration logging
  packages/build/src/commands/run.js
  packages/build/src/core/main.js
  packages/build/src/log/timer.js
  packages/build/src/telemetry/complete.js
Labels: feat/builds, type: feature

#1682 Improve Renovate configuration
  renovate.json
  renovate.json5
Labels: type: chore

#1678 Downgrade Ava
  packages/cache-utils/package-lock.json
  packages/cache-utils/package.json
Labels: test, type: chore

#1683 Downgrade `pretty-ms`
  packages/build/package-lock.json
  packages/build/package.json
Labels: type: chore

#1688 Add `--timersFile` CLI flag
  packages/build/src/core/bin.js
  packages/build/src/core/main.js
  packages/build/src/time/report.js
  packages/build/tests/helpers/temp.js
  packages/build/tests/time/fixtures/plugin/manifest.yml
  packages/build/tests/time/fixtures/plugin/netlify.toml
  packages/build/tests/time/fixtures/plugin/plugin.js
  packages/build/tests/time/fixtures/simple/netlify.toml
  packages/build/tests/time/tests.js
Labels: feat/builds, type: feature

#1689 Send metrics about plugins and `build.command`
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/commands/run.js
  packages/build/src/core/main.js
  packages/build/src/time/report.js
  packages/build/tests/time/tests.js
Labels: feat/builds, type: feature

#1690 Measure how long plugins take to load
  packages/build/src/core/main.js
  packages/build/tests/time/tests.js
Labels: feat/build-plugins, feat/builds, type: feature

#1638 Update `@netlify/config` `README`
  packages/config/README.md
Labels: type: chore

#1691 Measure how long it takes for plugins processes to start
  packages/build/src/core/main.js
  packages/build/tests/time/tests.js
Labels: feat/build-plugins, feat/builds, type: feature

#1692 Send metrics about plugins options loading
  packages/build/src/core/main.js
  packages/build/tests/time/tests.js
Labels: feat/build-plugins, feat/builds, type: feature

#1694 Measure how long it takes to retrieve config
  packages/build/src/core/main.js
  packages/build/tests/time/tests.js
Labels: feat/builds, type: feature

#1693 Rename `--testOpts.sendStatus` CLI flag to `--sendStatus`
  packages/build/src/core/bin.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/log/main.js
  packages/build/src/status/report.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/status/tests.js
Labels: feat/builds, type: feature

#1698 Add function wrapper to measure duration
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/commands/run.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/spawn.js
  packages/build/src/time/report.js
Labels: feat/builds, type: feature

#1700 Refactor main function
  packages/build/src/commands/error.js
  packages/build/src/core/main.js
  packages/build/src/error/handle.js
  packages/build/src/status/report.js
Labels: feat/builds, type: feature

#1701 Refactor how CLI flags are passed around
  packages/build/src/core/config.js
  packages/build/src/core/main.js
Labels: type: chore

#1703 Fix typo in `functions-utils` `README`
  packages/functions-utils/README.md
Labels: documentation, type: bug

#1702 Improve how the main function is measured
  packages/build/src/core/main.js
  packages/build/src/time/report.js
Labels: feat/builds, type: feature

#1705 Skip a test
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/log/tests.js
Labels: test, type: chore

#1687 Buildbot socket server client
  packages/build/src/buildbot_client/main.js
  packages/build/src/commands/run.js
  packages/build/src/core/main.js
  packages/build/src/error/parse/location.js
  packages/build/src/error/type.js
Labels: type: feature

#1707 Improve builds cancellation error handling
  packages/build/src/error/handle.js
Labels: type: bug

#1704 Refactor duration measuring
  packages/build/src/commands/run.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/spawn.js
  packages/build/src/time/main.js
  packages/build/src/time/measure.js
  packages/build/src/time/report.js
Labels: feat/builds, type: feature

#1708 Fix randomly failing test
  packages/build/src/error/monitor/start.js
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/env/tests.js
Labels: test, type: bug

#1709 Fix `cwd` option of `cache` utility
  packages/cache-utils/src/utils/cwd.js
Labels: type: bug

#1710 Fix caching empty directories
  packages/cache-utils/package-lock.json
  packages/cache-utils/package.json
  packages/cache-utils/src/fs.js
  packages/cache-utils/src/main.js
  packages/cache-utils/tests/save_restore.js
  renovate.json5
Labels: type: bug

#1720 Improve logging of `sendStatus` CLI flag
  packages/build/src/log/main.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: type: chore

#1721 Improve metrics names
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/commands/run.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/spawn.js
  packages/build/src/time/main.js
  packages/build/tests/time/tests.js
Labels: feat/build-plugins, feat/builds, type: feature

#1723 Fix crash during error reporting
  packages/build/src/error/monitor/report.js
  packages/build/src/error/parse/plugin.js
  packages/build/tests/error/fixtures/plugin_homepage_no_repo/manifest.yml
  packages/build/tests/error/fixtures/plugin_homepage_no_repo/netlify.toml
  packages/build/tests/error/fixtures/plugin_homepage_no_repo/package.json
  packages/build/tests/error/fixtures/plugin_homepage_no_repo/plugin.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/error/tests.js
Labels: type: bug

#1724 Fix error handling of invalid errors
  packages/build/src/error/parse/normalize.js
  packages/build/src/error/parse/parse.js
  packages/build/src/plugins/child/error.js
  packages/build/tests/error/fixtures/exception_array/manifest.yml
  packages/build/tests/error/fixtures/exception_array/netlify.toml
  packages/build/tests/error/fixtures/exception_array/plugin.js
  packages/build/tests/error/fixtures/exception_string/manifest.yml
  packages/build/tests/error/fixtures/exception_string/netlify.toml
  packages/build/tests/error/fixtures/exception_string/plugin.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/error/tests.js
Labels: type: bug
