Repository netlify/build, pull requests merged in 2020-03, with the labels that each got.

#865 Update list of plugins
  README.md
  scripts/docs.js
Labels: documentation

#863 Fix default value of `build.publish`
  packages/build/src/plugins/child/constants.js
  packages/config/src/files.js
Labels: bug

#866 Improve error messages in `@netlify/config`
  packages/build/tests/config/parse/snapshots/tests.js.md
  packages/build/tests/config/parse/snapshots/tests.js.snap
  packages/build/tests/config/validate/snapshots/tests.js.md
  packages/build/tests/config/validate/snapshots/tests.js.snap
  packages/config/src/index.js
  packages/config/src/parse/main.js
Labels: enhancement

#864 Fix invalid test
  packages/build/tests/core/telemetry/tests.js
Labels: test

#867 Update test snapshots
  packages/build/tests/config/cwd/snapshots/tests.js.md
  packages/build/tests/config/cwd/snapshots/tests.js.snap
  packages/build/tests/config/load/snapshots/tests.js.md
  packages/build/tests/config/load/snapshots/tests.js.snap
Labels: test

#873 Improve error message in `@netlify/config`
  packages/config/src/index.js
Labels: enhancement

#868 Improve how the configuration file path is retrieved
  packages/build/src/core/config.js
  packages/build/tests/cache/main/snapshots/tests.js.snap
  packages/build/tests/config/load/snapshots/tests.js.md
  packages/build/tests/config/load/snapshots/tests.js.snap
  packages/build/tests/config/normalize/snapshots/tests.js.md
  packages/build/tests/config/normalize/snapshots/tests.js.snap
  packages/build/tests/config/parse/snapshots/tests.js.md
  packages/build/tests/config/parse/snapshots/tests.js.snap
  packages/build/tests/config/validate/snapshots/tests.js.md
  packages/build/tests/config/validate/snapshots/tests.js.snap
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/core/dry/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.snap
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/config/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/env/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/install/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/utils/cache/snapshots/tests.js.snap
  packages/build/tests/utils/git/snapshots/tests.js.snap
  packages/build/tests/utils/load/snapshots/tests.js.snap
  packages/build/tests/utils/run/snapshots/tests.js.snap
  packages/config/src/index.js
  packages/config/src/path.js
Labels: enhancement

#875 Fix `context` default value
  packages/build/src/core/config.js
  packages/config/src/index.js
Labels: enhancement

#874 Validate that `base`, `publish` and `functions` are not outside the repository root directory
  packages/build/tests/config/validate/fixtures/build_base_parent/netlify.yml
  packages/build/tests/config/validate/fixtures/build_base_string/netlify.yml
  packages/build/tests/config/validate/fixtures/build_functions_parent/netlify.yml
  packages/build/tests/config/validate/fixtures/build_publish_parent/netlify.yml
  packages/build/tests/config/validate/snapshots/tests.js.md
  packages/build/tests/config/validate/snapshots/tests.js.snap
  packages/build/tests/config/validate/tests.js
  packages/config/src/validate/helpers.js
  packages/config/src/validate/validations.js
Labels: enhancement

#870 Do not automatically create `publish` and `functions` directories
  packages/build/tests/plugins/constants/fixtures/build_missing/publish/.gitkeep
  packages/build/tests/plugins/constants/fixtures/functions_src_missing/missing/.gitkeep
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/tests.js
  packages/build/tests/plugins/functions/fixtures/missing/missing/.gitkeep
  packages/build/tests/plugins/functions/snapshots/tests.js.md
  packages/build/tests/plugins/functions/tests.js
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/files.js
  packages/config/src/index.js
Labels: enhancement

#871 Add a test when there are no Netlify Functions
  packages/build/tests/plugins/functions/fixtures/none/functions/.gitkeep
  packages/build/tests/plugins/functions/fixtures/none/netlify.yml
  packages/build/tests/plugins/functions/snapshots/tests.js.md
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/tests.js
Labels: test

#872 Add `--repositoryRoot` CLI flag
  packages/build/src/core/bin.js
  packages/build/src/core/config.js
  packages/build/tests/core/cli/snapshots/tests.js.md
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/config/src/index.js
  packages/config/src/options.js
  packages/config/src/utils/remove_falsy.js
Labels: enhancement

#883 Fix tests (`.gitkeep` files)
  packages/build/tests/plugins/constants/fixtures/build_missing/publish/.gitkeep
  packages/build/tests/plugins/constants/fixtures/functions_src_missing/missing/.gitkeep
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/fixtures/missing/missing/.gitkeep
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
Labels: test

#884 Fix test on `plugins.type` backward compatibility fix
  packages/build/tests/config/validate/fixtures/plugins_type_renamed/netlify.yml
  packages/build/tests/config/validate/snapshots/tests.js.md
  packages/build/tests/config/validate/snapshots/tests.js.snap
Labels: test

#879 Remove permissions checks on build directory
  packages/build/tests/config/load/tests.js
  packages/config/src/base_dir.js
  packages/config/src/index.js
Labels: enhancement

#882 Use repository root when locating configuration file
  packages/build/tests/config/load/snapshots/tests.js.md
  packages/build/tests/config/load/snapshots/tests.js.snap
  packages/build/tests/config/load/tests.js
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/index.js
  packages/config/src/path.js
Labels: enhancement

#888 Fix current directory logging
  packages/build/src/core/config.js
  packages/build/src/log/main.js
  packages/build/tests/cache/main/snapshots/tests.js.snap
  packages/build/tests/config/cwd/snapshots/tests.js.snap
  packages/build/tests/config/load/snapshots/tests.js.md
  packages/build/tests/config/load/snapshots/tests.js.snap
  packages/build/tests/config/normalize/snapshots/tests.js.md
  packages/build/tests/config/normalize/snapshots/tests.js.snap
  packages/build/tests/config/parse/snapshots/tests.js.md
  packages/build/tests/config/parse/snapshots/tests.js.snap
  packages/build/tests/config/validate/snapshots/tests.js.md
  packages/build/tests/config/validate/snapshots/tests.js.snap
  packages/build/tests/core/cli/snapshots/tests.js.md
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/core/dry/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.snap
  packages/build/tests/core/telemetry/snapshots/tests.js.snap
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/config/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/env/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/install/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/utils/cache/snapshots/tests.js.snap
  packages/build/tests/utils/git/snapshots/tests.js.snap
  packages/build/tests/utils/load/snapshots/tests.js.snap
  packages/build/tests/utils/run/snapshots/tests.js.snap
Labels: enhancement

#890 Fix paths resolution inside the configuration file
  packages/build/src/core/main.js
  packages/build/src/plugins/options.js
  packages/build/tests/config/cwd/fixtures/build_base_cwd/netlify.yml
Labels: bug

#891 Remove some dead code
  packages/build/tests/config/load/tests.js
Labels: test

#889 Add a test for the `BUILD_DIR` constant
  packages/build/tests/plugins/constants/fixtures/build_default_base/base/.gitkeep
  packages/build/tests/plugins/constants/fixtures/build_default_base/netlify.yml
  packages/build/tests/plugins/constants/fixtures/build_default_base/plugin.js
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/tests.js
Labels: test

#895 Remove some tests
  packages/build/tests/config/load/fixtures/envvar/netlify.yml
  packages/build/tests/config/load/snapshots/tests.js.md
  packages/build/tests/config/load/snapshots/tests.js.snap
  packages/build/tests/config/load/tests.js
Labels: test

#896 Support `context` configuration property
  packages/build/tests/config/context/fixtures/array_merge/netlify.yml
  packages/build/tests/config/context/fixtures/deep_merge/netlify.yml
  packages/build/tests/config/context/fixtures/flag/netlify.yml
  packages/build/tests/config/context/fixtures/syntax_error/netlify.yml
  packages/build/tests/config/context/snapshots/tests.js.md
  packages/build/tests/config/context/snapshots/tests.js.snap
  packages/build/tests/config/context/tests.js
  packages/build/tests/config/validate/snapshots/tests.js.md
  packages/build/tests/config/validate/snapshots/tests.js.snap
  packages/config/src/context.js
  packages/config/src/index.js
Labels: enhancement

#898 Move a test
  packages/build/tests/config/cwd/snapshots/tests.js.md
  packages/build/tests/config/cwd/snapshots/tests.js.snap
  packages/build/tests/config/cwd/tests.js
  packages/build/tests/config/load/snapshots/tests.js.md
  packages/build/tests/config/load/snapshots/tests.js.snap
  packages/build/tests/config/load/tests.js
Labels: test

#897 Add `context` property validation
  packages/build/tests/config/context/snapshots/tests.js.md
  packages/build/tests/config/context/snapshots/tests.js.snap
  packages/build/tests/config/context/tests.js
  packages/build/tests/config/validate/fixtures/build_context_nested_object/netlify.yml
  packages/build/tests/config/validate/fixtures/build_context_nested_property/netlify.yml
  packages/build/tests/config/validate/fixtures/build_context_object/netlify.yml
  packages/build/tests/config/validate/fixtures/build_context_property/netlify.yml
  packages/build/tests/config/validate/snapshots/tests.js.md
  packages/build/tests/config/validate/snapshots/tests.js.snap
  packages/build/tests/config/validate/tests.js
  packages/config/src/index.js
  packages/config/src/validate/context.js
  packages/config/src/validate/example.js
  packages/config/src/validate/validations.js
Labels: enhancement

#899 Add branch-specific `context`
  packages/build/src/core/bin.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/plugins/env.js
  packages/build/src/plugins/git.js
  packages/build/tests/config/context/fixtures/branch/netlify.yml
  packages/build/tests/config/context/fixtures/branch_fallback/netlify.yml
  packages/build/tests/config/context/fixtures/context_flag/netlify.yml
  packages/build/tests/config/context/snapshots/tests.js.md
  packages/build/tests/config/context/snapshots/tests.js.snap
  packages/build/tests/config/context/tests.js
  packages/build/tests/core/cli/snapshots/tests.js.md
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/plugins/env/fixtures/git_branch/netlify.yml
  packages/build/tests/plugins/env/fixtures/git_branch/plugin.js
  packages/build/tests/plugins/env/snapshots/tests.js.md
  packages/build/tests/plugins/env/snapshots/tests.js.snap
  packages/build/tests/plugins/env/tests.js
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/branch.js
  packages/config/src/context.js
  packages/config/src/index.js
  packages/config/src/options.js
  packages/config/src/repository_root.js
Labels: enhancement

#900 Improve description of `--config` CLI flag
  packages/build/src/core/bin.js
  packages/build/tests/core/cli/snapshots/tests.js.md
  packages/build/tests/core/cli/snapshots/tests.js.snap
Labels: enhancement

#902 Add configuration merging logic
  packages/config/src/context.js
  packages/config/src/utils/merge.js
Labels: enhancement

#903 Improve error message when the `--config` CLI flag is invalid
  packages/build/tests/config/load/snapshots/tests.js.md
  packages/build/tests/config/load/snapshots/tests.js.snap
  packages/build/tests/core/cli/snapshots/tests.js.md
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/config/src/parse/main.js
  packages/config/src/path.js
Labels: enhancement

#901 style: update npm branding (NPM => npm)
  README.md
  packages/build/scaffold/install/index.js
  packages/build/scaffold/install/node/install-node.js
  packages/build/scaffold/install/node/run-npm.js
  packages/build/scaffold/install/node/run-yarn.js
  packages/build/src/error/plugin.js
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  scripts/docs.js
Labels: enhancement

#904 Add `--defaultConfig` CLI flag
  packages/build/src/core/bin.js
  packages/build/src/core/config.js
  packages/build/src/log/main.js
  packages/build/tests/config/load/fixtures/default_merge/default.yml
  packages/build/tests/config/load/fixtures/default_merge/netlify.yml
  packages/build/tests/config/load/fixtures/default_priority/default.yml
  packages/build/tests/config/load/fixtures/default_priority/netlify.yml
  packages/build/tests/config/load/snapshots/tests.js.md
  packages/build/tests/config/load/snapshots/tests.js.snap
  packages/build/tests/config/load/tests.js
  packages/config/src/index.js
Labels: enhancement

#905 Add a test to ensure branch contexts have higher priority
  packages/build/tests/config/context/fixtures/priority_merge/netlify.yml
  packages/build/tests/config/context/snapshots/tests.js.md
  packages/build/tests/config/context/snapshots/tests.js.snap
  packages/build/tests/config/context/tests.js
Labels: test

#906 Add `--cachedConfig` CLI flag
  packages/build/src/core/bin.js
  packages/build/src/core/config.js
  packages/build/src/log/main.js
  packages/build/tests/config/load/fixtures/cached_config/netlify.yml
  packages/build/tests/config/load/snapshots/tests.js.md
  packages/build/tests/config/load/snapshots/tests.js.snap
  packages/build/tests/config/load/tests.js
  packages/config/src/index.js
  packages/config/src/options.js
  packages/config/src/validate/context.js
Labels: enhancement

#907 Use `build.base` when loading the configuration file
  packages/build/tests/config/base/fixtures/default_config/base/netlify.yml
  packages/build/tests/config/base/fixtures/default_config/default.yml
  packages/build/tests/config/base/fixtures/default_config/netlify.yml
  packages/build/tests/config/base/fixtures/prop_config/base/netlify.yml
  packages/build/tests/config/base/fixtures/prop_config/netlify.yml
  packages/build/tests/config/base/fixtures/recursive/base/netlify.yml
  packages/build/tests/config/base/fixtures/recursive/base/plugin.js
  packages/build/tests/config/base/fixtures/recursive/base/second_base/netlify.yml
  packages/build/tests/config/base/fixtures/recursive/netlify.yml
  packages/build/tests/config/base/snapshots/tests.js.md
  packages/build/tests/config/base/snapshots/tests.js.snap
  packages/build/tests/config/base/tests.js
  packages/config/src/index.js
  packages/config/src/path.js
Labels: enhancement

#909 Add CLI
  packages/build/tests/config/cli/fixtures/empty/netlify.yml
  packages/build/tests/config/cli/snapshots/tests.js.md
  packages/build/tests/config/cli/snapshots/tests.js.snap
  packages/build/tests/config/cli/tests.js
  packages/build/tests/helpers/main.js
  packages/build/tests/helpers/normalize.js
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/bin/flags.js
  packages/config/src/bin/main.js
  packages/config/src/error.js
  packages/config/src/main.js
  packages/config/src/utils/polyfills.js
  packages/config/src/validate/context.js
Labels: enhancement

#911 Make `--config` CLI flag optional
  packages/build/src/core/config.js
  packages/build/tests/config/load/tests.js
  packages/config/src/bin/main.js
  packages/config/src/main.js
  packages/config/src/path.js
Labels: enhancement

#912 Add support for `build.environment` in local builds
  packages/build/src/core/main.js
  packages/build/src/plugins/env.js
  packages/build/tests/config/cli/snapshots/tests.js.md
  packages/build/tests/config/cli/snapshots/tests.js.snap
  packages/build/tests/plugins/env/fixtures/build/netlify.yml
  packages/build/tests/plugins/env/fixtures/build/plugin.js
  packages/build/tests/plugins/env/fixtures/build_readonly/netlify.yml
  packages/build/tests/plugins/env/fixtures/build_readonly/plugin.js
  packages/build/tests/plugins/env/snapshots/tests.js.md
  packages/build/tests/plugins/env/snapshots/tests.js.snap
  packages/build/tests/plugins/env/tests.js
  packages/build/tests/utils/cache/tests.js
  packages/config/src/normalize/main.js
Labels: enhancement

#910 Move some code around
  packages/build/tests/config/context/tests.js
  packages/build/tests/config/load/tests.js
  packages/build/tests/core/flags/tests.js
  packages/build/tests/helpers/dir.js
  packages/build/tests/helpers/main.js
  packages/build/tests/helpers/temp.js
  packages/build/tests/plugins/env/tests.js
  packages/build/tests/plugins/functions/tests.js
  packages/build/tests/plugins/install/tests.js
  packages/build/tests/plugins/load/tests.js
  packages/build/tests/utils/cache/tests.js
  packages/build/tests/utils/git/tests.js
Labels: test

#913 document that `run` is a thin wrapper
  packages/run-utils/README.md
Labels: documentation

#914 Fix CLI flags logging in local builds
  packages/build/src/log/main.js
  packages/build/tests/config/base/snapshots/tests.js.md
  packages/build/tests/config/base/snapshots/tests.js.snap
  packages/build/tests/config/context/snapshots/tests.js.md
  packages/build/tests/config/context/snapshots/tests.js.snap
  packages/build/tests/config/cwd/snapshots/tests.js.snap
  packages/build/tests/config/load/snapshots/tests.js.md
  packages/build/tests/config/load/snapshots/tests.js.snap
  packages/build/tests/config/normalize/snapshots/tests.js.snap
  packages/build/tests/config/parse/snapshots/tests.js.snap
  packages/build/tests/config/validate/snapshots/tests.js.md
  packages/build/tests/config/validate/snapshots/tests.js.snap
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/core/dry/snapshots/tests.js.snap
  packages/build/tests/core/flags/snapshots/tests.js.md
  packages/build/tests/core/flags/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.snap
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/config/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/duplicate/snapshots/tests.js.snap
  packages/build/tests/plugins/env/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/install/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/utils/cache/snapshots/tests.js.md
  packages/build/tests/utils/cache/snapshots/tests.js.snap
  packages/build/tests/utils/git/snapshots/tests.js.snap
  packages/build/tests/utils/load/snapshots/tests.js.snap
  packages/build/tests/utils/run/snapshots/tests.js.snap
  packages/run-utils/README.md
Labels: enhancement

#915 Fix missing newline after CLI flags logging
  packages/build/src/log/main.js
Labels: bug

#916 Improve `--cachedConfig` CLI flag
  packages/build/src/core/bin.js
  packages/build/tests/config/load/snapshots/tests.js.md
  packages/build/tests/config/load/snapshots/tests.js.snap
  packages/build/tests/config/load/tests.js
  packages/config/src/bin/flags.js
  packages/config/src/main.js
Labels: enhancement

#917 Never log `--cachedConfig` value
  packages/build/src/log/main.js
  packages/build/tests/config/load/snapshots/tests.js.md
  packages/build/tests/config/load/snapshots/tests.js.snap
  packages/build/tests/config/load/tests.js
Labels: enhancement

#919 Fix non-deterministic tests
  packages/build/tests/config/normalize/snapshots/tests.js.md
  packages/build/tests/config/normalize/snapshots/tests.js.snap
  packages/build/tests/config/validate/snapshots/tests.js.md
  packages/build/tests/config/validate/snapshots/tests.js.snap
  packages/build/tests/core/cli/tests.js
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.md
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.snap
  packages/build/tests/error/clean_stack/tests.js
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/helpers/main.js
  packages/build/tests/log/colors/tests.js
  packages/build/tests/plugins/run/snapshots/tests.js.md
  packages/build/tests/plugins/run/snapshots/tests.js.snap
Labels: test

#920 Add test about multiple lifecycle commands
  packages/build/tests/core/lifecycle/fixtures/multiple/netlify.yml
  packages/build/tests/core/lifecycle/snapshots/tests.js.md
  packages/build/tests/core/lifecycle/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle/tests.js
Labels: test

#923 Fix `BRANCH` environment variable
  packages/config/src/options/branch.js
Labels: bug

#925 Add a test for config warning messages colorization
  packages/build/tests/config/validate/tests.js
Labels: test

#926 Add tests for each `@netlify/config` CLI flag
  packages/build/tests/core/config/fixtures/cached_config/netlify.yml
  packages/build/tests/core/config/fixtures/context/netlify.yml
  packages/build/tests/core/config/fixtures/default_config/default.yml
  packages/build/tests/core/config/fixtures/default_config/netlify.yml
  packages/build/tests/core/config/fixtures/empty/netlify.yml
  packages/build/tests/core/config/snapshots/tests.js.md
  packages/build/tests/core/config/snapshots/tests.js.snap
  packages/build/tests/core/config/tests.js
Labels: test

#927 document utils.build.fail/cancel a little more
  docs/creating-a-plugin.md
Labels: documentation

#929 Add `--baseRelDir` CLI flag
  packages/build/src/core/bin.js
  packages/build/src/core/config.js
  packages/build/src/utils/remove_falsy.js
  packages/build/tests/core/config/fixtures/basereldir/base/netlify.yml
  packages/build/tests/core/config/fixtures/basereldir/netlify.yml
  packages/build/tests/core/config/snapshots/tests.js.md
  packages/build/tests/core/config/snapshots/tests.js.snap
  packages/build/tests/core/config/tests.js
  packages/config/src/bin/flags.js
  packages/config/src/main.js
  packages/config/src/options/main.js
  packages/config/src/utils/remove_falsy.js
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/base/tests.js
Labels: enhancement

#881 Ensure that `--cwd` and `--repositoryRoot` exist
  packages/config/src/options/main.js
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/cwd/tests.js
Labels: enhancement

#878 Better debugging of process warnings
  packages/build/src/core/main.js
  packages/build/src/error/process.js
  packages/build/tests/error/process/fixtures/process/netlify.yml
  packages/build/tests/error/process/snapshots/tests.js.md
  packages/build/tests/error/process/snapshots/tests.js.snap
  packages/build/tests/error/process/tests.js
Labels: enhancement

#894 Do not allow multiple configuration files
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/path.js
  packages/config/tests/load/fixtures/several/netlify.yaml
  packages/config/tests/load/fixtures/several/netlify.yml
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
Labels: enhancement

#893 Rename `BUILD_DIR` to `PUBLISH_DIR`
  docs/creating-a-plugin.md
  packages/build/src/plugins/child/constants.js
  packages/build/tests/plugins/constants/fixtures/build_absolute/plugin.js
  packages/build/tests/plugins/constants/fixtures/build_default/plugin.js
  packages/build/tests/plugins/constants/fixtures/build_default_base/plugin.js
  packages/build/tests/plugins/constants/fixtures/build_dir/netlify.yml
  packages/build/tests/plugins/constants/fixtures/build_dir/plugin.js
  packages/build/tests/plugins/constants/fixtures/build_missing/plugin.js
  packages/build/tests/plugins/constants/fixtures/build_relative/plugin.js
  packages/build/tests/plugins/constants/fixtures/publish_absolute/netlify.yml
  packages/build/tests/plugins/constants/fixtures/publish_absolute/plugin.js
  packages/build/tests/plugins/constants/fixtures/publish_default/netlify.yml
  packages/build/tests/plugins/constants/fixtures/publish_default/plugin.js
  packages/build/tests/plugins/constants/fixtures/publish_default_base/base/.gitkeep
  packages/build/tests/plugins/constants/fixtures/publish_default_base/netlify.yml
  packages/build/tests/plugins/constants/fixtures/publish_default_base/plugin.js
  packages/build/tests/plugins/constants/fixtures/publish_missing/netlify.yml
  packages/build/tests/plugins/constants/fixtures/publish_missing/plugin.js
  packages/build/tests/plugins/constants/fixtures/publish_relative/netlify.yml
  packages/build/tests/plugins/constants/fixtures/publish_relative/plugin.js
  packages/build/tests/plugins/constants/fixtures/publish_relative/publish/.gitkeep
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/tests.js
Labels: enhancement

#931 Improve `--defaultConfig` CLI flag
  packages/build/src/core/bin.js
  packages/build/src/log/main.js
  packages/build/tests/core/config/fixtures/default_config/default.yml
  packages/build/tests/core/config/snapshots/tests.js.md
  packages/build/tests/core/config/snapshots/tests.js.snap
  packages/build/tests/core/config/tests.js
  packages/build/tests/helpers/main.js
  packages/config/src/bin/flags.js
  packages/config/src/main.js
  packages/config/tests/base/fixtures/default_config/default.yml
  packages/config/tests/base/tests.js
  packages/config/tests/helpers/main.js
  packages/config/tests/load/fixtures/default_merge/default.yml
  packages/config/tests/load/fixtures/default_priority/default.yml
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
Labels: enhancement

#932 Improve error handling at the start of the build
  packages/build/src/core/main.js
Labels: bug

#937 Improves tests that involve API requests
  packages/build/src/core/api.js
  packages/build/src/core/site_info.js
  packages/build/src/telemetry/request.js
  packages/build/src/telemetry/track.js
  packages/build/tests/core/telemetry/server.js
  packages/build/tests/core/telemetry/snapshots/tests.js.md
  packages/build/tests/core/telemetry/snapshots/tests.js.snap
  packages/build/tests/core/telemetry/tests.js
  packages/build/tests/helpers/server.js
  packages/build/tests/plugins/env/tests.js
Labels: test

#936 Improve error messages of API calls
  packages/build/src/core/api.js
  packages/build/src/error/location.js
  packages/build/src/error/type.js
Labels: enhancement

#942 Fix randomly failing test
  packages/config/tests/cwd/tests.js
Labels: test

#943 Fix monorepo support
  packages/config/src/options/main.js
  packages/config/src/utils/is-netlify-ci.js
Labels: bug

#944 Regenerate plugins list
  README.md
Labels: documentation

#945 Upgrade OpenAPI definition
  packages/build/package-lock.json
Labels: dependencies

#941 Make `utils.build.cancel()` call `cancelSiteDeploy` endpoint
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/error/handle.js
  packages/build/src/error/type.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/build/tests.js
Labels: enhancement

#946 Fix plugin details logs
  packages/build/src/error/plugin.js
  packages/build/tests/error/plugin_load/fixtures/full/netlify.yml
  packages/build/tests/error/plugin_load/fixtures/full/node_modules/netlify-plugin-test/index.js
  packages/build/tests/error/plugin_load/fixtures/full/node_modules/netlify-plugin-test/package.json
  packages/build/tests/error/plugin_load/fixtures/full/package.json
  packages/build/tests/error/plugin_load/fixtures/partial/netlify.yml
  packages/build/tests/error/plugin_load/fixtures/partial/node_modules/netlify-plugin-test/index.js
  packages/build/tests/error/plugin_load/fixtures/partial/node_modules/netlify-plugin-test/package.json
  packages/build/tests/error/plugin_load/fixtures/partial/package.json
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/tests.js
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
Labels: bug

#947 Improve stack trace cleaning
  packages/build/src/error/clean_stack.js
Labels: bug

#948 Improve test helpers
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/helpers/normalize.js
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/utils/run/snapshots/tests.js.md
  packages/build/tests/utils/run/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
Labels: test

#949 Fix memory leak
  packages/build/src/core/commands.js
  packages/build/src/log/stream.js
Labels: bug

#955 Rename `pluginConfig` to `inputs` in event handlers
  README.md
  docs/creating-a-plugin.md
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/logic.js
  packages/build/src/plugins/child/main.js
  packages/build/src/plugins/config/validate_props.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/options.js
  packages/build/tests/plugins/config/fixtures/backward_compat/netlify.yml
  packages/build/tests/plugins/config/fixtures/backward_compat/plugin.js
  packages/build/tests/plugins/config/fixtures/coerce/plugin.js
  packages/build/tests/plugins/config/fixtures/default/plugin.js
  packages/build/tests/plugins/config/fixtures/simple/netlify.yml
  packages/build/tests/plugins/config/fixtures/simple/plugin.js
  packages/build/tests/plugins/config/snapshots/tests.js.md
  packages/build/tests/plugins/config/snapshots/tests.js.snap
  packages/build/tests/plugins/config/tests.js
  scripts/docs.js
Labels: enhancement

#957 test: disable commit signing during tests
  packages/build/tests/helpers/dir.js
Labels: test

#952 Fix deprecated lifecycle events
  README.md
  packages/build/tests/plugins/validate/snapshots/tests.js.md
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/config/src/normalize/events.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: bug

#956 Simplify lifecycle commands syntax
  README.md
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/core/commands.js
  packages/build/tests/cache/main/snapshots/tests.js.snap
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/core/config/snapshots/tests.js.md
  packages/build/tests/core/config/snapshots/tests.js.snap
  packages/build/tests/core/dry/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle/fixtures/empty/netlify.yml
  packages/build/tests/core/lifecycle/fixtures/multiple/netlify.yml
  packages/build/tests/core/lifecycle/snapshots/tests.js.md
  packages/build/tests/core/lifecycle/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle/tests.js
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.snap
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/config/snapshots/tests.js.md
  packages/build/tests/plugins/config/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/duplicate/snapshots/tests.js.snap
  packages/build/tests/plugins/env/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/install/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/run/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/utils/cache/snapshots/tests.js.snap
  packages/build/tests/utils/git/snapshots/tests.js.snap
  packages/build/tests/utils/load/snapshots/tests.js.snap
  packages/build/tests/utils/run/snapshots/tests.js.snap
  packages/config/src/normalize/main.js
  packages/config/src/validate/validations.js
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/fixtures/array_merge/netlify.yml
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/normalize/fixtures/array/netlify.yml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/fixtures/build_command_array/netlify.yml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
  scripts/docs.js
Labels: enhancement

#958 Rename `config` to `inputs` in the configuration file
  README.md
  docs/creating-a-plugin.md
  packages/build/src/plugins/options.js
  packages/build/tests/plugins/config/fixtures/backward_compat/netlify.yml
  packages/build/tests/plugins/config/fixtures/coerce/netlify.yml
  packages/build/tests/plugins/config/fixtures/prop/netlify.yml
  packages/build/tests/plugins/config/fixtures/simple/netlify.yml
  packages/build/tests/plugins/config/fixtures/unknown/netlify.yml
  packages/build/tests/plugins/duplicate/fixtures/inputs/netlify.yml
  packages/build/tests/plugins/duplicate/fixtures/inputs/plugin.js
  packages/build/tests/plugins/duplicate/fixtures/options/netlify.yml
  packages/build/tests/plugins/duplicate/snapshots/tests.js.md
  packages/build/tests/plugins/duplicate/snapshots/tests.js.snap
  packages/build/tests/plugins/duplicate/tests.js
  packages/config/src/normalize/main.js
  packages/config/src/validate/validations.js
  packages/config/tests/normalize/fixtures/config/netlify.yml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/validate/fixtures/plugins_config_renamed/netlify.yml
  packages/config/tests/validate/fixtures/plugins_inputs_object/netlify.yml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: enhancement

#961 Rename `plugin.config` to `plugin.inputs`
  docs/creating-a-plugin.md
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/normalize.js
  packages/build/src/plugins/child/validate.js
  packages/build/src/plugins/config/validate_config.js
  packages/build/src/plugins/config/validate_inputs.js
  packages/build/src/plugins/config/validate_schema.js
  packages/build/tests/plugins/config/fixtures/backward_compat_config/netlify.yml
  packages/build/tests/plugins/config/fixtures/backward_compat_config/plugin.js
  packages/build/tests/plugins/config/fixtures/backward_compat_pluginconfig/netlify.yml
  packages/build/tests/plugins/config/fixtures/backward_compat_pluginconfig/plugin.js
  packages/build/tests/plugins/config/fixtures/basic/plugin.js
  packages/build/tests/plugins/config/fixtures/coerce/plugin.js
  packages/build/tests/plugins/config/fixtures/default/plugin.js
  packages/build/tests/plugins/config/fixtures/object_props/plugin.js
  packages/build/tests/plugins/config/fixtures/prop/plugin.js
  packages/build/tests/plugins/config/fixtures/required/plugin.js
  packages/build/tests/plugins/config/fixtures/undefined/plugin.js
  packages/build/tests/plugins/config/fixtures/unknown/plugin.js
  packages/build/tests/plugins/config/snapshots/tests.js.md
  packages/build/tests/plugins/config/snapshots/tests.js.snap
  packages/build/tests/plugins/config/tests.js
  packages/build/tests/plugins/validate/snapshots/tests.js.md
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
Labels: enhancement

#965 Add `utils.build.failPlugin()`
  docs/creating-a-plugin.md
  packages/build/src/core/commands.js
  packages/build/src/error/type.js
  packages/build/src/log/main.js
  packages/build/src/plugins/child/utils.js
  packages/build/src/plugins/error.js
  packages/build/tests/error/build/fixtures/fail_plugin/netlify.yml
  packages/build/tests/error/build/fixtures/fail_plugin/plugin.js
  packages/build/tests/error/build/fixtures/fail_plugin/plugin_two.js
  packages/build/tests/error/build/fixtures/fail_plugin_error_option/netlify.yml
  packages/build/tests/error/build/fixtures/fail_plugin_error_option/plugin.js
  packages/build/tests/error/build/fixtures/fail_plugin_error_option/plugin_two.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/build/tests.js
Labels: enhancement

#969 Upgrade `zip-it-and-ship-it`
  packages/build/package-lock.json
  packages/build/package.json
Labels: dependencies

#964 Improve headers in error logs
  packages/build/src/error/serialize.js
  packages/build/src/error/type.js
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.md
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.snap
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/plugins/install/snapshots/tests.js.md
  packages/build/tests/plugins/install/snapshots/tests.js.snap
  packages/build/tests/utils/git/snapshots/tests.js.md
  packages/build/tests/utils/git/snapshots/tests.js.snap
  packages/build/tests/utils/load/snapshots/tests.js.md
  packages/build/tests/utils/load/snapshots/tests.js.snap
Labels: enhancement

#970 Document `netlify-plugin-rss`
  README.md
Labels: documentation

#966 Improve logging
  packages/build/src/log/main.js
  packages/build/tests/core/cli/snapshots/tests.js.md
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/core/config/snapshots/tests.js.md
  packages/build/tests/core/config/snapshots/tests.js.snap
  packages/build/tests/core/dry/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.md
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.snap
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.md
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/config/snapshots/tests.js.md
  packages/build/tests/plugins/config/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/duplicate/snapshots/tests.js.snap
  packages/build/tests/plugins/env/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/install/snapshots/tests.js.md
  packages/build/tests/plugins/install/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.md
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/utils/cache/snapshots/tests.js.snap
  packages/build/tests/utils/git/snapshots/tests.js.md
  packages/build/tests/utils/git/snapshots/tests.js.snap
  packages/build/tests/utils/load/snapshots/tests.js.md
  packages/build/tests/utils/load/snapshots/tests.js.snap
  packages/build/tests/utils/run/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: enhancement

#971 De-duplicate plugins list
  README.md
  package-lock.json
  package.json
  scripts/docs.js
Labels: documentation

#954 Remove examples
  CONTRIBUTING.md
  examples/README.md
  examples/backwards-compat/.gitignore
  examples/backwards-compat/README.md
  examples/backwards-compat/functions/one.js
  examples/backwards-compat/netlify.toml
  examples/backwards-compat/package-lock.json
  examples/backwards-compat/package.json
  examples/backwards-compat/src/index.html
  examples/example-one/.gitignore
  examples/example-one/README.md
  examples/example-one/functions/one.js
  examples/example-one/netlify.yml
  examples/example-one/package.json
  examples/example-one/plugins/example/index.js
  examples/example-one/plugins/example/package.json
  examples/example-one/src/index.html
  examples/example-two/.gitignore
  examples/example-two/README.md
  examples/example-two/functions/one.js
  examples/example-two/gulpfile.js
  examples/example-two/netlify.yml
  examples/example-two/package-lock.json
  examples/example-two/package.json
  examples/example-two/plugin.js
  examples/example-two/src/index.html
  package.json
  scripts/docs.js
Labels: documentation

#974 Fix error validation message
  packages/config/src/validate/validations.js
  packages/config/tests/validate/fixtures/build_lifecycle_events_array/netlify.yml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: bug

#976 Rename `utils.error` to `utils.build`
  docs/creating-a-plugin.md
  packages/build/src/error/build.js
  packages/build/src/error/handle.js
  packages/build/src/plugins/child/utils.js
  packages/build/tests/core/lifecycle_end/fixtures/on_end_several/plugin_invalid.js
  packages/build/tests/core/lifecycle_end/fixtures/on_error_several/plugin_invalid.js
  packages/build/tests/error/build/fixtures/cancel/netlify.yml
  packages/build/tests/error/build/fixtures/cancel/plugin.js
  packages/build/tests/error/build/fixtures/cancel_compat/netlify.yml
  packages/build/tests/error/build/fixtures/cancel_compat/plugin.js
  packages/build/tests/error/build/fixtures/cancel_error_option/netlify.yml
  packages/build/tests/error/build/fixtures/cancel_error_option/plugin.js
  packages/build/tests/error/build/fixtures/exception/netlify.yml
  packages/build/tests/error/build/fixtures/exception/plugin.js
  packages/build/tests/error/build/fixtures/exception_props/netlify.yml
  packages/build/tests/error/build/fixtures/exception_props/plugin.js
  packages/build/tests/error/build/fixtures/fail_build/netlify.yml
  packages/build/tests/error/build/fixtures/fail_build/plugin.js
  packages/build/tests/error/build/fixtures/fail_build_compat/netlify.yml
  packages/build/tests/error/build/fixtures/fail_build_compat/plugin.js
  packages/build/tests/error/build/fixtures/fail_build_error_option/netlify.yml
  packages/build/tests/error/build/fixtures/fail_build_error_option/plugin.js
  packages/build/tests/error/build/fixtures/fail_plugin/netlify.yml
  packages/build/tests/error/build/fixtures/fail_plugin/plugin.js
  packages/build/tests/error/build/fixtures/fail_plugin/plugin_two.js
  packages/build/tests/error/build/fixtures/fail_plugin_error_option/netlify.yml
  packages/build/tests/error/build/fixtures/fail_plugin_error_option/plugin.js
  packages/build/tests/error/build/fixtures/fail_plugin_error_option/plugin_two.js
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/build/tests.js
  packages/build/tests/error/clean_stack/fixtures/plugin/plugin.js
  packages/build/tests/error/plugin_load/fixtures/full/node_modules/netlify-plugin-test/index.js
  packages/build/tests/error/plugin_load/fixtures/partial/node_modules/netlify-plugin-test/index.js
  packages/build/tests/error/utils/snapshots/tests.js.snap
  packages/build/tests/utils/load/snapshots/tests.js.md
  packages/build/tests/utils/load/snapshots/tests.js.snap
Labels: enhancement

#981 Remove lifecycle validation check
  packages/config/src/validate/validations.js
  packages/config/tests/validate/fixtures/build_command_no_lifecycle/netlify.yml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: bug

#977 Move some line of code
  packages/build/src/plugins/child/load.js
Labels: enhancement

#979 Remove event handlers overriding
  packages/build/src/core/commands.js
  packages/build/src/log/main.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/main.js
  packages/build/src/plugins/child/validate.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/override.js
  packages/build/tests/plugins/load/fixtures/override/netlify.yml
  packages/build/tests/plugins/load/fixtures/override/node_modules/example/index.js
  packages/build/tests/plugins/load/fixtures/override/node_modules/netlify-plugin-example.js
  packages/build/tests/plugins/load/fixtures/override/override.js
  packages/build/tests/plugins/load/fixtures/override/package.json
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/load/tests.js
Labels: enhancement

#982 Remove `plugins[*].enabled`
  packages/build/src/plugins/options.js
  packages/build/tests/plugins/load/fixtures/enabled/netlify.yml
  packages/build/tests/plugins/load/fixtures/enabled/plugin.js
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/load/tests.js
  packages/config/src/validate/helpers.js
  packages/config/src/validate/validations.js
  packages/config/tests/validate/fixtures/plugins_enabled_boolean/netlify.yml
  packages/config/tests/validate/fixtures/plugins_package_required/netlify.yml
  packages/config/tests/validate/fixtures/plugins_package_string/netlify.yml
  packages/config/tests/validate/fixtures/plugins_type_renamed/netlify.yml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: feature

#985 Remove warning when automatically installing plugins
  packages/build/src/log/main.js
  packages/build/src/plugins/options.js
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
Labels: type: feature

#984 Make automatic installation of modules less verbose
  packages/build/src/utils/install.js
  packages/build/tests/plugins/functions/snapshots/tests.js.md
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/tests.js
  packages/build/tests/plugins/install/fixtures/yarn/plugin/package-lock.json
  packages/build/tests/plugins/install/snapshots/tests.js.md
  packages/build/tests/plugins/install/snapshots/tests.js.snap
  packages/build/tests/plugins/install/tests.js
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/load/tests.js
Labels: type: feature

#987 Remove unused backward compatibility fix
  packages/build/src/plugins/child/normalize.js
Labels: type: chore

#988 Move `constants` logic
  packages/build/src/core/config.js
  packages/build/src/core/constants.js
  packages/build/src/core/main.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/main.js
  packages/build/src/plugins/load.js
  packages/build/tests/plugins/constants/tests.js
  scripts/docs.js
Labels: type: chore

#990 Move some code from plugins to the parent process
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/load.js
Labels: type: chore

#994 Temporarily disable one test
  packages/build/tests/plugins/constants/tests.js
Labels: type: chore

#995 Improve error message on unknown input
  packages/build/src/plugins/manifest/check.js
  packages/build/tests/manifest/check/snapshots/tests.js.md
  packages/build/tests/manifest/check/snapshots/tests.js.snap
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.snap
Labels: type: feature

#998 Fix test not being run
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/tests.js
Labels: type: chore

#999 Fix Netlify config normalization
  packages/config/src/normalize/main.js
  packages/config/tests/normalize/fixtures/command_lifecycle/netlify.yml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
Labels: type: bug

#1000 Refactor serialization in logs
  packages/build/src/log/main.js
  packages/build/src/log/serialize.js
  packages/build/src/plugins/manifest/check.js
Labels: type: chore

#1002 Improve test snapshot normalization
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/core/config/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.md
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.snap
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/build/tests.js
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/helpers/normalize.js
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.snap
  packages/build/tests/manifest/validate/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/env/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/install/snapshots/tests.js.md
  packages/build/tests/plugins/install/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/utils/cache/snapshots/tests.js.snap
  packages/build/tests/utils/git/fixtures/file_match/plugin.js
  packages/build/tests/utils/git/snapshots/tests.js.md
  packages/build/tests/utils/git/snapshots/tests.js.snap
  packages/build/tests/utils/load/snapshots/tests.js.md
  packages/build/tests/utils/load/snapshots/tests.js.snap
  packages/build/tests/utils/run/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: chore

#1004 Fix `config` debug logs
  packages/build/src/log/main.js
  packages/build/tests/core/cli/snapshots/tests.js.snap
  packages/build/tests/core/config/snapshots/tests.js.md
  packages/build/tests/core/config/snapshots/tests.js.snap
  packages/build/tests/core/dry/snapshots/tests.js.md
  packages/build/tests/core/dry/snapshots/tests.js.snap
  packages/build/tests/core/flags/snapshots/tests.js.md
  packages/build/tests/core/flags/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle/snapshots/tests.js.md
  packages/build/tests/core/lifecycle/snapshots/tests.js.snap
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.md
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.snap
  packages/build/tests/error/build/snapshots/tests.js.snap
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.snap
  packages/build/tests/manifest/check/snapshots/tests.js.snap
  packages/build/tests/manifest/load/snapshots/tests.js.snap
  packages/build/tests/manifest/validate/snapshots/tests.js.snap
  packages/build/tests/plugins/api/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/build/tests/plugins/env/snapshots/tests.js.md
  packages/build/tests/plugins/env/snapshots/tests.js.snap
  packages/build/tests/plugins/functions/snapshots/tests.js.md
  packages/build/tests/plugins/functions/snapshots/tests.js.snap
  packages/build/tests/plugins/install/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/run/snapshots/tests.js.snap
  packages/build/tests/plugins/validate/snapshots/tests.js.snap
  packages/build/tests/utils/cache/snapshots/tests.js.snap
  packages/build/tests/utils/git/snapshots/tests.js.snap
  packages/build/tests/utils/load/snapshots/tests.js.snap
  packages/build/tests/utils/run/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: bug

#1005 Simplify some code related to local plugins
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/main.js
Labels: type: chore

#1006 Improve plugins automatic installation
  packages/build/package.json
  packages/build/src/log/main.js
  packages/build/src/plugins/options.js
  packages/build/src/utils/install.js
  packages/build/tests/plugins/load/fixtures/basedir/base/netlify.yml
  packages/build/tests/plugins/load/fixtures/basedir/base/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/load/fixtures/basedir/base/node_modules/netlify-plugin-test/package.json
  packages/build/tests/plugins/load/fixtures/basedir/base/package.json
  packages/build/tests/plugins/load/fixtures/installed_already/netlify.yml
  packages/build/tests/plugins/load/fixtures/installed_already/node_modules/isobject/LICENSE
  packages/build/tests/plugins/load/fixtures/installed_already/node_modules/isobject/README.md
  packages/build/tests/plugins/load/fixtures/installed_already/node_modules/isobject/index.cjs.js
  packages/build/tests/plugins/load/fixtures/installed_already/node_modules/isobject/index.d.ts
  packages/build/tests/plugins/load/fixtures/installed_already/node_modules/isobject/index.js
  packages/build/tests/plugins/load/fixtures/installed_already/node_modules/isobject/package.json
  packages/build/tests/plugins/load/fixtures/installed_already/package-lock.json
  packages/build/tests/plugins/load/fixtures/installed_already/package.json
  packages/build/tests/plugins/load/fixtures/non_existing/netlify.yml
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
  packages/build/tests/plugins/load/tests.js
Labels: type: feature

#1007 Improve local plugins automatic install
  packages/build/src/core/main.js
  packages/build/src/log/main.js
  packages/build/src/plugins/install.js
  packages/build/src/plugins_core/functions/plugin.js
  packages/build/src/utils/install.js
  packages/build/tests/plugins/install/snapshots/tests.js.md
  packages/build/tests/plugins/install/snapshots/tests.js.snap
Labels: type: feature

#1010 Temporarily disable one test
  packages/build/tests/plugins/env/tests.js
Labels: type: chore

#1015 Fix tests on Node 8.3.0
  packages/build/tests/plugins/load/fixtures/install_missing/netlify.yml
  packages/build/tests/plugins/load/fixtures/install_missing/package-lock.json
  packages/build/tests/plugins/load/fixtures/install_missing/package.json
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
Labels: test, type: chore

#1014 Allow running any local binary in tests
  packages/build/package.json
  packages/build/tests/helpers/main.js
Labels: test, type: chore

#1011 Improve Netlify Functions automatic install
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/plugins_core/functions/plugin.js
Labels: type: feature

#1012 Move all install logic to its own directory
  packages/build/package-lock.json
  packages/build/src/core/main.js
  packages/build/src/install/functions.js
  packages/build/src/install/local.js
  packages/build/src/install/main.js
  packages/build/src/install/missing.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/functions/plugin.js
Labels: type: chore

#1013 Fix tests that run `npm install`
  packages/build/tests/helpers/main.js
  packages/build/tests/helpers/normalize.js
  packages/build/tests/plugins/install/snapshots/tests.js.md
  packages/build/tests/plugins/install/snapshots/tests.js.snap
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.snap
Labels: type: chore

#1017 Add a test helper
  packages/build/tests/error/plugin_load/tests.js
  packages/build/tests/helpers/main.js
  packages/build/tests/plugins/env/tests.js
  packages/build/tests/plugins/install/tests.js
  packages/build/tests/plugins/load/tests.js
  packages/build/tests/utils/git/tests.js
  packages/config/tests/context/tests.js
  packages/config/tests/cwd/tests.js
  packages/config/tests/helpers/main.js
  packages/config/tests/load/fixtures/none/gitkeep
  packages/config/tests/load/tests.js
Labels: test, type: chore

#1019 Remove empty build commands
  packages/config/src/normalize/main.js
  packages/config/tests/normalize/fixtures/lifecycle_empty/netlify.yml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
Labels: type: bug

#1020 Downgrade `cp-file`
  packages/build/package-lock.json
  packages/build/package.json
Labels: type: bug

#1021 Upgrade `uuid`
  packages/build/package-lock.json
  packages/build/package.json
  packages/build/src/plugins/ipc.js
Labels: dependencies, type: chore

#1024 Fix security vulnerability by upgrading dependencies
  package-lock.json
  packages/build/package-lock.json
  packages/cache-utils/package-lock.json
  packages/config/package-lock.json
  packages/functions-utils/package-lock.json
Labels: type: security

#1023 Upgrade several dependencies
  package-lock.json
  package.json
  packages/build/package-lock.json
  packages/build/package.json
  packages/cache-utils/package-lock.json
  packages/cache-utils/package.json
  packages/config/package-lock.json
  packages/config/package.json
Labels: dependencies, type: chore

#1029 Fix "Lets" typo in CLI output
  packages/build/src/log/main.js
  packages/build/tests/cache/main/snapshots/tests.js.md
  packages/build/tests/core/cli/snapshots/tests.js.md
  packages/build/tests/core/config/snapshots/tests.js.md
  packages/build/tests/core/flags/snapshots/tests.js.md
  packages/build/tests/core/lifecycle/snapshots/tests.js.md
  packages/build/tests/core/lifecycle_end/snapshots/tests.js.md
  packages/build/tests/core/telemetry/snapshots/tests.js.md
  packages/build/tests/error/build/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/process/snapshots/tests.js.md
  packages/build/tests/error/stack/snapshots/tests.js.md
  packages/build/tests/install/functions/snapshots/tests.js.md
  packages/build/tests/install/local/snapshots/tests.js.md
  packages/build/tests/install/missing/snapshots/tests.js.md
  packages/build/tests/manifest/check/snapshots/tests.js.md
  packages/build/tests/manifest/load/snapshots/tests.js.md
  packages/build/tests/plugins/api/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/env/snapshots/tests.js.md
  packages/build/tests/plugins/functions/snapshots/tests.js.md
  packages/build/tests/plugins/load/snapshots/tests.js.md
  packages/build/tests/plugins/normalize/snapshots/tests.js.md
  packages/build/tests/plugins/run/snapshots/tests.js.md
  packages/build/tests/plugins/validate/snapshots/tests.js.md
  packages/build/tests/utils/cache/snapshots/tests.js.md
  packages/build/tests/utils/functions/snapshots/tests.js.md
  packages/build/tests/utils/git/snapshots/tests.js.md
  packages/build/tests/utils/load/snapshots/tests.js.md
  packages/build/tests/utils/run/snapshots/tests.js.md
Labels: type: bug

#1047 Fix relative paths in configuration file
  packages/build/tests/core/config/snapshots/tests.js.md
  packages/build/tests/core/config/snapshots/tests.js.snap
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/config/src/files.js
  packages/config/src/main.js
  packages/config/tests/base/fixtures/prop_config/base/netlify.yml
  packages/config/tests/base/fixtures/prop_config/netlify.yml
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/base/tests.js
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
Labels: type: bug

#1031 Fix Ava configuration
  ava.config.js
Labels: test, type: chore

#1032 Remove `istanbul ignore next` comments
  packages/build/src/log/colors.js
  packages/build/src/log/redact.js
  packages/build/src/log/stream.js
  packages/build/src/plugins_core/cache/plugin.js
  packages/build/src/plugins_core/main.js
  packages/cache-utils/src/dir.js
  packages/cache-utils/src/hash.js
  packages/config/src/validate/example.js
  packages/config/src/validate/helpers.js
  packages/config/src/validate/main.js
  packages/git-utils/src/main.js
  packages/git-utils/src/refs.js
Labels: test, type: chore

#1033 Fix tests documentation
  packages/build/tests/README.md
Labels: documentation, type: feature

#1038 Add `NETLIFY_BUILD_TEST` environment variable
  packages/build/tests/helpers/main.js
  packages/cache-utils/src/dir.js
  packages/config/src/options/main.js
Labels: test, type: chore

#1040 Fix `cache-utils` missing dependency
  packages/cache-utils/package-lock.json
  packages/cache-utils/package.json
  packages/cache-utils/src/main.js
  packages/cache-utils/src/utils/polyfills.js
Labels: type: bug

#1041 Add a `cacheDir` option to the `cache` utility
  packages/cache-utils/src/dir.js
  packages/cache-utils/src/list.js
  packages/cache-utils/src/main.js
  packages/cache-utils/src/path.js
Labels: type: feature

#1037 Improve the `functions` utility
  packages/build/src/plugins/child/utils.js
  packages/build/tests/utils/load/snapshots/tests.js.md
  packages/build/tests/utils/load/snapshots/tests.js.snap
  packages/functions-utils/src/main.js
Labels: type: feature

#1035 Add `head` option to the `git` utility.
  packages/build/tests/utils/git/snapshots/tests.js.md
  packages/build/tests/utils/git/snapshots/tests.js.snap
  packages/git-utils/src/commits.js
  packages/git-utils/src/diff.js
  packages/git-utils/src/main.js
  packages/git-utils/src/refs.js
  packages/git-utils/src/stats.js
Labels: type: feature

#1036 Fix environment variable `CACHED_COMMIT_REF` in the `git` utility
  packages/git-utils/src/refs.js
Labels: type: feature

#1049 Fix `build.functions` and `build.publish` resolution when `build.base` starts with `/`
  packages/config/src/build_dir.js
  packages/config/src/files.js
  packages/config/src/main.js
  packages/config/src/path.js
  packages/config/tests/base/fixtures/prop_config/netlify.yml
Labels: type: bug

#1046 Improve plugin `utils` tests
  packages/build/tests/helpers/main.js
  packages/build/tests/plugins/utils/fixtures/error/netlify.yml
  packages/build/tests/plugins/utils/fixtures/error/node_modules/@netlify/git-utils/index.js
  packages/build/tests/plugins/utils/fixtures/error/package.json
  packages/build/tests/plugins/utils/fixtures/error/plugin.js
  packages/build/tests/plugins/utils/fixtures/function_async/netlify.yml
  packages/build/tests/plugins/utils/fixtures/function_async/node_modules/@netlify/git-utils/index.js
  packages/build/tests/plugins/utils/fixtures/function_async/package.json
  packages/build/tests/plugins/utils/fixtures/function_async/plugin.js
  packages/build/tests/plugins/utils/fixtures/function_sync/netlify.yml
  packages/build/tests/plugins/utils/fixtures/function_sync/node_modules/@netlify/git-utils/index.js
  packages/build/tests/plugins/utils/fixtures/function_sync/package.json
  packages/build/tests/plugins/utils/fixtures/function_sync/plugin.js
  packages/build/tests/plugins/utils/fixtures/functions/netlify.yml
  packages/build/tests/plugins/utils/fixtures/functions/plugin.js
  packages/build/tests/plugins/utils/fixtures/functions/test/test.js
  packages/build/tests/plugins/utils/fixtures/git_no_root/netlify.yml
  packages/build/tests/plugins/utils/fixtures/git_no_root/plugin.js
  packages/build/tests/plugins/utils/fixtures/git_no_root_delayed/netlify.yml
  packages/build/tests/plugins/utils/fixtures/git_no_root_delayed/plugin.js
  packages/build/tests/plugins/utils/fixtures/none/netlify.yml
  packages/build/tests/plugins/utils/fixtures/none/plugin.js
  packages/build/tests/plugins/utils/snapshots/tests.js.md
  packages/build/tests/plugins/utils/snapshots/tests.js.snap
  packages/build/tests/plugins/utils/tests.js
  packages/build/tests/utils/load/snapshots/tests.js.snap
  packages/build/tests/utils/load/tests.js
Labels: test, type: chore

#1034 Refactor test utilities
  packages/build/tests/core/config/tests.js
  packages/build/tests/helpers/common.js
  packages/build/tests/helpers/main.js
  packages/build/tests/helpers/normalize.js
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/tests/base/tests.js
  packages/config/tests/cli/tests.js
  packages/config/tests/context/tests.js
  packages/config/tests/cwd/tests.js
  packages/config/tests/helpers/main.js
  packages/config/tests/load/tests.js
  packages/config/tests/normalize/tests.js
  packages/config/tests/parse/tests.js
  packages/config/tests/validate/tests.js
Labels: test, type: chore

#1044 Improve tests of the `git` utility
  packages/build/tests/utils/git/fixtures/commits/netlify.yml
  packages/build/tests/utils/git/fixtures/commits/plugin.js
  packages/build/tests/utils/git/fixtures/defined/netlify.yml
  packages/build/tests/utils/git/fixtures/defined/plugin.js
  packages/build/tests/utils/git/fixtures/delayed/netlify.yml
  packages/build/tests/utils/git/fixtures/diff/netlify.yml
  packages/build/tests/utils/git/fixtures/diff/plugin.js
  packages/build/tests/utils/git/fixtures/file_match/netlify.yml
  packages/build/tests/utils/git/fixtures/file_match/plugin.js
  packages/build/tests/utils/git/fixtures/full/netlify.yml
  packages/build/tests/utils/git/fixtures/full/plugin.js
  packages/build/tests/utils/git/fixtures/lines/netlify.yml
  packages/build/tests/utils/git/fixtures/lines/plugin.js
  packages/build/tests/utils/git/snapshots/tests.js.md
  packages/build/tests/utils/git/snapshots/tests.js.snap
  packages/build/tests/utils/git/tests.js
  packages/git-utils/package-lock.json
  packages/git-utils/package.json
  packages/git-utils/src/refs.js
  packages/git-utils/tests/main.js
Labels: test, type: chore

#1043 Improve tests of the `functions` utility
  packages/build/tests/utils/functions/fixtures/already/functions/test.js
  packages/build/tests/utils/functions/fixtures/already/netlify.yml
  packages/build/tests/utils/functions/fixtures/already/plugin.js
  packages/build/tests/utils/functions/fixtures/directory/netlify.yml
  packages/build/tests/utils/functions/fixtures/directory/plugin.js
  packages/build/tests/utils/functions/fixtures/directory/test/index.js
  packages/build/tests/utils/functions/fixtures/missing/netlify.yml
  packages/build/tests/utils/functions/fixtures/missing/plugin.js
  packages/build/tests/utils/functions/fixtures/simple/netlify.yml
  packages/build/tests/utils/functions/fixtures/simple/plugin.js
  packages/build/tests/utils/functions/snapshots/tests.js.md
  packages/build/tests/utils/functions/snapshots/tests.js.snap
  packages/build/tests/utils/functions/tests.js
  packages/functions-utils/package-lock.json
  packages/functions-utils/package.json
  packages/functions-utils/tests/fixtures/directory/test/index.js
  packages/functions-utils/tests/fixtures/file/test.js
  packages/functions-utils/tests/helpers/main.js
  packages/functions-utils/tests/main.js
Labels: test, type: chore

#1045 Improve tests of the `run` utility
  packages/build/tests/utils/run/fixtures/command/netlify.yml
  packages/build/tests/utils/run/fixtures/command/plugin.js
  packages/build/tests/utils/run/fixtures/defined/netlify.yml
  packages/build/tests/utils/run/fixtures/defined/plugin.js
  packages/build/tests/utils/run/fixtures/local/netlify.yml
  packages/build/tests/utils/run/fixtures/local/plugin.js
  packages/build/tests/utils/run/fixtures/no_args/netlify.yml
  packages/build/tests/utils/run/fixtures/no_args/plugin.js
  packages/build/tests/utils/run/fixtures/no_args_options/netlify.yml
  packages/build/tests/utils/run/fixtures/no_args_options/plugin.js
  packages/build/tests/utils/run/fixtures/stderr/netlify.yml
  packages/build/tests/utils/run/fixtures/stderr/plugin.js
  packages/build/tests/utils/run/fixtures/stdio/netlify.yml
  packages/build/tests/utils/run/fixtures/stdio/plugin.js
  packages/build/tests/utils/run/fixtures/stdout/netlify.yml
  packages/build/tests/utils/run/fixtures/stdout/plugin.js
  packages/build/tests/utils/run/snapshots/tests.js.md
  packages/build/tests/utils/run/snapshots/tests.js.snap
  packages/build/tests/utils/run/tests.js
  packages/run-utils/package-lock.json
  packages/run-utils/package.json
  packages/run-utils/tests/fixtures/run.js
  packages/run-utils/tests/main.js
Labels: test, type: chore

#1050 Remove `omit.js`
  packages/build/package.json
  packages/build/src/error/serialize.js
  packages/build/src/log/main.js
  packages/build/src/plugins/env.js
  packages/build/src/utils/omit.js
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/utils/omit.js
  packages/config/src/validate/validations.js
Labels: type: chore

#1051 Fix duplicated paths bug
  packages/build/src/core/config.js
  packages/config/src/options/main.js
Labels: type: bug

#1052 Fix tests failing on Windows
  ava.config.js
  packages/cache-utils/src/list.js
  packages/cache-utils/src/path.js
  packages/cache-utils/tests/dir.js
  packages/cache-utils/tests/has.js
  packages/cache-utils/tests/hash.js
  packages/cache-utils/tests/helpers/main.js
  packages/cache-utils/tests/list.js
  packages/cache-utils/tests/move.js
  packages/cache-utils/tests/path.js
  packages/cache-utils/tests/remove.js
  packages/cache-utils/tests/save_restore.js
  packages/cache-utils/tests/ttl.js
Labels: test, type: chore

#1054 Fix `cache` utility crashing builds
  packages/cache-utils/README.md
  packages/cache-utils/package-lock.json
  packages/cache-utils/package.json
  packages/cache-utils/src/hash.js
  packages/cache-utils/src/main.js
  packages/cache-utils/src/manifest.js
  packages/cache-utils/src/path.js
  packages/cache-utils/tests/hash.js
Labels: type: bug

#1062 Document NETLIFY_BUILD_CLI_VERSION
  CONTRIBUTING.md
Labels: documentation, type: chore

#991 Remove `NETLIFY_CONFIG_*` environment variables
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/env.js
  packages/config/src/main.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
  packages/config/tests/validate/fixtures/build_command_lifecycle_envvar/netlify.yml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: feature

#992 Revert monorepo bug workaround
  packages/config/src/options/main.js
  packages/config/src/utils/is-netlify-ci.js
Labels: type: chore

#1060 Improve `CONTRIBUTING.md`
  CONTRIBUTING.md
  scripts/docs.js
Labels: documentation, type: chore

#1066 Inline documentation
  README.md
  package-lock.json
  package.json
  scripts/docs.js
Labels: documentation, type: chore

#1067 Use doctoc
  README.md
  package-lock.json
  package.json
  scripts/docs.js
Labels: documentation, type: chore

#1057 Improve bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type: feature

#1058 Fix GitHub labels in issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type: chore

#1061 Upgrade `js-client`
  packages/build/package-lock.json
  packages/build/package.json
Labels: type: chore

#1059 Improve npm scripts
  package.json
Labels: type: chore

#1065 Validate that `cwd` and `repositoryRoot` options are directories
  packages/config/src/options/main.js
  packages/config/src/utils/dir-exists.js
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/cwd/tests.js
Labels: type: feature

#1063 Improve performance of configuration file load
  packages/config/package-lock.json
  packages/config/package.json
  packages/config/src/files.js
  packages/config/src/path.js
Labels: type: chore

#1074 Remove Codecov token from GitHub action
  .github/workflows/workflow.yml
  scripts/coverage.sh
Labels: type: chore

#1073 Separate linting and testing in GitHub actions UI
  .github/workflows/workflow.yml
  package.json
Labels: type: chore

#1072 Run GitHub actions on PRs coming from forks
  .github/workflows/workflow.yml
Labels: type: chore

#1075 Improve error message when plugin aborts
  packages/build/src/plugins/ipc.js
  packages/build/tests/error/plugin_load/snapshots/tests.js.md
  packages/build/tests/error/plugin_load/snapshots/tests.js.snap
Labels: type: feature

#1076 Fix `cache` utils in local builds
  packages/build/tests/plugins/constants/snapshots/tests.js.md
  packages/build/tests/plugins/constants/snapshots/tests.js.snap
  packages/cache-utils/src/dir.js
Labels: type: bug
