Repository netlify/build, pull requests merged in 2021-04, with the labels that each got.

#2519 fix: reinstate legacy build.functions property
  packages/config/src/main.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
Labels: type: bug

#2518 feat: add functions config object to build output
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/config/src/log/cleanup.js
Labels: type: feature

#2514 feat: improve lingering processes warning message, comments and logic
  packages/build/src/core/lingering.js
  packages/build/src/log/messages/core.js
  packages/build/tests/core/tests.js
Labels: type: feature

#2524 fix: remove some code
  package-lock.json
  packages/build/package.json
  packages/build/src/core/feature_flags.js
  packages/build/src/core/main.js
  packages/build/src/plugins_core/add.js
  packages/build/src/plugins_core/list.js
  packages/build/tests/plugins/fixtures/dpc_headers_file/_headers
  packages/build/tests/plugins/fixtures/dpc_headers_toml/netlify.toml
  packages/build/tests/plugins/fixtures/dpc_inject_html/netlify.toml
  packages/build/tests/plugins/fixtures/dpc_inject_html/publish/index.html
  packages/build/tests/plugins/fixtures/no_config/.gitkeep
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: bug, type: chore

#2527 fix: do not print internal information in the build logs
  packages/build/src/log/messages/config.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: bug

#2534 chore(renovate): ignore ps-list major updates
  renovate.json5
Labels: type: chore

#2533 chore(renovate): enable automerge
  renovate.json5
Labels: type: chore

#2535 fix(feature_flag): remove telemetry feature flag code
  packages/build/src/core/feature_flags.js
  packages/build/src/core/normalize_flags.js
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/telemetry/tests.js
Labels: init/build-telemetry-proxy, type: bug

#2541 fix: validate `build.command` even when not used due to config merge
  packages/config/src/validate/validations.js
  packages/config/tests/validate/fixtures/build_command_merge/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: bug

#2543 chore(release-please): use GitHub app token
  .github/workflows/release-please.yml
Labels: type: chore

#2540 feat: refactor `plugins[*].origin`
  packages/config/src/merge.js
  packages/config/src/origin.js
Labels: type: feature

#2545 feat: refactor how `origin` is added to context-specific configs
  packages/config/src/context.js
  packages/config/src/origin.js
Labels: type: feature

#2547 fix: improve config normalization logic
  packages/config/src/context.js
  packages/config/src/main.js
  packages/config/src/merge_normalize.js
  packages/config/src/validate/main.js
Labels: type: bug, type: feature

#2549 feat: refactor configuration property origins
  packages/config/src/context.js
  packages/config/src/main.js
  packages/config/src/merge.js
  packages/config/src/merge_normalize.js
  packages/config/src/origin.js
Labels: type: feature

#2551 feat: validate `context.{context}.*` properties
  packages/config/src/case.js
  packages/config/src/context.js
  packages/config/src/validate/main.js
  packages/config/tests/normalize/fixtures/props_case_context/netlify.toml
  packages/config/tests/normalize/fixtures/props_case_default_config/base/.gitkeep
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/validate/fixtures/build_context_validation/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: bug, type: feature

#2558 fix: context properties should not unset plugins
  packages/config/src/origin.js
  packages/config/tests/context/fixtures/context_reset/netlify.toml
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/context/tests.js
Labels: type: bug

#2555 feat: improve how context-specific config are merged
  packages/config/src/context.js
Labels: type: feature

#2562 feat: refactors how plugins configurations are currently merged
  packages/config/src/merge.js
Labels: type: feature

#2561 feat: refactor configuration merge logic
  packages/config/src/context.js
  packages/config/src/files.js
  packages/config/src/main.js
  packages/config/src/merge.js
  packages/config/src/normalize.js
  packages/config/src/utils/merge.js
Labels: type: feature

#2564 feat: refactor configuration merge logic
  packages/config/src/merge.js
  packages/config/src/utils/group.js
  packages/config/tests/normalize/fixtures/merge_netlify_toml_default/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature

#2566 feat: move validation related to duplicated plugins configuration
  packages/config/src/merge.js
  packages/config/src/merge_normalize.js
  packages/config/src/validate/identical.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: feature

#2567 feat: allow context-specific plugins configuration
  packages/config/src/main.js
  packages/config/src/merge.js
  packages/config/src/utils/merge.js
  packages/config/tests/normalize/fixtures/merge_netlify_toml_context/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature

#2570 feat: add a test related to context-specific plugins config
  package-lock.json
  packages/config/tests/normalize/fixtures/merge_netlify_toml_context_last/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
Labels: type: feature

#2467 fix: improve lingering processes warning message
  packages/build/src/log/messages/core.js
Labels: type: bug

#2576 fix: warning message link
  package-lock.json
  packages/build/package.json
  packages/build/src/log/messages/core.js
Labels: type: bug

#2587 chore: add p-reduce and path-key to `renovate.json5`
  renovate.json5
Labels: type: chore

#2572 feat: deep merge context-specific plugin config
  packages/config/src/utils/merge.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/normalize/fixtures/merge_netlify_toml_context/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
Labels: type: feature

#2596 chore: allow spaces in CLI flags in tests
  packages/build/tests/helpers/common.js
Labels: type: chore

#2595 feat!: simplify `inlineConfig`, `defaultConfig` and `cachedConfig` CLI flags
  packages/build/src/core/flags.js
  packages/build/tests/commands/tests.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/error/tests.js
  packages/build/tests/log/tests.js
  packages/build/tests/plugins/tests.js
  packages/config/src/bin/flags.js
  packages/config/src/default.js
  packages/config/src/main.js
  packages/config/src/options/main.js
  packages/config/tests/base/tests.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
  packages/config/tests/log/tests.js
  packages/config/tests/normalize/tests.js
  packages/config/tests/validate/tests.js
Labels: type: feature

#2603 fix: `@netlify/config` major release
  package-lock.json
  packages/build/package.json
Labels: type: bug

#2606 chore: rename default branch from master to main
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/fossa.yml
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
  README.md
  codecov.yml
  packages/cache-utils/README.md
  packages/functions-utils/README.md
  packages/git-utils/README.md
  packages/run-utils/README.md
Labels: type: chore

#2612 feat: refactor incompatible/outdated plugins warnings
  packages/build/src/log/messages/plugins.js
Labels: type: feature

#2615 fix: failing esbuild tests
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/helpers/normalize.js
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
Labels: type: bug

#2338 chore: improve how feature flags are logged in debug mode
  packages/build/src/log/messages/config.js
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: chore

#2617 feat: start pinning plugin versions
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
Labels: type: feature

#2643 fix(deps): memoize-one cjs exports breaking changes
  package-lock.json
  packages/build/package.json
  packages/build/src/error/monitor/start.js
  packages/build/src/plugins/child/lazy.js
Labels: type: bug

#2636 chore: fix manual publishing
  package.json
Labels: type: chore

#2637 chore: fix some documentation links
  packages/build/tests/README.md
Labels: type: chore

#2638 fix: fix `utils.git` for repositories with `main` branch
  packages/git-utils/src/refs.js
Labels: type: bug

#2639 fix: support `main` branch in `@netlify/config`
  packages/config/README.md
  packages/config/src/options/branch.js
Labels: type: bug

#2641 feat: validate all contexts in configuration
  package-lock.json
  packages/config/package.json
  packages/config/src/context.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: chore, type: feature

#2648 feat: improve context-specific configuration validation
  packages/config/src/context.js
  packages/config/src/log/logger.js
  packages/config/src/log/messages.js
  packages/config/src/log/theme.js
  packages/config/src/main.js
  packages/config/src/validate/context.js
  packages/config/tests/validate/fixtures/build_context_plugins_nowarn_global/netlify.toml
  packages/config/tests/validate/fixtures/build_context_plugins_nowarn_none/netlify.toml
  packages/config/tests/validate/fixtures/build_context_plugins_warn/netlify.toml
  packages/config/tests/validate/fixtures/build_context_plugins_warn_inputs/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: feature

#2653 fix(deps): memoize-one breaking change in exports
  package-lock.json
  packages/build/package.json
  packages/build/src/error/monitor/start.js
  packages/build/src/plugins/child/lazy.js
Labels: type: bug

#2652 fix: add some newlines before some warning message
  packages/config/src/log/messages.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: bug

#2671 chore: do not upgrade modules using ES modules
  renovate.json5
Labels: type: chore

#2651 fix: missing colors in `@netlify/config` warnings
  packages/config/src/log/logger.js
  packages/config/src/log/messages.js
Labels: type: bug

#2649 chore(node_version): move node version assertion logic to an earlier point in build
  package-lock.json
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/core/user_node_version.js
  packages/build/src/plugins/node_version.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: init/deprecate-node-8, proj/move-builds-from-node8, type: chore

#2673 feat: remove `--ui-plugins` CLI flag
  package-lock.json
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/core/normalize_flags.js
  packages/build/src/log/messages/config.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2677 fix: do not fail when plugin error has `toJSON()` method
  packages/build/src/error/build.js
  packages/build/src/error/info.js
  packages/build/tests/error/fixtures/plugin_error_to_json/manifest.yml
  packages/build/tests/error/fixtures/plugin_error_to_json/netlify.toml
  packages/build/tests/error/fixtures/plugin_error_to_json/plugin.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/error/tests.js
Labels: type: bug

#2674 feat: allow buildbot to pin plugin versions in `@netlify/config`
  packages/config/src/validate/validations.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
  packages/config/tests/validate/fixtures/plugins_pinned_version_string/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: feature

#2634 fix(telemetry): fwd relevant `nodeVersion` information
  packages/build/src/core/main.js
  packages/build/src/telemetry/main.js
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/telemetry/tests.js
Labels: init/deprecate-node-8, proj/move-builds-from-node8, type: bug

#2688 chore: improve HTTP mocking test helper
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/helpers/server.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
Labels: type: chore

#2689 chore: fix snapshot normalization of ports
  packages/build/tests/helpers/normalize.js
Labels: type: chore

#2691 feat: improve debugging of plugins versioning
  packages/build/src/core/main.js
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/spawn.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2683 feat: call `updatePlugin` to pin plugins' versions
  .gitignore
  packages/build/src/commands/run_commands.js
  packages/build/src/core/main.js
  packages/build/src/plugins/pinned_version.js
  packages/build/src/plugins_core/add.js
  packages/build/tests/plugins/fixtures/pin_build_failed/.netlify/plugins/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/pin_build_failed/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/pin_build_failed/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/pin_build_failed/.netlify/plugins/package.json
  packages/build/tests/plugins/fixtures/pin_build_failed/netlify.toml
  packages/build/tests/plugins/fixtures/pin_build_failed/package.json
  packages/build/tests/plugins/fixtures/pin_module/netlify.toml
  packages/build/tests/plugins/fixtures/pin_module/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/fixtures/pin_module/node_modules/netlify-plugin-test/manifest.yml
  packages/build/tests/plugins/fixtures/pin_module/node_modules/netlify-plugin-test/package.json
  packages/build/tests/plugins/fixtures/pin_module/package.json
  packages/build/tests/plugins/fixtures/pin_plugin_failed/.netlify/plugins/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/pin_plugin_failed/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/pin_plugin_failed/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/pin_plugin_failed/.netlify/plugins/package.json
  packages/build/tests/plugins/fixtures/pin_plugin_failed/netlify.toml
  packages/build/tests/plugins/fixtures/pin_plugin_failed/package.json
  packages/build/tests/plugins/fixtures/pin_success/.netlify/plugins/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/pin_success/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/pin_success/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/pin_success/.netlify/plugins/package.json
  packages/build/tests/plugins/fixtures/pin_success/netlify.toml
  packages/build/tests/plugins/fixtures/pin_success/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2693 chore: revert updatePlugin PR
  packages/build/src/plugins/pinned_version.js
Labels: type: bug, type: chore

#2694 fix: use the proper conventional commit in PR title
  packages/build/src/plugins/pinned_version.js
Labels: type: bug

#2696 fix: improve temporary fix for the `updatePlugin` bug
  packages/build/src/plugins/pinned_version.js
Labels: type: bug

#2702 fix: percent-encode the `package` parameter of the `updatePlugin` endpoint
  packages/build/src/plugins/pinned_version.js
Labels: type: bug

#2703 fix: do not run `updateSite` for `netlify.toml`-only plugins
  packages/build/src/plugins/pinned_version.js
  packages/build/tests/plugins/fixtures/pin_module/.netlify/plugins/node_modules/.package-lock.json
  packages/build/tests/plugins/fixtures/pin_module/.netlify/plugins/node_modules/netlify-plugin-contextual-env/.circleci/config.yml
  packages/build/tests/plugins/fixtures/pin_module/.netlify/plugins/node_modules/netlify-plugin-contextual-env/.prettierrc
  packages/build/tests/plugins/fixtures/pin_module/.netlify/plugins/node_modules/netlify-plugin-contextual-env/CHANGELOG.md
  packages/build/tests/plugins/fixtures/pin_module/.netlify/plugins/node_modules/netlify-plugin-contextual-env/README.md
  packages/build/tests/plugins/fixtures/pin_module/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/pin_module/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/pin_module/.netlify/plugins/node_modules/netlify-plugin-contextual-env/src/index.js
  packages/build/tests/plugins/fixtures/pin_module/.netlify/plugins/node_modules/netlify-plugin-contextual-env/src/index.test.js
  packages/build/tests/plugins/fixtures/pin_module/.netlify/plugins/package-lock.json
  packages/build/tests/plugins/fixtures/pin_module/.netlify/plugins/package.json
  packages/build/tests/plugins/fixtures/pin_success/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: bug

#2704 fix: re-enable `updateSite` endpoint
  packages/build/src/plugins/pinned_version.js
Labels: type: bug

#2709 feat(plugins): expose NETLIFY_API_HOST constant to plugins
  packages/build/src/core/constants.js
  packages/build/src/core/main.js
  packages/build/src/core/normalize_flags.js
  packages/build/tests/plugins/fixtures/netlify_api_host/manifest.yml
  packages/build/tests/plugins/fixtures/netlify_api_host/netlify.toml
  packages/build/tests/plugins/fixtures/netlify_api_host/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2706 chore: improve test snapshots of plugin versions
  packages/build/tests/helpers/normalize.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: chore

#2713 chore: fix tests related to version pinning
  packages/build/tests/plugins/fixtures/pin_build_failed/netlify.toml
  packages/build/tests/plugins/fixtures/pin_plugin_failed/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: chore, type: feature

#2714 feat: pin plugins versions
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature
