Repository netlify/build, pull requests merged in 2021-09, with the labels that each got.

#3586 fix: error handling of syntax errors in plugin configuration changes
  packages/build/src/core/config.js
  packages/build/tests/plugins/fixtures/config_mutate_invalid_syntax/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_invalid_syntax/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_invalid_syntax/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/config/src/error.js
  packages/config/src/mutations/apply.js
Labels: type: bug, automerge

#3590 fix: add warning message when the same header is used with different cases
  packages/config/src/headers.js
  packages/config/src/log/messages.js
  packages/config/tests/parse/fixtures/headers_duplicate_case/_headers
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/parse/tests.js
Labels: type: bug

#3593 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: type: chore

#3594 fix: monitor whether headers with different cases have the same path
  packages/config/src/log/messages.js
  packages/config/tests/parse/fixtures/headers_duplicate_case_different/_headers
  packages/config/tests/parse/fixtures/headers_duplicate_case_same/_headers
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/parse/tests.js
Labels: type: bug

#3597 chore: add a test for `repositoryRoot`
  packages/build/tests/helpers/common.js
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/cwd/tests.js
Labels: type: chore

#3598 fix: repository root directory validation
  packages/config/src/base.js
  packages/config/src/files.js
  packages/config/src/validate/helpers.js
  packages/config/src/validate/validations.js
  packages/config/tests/validate/fixtures/build_publish_parent_build/base/netlify.toml
  packages/config/tests/validate/fixtures/build_publish_parent_build/netlify.toml
  packages/config/tests/validate/fixtures/build_publish_parent_root/base/netlify.toml
  packages/config/tests/validate/fixtures/build_publish_parent_root/netlify.toml
  packages/config/tests/validate/fixtures/function_config_invalid_included_files/netlify.toml
  packages/config/tests/validate/fixtures/function_config_invalid_included_files_2/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: bug, automerge

#3609 chore: fix broken test snapshots with Ava v3
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
Labels: type: chore

#3610 chore: remove unused feature flag
  packages/build/src/core/feature_flags.js
Labels: type: chore

#3608 feat: warn when `_headers`/`_redirects` file is missing
  packages/build/src/core/feature_flags.js
  packages/build/src/core/main.js
  packages/build/src/core/missing_side_file.js
  packages/build/src/log/messages/core.js
  packages/build/tests/core/fixtures/missing_headers_warning/_headers
  packages/build/tests/core/fixtures/missing_headers_warning/netlify.toml
  packages/build/tests/core/fixtures/missing_headers_warning/publish/.gitkeep
  packages/build/tests/core/fixtures/missing_redirects_absent/netlify.toml
  packages/build/tests/core/fixtures/missing_redirects_absent/publish/_redirects
  packages/build/tests/core/fixtures/missing_redirects_base/base/_redirects
  packages/build/tests/core/fixtures/missing_redirects_base/base/netlify.toml
  packages/build/tests/core/fixtures/missing_redirects_base/base/publish/.gitkeep
  packages/build/tests/core/fixtures/missing_redirects_base/netlify.toml
  packages/build/tests/core/fixtures/missing_redirects_none/netlify.toml
  packages/build/tests/core/fixtures/missing_redirects_none/publish/.gitkeep
  packages/build/tests/core/fixtures/missing_redirects_present/_redirects
  packages/build/tests/core/fixtures/missing_redirects_present/netlify.toml
  packages/build/tests/core/fixtures/missing_redirects_present/publish/_redirects
  packages/build/tests/core/fixtures/missing_redirects_warning/_redirects
  packages/build/tests/core/fixtures/missing_redirects_warning/netlify.toml
  packages/build/tests/core/fixtures/missing_redirects_warning/publish/.gitkeep
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: type: feature, automerge

#3613 chore: do not prettify `.release-please-manifest.json`
  package.json
Labels: type: chore

#3612 feat: remove `netlify_build_warning_missing_headers` feature flag
  packages/build/src/core/feature_flags.js
  packages/build/src/core/main.js
  packages/build/src/core/missing_side_file.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: type: feature, automerge

#3616 chore: fix test snapshots not updating
  packages/build/tests/error/tests.js
  packages/build/tests/install/tests.js
  packages/build/tests/log/tests.js
Labels: type: chore, automerge

#3623 fix: `utils.git` crashes when commit messages or authors have uncommon characters
  packages/git-utils/src/commits.js
Labels: type: bug

#3625 chore: fix some test to use a more recent Node.js version
  packages/build/tests/core/tests.js
Labels: type: chore, automerge

#3619 feat(build): pass ES module feature flag to zisi
  .eslintrc.js
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/core/fixtures/functions_es_modules/functions/function_with_es_module.js
  packages/build/tests/core/fixtures/functions_es_modules/helper.js
  packages/build/tests/core/fixtures/functions_es_modules/netlify.toml
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: type: feature, automerge

#3640 fix(ci): node 10 npm setup process
  .github/workflows/workflow.yml
  package.json
Labels: type: bug, automerge

#3638 fix: remove zisiEsbuildDynamicImports feature flag
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins_core/functions/index.js
Labels: type: bug, automerge

#3642 chore: remove lerna
  package-lock.json
  package.json
Labels: type: chore

#3630 feat: use internal functions directory in functions utils
  packages/build/src/plugins/child/utils.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/functions-utils/src/main.js
  packages/functions-utils/tests/fixtures/file/test.js
  packages/functions-utils/tests/fixtures/file/test_2.js
  packages/functions-utils/tests/main.js
Labels: type: feature

#3632 feat: add support for `parseWithEsbuild` feature flag
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/core/tests.js
Labels: type: feature, automerge

#3671 chore: add CI tests with unpinned dependencies versions
  .github/workflows/workflow.yml
Labels: type: chore

#3674 fix: check for functionsSrc in "module not found" error
  packages/build/src/plugins_core/functions/error.js
Labels: type: bug
