Repository netlify/build, pull requests merged in 2021-11, with the labels that each got.

#3797 feat(build): add `INTERNAL_FUNCTIONS_SRC` to types
  packages/build/test-d/netlify_plugin_options.ts
  packages/build/types/netlify_plugin_options.d.ts
Labels: type: feature, automerge

#3807 fix: report TOML parsing errors as user errors
  packages/build/src/error/parse/normalize.js
  packages/build/tests/error/fixtures/invalid_instance/manifest.yaml
  packages/build/tests/error/fixtures/invalid_instance/netlify.toml
  packages/build/tests/error/fixtures/invalid_instance/plugin.js
  packages/build/tests/error/fixtures/toml_parsing/netlify.toml
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/error/tests.js
Labels: type: bug, automerge

#3812 fix: updates to plugin options types
  packages/build/test-d/config/functions.ts
  packages/build/types/config/functions.d.ts
  packages/build/types/options/netlify_plugin_build_util.d.ts
Labels: type: bug, automerge

#3816 fix: export more build plugin types
  packages/build/types/index.d.ts
  packages/build/types/netlify_event.d.ts
  packages/build/types/netlify_event_handler.d.ts
  packages/build/types/netlify_plugin.d.ts
  packages/build/types/netlify_plugin_constants.d.ts
  packages/build/types/netlify_plugin_options.d.ts
  packages/build/types/options/index.d.ts
Labels: type: bug, automerge

#3832 chore: improve tests of plugin TypeScript types
  packages/build/test-d/config/build.ts
  packages/build/test-d/config/functions.ts
  packages/build/test-d/config/inputs.ts
  packages/build/test-d/config/netlify_config.ts
  packages/build/test-d/netlify_plugin.ts
  packages/build/test-d/netlify_plugin_options.ts
  packages/build/test-d/options/netlify_plugin_build_util.ts
  packages/build/test-d/options/netlify_plugin_cache_util.ts
  packages/build/test-d/options/netlify_plugin_git_util.ts
  packages/build/test-d/options/netlify_plugin_run_util.ts
  packages/build/test-d/options/netlify_plugin_status_util.ts
Labels: type: chore

#3817 feat: pass `nftTranspile` feature flag to ZISI
  packages/build/src/plugins_core/functions/feature_flags.js
  packages/build/tests/core/tests.js
Labels: type: feature

#3831 feat: warn about large function bundles
  packages/build/src/log/messages/core_steps.js
  packages/build/tests/core/fixtures/zip_too_big/netlify/functions/foo.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: type: feature, automerge

#3843 fix: improve verbosity of `netlifyConfig.functions.*` changes
  packages/build/src/log/messages/mutations.js
  packages/build/src/steps/update_config.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_no_log_debug/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_functions_no_log_debug/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_functions_no_log_debug/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: bug, automerge

#3850 fix: allow `interface`s to be used as Plugins generics inputs
  packages/build/test-d/config/inputs.ts
  packages/build/types/config/inputs.d.ts
  packages/build/types/netlify_event_handler.d.ts
  packages/build/types/netlify_plugin_options.d.ts
Labels: type: bug

#3849 Revert "feat: warn about large function bundles"
  packages/build/src/log/messages/core_steps.js
  packages/build/tests/core/fixtures/zip_too_big/netlify/functions/foo.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: type: chore, automerge

#3854 feat: add `buildbot_nft_transpile_esm` feature flag
  packages/build/src/plugins_core/functions/feature_flags.js
  packages/build/tests/core/tests.js
Labels: type: feature

#3857 feat: add TypeScript error information on type failures
  packages/build/src/error/monitor/print.js
  packages/build/src/error/monitor/report.js
  packages/build/src/error/parse/parse.js
  packages/build/src/error/parse/serialize_log.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/logic.js
  packages/build/src/plugins/child/typescript.js
  packages/build/tests/error/fixtures/typescript/manifest.yml
  packages/build/tests/error/fixtures/typescript/netlify.toml
  packages/build/tests/error/fixtures/typescript/plugin.ts
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/error/tests.js
  packages/build/tests/helpers/normalize.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature, automerge

#3859 fix: calling `ts-node` in production
  packages/build/src/plugins/child/typescript.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/error/tests.js
Labels: type: bug, automerge

#3862 fix: simplify plugin types debugging
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/logic.js
  packages/build/src/plugins/child/typescript.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/plugins/fixtures/ts_transpile/plugin.ts
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: bug, automerge

#3874 chore: simplify `renovate.json5`
  renovate.json5
Labels: type: chore

#3873 chore!: drop support for Node 10
  .github/workflows/workflow.yml
  package-lock.json
  package.json
  packages/build/package.json
  packages/build/src/plugins/node_version.js
  packages/build/tests/core/tests.js
  packages/build/tests/helpers/normalize.js
  packages/build/tests/plugins/fixtures/engines/package.json
  packages/build/tests/plugins/fixtures/version_greater_than_minimum/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/cache-utils/package.json
  packages/config/package.json
  packages/functions-utils/package.json
  packages/git-utils/package.json
  packages/run-utils/package.json
Labels: type: chore

#3877 fix: netlify build dependencies
  package-lock.json
  packages/build/package.json
Labels: type: bug, automerge

#3881 chore: simplify tests after removing Node 10 support
  packages/build/tests/error/tests.js
  packages/build/tests/plugins/tests.js
Labels: type: chore, automerge

#3882 fix: remove `@ungap/from-entries`
  packages/build/package.json
  packages/build/src/plugins/list.js
  packages/config/package.json
  packages/config/src/env/main.js
Labels: type: chore, type: bug, automerge

#3883 fix: remove `array-flat-polyfill`
  packages/build/package.json
  packages/build/src/core/bin.js
  packages/build/src/core/main.js
  packages/build/src/plugins/child/main.js
  packages/build/src/utils/polyfills.js
  packages/cache-utils/package.json
  packages/cache-utils/src/main.js
  packages/cache-utils/src/utils/polyfills.js
  packages/config/package.json
  packages/config/src/bin/main.js
  packages/config/src/main.js
  packages/config/src/utils/polyfills.js
Labels: type: chore, type: bug, automerge

#3880 fix: improve plugin process IPC
  packages/build/src/error/build.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/ipc.js
  packages/build/src/plugins/load.js
  packages/build/src/plugins/spawn.js
Labels: type: bug, automerge

#3895 fix: force a release
  package.json
Labels: type: bug, automerge

#3896 fix: force release
  packages/build/package.json
Labels: type: bug, automerge
