Repository netlify/build, pull requests merged in 2021-05, with the labels that each got.

#2681 feat: add support for `functions.included_files` config property
  package-lock.json
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/core/fixtures/functions_config_1/netlify.toml
  packages/build/tests/core/fixtures/functions_config_2/netlify.toml
  packages/build/tests/core/fixtures/functions_config_3/netlify.toml
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/config/src/functions_config.js
  packages/config/src/validate/validations.js
  packages/config/tests/normalize/fixtures/function_config_included_files/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/validate/fixtures/function_config_invalid_included_files_1/netlify.toml
  packages/config/tests/validate/fixtures/function_config_invalid_included_files_2/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: feature

#2717 fix: local builds version pinning
  packages/config/src/api/build_settings.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/api/tests.js
Labels: type: feature

#2739 chore: remove some dead code
  packages/build/src/plugins/resolve.js
Labels: type: chore

#2732 feat: add more plugin metrics
  packages/build/src/core/main.js
  packages/build/src/telemetry/main.js
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/telemetry/tests.js
Labels: type: feature

#2740 feat: pin `netlify.toml`-installed plugins versions
  packages/build/src/core/main.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/pinned_version.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/helpers/server.js
  packages/build/tests/plugins/fixtures/pin_config_module/netlify.toml
  packages/build/tests/plugins/fixtures/pin_config_module/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/pin_config_module/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/pin_config_module/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/pin_config_module/package.json
  packages/build/tests/plugins/fixtures/pin_config_success/.netlify/plugins/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/pin_config_success/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/pin_config_success/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/pin_config_success/.netlify/plugins/package.json
  packages/build/tests/plugins/fixtures/pin_config_success/netlify.toml
  packages/build/tests/plugins/fixtures/pin_config_success/package.json
  packages/build/tests/plugins/fixtures/pin_config_ui/.netlify/plugins/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/pin_config_ui/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/pin_config_ui/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/pin_config_ui/.netlify/plugins/package.json
  packages/build/tests/plugins/fixtures/pin_config_ui/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2749 fix: 404 in production with `updatePlugin`
  packages/build/src/plugins/pinned_version.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2753 fix: simplify version pinning logic
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
Labels: type: chore, type: feature

#2756 feat: add support for `0.*` versions in outdated plugins message
  packages/build/src/log/messages/plugins.js
  packages/build/src/utils/semver.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2758 feat: add support for `0.*` versions when pinning versions
  packages/build/src/plugins/pinned_version.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2764 feat: fix test snapshots related to version pinning
  packages/build/tests/helpers/normalize.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2762 feat: improve version pinning
  packages/build/src/plugins/compatibility.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2777 chore: upgrade `js-client`
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/status/tests.js
  packages/config/package.json
Labels: type: chore

#2773 feat: show warning about modules with dynamic imports
  package-lock.json
  packages/build/src/log/messages/core_commands.js
  packages/build/tests/core/fixtures/esbuild_errors_1/functions/function_simple.js
  packages/build/tests/core/fixtures/esbuild_errors_1/functions/function_with_dynamic_require.js
  packages/build/tests/core/fixtures/esbuild_errors_1/functions/function_with_native.js
  packages/build/tests/core/fixtures/esbuild_errors_1/functions/node_modules/test/index.js
  packages/build/tests/core/fixtures/esbuild_errors_1/functions/node_modules/test/native.node
  packages/build/tests/core/fixtures/esbuild_errors_1/functions/node_modules/test/package.json
  packages/build/tests/core/fixtures/esbuild_errors_1/functions/package.json
  packages/build/tests/core/fixtures/esbuild_errors_1/netlify.toml
  packages/build/tests/core/fixtures/esbuild_errors_2/functions/function_with_module.js
  packages/build/tests/core/fixtures/esbuild_errors_2/functions/node_modules/@org/another-test/index.js
  packages/build/tests/core/fixtures/esbuild_errors_2/functions/node_modules/@org/another-test/package.json
  packages/build/tests/core/fixtures/esbuild_errors_2/functions/node_modules/test/index.js
  packages/build/tests/core/fixtures/esbuild_errors_2/functions/node_modules/test/package.json
  packages/build/tests/core/fixtures/esbuild_errors_2/functions/package.json
  packages/build/tests/core/fixtures/esbuild_errors_2/netlify.toml
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: type: feature

#2785 feat(config): return repository root
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/config/README.md
  packages/config/src/main.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature

#2783 feat: allow commands to add tags to the metrics + `bundler` tag
  packages/build/src/commands/core_command.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/src/time/main.js
  packages/build/src/time/report.js
  packages/build/tests/time/fixtures/functions_esbuild/functions/function_one.js
  packages/build/tests/time/fixtures/functions_esbuild/functions/function_two.js
  packages/build/tests/time/fixtures/functions_esbuild/netlify.toml
  packages/build/tests/time/fixtures/functions_zisi/functions/function_one.js
  packages/build/tests/time/fixtures/functions_zisi/functions/function_two.js
  packages/build/tests/time/fixtures/functions_zisi/netlify.toml
  packages/build/tests/time/tests.js
Labels: type: feature

#2791 feat: change shape of `compatibility` field
  packages/build/src/plugins/list.js
Labels: type: feature

#2795 feat: simplify version pinning logic
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/list.js
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2798 feat: add build logs to explain how to upgrade plugins
  packages/build/src/log/messages/compatibility.js
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/spawn.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2797 fix: improve `compatibility`-related warning messages
  packages/build/src/log/messages/compatibility.js
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: bug

#2824 chore: fix test coverage upload
  .github/workflows/workflow.yml
Labels: type: chore

#2826 chore: add default `config.functions.*`
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/config/src/functions_config.js
  packages/config/src/normalize.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: chore, type: feature

#2838 feat(config): consider package.json when detecting base directory
  packages/config/src/options/base.js
  packages/config/tests/cwd/fixtures/build_base_package_json/netlify.toml
  packages/config/tests/cwd/fixtures/build_base_package_json/subdir/package.json
  packages/config/tests/cwd/fixtures/relative_cwd/netlify.toml
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/cwd/tests.js
Labels: type: feature

#2837 feat: add `installType` to telemetry
  packages/build/src/telemetry/main.js
  packages/build/tests/telemetry/fixtures/plugin_package/netlify.toml
  packages/build/tests/telemetry/fixtures/plugin_package/node_modules/netlify-plugin-test/index.js
  packages/build/tests/telemetry/fixtures/plugin_package/node_modules/netlify-plugin-test/manifest.yml
  packages/build/tests/telemetry/fixtures/plugin_package/node_modules/netlify-plugin-test/package.json
  packages/build/tests/telemetry/fixtures/plugin_package/package.json
  packages/build/tests/telemetry/fixtures/plugin_success/manifest.yml
  packages/build/tests/telemetry/fixtures/plugin_success/netlify.toml
  packages/build/tests/telemetry/fixtures/plugin_success/plugin.js
  packages/build/tests/telemetry/fixtures/plugins_cache_config/.netlify/plugins/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/telemetry/fixtures/plugins_cache_config/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/telemetry/fixtures/plugins_cache_config/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/telemetry/fixtures/plugins_cache_config/.netlify/plugins/package.json
  packages/build/tests/telemetry/fixtures/plugins_cache_config/netlify.toml
  packages/build/tests/telemetry/fixtures/plugins_cache_config/package.json
  packages/build/tests/telemetry/fixtures/plugins_cache_ui/.netlify/plugins/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/telemetry/fixtures/plugins_cache_ui/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/telemetry/fixtures/plugins_cache_ui/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/telemetry/fixtures/plugins_cache_ui/.netlify/plugins/package.json
  packages/build/tests/telemetry/fixtures/plugins_cache_ui/package.json
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/telemetry/tests.js
Labels: type: feature

#2840 feat: make `netlifyConfig` readonly
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/mutations.js
  packages/build/tests/plugins/fixtures/config_readonly_deep/manifest.yml
  packages/build/tests/plugins/fixtures/config_readonly_deep/netlify.toml
  packages/build/tests/plugins/fixtures/config_readonly_deep/plugin.js
  packages/build/tests/plugins/fixtures/config_readonly_define/manifest.yml
  packages/build/tests/plugins/fixtures/config_readonly_define/netlify.toml
  packages/build/tests/plugins/fixtures/config_readonly_define/plugin.js
  packages/build/tests/plugins/fixtures/config_readonly_delete/manifest.yml
  packages/build/tests/plugins/fixtures/config_readonly_delete/netlify.toml
  packages/build/tests/plugins/fixtures/config_readonly_delete/plugin.js
  packages/build/tests/plugins/fixtures/config_readonly_prevent/manifest.yml
  packages/build/tests/plugins/fixtures/config_readonly_prevent/netlify.toml
  packages/build/tests/plugins/fixtures/config_readonly_prevent/plugin.js
  packages/build/tests/plugins/fixtures/config_readonly_proto/manifest.yml
  packages/build/tests/plugins/fixtures/config_readonly_proto/netlify.toml
  packages/build/tests/plugins/fixtures/config_readonly_proto/plugin.js
  packages/build/tests/plugins/fixtures/config_readonly_set/manifest.yml
  packages/build/tests/plugins/fixtures/config_readonly_set/netlify.toml
  packages/build/tests/plugins/fixtures/config_readonly_set/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2845 feat: pass `netlifyConfig` to each event handler
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run_command.js
  packages/build/src/core/main.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/load.js
Labels: type: feature

#2847 feat: pass mutated `netlifyConfig` everywhere
  packages/build/src/commands/plugin.js
  packages/build/src/commands/return.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/main.js
  packages/build/src/plugins/child/run.js
Labels: type: feature

#2849 chore: fix some comments
  packages/build/src/commands/constants.js
  packages/build/src/core/constants.js
  packages/config/src/files.js
Labels: type: chore

#2850 feat: allow `constants` to be mutated during builds
  packages/build/src/commands/constants.js
  packages/build/src/commands/run_command.js
  packages/build/src/core/constants.js
  packages/build/src/core/main.js
Labels: type: feature

#2852 feat: allow mutating `netlifyConfig.functionsDirectory`
  packages/build/src/plugins/child/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_build/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_build/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_build/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_bundling/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_bundling/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_bundling/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_bundling/test_functions/.gitkeep
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_constants/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_constants/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_constants/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_constants/test_functions/.gitkeep
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_default/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_default/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_default/netlify/functions/.gitkeep
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_default/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_default/test_functions/.gitkeep
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_nested/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_nested/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_nested/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_skip/functions/.gitkeep
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_skip/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_skip/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_skip/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_star/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_star/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_star/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_utils/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_utils/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_utils/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_utils/test_functions/test.js
  packages/build/tests/plugins/fixtures/config_mutate_general/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_general/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_general/one.js
  packages/build/tests/plugins/fixtures/config_mutate_general/test_functions/.gitkeep
  packages/build/tests/plugins/fixtures/config_mutate_general/two.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2857 feat: allow mutating `netlifyConfig.functions`
  packages/build/src/plugins/child/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_any/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_functions_any/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_functions_any/netlify/functions/.gitkeep
  packages/build/tests/plugins/fixtures/config_mutate_functions_any/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_bundling/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_functions_bundling/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_functions_bundling/netlify/functions/test.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_bundling/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2864 chore: update package dependency graph in README
  CONTRIBUTING.md
Labels: type: chore

#2865 feat: improve normalization of `constants`
  packages/build/src/core/constants.js
  packages/build/tests/plugins/fixtures/publish_default/plugin.js
  packages/build/tests/plugins/fixtures/publish_default_base/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2866 feat: allow mutating `build.publish` and `build.edge_handlers`
  packages/build/src/plugins/child/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_constants/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_constants/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_constants/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_constants/test/.gitkeep
  packages/build/tests/plugins/fixtures/config_mutate_publish_constants/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_publish_constants/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_publish_constants/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_publish_constants/test/.gitkeep
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2869 chore: remove dead code
  packages/build/src/commands/core_command.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/dry.js
  packages/build/src/core/main.js
  packages/build/src/plugins_core/functions/index.js
Labels: type: chore

#2868 feat: make build command a core command
  packages/build/src/commands/core_command.js
  packages/build/src/commands/error.js
  packages/build/src/commands/get.js
  packages/build/src/commands/return.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/dry.js
  packages/build/src/core/main.js
  packages/build/src/log/description.js
  packages/build/src/log/messages/commands.js
  packages/build/src/log/messages/dry.js
  packages/build/src/plugins_core/build_command.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/src/plugins_core/functions_install/index.js
Labels: type: feature

#2875 feat: allow mutating `build.functions`, `functions.directory` and `functions.*.directory`
  packages/build/src/plugins/child/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_build/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_build/test_functions/.gitkeep
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_nested/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_nested/test_functions/.gitkeep
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_star/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_star/test_functions/.gitkeep
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2874 feat: allow mutating `build.command`
  packages/build/src/commands/get.js
  packages/build/src/commands/run_command.js
  packages/build/src/core/dry.js
  packages/build/src/core/main.js
  packages/build/src/log/description.js
  packages/build/src/log/messages/commands.js
  packages/build/src/log/messages/dry.js
  packages/build/src/plugins/child/mutations.js
  packages/build/src/plugins_core/build_command.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/plugins/fixtures/config_mutate_build_command_add/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_build_command_add/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_build_command_add/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_build_command_change/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_build_command_change/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_build_command_change/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_build_command_remove/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_build_command_remove/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_build_command_remove/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature
