Repository netlify/build, pull requests merged in 2021-03, with the labels that each got.

#2320 feat: print migration guides
  packages/build/src/log/logger.js
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/list.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2321 feat: improve tests related to `compatibility`
  packages/build/tests/helpers/normalize.js
  packages/build/tests/plugins/fixtures/plugins_compat_node_version/.env
  packages/build/tests/plugins/fixtures/plugins_compat_node_version/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2335 chore: release @netlify/build 9.6.0
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, type: chore

#2336 feat: do not sort `compatibility` field
  packages/build/src/plugins/list.js
Labels: type: feature

#2337 feat: improve `migrationGuide` test
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2322 feat: add `compatibility[*].siteDependencies`
  packages/build/src/core/main.js
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/fixtures/plugins_compat_site_dependencies/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_compat_site_dependencies/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2339 Add branded README image
  README.md
  build.png
Labels: type: feature

#2350 fix: stop printing output from esbuild
  packages/build/src/log/messages/core_commands.js
Labels: type: bug

#2358 fix: fix esbuild error reporting
  packages/build/src/log/messages/core_commands.js
  packages/build/src/plugins_core/functions/index.js
Labels: type: bug

#2361 fix: add dependency error messages for esbuild
  packages/build/src/plugins_core/functions/error.js
  packages/build/tests/install/fixtures/optional-many/functions/index.js
  packages/build/tests/install/fixtures/optional-many/functions/package.json
  packages/build/tests/install/fixtures/optional-many/netlify.toml
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/install/tests.js
Labels: type: bug

#2349 fix: telemetry
  packages/build/package.json
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/core/normalize_flags.js
  packages/build/src/core/severity.js
  packages/build/src/telemetry/complete.js
  packages/build/src/telemetry/main.js
  packages/build/src/telemetry/request.js
  packages/build/src/telemetry/track.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/helpers/main.js
  packages/build/tests/telemetry/fixtures/cancel/manifest.yml
  packages/build/tests/telemetry/fixtures/cancel/netlify.toml
  packages/build/tests/telemetry/fixtures/cancel/plugin.js
  packages/build/tests/telemetry/fixtures/invalid/netlify.toml
  packages/build/tests/telemetry/fixtures/plugin_error/manifest.yml
  packages/build/tests/telemetry/fixtures/plugin_error/netlify.toml
  packages/build/tests/telemetry/fixtures/plugin_error/plugin.js
  packages/build/tests/telemetry/fixtures/success/netlify.toml
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/telemetry/tests.js
Labels: type: bug

#2364 chore: fix Node 8 in CI
  .gitignore
  lerna.json
  package-lock.json
  package.json
  renovate.json5
Labels: type: bug, type: chore

#2288 feat: allow passing Netlify API host to Netlify API client
  package-lock.json
  packages/build/src/core/config.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.snap
  packages/config/src/main.js
  packages/config/src/options/main.js
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: chore

#2372 chore: add `--cache-dir`
  packages/build/src/core/constants.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/core/normalize_flags.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/cache-utils/src/dir.js
Labels: type: chore

#2379 fix: fix `host` option in `@netlify/config`
  packages/build/src/core/config.js
  packages/config/src/main.js
  packages/config/src/options/main.js
Labels: type: bug

#2381 chore: small refactoring of `@netlify/config` options retrieval
  packages/config/src/main.js
Labels: type: chore

#2383 chore: fix `functions-utils` with new ZISI release
  packages/functions-utils/package.json
  packages/functions-utils/tests/main.js
Labels: type: chore

#2382 chore: simplify cache directory logic
  package-lock.json
  packages/build/package.json
  packages/build/src/core/constants.js
  packages/cache-utils/package.json
  packages/cache-utils/src/dir.js
  packages/cache-utils/src/list.js
  packages/cache-utils/src/main.js
  packages/cache-utils/src/path.js
  packages/cache-utils/tests/dir.js
  packages/cache-utils/tests/helpers/main.js
  renovate.json5
Labels: type: chore

#2394 fix: fix error handling when importing a non-existing local file
  packages/build/src/plugins_core/functions/error.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: type: bug

#2408 fix(compatibility): properly handle dependency ranges
  package-lock.json
  packages/build/package.json
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/fixtures/plugins_compat_site_dependencies_range/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_compat_site_dependencies_range/node_modules/dependency-with-range/package.json
  packages/build/tests/plugins/fixtures/plugins_compat_site_dependencies_range/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: bug

#2415 fix: build process never exits
  packages/build/src/telemetry/main.js
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/telemetry/tests.js
Labels: type: bug

#2400 chore: add trailing slash to publish command
  CONTRIBUTING.md
Labels: type: chore

#2418 chore: refactor `plugin.expectedVersion`
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/resolve.js
Labels: type: chore

#2422 feat: add warning messages when using plugins that are too recent and incompatible
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/spawn.js
  packages/build/tests/plugins/fixtures/plugins_incompatible_package_json/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_incompatible_package_json/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/plugins_incompatible_package_json/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/plugins_incompatible_package_json/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/plugins_incompatible_package_json/package.json
  packages/build/tests/plugins/fixtures/plugins_incompatible_package_json_same_major/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_incompatible_package_json_same_major/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/plugins_incompatible_package_json_same_major/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/plugins_incompatible_package_json_same_major/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/plugins_incompatible_package_json_same_major/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2419 chore: allow cross-package errors
  packages/build/src/core/main.js
  packages/build/src/error/build.js
  packages/build/src/error/handle.js
  packages/build/src/error/info.js
  packages/build/src/error/parse/parse.js
  packages/build/src/error/parse/properties.js
  packages/build/src/plugins/child/error.js
Labels: type: chore

#2425 fix: rename internal variable
  packages/build/src/error/info.js
Labels: type: bug, type: chore

#2390 feat: add functions configuration API to @netlify/config
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/config/src/functions_config.js
  packages/config/src/normalize.js
  packages/config/src/validate/helpers.js
  packages/config/src/validate/validations.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/fixtures/function_config_all_levels/netlify.toml
  packages/config/tests/normalize/fixtures/function_config_ambiguous/netlify.toml
  packages/config/tests/normalize/fixtures/function_config_top_level/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/fixtures/function_config_invalid_external_modules/netlify.toml
  packages/config/tests/validate/fixtures/function_config_invalid_function_block/netlify.toml
  packages/config/tests/validate/fixtures/function_config_invalid_ignored_modules/netlify.toml
  packages/config/tests/validate/fixtures/function_config_invalid_root/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: init/es-func-bundle, proj/func-config-api, type: feature

#2430 feat: add functions.*.node_bundler config property
  packages/config/src/functions_config.js
  packages/config/src/validate/validations.js
  packages/config/tests/normalize/fixtures/function_config_all_levels/netlify.toml
  packages/config/tests/normalize/fixtures/function_config_top_level/netlify.toml
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/validate/fixtures/function_config_invalid_node_bundler/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: init/es-func-bundle, proj/func-config-api, type: feature

#2414 feat: add functions configuration API to @netlify/build
  package-lock.json
  packages/build/package.json
  packages/build/src/commands/core_command.js
  packages/build/src/commands/run_command.js
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/core/fixtures/functions_config_1/functions/function_one.js
  packages/build/tests/core/fixtures/functions_config_1/functions/function_two.js
  packages/build/tests/core/fixtures/functions_config_1/netlify.toml
  packages/build/tests/core/fixtures/functions_config_2/functions/function_one.js
  packages/build/tests/core/fixtures/functions_config_2/netlify.toml
  packages/build/tests/core/fixtures/functions_config_3/functions/function_one.js
  packages/build/tests/core/fixtures/functions_config_3/functions/function_two.js
  packages/build/tests/core/fixtures/functions_config_3/netlify.toml
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/fixtures/optional-esbuild/functions/index.js
  packages/build/tests/install/fixtures/optional-esbuild/functions/package-lock.json
  packages/build/tests/install/fixtures/optional-esbuild/functions/package.json
  packages/build/tests/install/fixtures/optional-esbuild/netlify.toml
  packages/build/tests/install/fixtures/optional-many-esbuild/functions/index.js
  packages/build/tests/install/fixtures/optional-many-esbuild/functions/package.json
  packages/build/tests/install/fixtures/optional-many-esbuild/netlify.toml
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/install/tests.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: init/es-func-bundle, proj/func-config-api, type: feature

#2437 fix: reinstate notice about bundling errors and warnings
  packages/build/src/log/messages/core_commands.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/core/fixtures/esbuild_errors/functions/function_simple.js
  packages/build/tests/core/fixtures/esbuild_errors/functions/function_with_dynamic_require.js
  packages/build/tests/core/fixtures/esbuild_errors/functions/function_with_native.js
  packages/build/tests/core/fixtures/esbuild_errors/functions/node_modules/test/index.js
  packages/build/tests/core/fixtures/esbuild_errors/functions/node_modules/test/native.node
  packages/build/tests/core/fixtures/esbuild_errors/functions/node_modules/test/package.json
  packages/build/tests/core/fixtures/esbuild_errors/functions/package.json
  packages/build/tests/core/fixtures/esbuild_errors/netlify.toml
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: init/es-func-bundle, type: bug

#2432 fix: add `exit` event handler to prevent invalid exit code `0`
  packages/build/src/core/bin.js
  packages/build/src/core/severity.js
Labels: type: bug

#2438 fix(telemetry): wait for telemetry completion
  packages/build/src/core/feature_flags.js
  packages/build/src/core/normalize_flags.js
  packages/build/src/telemetry/main.js
  packages/build/src/telemetry/request.js
  packages/build/tests/helpers/server.js
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/telemetry/tests.js
Labels: action_item, init/build-telemetry-proxy, type: bug

#2447 feat: add context support to the functions block
  packages/config/src/context.js
  packages/config/tests/context/fixtures/array_merge/netlify.toml
  packages/config/tests/context/fixtures/branch/netlify.toml
  packages/config/tests/context/fixtures/branch_fallback/netlify.toml
  packages/config/tests/context/fixtures/context_default/netlify.toml
  packages/config/tests/context/fixtures/context_flag/netlify.toml
  packages/config/tests/context/fixtures/deep_merge/netlify.toml
  packages/config/tests/context/fixtures/priority_merge/netlify.toml
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
Labels: init/es-func-bundle, proj/func-config-api, type: feature

#2451 feat: move plugins initialization code
  packages/build/src/core/main.js
  packages/build/src/plugins/options.js
Labels: type: feature

#2454 feat: move core plugins logic
  packages/build/src/core/main.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins_core/add.js
  packages/build/src/plugins_core/list.js
Labels: type: feature

#2455 chore(telemetry): disable default request timeout in most of the telemetry tests
  packages/build/src/telemetry/main.js
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/telemetry/tests.js
Labels: init/build-telemetry-proxy, type: chore

#2457 feat: add skipped `plugin_runs`
  packages/build/src/core/main.js
  packages/build/src/status/report.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/status/tests.js
Labels: type: feature

#2439 chore: conditional build error logs
  packages/build/src/error/handle.js
  packages/build/src/error/parse/parse.js
  packages/build/src/error/type.js
Labels: init/build-telemetry-proxy, type: chore

#2458 fix(telemetry): set a default user_id for production builds
  packages/build/src/telemetry/main.js
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/telemetry/tests.js
Labels: init/build-telemetry-proxy, type: bug

#2461 chore(prepublish): use npm ci instead of npm install on prepublish
  package.json
Labels: type: chore

#2463 fix(telemetry): s/user_id/userId/
  packages/build/src/telemetry/main.js
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
Labels: init/build-telemetry-proxy, type: bug

#2469 feat: remove legacy code related to `netlify-automatic-functions`
  packages/build/src/commands/constants.js
  packages/build/src/core/constants.js
  packages/build/src/core/main.js
  packages/build/src/log/messages/core.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2468 feat: remove unused warning message
  packages/build/src/install/missing.js
  packages/build/src/log/messages/install.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2456 chore: test path normalisation
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/helpers/normalize.js
  packages/build/tests/helpers/tcp_server.js
  packages/build/tests/helpers/temp.js
  packages/build/tests/install/fixtures/modules/functions/node_modules/math-avg/index.js
  packages/build/tests/install/fixtures/modules/functions/node_modules/math-avg/license
  packages/build/tests/install/fixtures/modules/functions/node_modules/math-avg/manifest.yml
  packages/build/tests/install/fixtures/modules/functions/node_modules/math-avg/package.json
  packages/build/tests/install/fixtures/modules/functions/node_modules/math-avg/readme.md
  packages/build/tests/install/fixtures/modules/functions/test.js
  packages/build/tests/install/fixtures/modules/netlify.toml
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/install/tests.js
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/cli/tests.js
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: chore

#2474 chore: simplify lingering process query brackets
  packages/build/src/core/lingering.js
Labels: type: chore, type: feature

#2473 fix: improve lingering processes query
  packages/build/src/core/lingering.js
Labels: type: chore, type: feature

#2475 feat: improve lingering processes list
  packages/build/src/core/lingering.js
Labels: type: feature

#2480 fix: do not fail when there are no lingering processes
  packages/build/src/core/lingering.js
Labels: type: bug

#2479 feat: improve lingering process message to add bullet points
  packages/build/src/core/lingering.js
  packages/build/src/log/messages/core.js
  packages/build/tests/core/tests.js
Labels: type: feature

#2470 feat: distinguish between warnings and errors in build logs
  packages/build/src/log/logger.js
  packages/build/src/log/messages/core.js
  packages/build/src/log/messages/core_commands.js
  packages/build/src/log/messages/plugins.js
  packages/build/src/log/theme.js
Labels: type: feature

#2486 fix: do not show an empty list of lingering processes
  packages/build/src/core/lingering.js
Labels: type: bug

#2495 chore: add `read-pkg-up` to list of dependencies which cannot be upgraded
  renovate.json5
Labels: type: chore

#2499 chore: add comments on the list of ignored lingering commands
  packages/build/src/core/lingering.js
Labels: type: chore, type: feature

#2500 feat: make lingering processes logic work on Windows
  packages/build/package.json
  packages/build/src/core/lingering.js
  packages/build/tests/core/tests.js
Labels: type: feature

#2498 feat: add functions.directory support to @netlify/build
  packages/build/src/core/constants.js
  packages/build/tests/core/fixtures/core/netlify.toml
  packages/build/tests/core/fixtures/esbuild_errors/netlify.toml
  packages/build/tests/core/fixtures/functions_config_1/netlify.toml
  packages/build/tests/core/fixtures/functions_config_2/netlify.toml
  packages/build/tests/core/fixtures/functions_config_3/netlify.toml
  packages/build/tests/core/fixtures/several/netlify.toml
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/error/fixtures/dependencies/netlify.toml
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/fixtures/dir/netlify.toml
  packages/build/tests/install/fixtures/functions_error/netlify.toml
  packages/build/tests/install/fixtures/functions_npm/netlify.toml
  packages/build/tests/install/fixtures/functions_yarn/netlify.toml
  packages/build/tests/install/fixtures/functions_yarn_ci/netlify.toml
  packages/build/tests/install/fixtures/local_dep/netlify.toml
  packages/build/tests/install/fixtures/mispelled_dep/netlify.toml
  packages/build/tests/install/fixtures/modules/netlify.toml
  packages/build/tests/install/fixtures/optional-esbuild/netlify.toml
  packages/build/tests/install/fixtures/optional-many-esbuild/netlify.toml
  packages/build/tests/install/fixtures/optional-many/netlify.toml
  packages/build/tests/install/fixtures/optional/netlify.toml
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/plugins/fixtures/functions/netlify.toml
  packages/build/tests/plugins/fixtures/functions_package_json_invalid/netlify.toml
  packages/build/tests/plugins/fixtures/functions_src_dynamic_ignore/netlify.toml
  packages/build/tests/plugins/fixtures/functions_src_missing/netlify.toml
  packages/build/tests/plugins/fixtures/functions_src_relative/netlify.toml
  packages/build/tests/plugins/fixtures/missing/netlify.toml
  packages/build/tests/plugins/fixtures/none/netlify.toml
  packages/build/tests/plugins/fixtures/regular_file/netlify.toml
  packages/build/tests/plugins/fixtures/simple/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/fixtures/core_command_error/netlify.toml
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/config/src/log/cleanup.js
Labels: init/es-func-bundle, proj/func-config-api, type: feature

#2501 fix(telemetry): report telemetry errors without impacting builds
  packages/build/src/core/main.js
  packages/build/src/error/type.js
  packages/build/src/telemetry/main.js
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/telemetry/tests.js
Labels: init/build-telemetry-proxy, type: bug

#2442 chore: automate npm publishing
  .github/workflows/release-please.yml
  CONTRIBUTING.md
  package.json
Labels: type: chore

#2506 chore: add documentation about adding new error types in Bugsnag
  packages/build/src/error/type.js
Labels: documentation, type: chore

#2511 fix: disable 2 Yarn-related tests on Node <14
  packages/build/tests/install/tests.js
Labels: type: bug

#2513 chore(release-please): install deps before publishing to npm
  .github/workflows/release-please.yml
  package.json
Labels: type: chore
