Repository netlify/build, pull requests merged in 2021-12, with the labels that each got.

#3908 fix: correct redirect conditions type
  packages/build/test-d/config/netlify_config.ts
  packages/build/types/config/netlify_config.d.ts
Labels: type: bug, automerge

#3906 feat!: support pure ES modules in local Build plugins
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/logic.js
  packages/build/src/plugins/child/validate.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/plugins/fixtures/es_modules_local/manifest.yml
  packages/build/tests/plugins/fixtures/es_modules_local/netlify.toml
  packages/build/tests/plugins/fixtures/es_modules_local/package.json
  packages/build/tests/plugins/fixtures/es_modules_local/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
Labels: type: feature, automerge

#3851 fix: add types for `utils.functions`
  packages/build/test-d/options/netlify_plugin_functions_util.ts
  packages/build/types/index.d.ts
  packages/build/types/options/netlify_plugin_functions_util.d.ts
  packages/build/types/options/netlify_plugin_utils.d.ts
Labels: type: bug, automerge

#3923 chore: remove some dead code in `.eslintrc.js`
  .eslintrc.js
Labels: type: chore

#3925 feat: pass additional feature flags to zip-it-and-ship-it
  .eslintrc.js
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins_core/functions/feature_flags.js
  packages/build/tests/core/tests.js
  packages/build/tests/telemetry/tests.js
Labels: type: feature, automerge

#3806 feat: add `buildbot_create_functions_manifest` feature flag
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3934 feat: add a `verbose` flag
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/core/normalize_flags.js
  packages/build/src/log/messages/ipc.js
  packages/build/src/plugins/child/error.js
  packages/build/src/plugins/child/load.js
  packages/build/src/plugins/child/main.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/ipc.js
  packages/build/src/plugins/load.js
  packages/build/src/steps/plugin.js
  packages/build/src/steps/run_step.js
  packages/build/src/steps/run_steps.js
  packages/build/tests/log/fixtures/verbose/manifest.yml
  packages/build/tests/log/fixtures/verbose/netlify.toml
  packages/build/tests/log/fixtures/verbose/plugin.js
  packages/build/tests/log/fixtures/verbose_error/manifest.yml
  packages/build/tests/log/fixtures/verbose_error/netlify.toml
  packages/build/tests/log/fixtures/verbose_error/plugin.js
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/log/tests.js
Labels: type: chore, automerge

#3937 fix: load plugin utilities directly
  package.json
  packages/build/src/plugins/child/utils.js
Labels: type: chore

#3936 chore!: use pure ES modules with `run-utils`
  .eslintrc.js
  package.json
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/child/utils.js
  packages/run-utils/package.json
  packages/run-utils/src/main.js
  packages/run-utils/tests/fixtures/run.js
  packages/run-utils/tests/main.mjs
Labels: type: chore

#3943 chore!: use pure ES modules with `git-utils`
  .eslintrc.js
  packages/build/src/plugins/child/utils.js
  packages/git-utils/package.json
  packages/git-utils/src/commits.js
  packages/git-utils/src/diff.js
  packages/git-utils/src/exec.js
  packages/git-utils/src/main.js
  packages/git-utils/src/match.js
  packages/git-utils/src/refs.js
  packages/git-utils/src/stats.js
  packages/git-utils/tests/main.mjs
Labels: type: chore, automerge

#3942 chore!: use pure ES modules with `functions-utils`
  .eslintrc.js
  packages/build/src/plugins/child/utils.js
  packages/functions-utils/package.json
  packages/functions-utils/src/main.js
  packages/functions-utils/tests/fixtures/directory/test/index.js
  packages/functions-utils/tests/fixtures/file/test.js
  packages/functions-utils/tests/fixtures/file/test.mjs
  packages/functions-utils/tests/fixtures/file/test_2.js
  packages/functions-utils/tests/fixtures/file/test_2.mjs
  packages/functions-utils/tests/fixtures/list/four.js/four.js.js
  packages/functions-utils/tests/fixtures/list/one/index.js
  packages/functions-utils/tests/fixtures/list/test.js
  packages/functions-utils/tests/fixtures/list/two/three.js
  packages/functions-utils/tests/fixtures/list/two/two.js
  packages/functions-utils/tests/helpers/main.js
  packages/functions-utils/tests/main.mjs
Labels: type: chore, automerge

#3944 chore!: use pure ES modules with `cache-utils`
  .eslintrc.js
  packages/build/src/core/constants.js
  packages/build/src/plugins/child/utils.js
  packages/cache-utils/package.json
  packages/cache-utils/src/dir.js
  packages/cache-utils/src/expire.js
  packages/cache-utils/src/fs.js
  packages/cache-utils/src/hash.js
  packages/cache-utils/src/list.js
  packages/cache-utils/src/main.js
  packages/cache-utils/src/manifest.js
  packages/cache-utils/src/path.js
  packages/cache-utils/src/utils/cwd.js
  packages/cache-utils/tests/digests.mjs
  packages/cache-utils/tests/dir.mjs
  packages/cache-utils/tests/has.mjs
  packages/cache-utils/tests/helpers/main.js
  packages/cache-utils/tests/list.mjs
  packages/cache-utils/tests/move.js
  packages/cache-utils/tests/move.mjs
  packages/cache-utils/tests/path.mjs
  packages/cache-utils/tests/remove.mjs
  packages/cache-utils/tests/save_restore.mjs
  packages/cache-utils/tests/ttl.mjs
Labels: type: chore, automerge

#3954 chore: fix releasing of `@netlify/functions-utils`
  .github/workflows/release-please.yml
  CONTRIBUTING.md
Labels: type: chore, automerge

#3964 fix: use ESM-compatible JSON imports
  packages/build/src/core/constants.js
  packages/build/src/error/monitor/start.js
  packages/build/src/log/messages/core.js
  packages/build/src/log/old_version.js
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/node_version.js
  packages/build/src/plugins/options.js
  packages/build/src/telemetry/main.js
  packages/build/src/utils/json.js
  packages/build/tests/core/tests.js
  packages/build/tests/edge_handlers/tests.js
Labels: type: chore, automerge

#3963 fix: use static imports with `@netlify/config`
  packages/config/src/api/client.js
  packages/config/src/headers.js
  packages/config/src/main.js
  packages/config/src/redirects.js
Labels: type: chore, automerge
