Repository netlify/build, pull requests merged in 2021-08, with the labels that each got.

#3373 feat: re-add support for feature-flagging plugin versions
  packages/build/src/core/main.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/list.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: automerge, type: feature

#3379 feat(build): return config mutations
  packages/build/src/commands/run_commands.js
  packages/build/src/core/main.js
  packages/build/tests/core/fixtures/plugin_mutations/manifest.yml
  packages/build/tests/core/fixtures/plugin_mutations/netlify.toml
  packages/build/tests/core/fixtures/plugin_mutations/plugin.js
  packages/build/tests/core/tests.js
  packages/config/src/mutations/update.js
  packages/config/tests/mutate/tests.js
Labels: automerge, type: feature

#3378 feat: enable functions bundling manifest
  .gitignore
  package-lock.json
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/core/fixtures/functions_internal_manifest/.netlify/functions-internal/function_three.js
  packages/build/tests/core/fixtures/functions_internal_manifest/netlify/functions/function_one.js
  packages/build/tests/core/fixtures/functions_internal_manifest/netlify/functions/function_two.js
  packages/build/tests/core/fixtures/functions_internal_no_manifest_1/.netlify/functions-internal/function_three.js
  packages/build/tests/core/fixtures/functions_internal_no_manifest_1/netlify/functions/function_one.js
  packages/build/tests/core/fixtures/functions_internal_no_manifest_1/netlify/functions/function_two.js
  packages/build/tests/core/fixtures/functions_internal_no_manifest_2/.netlify/functions-internal/function_three.js
  packages/build/tests/core/fixtures/functions_internal_no_manifest_2/netlify/functions/function_one.js
  packages/build/tests/core/fixtures/functions_internal_no_manifest_2/netlify/functions/function_two.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: automerge, type: feature

#3385 chore: fix typo in code comment
  packages/build/src/plugins/child/diff.js
Labels: automerge, type: chore

#3386 chore: small refactor of `configMutation` code
  packages/build/src/plugins/child/diff.js
Labels: automerge, type: chore

#3387 chore: remove dead code
  packages/build/src/commands/update_config.js
Labels: automerge, type: chore

#3384 feat: improve config simplification
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/config/src/mutations/update.js
  packages/config/src/simplify.js
  packages/config/tests/mutate/snapshots/tests.js.md
  packages/config/tests/mutate/snapshots/tests.js.snap
Labels: automerge, type: feature

#3389 feat: allow modifying `build.environment`
  packages/build/tests/plugins/fixtures/config_mutate_env_all/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_env_all/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_env_all/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_env_prop/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_env_prop/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_env_prop/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/config/src/mutations/apply.js
  packages/config/src/mutations/config_prop_name.js
Labels: automerge, type: feature

#3392 feat: do not log modified `build.environment`
  packages/build/src/log/messages/config.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: automerge, type: feature

#3393 feat: update environment variables with `netlifyConfig.build.environment`
  packages/build/src/env/changes.js
  packages/build/src/plugins/child/run.js
  packages/build/tests/plugins/fixtures/env_changes_build_command/manifest.yml
  packages/build/tests/plugins/fixtures/env_changes_build_command/netlify.toml
  packages/build/tests/plugins/fixtures/env_changes_build_command/plugin.js
  packages/build/tests/plugins/fixtures/env_changes_build_command/print_env.js
  packages/build/tests/plugins/fixtures/env_changes_build_mix/manifest.yml
  packages/build/tests/plugins/fixtures/env_changes_build_mix/netlify.toml
  packages/build/tests/plugins/fixtures/env_changes_build_mix/plugin.js
  packages/build/tests/plugins/fixtures/env_changes_build_on_error/manifest.yml
  packages/build/tests/plugins/fixtures/env_changes_build_on_error/netlify.toml
  packages/build/tests/plugins/fixtures/env_changes_build_on_error/plugin.js
  packages/build/tests/plugins/fixtures/env_changes_build_plugin/manifest.yml
  packages/build/tests/plugins/fixtures/env_changes_build_plugin/netlify.toml
  packages/build/tests/plugins/fixtures/env_changes_build_plugin/plugin.js
  packages/build/tests/plugins/fixtures/env_changes_build_plugin/plugin_two.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: automerge, type: feature

#3394 fix: persist `build.environment` changes to `netlify.toml`
  packages/config/src/simplify.js
Labels: automerge, type: feature

#3397 chore: pin release please version
  .github/workflows/release-please.yml
Labels: type: chore

#3396 fix: `redirects[*].status` should not be a float in `netlify.toml`
  packages/build/tests/plugins/fixtures/config_save_redirects/_redirects_file
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/config/src/utils/toml.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: bug, automerge

#3408 chore: improve redirects test
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: chore, automerge

#3410 chore: fix codecov GitHub action
  .github/workflows/workflow.yml
Labels: type: chore, automerge

#3412 feat: fix log messages related to redirects upload
  packages/build/src/log/messages/config.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#3411 feat: pass `rustTargetDirectory` to ZISI
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/core/tests.js
Labels: type: feature

#3416 chore: remove conditional statements around node 8 test executions
  packages/build/tests/core/tests.js
  packages/build/tests/install/tests.js
  packages/build/tests/plugins/tests.js
  packages/build/tests/status/tests.js
  packages/build/tests/time/tests.js
  packages/config/tests/parse/tests.js
  packages/functions-utils/tests/main.js
Labels: type: chore, automerge

#3422 fix: error handling of headers and redirects
  packages/build/src/core/config.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/tests/plugins/fixtures/config_create_headers_command_error/command.js
  packages/build/tests/plugins/fixtures/config_create_headers_command_error/netlify.toml
  packages/build/tests/plugins/fixtures/config_create_headers_plugin_error/manifest.yml
  packages/build/tests/plugins/fixtures/config_create_headers_plugin_error/netlify.toml
  packages/build/tests/plugins/fixtures/config_create_headers_plugin_error/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/config/src/headers.js
  packages/config/src/mutations/update.js
  packages/config/src/redirects.js
Labels: type: bug

#3415 chore: remove `fast-deep-equal`
  package-lock.json
  packages/build/package.json
  packages/build/src/commands/update_config.js
  packages/build/src/plugins/child/diff.js
  packages/config/package.json
  packages/config/src/headers.js
  packages/config/src/redirects.js
Labels: type: chore, automerge

#3421 chore(deps): update chalk
  package-lock.json
  packages/build/package.json
  packages/config/package.json
  renovate.json5
Labels: type: chore, automerge

#3420 chore(deps): update dev dependencies blocked by Node 8 support
  package-lock.json
  package.json
  packages/build/package.json
  packages/config/package.json
  renovate.json5
Labels: type: chore, automerge

#3417 chore(deps): update ava to latest 3.x
  package-lock.json
  package.json
  packages/build/package.json
  packages/build/tests/plugins/fixtures/handlers_simple/netlify/edge-handlers/test.js
  packages/cache-utils/package.json
  packages/config/package.json
  packages/functions-utils/package.json
  packages/git-utils/package.json
  packages/run-utils/package.json
  renovate.json5
Labels: type: chore, automerge

#3429 fix(deps): bump clean-stack to 3.x
  package-lock.json
  packages/build/package.json
  renovate.json5
Labels: type: bug, automerge

#3425 feat: remove some double newlines in the build logs
  packages/build/src/log/messages/config.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature, automerge

#3426 feat: improve warning messages shown with invalid redirects/headers
  package-lock.json
  packages/build/src/core/config.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature, automerge

#3424 fix: fix how redirects/headers check for duplicates
  packages/config/src/headers.js
  packages/config/src/redirects.js
  packages/config/tests/parse/fixtures/headers_both/netlify.toml
  packages/config/tests/parse/fixtures/headers_both/publish/_headers
  packages/config/tests/parse/fixtures/redirects_both/netlify.toml
  packages/config/tests/parse/fixtures/redirects_both/publish/_redirects
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
Labels: type: bug, automerge

#3437 fix: avoid debug mode to be too verbose
  packages/build/src/core/config.js
Labels: type: bug

#3439 feat: remove headers/redirects duplicate filtering
  packages/config/src/headers.js
  packages/config/src/redirects.js
Labels: type: feature, automerge

#3444 chore(renovate): move/remove dependency update locks on renovate's config
  renovate.json5
Labels: type: chore, automerge

#3446 fix: delete `_redirects`/`_headers` when persisted to `netlify.toml`
  packages/build/tests/plugins/fixtures/config_delete_headers/_headers_file
  packages/build/tests/plugins/fixtures/config_delete_headers/manifest.yml
  packages/build/tests/plugins/fixtures/config_delete_headers/netlify.toml
  packages/build/tests/plugins/fixtures/config_delete_headers/plugin.js
  packages/build/tests/plugins/fixtures/config_delete_redirects/_redirects_file
  packages/build/tests/plugins/fixtures/config_delete_redirects/manifest.yml
  packages/build/tests/plugins/fixtures/config_delete_redirects/netlify.toml
  packages/build/tests/plugins/fixtures/config_delete_redirects/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/config/src/mutations/update.js
  packages/config/tests/mutate/tests.js
Labels: type: bug, automerge

#3450 chore: regenerate test snapshots with Ava v3
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/time/snapshots/tests.js.md
  packages/build/tests/time/snapshots/tests.js.snap
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/mutate/snapshots/tests.js.md
  packages/config/tests/mutate/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: chore, automerge

#3449 chore: fix colors in tests
  package.json
  packages/build/tests/log/tests.js
Labels: type: chore, automerge

#3470 fix(deps): remove cp-file usage
  package-lock.json
  packages/build/package.json
  packages/build/tests/plugins/fixtures/config_mutate_headers_before/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_redirects_before/plugin.js
  packages/build/tests/plugins/fixtures/config_save_headers/plugin.js
  packages/build/tests/plugins/fixtures/config_save_redirects/plugin.js
  packages/build/tests/plugins/tests.js
  packages/config/package.json
  packages/config/src/mutations/update.js
  packages/config/tests/mutate/tests.js
Labels: type: chore, automerge

#3468 feat: simplify headers parsing
  packages/config/src/headers.js
Labels: type: feature

#3475 feat: simplify redirects parsing
  packages/config/src/redirects.js
Labels: type: feature

#3474 fix: rely on `package.engines.node` for plugin version support instead of a hardcoded var
  packages/build/src/plugins/node_version.js
Labels: type: chore, automerge

#3480 fix(utils): remove condition around `require.resolve` invocation
  packages/build/src/utils/resolve.js
Labels: type: chore, automerge

#3463 chore(tests): drop node 8 specific test normalisation
  packages/build/tests/helpers/normalize.js
Labels: type: chore, automerge

#3482 chore: remove some dead code
  packages/config/src/headers.js
  packages/config/src/redirects.js
Labels: type: chore

#3504 chore(snapshots): update the error snapshots with ava 3's new order
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
Labels: type: chore, automerge

#3478 chore(imports): move zisi imports to the top level of the file(s)
  packages/build/src/plugins_core/functions/index.js
  packages/build/src/plugins_core/functions/utils.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/functions-utils/src/main.js
Labels: type: chore, automerge

#3517 chore: update `renovate.json5`
  renovate.json5
Labels: type: chore

#3511 fix: refactor headers and redirects logic
  packages/config/src/headers.js
  packages/config/src/main.js
  packages/config/src/mutations/update.js
  packages/config/src/redirects.js
Labels: type: chore, automerge

#3516 fix(cache-utils): don't cache junk files nor list them as cached
  package-lock.json
  packages/cache-utils/package.json
  packages/cache-utils/src/fs.js
  packages/cache-utils/tests/has.js
  packages/cache-utils/tests/helpers/main.js
  renovate.json5
Labels: type: bug, automerge

#3520 feat(telemetry): report both build and deploy ids
  packages/build/src/core/main.js
  packages/build/src/core/normalize_flags.js
  packages/build/src/telemetry/main.js
  packages/build/tests/telemetry/tests.js
Labels: type: feature, automerge

#3526 fix: duplicate code
  packages/config/src/env/main.js
Labels: type: chore, type: bug

#3527 feat(build-id): add a `build-id` flag and expose `BUILD_ID` based on said flag
  packages/build/src/core/config.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/fixtures/build_id/manifest.yml
  packages/build/tests/env/fixtures/build_id/netlify.toml
  packages/build/tests/env/fixtures/build_id/plugin.js
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/env/tests.js
  packages/config/src/env/main.js
  packages/config/src/main.js
  packages/config/tests/env/tests.js
Labels: type: feature, automerge

#3529 chore(ci): cache `npm` depencies between CI runs
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
Labels: type: chore, automerge

#3510 fix: remove unused error handlers
  packages/config/src/headers.js
  packages/config/src/log/messages.js
  packages/config/src/redirects.js
Labels: type: chore, automerge

#3537 bug: patch fossa install process
  .github/workflows/fossa.yml
Labels: type: chore

#3553 chore: improve `functionsDistDir` test
  packages/build/tests/helpers/temp.js
  packages/build/tests/plugins/tests.js
Labels: type: chore

#3552 feat: add `--buildersDistDir` flag
  packages/build/src/core/flags.js
  packages/build/src/core/normalize_flags.js
  packages/build/src/log/messages/config.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature
