Repository netlify/build, pull requests merged in 2021-02, with the labels that each got.

#2236 chore: fix typo in error message
  packages/build/src/log/messages/core_commands.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: chore

#2234 chore: do not upgrade `path-type`
  renovate.json5
Labels: type: chore

#2239 fix: add SITE_ID and SITE_NAME env vars to local builds
  packages/config/src/env/main.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/api/tests.js
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/env/tests.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.snap
Labels: type: bug

#2242 chore(docs): adding a note on releasing config and build
  CONTRIBUTING.md
Labels: type: chore

#2244 chore(deps): bring build's config depedency to the latest version
  packages/build/package-lock.json
  packages/build/package.json
Labels: type: chore

#2245 fix(deps): force a release for #2244 and bump zip-it-and-ship-it
  packages/build/package.json
  packages/functions-utils/package.json
Labels: type: bug

#2246 feat: remove deploy feature flag
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2243 chore: migrate masterIssue to dependencyDashboard
  renovate.json5
Labels: type: chore

#2251 chore(docs): capitalize all instances of noun Renovate
  CONTRIBUTING.md
Labels: type: chore

#2188 feat!: use netlify/functions as the default functions directory
  packages/build/src/commands/constants.js
  packages/build/src/core/constants.js
  packages/build/src/log/messages/core.js
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/fixtures/functions_src_default_and_legacy/manifest.yml
  packages/build/tests/plugins/fixtures/functions_src_default_and_legacy/netlify-automatic-functions/.gitkeep
  packages/build/tests/plugins/fixtures/functions_src_default_and_legacy/netlify.toml
  packages/build/tests/plugins/fixtures/functions_src_default_and_legacy/netlify/functions/.gitkeep
  packages/build/tests/plugins/fixtures/functions_src_default_and_legacy/plugin.js
  packages/build/tests/plugins/fixtures/functions_src_dynamic/plugin.js
  packages/build/tests/plugins/fixtures/functions_src_dynamic_bundle/plugin.js
  packages/build/tests/plugins/fixtures/functions_src_dynamic_ignore/plugin.js
  packages/build/tests/plugins/fixtures/functions_src_legacy/manifest.yml
  packages/build/tests/plugins/fixtures/functions_src_legacy/netlify-automatic-functions/.gitkeep
  packages/build/tests/plugins/fixtures/functions_src_legacy/netlify.toml
  packages/build/tests/plugins/fixtures/functions_src_legacy/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/build/tests/status/snapshots/tests.js.snap
  packages/config/src/files.js
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/fixtures/default_functions_not_defined/netlify/functions/.gitkeep
  packages/config/tests/normalize/fixtures/default_functions_not_defined_directory_not_found/.gitkeep
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/normalize/tests.js
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: needs docs, type: feature

#2257 chore: fix linting and formatting on npm@7
  package.json
Labels: type: chore

#2256 feat: pass esbuild parameters to ZISI
  packages/build/src/commands/core_command.js
  packages/build/src/commands/run_command.js
  packages/build/src/log/messages/core_commands.js
  packages/build/src/plugins_core/functions/index.js
Labels: type: feature

#2267 fix: improve Bugsnag reporting of upload errors
  packages/build/src/error/monitor/normalize.js
Labels: type: bug

#2275 chore: use npm workspaces
  .github/workflows/workflow.yml
  .gitignore
  CONTRIBUTING.md
  lerna.json
  package-lock.json
  package.json
  packages/build/package-lock.json
  packages/cache-utils/package-lock.json
  packages/config/package-lock.json
  packages/functions-utils/package-lock.json
  packages/git-utils/package-lock.json
  packages/run-utils/package-lock.json
Labels: type: chore

#2277 bug: fix docs link in missing manifest error message
  package-lock.json
  packages/build/src/plugins/manifest/path.js
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: chore

#2278 fix: fix `files` in `package.json` with `npm@7`
  packages/build/package.json
  packages/cache-utils/package.json
  packages/config/package.json
  packages/functions-utils/package.json
  packages/git-utils/package.json
  packages/run-utils/package.json
Labels: type: bug

#2287 chore: fix typo in test
  packages/build/tests/plugins/tests.js
Labels: test, type: chore

#2286 chore: refactor missing plugins logic
  packages/build/src/install/missing.js
  packages/build/src/plugins/resolve.js
Labels: type: chore, type: feature

#2304 chore: fix `import/no-extraneous-dependencies` ESLint rule
  .eslintrc.js
Labels: type: chore

#2305 chore: fix linting with npm 7 workspaces
  .eslintrc.js
Labels: type: chore

#2289 feat: print warnings for outdated plugins
  packages/build/src/log/logger.js
  packages/build/src/log/messages/plugins.js
  packages/build/src/log/theme.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/resolve.js
  packages/build/src/plugins/spawn.js
  packages/build/tests/plugins/fixtures/plugins_outdated_package_json/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_outdated_package_json/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins/fixtures/plugins_outdated_package_json/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins/fixtures/plugins_outdated_package_json/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins/fixtures/plugins_outdated_package_json/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2307 feat: allow `version` in `plugins.json` to be an object
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/list.js
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2310 feat: add `plugin.compatibility` field
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/list.js
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2311 feat: move where the plugin Node.js version is resolved
  packages/build/src/core/main.js
  packages/build/src/plugins/node_version.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/src/plugins/spawn.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2308 feat: add feature flag for esbuild rollout
  .eslintrc.js
  packages/build/src/commands/core_command.js
  packages/build/src/commands/run_command.js
  packages/build/src/core/feature_flags.js
  packages/build/src/log/logger.js
  packages/build/src/log/messages/core_commands.js
  packages/build/src/plugins_core/functions/index.js
Labels: type: feature

#2315 feat: add `compatibility[*].nodeVersion`
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
  packages/build/tests/plugins/fixtures/plugins_compat_node_version/.env
  packages/build/tests/plugins/fixtures/plugins_compat_node_version/netlify.toml
  packages/build/tests/plugins/fixtures/plugins_compat_node_version/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2318 feat: turn `compatibility` field into an array
  packages/build/src/plugins/list.js
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2319 feat: print warnings when using `compatibility` versions
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature
