Repository netlify/build, pull requests merged in 2021-07, with the labels that each got.

#3161 feat: allow array configuration property to be modified
  packages/build/package.json
  packages/build/src/plugins/child/track.js
  packages/build/src/plugins/config_prop_name.js
  packages/build/src/plugins/mutations.js
  packages/build/src/utils/set.js
  packages/build/tests/plugins/fixtures/config_mutate_array_index/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_array_index/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_array_index/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_array_push/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_array_push/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_array_push/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_new/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3162 feat: log updated config when changed, in debug mode
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run_command.js
  packages/build/src/log/messages/config.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#3167 feat: reduce verbose logs when changing `netlifyConfig`
  packages/build/src/core/config.js
Labels: type: chore, type: feature

#3168 feat: detect when `_redirects` are created during builds
  packages/build/package.json
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run_command.js
  packages/build/tests/plugins/fixtures/config_create_redirects/manifest.yml
  packages/build/tests/plugins/fixtures/config_create_redirects/netlify.toml
  packages/build/tests/plugins/fixtures/config_create_redirects/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3163 feat: allow mutating more configuration properties
  packages/build/src/plugins/config_prop_name.js
  packages/build/src/plugins/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_all/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_all/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_all/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_processing_all/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_processing_all/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_processing_all/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_processing_prop/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_processing_prop/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_processing_prop/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_redirects_all/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_redirects_all/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_redirects_all/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_services_all/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_services_all/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_services_all/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_services_prop/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_services_prop/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_services_prop/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3171 feat: detect when build command adds `_redirects` file
  packages/build/src/commands/core_command.js
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/update_config.js
  packages/build/src/plugins_core/build_command.js
  packages/build/tests/plugins/fixtures/config_create_redirects_command/command.js
  packages/build/tests/plugins/fixtures/config_create_redirects_command/manifest.yml
  packages/build/tests/plugins/fixtures/config_create_redirects_command/netlify.toml
  packages/build/tests/plugins/fixtures/config_create_redirects_command/plugin.js
  packages/build/tests/plugins/fixtures/config_create_redirects_plugin/manifest.yml
  packages/build/tests/plugins/fixtures/config_create_redirects_plugin/netlify.toml
  packages/build/tests/plugins/fixtures/config_create_redirects_plugin/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3183 chore: add `figures` to `renovate.json5`
  renovate.json5
Labels: type: chore

#3174 feat: refactor config contexts logic
  packages/config/src/context.js
  packages/config/src/main.js
  packages/config/src/validate/context.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
Labels: type: feature

#3187 feat: change how `priorityConfig` interacts with contexts
  packages/build/src/commands/core_command.js
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/commands/update_config.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/src/plugins/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_all/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_all/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_all/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/config/README.md
  packages/config/src/bin/flags.js
  packages/config/src/main.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
Labels: type: chore, type: feature

#3190 feat: change `origin` of `inlineConfig` and `priorityConfig`
  packages/build/src/log/description.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/config/src/main.js
  packages/config/src/origin.js
  packages/config/src/redirects.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/parse/tests.js
Labels: type: feature

#3193 feat!: merge `priorityConfig` with `inlineConfig`
  packages/build/src/commands/core_command.js
  packages/build/src/commands/plugin.js
  packages/build/src/commands/return.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/commands/update_config.js
  packages/build/src/core/config.js
  packages/build/src/plugins/mutations.js
  packages/config/README.md
  packages/config/src/base.js
  packages/config/src/bin/flags.js
  packages/config/src/inline_config.js
  packages/config/src/log/main.js
  packages/config/src/main.js
  packages/config/src/merge_normalize.js
  packages/config/src/redirects.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/log/tests.js
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/parse/tests.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: feature

#3199 feat: fix `context` override for `edge_handlers`
  packages/config/src/context.js
  packages/config/tests/context/fixtures/context_edge_handlers_build/netlify.toml
  packages/config/tests/context/fixtures/context_edge_handlers_top/netlify.toml
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/context/tests.js
Labels: type: feature

#3200 feat: allow mutating `edge_handlers` in plugins
  packages/build/src/plugins/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_all/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_all/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_edge_handlers_all/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3203 feat: move some mutation logic to `@netlify/config`
  packages/build/package.json
  packages/build/src/commands/core_command.js
  packages/build/src/commands/plugin.js
  packages/build/src/commands/update_config.js
  packages/build/src/core/config.js
  packages/build/src/plugins/events.js
  packages/config/package.json
  packages/config/src/events.js
  packages/config/src/functions_config.js
  packages/config/src/main.js
  packages/config/src/mutations/apply.js
  packages/config/src/mutations/config_prop_name.js
  packages/config/src/mutations/normalize_priority.js
  packages/config/src/mutations/side_files.js
  packages/config/src/utils/set.js
Labels: type: feature

#3211 feat!: add `configMutations` flag to `@netlify/config`
  packages/build/src/commands/core_command.js
  packages/build/src/commands/plugin.js
  packages/build/src/commands/return.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/commands/update_config.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/config/README.md
  packages/config/src/bin/flags.js
  packages/config/src/error.js
  packages/config/src/inline_config.js
  packages/config/src/log/main.js
  packages/config/src/main.js
  packages/config/src/mutations/apply.js
  packages/config/src/mutations/normalize_priority.js
  packages/config/src/options/main.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
Labels: type: feature

#3207 feat!: return `redirectsPath` from `@netlify/config`
  packages/build/package.json
  packages/build/src/commands/core_command.js
  packages/build/src/commands/plugin.js
  packages/build/src/commands/return.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/commands/update_config.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/plugins/fixtures/config_create_redirects_command_dynamic/command.js
  packages/build/tests/plugins/fixtures/config_create_redirects_command_dynamic/manifest.yml
  packages/build/tests/plugins/fixtures/config_create_redirects_command_dynamic/netlify.toml
  packages/build/tests/plugins/fixtures/config_create_redirects_command_dynamic/plugin.js
  packages/build/tests/plugins/fixtures/config_create_redirects_command_dynamic/test/.gitkeep
  packages/build/tests/plugins/fixtures/config_create_redirects_plugin_dynamic/manifest.yml
  packages/build/tests/plugins/fixtures/config_create_redirects_plugin_dynamic/netlify.toml
  packages/build/tests/plugins/fixtures/config_create_redirects_plugin_dynamic/plugin.js
  packages/build/tests/plugins/fixtures/config_create_redirects_plugin_dynamic/test/.gitkeep
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/config/README.md
  packages/config/package.json
  packages/config/src/main.js
  packages/config/src/mutations/side_files.js
  packages/config/src/redirects.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature

#3208 chore: rename a variable
  packages/config/src/api/site_info.js
  packages/config/src/build_dir.js
  packages/config/src/error.js
  packages/config/src/log/messages.js
  packages/config/src/options/main.js
  packages/config/src/parse.js
  packages/config/src/validate/identical.js
  packages/config/src/validate/main.js
Labels: type: chore

#3218 feat: fix the payload sent during deploy to the buildbot
  packages/build/src/plugins_core/deploy/buildbot_client.js
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3221 fix: handle `plugins[*].pinned_version` being an empty string
  packages/config/src/normalize.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
Labels: type: bug

#3224 feat: persist configuration changes to `netlify.toml`
  .gitignore
  packages/build/src/commands/run_commands.js
  packages/build/src/core/config.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/core/normalize_flags.js
  packages/build/src/log/messages/config.js
  packages/build/tests/plugins/fixtures/config_save_changes/manifest.yml
  packages/build/tests/plugins/fixtures/config_save_changes/netlify.toml
  packages/build/tests/plugins/fixtures/config_save_changes/plugin.js
  packages/build/tests/plugins/fixtures/config_save_context/manifest.yml
  packages/build/tests/plugins/fixtures/config_save_context/netlify.toml
  packages/build/tests/plugins/fixtures/config_save_context/plugin.js
  packages/build/tests/plugins/fixtures/config_save_empty/manifest.yml
  packages/build/tests/plugins/fixtures/config_save_empty/plugin.js
  packages/build/tests/plugins/fixtures/config_save_none/manifest.yml
  packages/build/tests/plugins/fixtures/config_save_none/netlify.toml
  packages/build/tests/plugins/fixtures/config_save_none/plugin.js
  packages/build/tests/plugins/fixtures/config_save_redirects/_redirects_file
  packages/build/tests/plugins/fixtures/config_save_redirects/manifest.yml
  packages/build/tests/plugins/fixtures/config_save_redirects/netlify.toml
  packages/build/tests/plugins/fixtures/config_save_redirects/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/config/package.json
  packages/config/src/context.js
  packages/config/src/files.js
  packages/config/src/main.js
  packages/config/src/merge.js
  packages/config/src/mutations/update.js
  packages/config/src/normalize.js
  packages/config/src/parse.js
  packages/config/src/utils/toml.js
  packages/config/tests/mutate/fixtures/context/netlify.toml
  packages/config/tests/mutate/fixtures/merge/netlify.toml
  packages/config/tests/mutate/fixtures/noop/.gitkeep
  packages/config/tests/mutate/fixtures/redirects_change/_redirects
  packages/config/tests/mutate/fixtures/redirects_no_change/_redirects
  packages/config/tests/mutate/fixtures/redirects_none/.gitkeep
  packages/config/tests/mutate/fixtures/redirects_undefined/_redirects
  packages/config/tests/mutate/fixtures/save/.gitkeep
  packages/config/tests/mutate/fixtures/update/.gitkeep
  packages/config/tests/mutate/snapshots/tests.js.md
  packages/config/tests/mutate/snapshots/tests.js.snap
  packages/config/tests/mutate/tests.js
Labels: type: feature

#3223 chore: remove some dead code
  packages/build/src/core/config.js
Labels: type: chore

#3233 fix: save the `netlify.toml` earlier
  packages/build/src/commands/core_command.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/main.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/tests/helpers/tcp_server.js
  packages/build/tests/plugins/fixtures/config_save_deploy/manifest.yml
  packages/build/tests/plugins/fixtures/config_save_deploy/plugin.js
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3231 fix: return `redirects` with `@netlify/config`
  packages/config/src/bin/main.js
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
Labels: type: bug

#3243 chore(deps): remove unused dev dependency
  package-lock.json
  packages/build/package.json
  renovate.json5
Labels: type: chore

#3235 feat: add default values for `build.processing` and `build.services`
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/config/src/log/cleanup.js
  packages/config/src/normalize.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/mutate/snapshots/tests.js.md
  packages/config/tests/mutate/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature

#3237 chore: skip some tests that randomly fail
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/install/tests.js
Labels: type: chore

#3242 fix: allow `netlifyConfig.redirects` to be modified before `_redirects` is added
  packages/build/package.json
  packages/build/src/commands/update_config.js
  packages/build/tests/plugins/fixtures/config_mutate_redirects_after/_redirects
  packages/build/tests/plugins/fixtures/config_mutate_redirects_after/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_redirects_after/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_redirects_after/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_redirects_before/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_redirects_before/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_redirects_before/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_redirects_before/redirects_file
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/config/package.json
  packages/config/src/redirects.js
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/parse/tests.js
Labels: type: feature

#3249 feat: move configMutations logging logic
  packages/build/src/commands/update_config.js
  packages/build/src/log/messages/config.js
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/child/track.js
Labels: type: feature

#3250 feat: do not validate against `preventExtensions()` nor `setPrototypeOf()`
  packages/build/src/plugins/child/track.js
  packages/build/tests/plugins/fixtures/config_readonly_prevent/manifest.yml
  packages/build/tests/plugins/fixtures/config_readonly_prevent/netlify.toml
  packages/build/tests/plugins/fixtures/config_readonly_prevent/plugin.js
  packages/build/tests/plugins/fixtures/config_readonly_proto/manifest.yml
  packages/build/tests/plugins/fixtures/config_readonly_proto/netlify.toml
  packages/build/tests/plugins/fixtures/config_readonly_proto/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3252 feat: move configMutations validation logic
  packages/build/src/commands/update_config.js
  packages/build/src/plugins/child/track.js
Labels: type: feature

#3254 feat: use a diff instead of a Proxy for configuration mutations
  packages/build/package.json
  packages/build/src/commands/update_config.js
  packages/build/src/plugins/child/diff.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/child/track.js
  packages/build/tests/plugins/fixtures/config_mutate_define_undefined/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_delete/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_set_null/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_set_undefined/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_symbol/netlify.toml
  packages/build/tests/plugins/fixtures/config_readonly_define/plugin.js
  packages/build/tests/plugins/fixtures/config_readonly_delete/netlify.toml
  packages/build/tests/plugins/fixtures/config_readonly_delete/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3259 feat: fix `_redirects` to `netlify.toml` before deploy
  packages/build/tests/plugins/fixtures/config_save_redirects/netlify.toml
  packages/build/tests/plugins/fixtures/config_save_redirects/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/config/src/main.js
  packages/config/src/mutations/update.js
  packages/config/src/redirects.js
  packages/config/tests/mutate/snapshots/tests.js.md
  packages/config/tests/mutate/snapshots/tests.js.snap
Labels: type: feature

#3262 feat: add debug logs to deploys
  packages/build/src/commands/core_command.js
  packages/build/src/core/config.js
  packages/build/src/log/messages/config.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#3264 chore: improve tests related to `--saveConfig`
  packages/build/tests/helpers/tcp_server.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: chore

#3265 feat: restore `netlify.toml` and `_redirects` after deploy
  packages/build/src/core/config.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/config/package.json
  packages/config/src/main.js
  packages/config/src/mutations/update.js
Labels: type: feature

#3268 feat: simplify the `netlify.toml` being saved on configuration changes
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/config/src/context.js
  packages/config/src/log/cleanup.js
  packages/config/src/log/options.js
  packages/config/src/log/remove.js
  packages/config/src/mutations/update.js
  packages/config/src/simplify.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/mutate/tests.js
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
Labels: type: feature

#3271 feat: delete `netlify.toml` after deploy if it was created due to configuration changes
  packages/build/tests/plugins/tests.js
  packages/config/src/mutations/update.js
Labels: type: feature

#3258 chore: remove general CODEOWNERS rule
  .github/CODEOWNERS
Labels: type: chore

#3240 chore: refactor statsd tests
  package-lock.json
  packages/build/package.json
  packages/build/tests/helpers/udp_server.js
  packages/build/tests/time/tests.js
Labels: type: chore

#3291 chore: skip main CI steps in release branches
  .github/workflows/workflow.yml
Labels: type: chore

#3292 test(snapshots): normalize prerelease
  packages/build/tests/helpers/normalize.js
  packages/build/tests/status/tests.js
Labels: type: chore

#3296 feat!: change edge-handler default directory
  packages/build/src/core/constants.js
  packages/build/src/plugins_core/list.js
  packages/build/tests/plugins/fixtures/edge_handlers_src_auto/netlify/edge-handlers/.gitkeep
  packages/build/tests/plugins/fixtures/edge_handlers_src_dynamic/plugin.js
  packages/build/tests/plugins/fixtures/edge_handlers_src_dynamic_ignore/plugin.js
  packages/build/tests/plugins/fixtures/handlers_simple/netlify/edge-handlers/data.json
  packages/build/tests/plugins/fixtures/handlers_simple/netlify/edge-handlers/test.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/config/docs/file_paths.md
  packages/config/src/files.js
  packages/config/tests/normalize/fixtures/default_handlers_not_defined/netlify/edge-handlers/.gitkeep
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
Labels: type: feature

#3301 chore(dependencies): bump @netlify/config major version
  package-lock.json
  packages/build/package.json
Labels: type: chore

#3308 docs: Update CODEOWNERS
  .github/CODEOWNERS
Labels: type: chore

#3213 feat: bundle functions from `.netlify/functions-internal`
  .gitignore
  packages/build/src/commands/run_command.js
  packages/build/src/core/constants.js
  packages/build/src/core/dry.js
  packages/build/src/core/main.js
  packages/build/src/log/messages/core_commands.js
  packages/build/src/plugins/child/utils.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/core/fixtures/functions_internal/.netlify/functions-internal/function_three.js
  packages/build/tests/core/fixtures/functions_internal/netlify/functions/function_one.js
  packages/build/tests/core/fixtures/functions_internal/netlify/functions/function_two.js
  packages/build/tests/core/fixtures/functions_internal_main_missing/.gitkeep
  packages/build/tests/core/fixtures/functions_internal_missing/netlify/functions/function_one.js
  packages/build/tests/core/fixtures/functions_internal_missing/netlify/functions/function_two.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/plugins/fixtures/functions_list/.netlify/functions-internal/internal_1.js
  packages/build/tests/plugins/fixtures/functions_list/manifest.yml
  packages/build/tests/plugins/fixtures/functions_list/netlify.toml
  packages/build/tests/plugins/fixtures/functions_list/netlify/functions/user_1.js
  packages/build/tests/plugins/fixtures/functions_list/plugin.js
  packages/build/tests/plugins/fixtures/functions_src_default/plugin.js
  packages/build/tests/plugins/fixtures/functions_src_default_and_legacy/plugin.js
  packages/build/tests/plugins/fixtures/functions_src_dynamic/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3313 fix: fossa workflow
  .github/workflows/fossa.yml
Labels: type: bug

#3314 fix: bundle functions from internal directory if configured user dire…
  .gitignore
  packages/build/src/log/messages/core_commands.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/src/plugins_core/functions/utils.js
  packages/build/tests/core/fixtures/functions_internal_user_missing/.gitkeep
  packages/build/tests/core/fixtures/functions_user_missing/.netlify/functions-internal/function_one.js
  packages/build/tests/core/fixtures/functions_user_missing/.netlify/functions-internal/function_two.js
  packages/build/tests/core/fixtures/functions_user_missing/netlify.toml
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
Labels: type: bug

#3304 feat: add support for feature-flagging plugin versions
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/list.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3318 fix: revert "feat: add support for feature-flagging plugin versions"
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/expected_version.js
  packages/build/src/plugins/list.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: bug

#3326 fix: allow functions directory to be a symlink
  packages/build/src/plugins_core/functions/utils.js
  packages/build/tests/plugins/fixtures/symlink/functions-link
  packages/build/tests/plugins/fixtures/symlink/functions/test.js
  packages/build/tests/plugins/fixtures/symlink/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: bug

#3322 chore!: deprecate Node 8
  .github/workflows/workflow.yml
  package-lock.json
  package.json
  packages/build/package.json
  packages/build/tests/error/tests.js
  packages/build/tests/plugins/fixtures/functions_list/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/cache-utils/package.json
  packages/config/package.json
  packages/functions-utils/package.json
  packages/git-utils/package.json
  packages/run-utils/package.json
Labels: type: chore

#3328 feat(telemetry): report the framework provided
  packages/build/src/core/main.js
  packages/build/src/telemetry/main.js
  packages/build/tests/telemetry/tests.js
Labels: type: feature

#3350 chore: small code simplification
  packages/build/src/core/dry.js
Labels: type: chore

#3347 chore: switch to manifest releaser
  .github/workflows/release-please.yml
  .release-please-manifest.json
  CONTRIBUTING.md
  package.json
  release-please-config.json
Labels: type: chore

#3351 feat: add `NETLIFY_LOCAL` environment variable
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/config/src/env/main.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/env/tests.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/mutate/snapshots/tests.js.md
  packages/config/tests/mutate/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature

#3353 chore: add kodiak
  .github/.kodiak.toml
Labels: type: chore

#3354 chore: use releases_created instead of release_created
  .github/workflows/release-please.yml
Labels: automerge, type: chore

#3355 feat: add versioning to `plugins.json`
  packages/build/src/plugins/list.js
Labels: type: feature

#3358 fix: update `plugins.json` version
  packages/build/src/plugins/list.js
Labels: type: bug

#3361 feat: allow adding new properties to `compatibility`
  packages/build/src/plugins/compatibility.js
  packages/build/src/plugins/list.js
Labels: automerge, type: feature

#3363 fix: `deployDir` parameter sent to buildbot during deploys
  packages/build/src/plugins_core/deploy/buildbot_client.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/tests/plugins/fixtures/deploy_dir_path/base/netlify.toml
  packages/build/tests/plugins/fixtures/deploy_dir_path/base/publish/.gitkeep
  packages/build/tests/plugins/fixtures/deploy_dir_path/netlify.toml
  packages/build/tests/plugins/tests.js
Labels: automerge, type: bug
