Repository netlify/build, pull requests merged in 2021-01, with the labels that each got.

#2159 Skip a randomly failing test
  packages/build/tests/error/tests.js
Labels: type: chore

#2163 chore: remove netlify package rules
  renovate.json5
Labels: type: chore

#2175 Add warning logs for `netlify/functions`
  packages/build/src/core/constants.js
  packages/build/src/core/main.js
  packages/build/src/log/messages/core.js
  packages/build/tests/core/fixtures/netlify_dir/netlify/.gitkeep
  packages/build/tests/core/fixtures/netlify_functions_dir/netlify/functions/.gitkeep
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: type: feature

#2176 Improve debugging of environment variables
  packages/config/src/log/cleanup.js
  packages/config/src/log/main.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
Labels: type: feature

#2177 chore: add PR labeler action
  .github/workflows/labeler.yml
Labels: type: chore

#2158 chore: add release please
  .github/workflows/release-please.yml
  CONTRIBUTING.md
  package.json
Labels: type: chore

#2182 fix(windows): show windows path separator in netlify dir warning message
  packages/build/src/core/constants.js
Labels: type: bug

#2183 Add `prepublish` npm scripts
  CONTRIBUTING.md
  package.json
  packages/build/package.json
  packages/cache-utils/package.json
  packages/config/package.json
  packages/functions-utils/package.json
  packages/git-utils/package.json
  packages/run-utils/package.json
Labels: type: chore

#2184 Do not allow `process.env` IPC between plugins
  packages/build/src/commands/build_command.js
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run_command.js
  packages/build/src/env/changes.js
  packages/build/src/plugins/child/run.js
  packages/build/tests/plugins/fixtures/env_changes_plugin/plugin.js
  packages/build/tests/plugins/fixtures/env_changes_plugin/plugin_two.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2012 Upgrade to Node 15
  .github/workflows/workflow.yml
  packages/build/src/log/stream.js
  packages/build/src/time/report.js
  packages/build/tests/error/fixtures/cancel_callback/plugin.js
  packages/build/tests/error/fixtures/early_exit/plugin_slow.js
  packages/build/tests/error/fixtures/fail_build_callback/plugin.js
  packages/build/tests/error/fixtures/fail_plugin_callback/plugin.js
  packages/build/tests/error/fixtures/uncaught/plugin.js
  packages/build/tests/error/fixtures/unhandled_promise/plugin.js
  packages/build/tests/error/fixtures/warning/plugin.js
  packages/build/tests/plugins/fixtures/interleave/plugin.js
  packages/cache-utils/tests/helpers/main.js
Labels: type: chore

#2191 Fix circular dependencies
  packages/build/src/commands/error.js
  packages/build/src/commands/get.js
  packages/build/src/commands/run_command.js
  packages/build/src/core/dry.js
  packages/build/src/plugins/child/utils.js
  packages/build/src/plugins/events.js
  packages/build/src/plugins_core/deploy/buildbot_client.js
  packages/build/src/status/success.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
Labels: type: bug, type: feature

#2207 chore: release @netlify/build 8.1.1
  packages/build/CHANGELOG.md
  packages/build/package-lock.json
  packages/build/package.json
Labels: autorelease: pending, type: chore

#2192 feat: run deploy logic as core instead of plugin
  packages/build/src/commands/core_command.js
  packages/build/src/commands/get.js
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/constants.js
  packages/build/src/core/dry.js
  packages/build/src/core/main.js
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins_core/deploy/buildbot_client.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/src/plugins_core/main.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2212 feat: add back `process.env` plugins communication
  packages/build/src/commands/build_command.js
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run_command.js
  packages/build/src/env/changes.js
  packages/build/src/plugins/child/run.js
  packages/build/tests/plugins/fixtures/env_changes_plugin/plugin.js
  packages/build/tests/plugins/fixtures/env_changes_plugin/plugin_two.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: bug, type: feature

#2190 feat: allow override of API URL
  packages/config/README.md
  packages/config/src/api/client.js
  packages/config/src/bin/flags.js
Labels: type: feature
