Repository netlify/build, pull requests merged in 2021-06, with the labels that each got.

#2895 feat: add support for experimental ZISI v2 handler
  packages/build/src/commands/core_command.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/feature_flags.js
  packages/build/src/core/main.js
  packages/build/src/plugins_core/functions/index.js
Labels: type: feature

#2894 feat: validate when mutating a property too late
  packages/build/src/plugins/child/mutations.js
  packages/build/src/plugins/child/run.js
  packages/build/tests/plugins/fixtures/config_mutate_too_late/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_too_late/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_too_late/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2911 feat: monitor total time for user/system/plugin code
  packages/build/src/time/aggregate.js
  packages/build/tests/time/snapshots/tests.js.md
  packages/build/tests/time/snapshots/tests.js.snap
Labels: type: feature

#2915 fix: configuration mutation of object values
  packages/build/src/plugins/child/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_new/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_functions_new/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_functions_new/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2927 fix: correct usage of ZISI's basePath property
  packages/build/src/plugins_core/functions/index.js
Labels: type: bug

#2934 chore: improve test snapshots normalization
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/helpers/normalize.js
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
Labels: type: chore

#2933 feat(metrics): report distribution metrics under a feature flag
  packages/build/src/core/feature_flags.js
  packages/build/src/core/main.js
  packages/build/src/time/report.js
  packages/build/tests/time/tests.js
Labels: theme/telemetry, type: feature

#2940 feat: fix `functions.directory` mutation
  packages/build/src/plugins/child/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_build/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_nested/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_star/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2941 feat: handle symbols mutations on `netlifyConfig`
  packages/build/src/plugins/child/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_symbol/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_symbol/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_symbol/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#2939 chore: fix test titles
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: chore

#2936 chore: allow feature flags with `@netlify/config`
  packages/build/src/core/normalize_flags.js
  packages/config/src/bin/flags.js
  packages/config/src/log/options.js
  packages/config/src/options/feature_flags.js
  packages/config/src/options/main.js
  packages/config/tests/helpers/main.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
Labels: type: chore

#2946 fix: `@netlify/config` `README` update
  packages/config/README.md
  packages/config/src/bin/flags.js
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
Labels: type: bug, type: chore

#2945 feat: log when `netlifyConfig` is mutated
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/child/mutations.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2944 feat: allow mutating `functions.*` top-level properties
  packages/build/src/plugins/child/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_any/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_nested/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#2953 chore: small refactoring
  packages/config/package.json
  packages/config/src/files.js
  packages/config/src/log/messages.js
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
Labels: type: chore, type: feature

#2954 feat: refactor configuration file paths resolution
  packages/config/src/options/main.js
Labels: type: chore, type: feature

#2951 feat: simplify code related to `base` directory
  packages/config/src/main.js
Labels: type: feature

#2957 fix: improve error handling of plugins list fetch error
  packages/build/src/plugins/list.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: bug

#2965 chore: rename a variable
  packages/config/src/files.js
  packages/config/src/main.js
Labels: type: chore

#2968 chore: move lines of code
  packages/config/src/base.js
  packages/config/src/main.js
Labels: type: chore

#2970 fix: refactor warning message related to monorepo `publish` default value
  packages/config/src/files.js
  packages/config/src/log/messages.js
Labels: type: bug, type: chore

#2967 feat: only monitor the duration of Netlify maintained plugins
  packages/build/src/time/aggregate.js
  packages/build/tests/time/fixtures/community_plugin/netlify.toml
  packages/build/tests/time/fixtures/community_plugin/one/index.js
  packages/build/tests/time/fixtures/community_plugin/one/manifest.yml
  packages/build/tests/time/fixtures/community_plugin/two/index.js
  packages/build/tests/time/fixtures/community_plugin/two/manifest.yml
  packages/build/tests/time/fixtures/system_plugin/netlify.toml
  packages/build/tests/time/fixtures/system_plugin/netlify_plugin_nextjs/index.js
  packages/build/tests/time/fixtures/system_plugin/netlify_plugin_nextjs/manifest.yml
  packages/build/tests/time/fixtures/system_plugin/netlify_plugin_sitemap/index.js
  packages/build/tests/time/fixtures/system_plugin/netlify_plugin_sitemap/manifest.yml
  packages/build/tests/time/snapshots/tests.js.md
  packages/build/tests/time/snapshots/tests.js.snap
  packages/build/tests/time/tests.js
Labels: type: feature

#2977 chore: fix race condition in test
  packages/build/tests/core/fixtures/esbuild_errors_2/functions/function_with_module.js
  packages/build/tests/core/fixtures/esbuild_errors_2/functions/node_modules/test/index.js
  packages/build/tests/core/fixtures/esbuild_errors_2/functions/node_modules/test/package.json
  packages/build/tests/core/fixtures/esbuild_errors_2/functions/package.json
Labels: type: chore

#2980 fix(deps): revert dependency @netlify/zip-it-and-ship-it to ^4.2.7
  package-lock.json
  packages/build/package.json
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/functions-utils/package.json
Labels: type: bug

#2981 fix: force release of Build
  packages/build/src/plugins_core/functions/index.js
Labels: type: bug

#2983 fix: pin ZISI to v4.2.7
  package-lock.json
  packages/build/package.json
Labels: type: bug

#2960 feat: improve feature flags logic
  packages/build/src/core/bin.js
  packages/build/src/core/config.js
  packages/build/src/core/feature_flags.js
  packages/build/src/core/main.js
  packages/build/src/core/normalize_flags.js
  packages/build/src/log/messages/config.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/helpers/common.js
  packages/build/tests/helpers/main.js
  packages/build/tests/time/tests.js
  packages/config/src/bin/flags.js
  packages/config/src/options/feature_flags.js
  packages/config/src/options/main.js
  packages/config/tests/helpers/main.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
Labels: type: chore

#2988 feat!: improve support for monorepo sites without a `publish` directory
  packages/build/src/core/constants.js
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/config/src/files.js
  packages/config/src/log/messages.js
  packages/config/src/main.js
  packages/config/src/merge_normalize.js
  packages/config/src/normalize.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/base/tests.js
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature

#2991 fix: allow using no feature flags
  packages/build/src/log/messages/config.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: type: bug

#2976 chore: rename a variable
  packages/config/src/main.js
  packages/config/src/path.js
Labels: type: chore

#2973 fix: refactor a warning message
  packages/config/src/build_dir.js
  packages/config/src/files.js
  packages/config/src/log/messages.js
Labels: type: chore

#2997 feat: refactor some logic related to the `base` directory
  packages/config/src/base.js
  packages/config/src/build_dir.js
  packages/config/src/files.js
  packages/config/src/main.js
Labels: type: chore, type: feature

#2999 fix: move some lines of code
  packages/config/src/files.js
  packages/config/src/main.js
Labels: type: chore

#3003 feat: add `config.redirects`
  package-lock.json
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/config/package.json
  packages/config/src/log/cleanup.js
  packages/config/src/log/messages.js
  packages/config/src/log/remove.js
  packages/config/src/main.js
  packages/config/src/redirects.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/fixtures/redirects_both/netlify.toml
  packages/config/tests/parse/fixtures/redirects_both/publish/_redirects
  packages/config/tests/parse/fixtures/redirects_field/netlify.toml
  packages/config/tests/parse/fixtures/redirects_field_error/netlify.toml
  packages/config/tests/parse/fixtures/redirects_file/netlify.toml
  packages/config/tests/parse/fixtures/redirects_file/publish/_redirects
  packages/config/tests/parse/fixtures/redirects_file_error/netlify.toml
  packages/config/tests/parse/fixtures/redirects_file_error/publish/_redirects
  packages/config/tests/parse/fixtures/redirects_no_publish/_redirects
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/parse/tests.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature

#3012 chore(deps): ignore major updates for dot-prop
  renovate.json5
Labels: type: chore

#3016 fix: revert `redirects` parsing
  packages/build/tests/helpers/main.js
  packages/config/src/main.js
  packages/config/src/options/feature_flags.js
  packages/config/src/redirects.js
  packages/config/tests/helpers/main.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
Labels: type: bug

#3015 fix(feature_flags): remove distribution metrics feature flag
  packages/build/src/core/feature_flags.js
  packages/build/src/core/main.js
  packages/build/src/time/report.js
  packages/build/tests/time/snapshots/tests.js.md
  packages/build/tests/time/snapshots/tests.js.snap
  packages/build/tests/time/tests.js
Labels: theme/telemetry, type: bug, type: chore

#3023 fix: pin zisi version in functions utils
  packages/config/package.json
  packages/functions-utils/package.json
Labels: type: bug

#3022 fix(metrics): remove timing metrics report
  packages/build/src/time/report.js
  packages/build/tests/time/snapshots/tests.js.md
  packages/build/tests/time/snapshots/tests.js.snap
  packages/build/tests/time/tests.js
Labels: theme/telemetry, type: bug

#3028 feat: add `--output` CLI flag to `@netlify/config`
  package-lock.json
  packages/config/package.json
  packages/config/src/bin/flags.js
  packages/config/src/bin/main.js
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/cli/tests.js
Labels: type: chore

#2952 fix(plugins): add warning message for local/package.json plugins relying on old node versions
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/node_version.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/build/tests/status/tests.js
Labels: type: bug

#3038 fix: do not print warning messages for plugins from the directory
  packages/build/src/plugins/node_version.js
  packages/build/src/plugins/resolve.js
Labels: type: bug

#3037 feat: add `--cachedConfigPath` CLI flag
  packages/build/src/core/config.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/log/messages/config.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/config/src/bin/flags.js
  packages/config/src/cached_config.js
  packages/config/src/log/main.js
  packages/config/src/main.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
Labels: type: chore, type: feature

#3042 chore: fix improper usage of `useBinary` in tests
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
Labels: type: chore

#3047 fix: remove `netlify_config_default_publish` feature flag
  packages/build/src/core/constants.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/helpers/main.js
  packages/config/src/build_dir.js
  packages/config/src/log/messages.js
  packages/config/src/main.js
  packages/config/src/merge_normalize.js
  packages/config/src/normalize.js
  packages/config/src/options/feature_flags.js
  packages/config/src/redirects.js
  packages/config/tests/helpers/main.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
Labels: type: chore

#3046 fix: log `--cachedConfigPath` in verbose mode
  packages/build/src/log/messages/config.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
Labels: type: chore

#3057 feat: return `accounts` and `addons` from `@netlify/config`
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/config/README.md
  packages/config/src/main.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature

#3056 feat: pass `publish` directory to the buildbot during deploys
  packages/build/src/plugins_core/deploy/buildbot_client.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3066 feat: improve verbose logging
  packages/build/src/log/messages/config.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#3078 feat: add `build.publishOrigin` to `@netlify/config`
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/time/snapshots/tests.js.snap
  packages/config/README.md
  packages/config/src/log/cleanup.js
  packages/config/src/normalize.js
  packages/config/src/origin.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature

#3059 feat: do not print `redirects` with the `@netlify/config` CLI
  packages/config/src/bin/main.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
Labels: type: feature

#3083 fix: set `redirects` to an empty array with `@netlify/config` binary output
  packages/config/src/bin/main.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
Labels: type: bug, type: chore

#3095 fix: pin zip-it-and-ship-it to version 4.4.2
  package-lock.json
  packages/build/package.json
  packages/functions-utils/package.json
Labels: type: bug

#3093 feat: add `configMutations` internal variable
  packages/build/src/plugins/child/mutations.js
  packages/build/src/plugins/child/run.js
Labels: type: feature

#3081 fix(plugins): feature flag plugin execution with the system node version
  packages/build/src/core/feature_flags.js
  packages/build/src/core/main.js
  packages/build/src/plugins/node_version.js
  packages/build/src/plugins/options.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/commands/snapshots/tests.js.md
  packages/build/tests/commands/snapshots/tests.js.snap
  packages/build/tests/core/fixtures/local_node_path_unused/manifest.yml
  packages/build/tests/core/fixtures/local_node_path_unused/netlify.toml
  packages/build/tests/core/fixtures/local_node_path_unused/plugin.js
  packages/build/tests/core/fixtures/package_node_path_unused/netlify.toml
  packages/build/tests/core/fixtures/package_node_path_unused/node_modules/netlify-plugin-test/index.js
  packages/build/tests/core/fixtures/package_node_path_unused/node_modules/netlify-plugin-test/manifest.yml
  packages/build/tests/core/fixtures/package_node_path_unused/node_modules/netlify-plugin-test/package.json
  packages/build/tests/core/fixtures/package_node_path_unused/package.json
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/helpers/main.js
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: init/deprecate-node-8, type: feature

#3108 chore: revert "fix(deps): update dependency @netlify/zip-it-and-ship-it to v4.6.0"
  package-lock.json
  packages/build/package.json
  packages/functions-utils/package.json
Labels: type: chore

#3109 feat!: do not print `@netlify/config` return value when `output` is defined
  packages/config/src/bin/main.js
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/cli/tests.js
Labels: type: feature

#3101 feat: move proxy handler logic
  packages/build/package.json
  packages/build/src/plugins/child/mutations.js
  packages/build/src/plugins/child/run.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_any/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_build/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_nested/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_star/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#3102 feat: add `priorityConfig` to `@netlify/config`
  packages/config/README.md
  packages/config/src/base.js
  packages/config/src/bin/flags.js
  packages/config/src/inline_config.js
  packages/config/src/log/main.js
  packages/config/src/main.js
  packages/config/src/merge_normalize.js
  packages/config/src/origin.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/log/tests.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: feature

#3113 feat: move `netlifyConfig` mutations validation logic
  packages/build/src/plugins/child/mutations.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#3125 chore: add `keep-func-props` to `renovate.json5`
  renovate.json5
Labels: type: chore

#3117 feat: simplify proxy logic
  packages/build/src/plugins/child/mutations.js
  packages/build/src/plugins/child/run.js
Labels: type: chore, type: feature

#3115 feat: add `config.redirectsOrigin`
  packages/config/src/origin.js
  packages/config/src/redirects.js
  packages/config/tests/parse/fixtures/empty/.gitkeep
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/parse/tests.js
Labels: type: feature

#3128 feat: log `redirectsOrigin` in debug mode
  packages/config/src/log/cleanup.js
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/parse/tests.js
Labels: type: feature

#3132 feat: split mutations logic
  packages/build/src/log/messages/plugins.js
  packages/build/src/plugins/child/config_prop_name.js
  packages/build/src/plugins/child/mutations.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/child/track.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#3135 feat: apply `netlifyConfig` modifications in the parent process
  packages/build/src/commands/plugin.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/child/track.js
  packages/build/src/plugins/config_prop_name.js
  packages/build/src/plugins/mutations.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: type: feature

#3138 chore(ci): add prerelease action
  .github/workflows/pre-release.yml
  CONTRIBUTING.md
Labels: type: chore

#3143 feat: add `priorityConfig` to `@netlify/build`
  packages/build/package.json
  packages/build/src/commands/plugin.js
  packages/build/src/commands/return.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/plugins/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_persist/manifest.yml
  packages/build/tests/plugins/fixtures/config_mutate_persist/netlify.toml
  packages/build/tests/plugins/fixtures/config_mutate_persist/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3145 feat: remove `zisiHandlerV2` feature flag
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins_core/functions/index.js
Labels: type: feature

#3147 feat: call `@netlify/config` when the configuration is modified
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run_command.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/config.js
  packages/build/src/core/main.js
Labels: type: feature

#3153 feat: validate and normalize config properties modified by plugins
  packages/build/package.json
  packages/build/src/commands/plugin.js
  packages/build/src/commands/run_commands.js
  packages/build/src/core/config.js
  packages/build/src/plugins/config_prop_name.js
  packages/build/src/plugins/mutations.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_directory_nested/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_functions_new/plugin.js
  packages/build/tests/plugins/fixtures/config_mutate_persist/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: feature

#3150 feat: remove redirects parsing feature flag
  packages/build/tests/helpers/main.js
  packages/config/src/main.js
  packages/config/src/options/feature_flags.js
  packages/config/src/redirects.js
  packages/config/tests/helpers/main.js
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
Labels: type: feature

#3144 fix(plugins): only rely in the system node version for plugins running Node <10
  packages/build/src/plugins/node_version.js
Labels: type: bug

#3158 feat: allow plugins to unset configuration properties
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/config/src/api/client.js
  packages/config/src/case.js
  packages/config/src/files.js
  packages/config/src/functions_config.js
  packages/config/src/inline_config.js
  packages/config/src/normalize.js
  packages/config/src/origin.js
  packages/config/src/utils/merge.js
  packages/config/src/utils/remove_falsy.js
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/load/tests.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature
