Repository netlify/build, pull requests merged in 2022-01, with the labels that each got.

#3997 feat: remove `buildbot_scheduled_functions` feature flag
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/core/tests.js
Labels: type: feature, automerge

#3995 chore(ci-release): use v2 of release please action
  .github/workflows/release-please.yml
Labels: type: chore, automerge

#4023 feat: update `README.md` to use ES modules with plugins
  packages/cache-utils/README.md
  packages/functions-utils/README.md
  packages/git-utils/README.md
Labels: type: feature, automerge

#4022 chore: add a test for ESM plugins
  packages/build/tests/plugins/fixtures/es_modules_module/netlify.toml
  packages/build/tests/plugins/fixtures/es_modules_module/node_modules/netlify-plugin-test/main.js
  packages/build/tests/plugins/fixtures/es_modules_module/node_modules/netlify-plugin-test/manifest.yml
  packages/build/tests/plugins/fixtures/es_modules_module/node_modules/netlify-plugin-test/package.json
  packages/build/tests/plugins/fixtures/es_modules_module/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: type: chore, automerge

#4025 chore: remove make-dir and use fs promises
  package-lock.json
  packages/build/package.json
  packages/build/src/install/missing.js
  packages/build/src/log/messages/mutations.js
  packages/build/src/plugins/manifest/load.js
  packages/build/tests/core/tests.js
  packages/build/tests/functions/tests.js
  packages/build/tests/helpers/temp.js
  packages/build/tests/mutate_headers_redirects/fixtures/headers_before/plugin.js
  packages/build/tests/mutate_headers_redirects/fixtures/headers_command/command.js
  packages/build/tests/mutate_headers_redirects/fixtures/headers_command_dynamic/command.js
  packages/build/tests/mutate_headers_redirects/fixtures/headers_plugin/plugin.js
  packages/build/tests/mutate_headers_redirects/fixtures/headers_plugin_dynamic/plugin.js
  packages/build/tests/mutate_headers_redirects/fixtures/redirects_before/plugin.js
  packages/build/tests/mutate_headers_redirects/fixtures/redirects_command/command.js
  packages/build/tests/mutate_headers_redirects/fixtures/redirects_command_dynamic/command.js
  packages/build/tests/mutate_headers_redirects/fixtures/redirects_plugin/plugin.js
  packages/build/tests/mutate_headers_redirects/fixtures/redirects_plugin_dynamic/plugin.js
  packages/build/tests/mutate_save/fixtures/headers_command_error/command.js
  packages/build/tests/mutate_save/fixtures/save_headers/plugin.js
  packages/build/tests/mutate_save/fixtures/save_redirects/plugin.js
  packages/build/tests/mutate_save/tests.js
  packages/build/tests/plugins_list/tests.js
  packages/cache-utils/package.json
  packages/cache-utils/src/manifest.js
  packages/cache-utils/tests/digests.js
  packages/cache-utils/tests/dir.js
  packages/cache-utils/tests/helpers/main.js
  packages/cache-utils/tests/save_restore.js
  packages/config/package.json
  packages/config/src/bin/main.js
  packages/config/src/cached_config.js
  packages/config/src/mutations/update.js
  packages/config/src/options/base.js
  packages/config/src/parse.js
  packages/config/tests/cli/tests.js
  packages/config/tests/load/tests.js
  packages/config/tests/mutate/tests.js
Labels: type: chore, automerge

#4024 chore(deps): replace nyc with c8 and remove unneeded devDependencies
  .c8rc.json
  .gitignore
  .nycrc.yml
  package-lock.json
  package.json
Labels: type: chore, automerge

#4030 fix: use fs promises directly
  packages/build/src/plugins_core/functions/utils.js
  packages/cache-utils/src/fs.js
  packages/functions-utils/src/main.js
Labels: type: chore

#4034 chore: fix Husky
  package.json
Labels: type: chore, automerge

#4035 fix: husky binary not found
  package-lock.json
  package.json
Labels: type: bug, automerge

#4036 fix(deps): update del to v6.0.0
  package-lock.json
  packages/cache-utils/package.json
  packages/config/package.json
  packages/functions-utils/package.json
Labels: type: chore, automerge

#4037 fix(deps): update yargs to v16.0.0
  package-lock.json
  packages/build/package.json
  packages/build/src/core/bin.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/config/package.json
  packages/config/src/bin/flags.js
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
Labels: type: chore

#4045 fix: upgrade Yargs to v17
  package-lock.json
  packages/build/package.json
  packages/build/src/core/flags.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/config/package.json
  packages/config/src/bin/flags.js
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
Labels: type: chore, type: bug, automerge

#4052 fix(deps): add missing ts-node peer dependencies
  package-lock.json
  packages/build/package.json
Labels: type: chore

#4058 feat: pass `zipGo` property to ZISI
  packages/build/src/plugins_core/functions/index.js
  packages/build/tests/core/tests.js
Labels: type: feature, automerge

#4066 fix: pin zip-it-and-ship-it to v5.4.1
  package-lock.json
  packages/build/package.json
Labels: type: bug

#4071 fix: pin zip-it-and-ship-it to v5.4.1
  package-lock.json
  packages/build/package.json
  packages/functions-utils/package.json
Labels: type: bug, automerge
