Repository netlify/build, pull requests merged in 2022-08, with the labels that each got.

#4400 feat: improve normalization of function bundling errors
  .eslintrc.cjs
  packages/build/src/error/monitor/normalize.js
  packages/build/src/error/type.js
  packages/build/tests/core/tests.js
  packages/build/tests/helpers/normalize.js
  packages/build/tests/monitor/fixtures/edge_function_error/netlify/edge-functions/trouble.ts
  packages/build/tests/monitor/fixtures/function_bundling_error/netlify/functions/trouble.ts
  packages/build/tests/monitor/fixtures/serverless_function/netlify/functions/hello.ts
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/build/tests/monitor/tests.js
Labels: type: feature, automerge

#4403 fix: remove extraneous character from error group
  packages/build/src/error/type.js
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
Labels: type: bug

#4406 feat: add support for system logger
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/log/logger.js
  packages/build/src/log/messages/edge_manifest.js
  packages/build/src/plugins_core/edge_functions/index.js
  packages/build/src/steps/core_step.js
  packages/build/src/steps/run_step.js
  packages/build/src/steps/run_steps.js
  packages/build/tests/edge_functions/snapshots/tests.js.md
  packages/build/tests/edge_functions/snapshots/tests.js.snap
  packages/build/tests/edge_functions/tests.js
  packages/build/tests/mutate/snapshots/tests.js.md
  packages/build/tests/mutate/snapshots/tests.js.snap
  packages/build/tests/unit/logger/tests.js
Labels: type: feature

#4408 fix: do not print system logs to stdout when debug mode is off
  packages/build/src/log/logger.js
  packages/build/tests/edge_functions/snapshots/tests.js.md
  packages/build/tests/edge_functions/snapshots/tests.js.snap
Labels: type: bug

#4415 feat: set Edge Bundler system logger behind feature flag
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins_core/edge_functions/index.js
Labels: type: feature

#4414 feat: improve serialization of system log input
  packages/build/src/log/logger.js
  packages/build/tests/unit/logger/snapshots/tests.js.md
  packages/build/tests/unit/logger/snapshots/tests.js.snap
  packages/build/tests/unit/logger/tests.js
Labels: type: feature, automerge

#4427 fix: hide `systemLogFile` flag from output
  packages/build/src/log/messages/config.js
  packages/build/tests/edge_functions/snapshots/tests.js.md
  packages/build/tests/edge_functions/snapshots/tests.js.snap
  packages/build/tests/edge_functions/tests.js
Labels: type: bug, automerge

#4429 fix: pass system log to runCoreSteps
  .eslintrc.cjs
  packages/build/src/core/main.js
  packages/build/src/steps/run_core_steps.js
  packages/build/src/steps/run_step.js
  packages/build/src/steps/run_steps.js
  packages/config/src/bin/flags.js
  packages/config/src/main.js
  packages/config/src/validate/validations.js
Labels: type: bug

#4413 fix: coerce environment variable to string
  packages/config/src/env/main.js
  packages/config/tests/env/fixtures/file_env_not_string/netlify.toml
  packages/config/tests/env/tests.js
Labels: type: chore, type: bug

#4435 chore: update package-lock to include zip-it-and-ship-it with carot
  package-lock.json
Labels: type: chore

#4433 chore: delete lerna.json
  lerna.json
Labels: type: chore, automerge

#4418 Fix: handle 422
  packages/build/src/plugins_core/deploy/buildbot_client.js
Labels: type: bug, automerge

#4436 feat: improve messaging around runtimes in log outputs
  packages/build/src/log/messages/compatibility.js
  packages/build/src/plugins/spawn.js
Labels: type: feature, automerge

#4431 feat: add `onPreDev` and `onDev` events
  packages/build/src/core/build.js
  packages/build/src/core/dev.js
  packages/build/src/core/flags.js
  packages/build/src/core/main.js
  packages/build/src/core/normalize_flags.js
  packages/build/src/log/messages/config.js
  packages/build/src/plugins/child/validate.js
  packages/build/src/plugins/events.js
  packages/build/src/steps/get.js
  packages/build/tests/helpers/main.js
  packages/build/tests/plugins_events/fixtures/dev_and_build/manifest.yml
  packages/build/tests/plugins_events/fixtures/dev_and_build/netlify.toml
  packages/build/tests/plugins_events/fixtures/dev_and_build/plugin.js
  packages/build/tests/plugins_events/snapshots/tests.js.md
  packages/build/tests/plugins_events/snapshots/tests.js.snap
  packages/build/tests/plugins_events/tests.js
  packages/config/src/events.js
  packages/config/src/main.js
Labels: type: feature, automerge

#4438 chore: add tests to ensure build plugins can manipulate netlifyToml.edge_functions array
  packages/build/tests/edge_functions/fixtures/functions_plugin_mutations/.netlify/edge-functions/mutated-function.ts
  packages/build/tests/edge_functions/fixtures/functions_plugin_mutations/manifest.yml
  packages/build/tests/edge_functions/fixtures/functions_plugin_mutations/netlify.toml
  packages/build/tests/edge_functions/fixtures/functions_plugin_mutations/plugin.js
  packages/build/tests/edge_functions/snapshots/tests.js.md
  packages/build/tests/edge_functions/snapshots/tests.js.snap
  packages/build/tests/edge_functions/tests.js
Labels: type: chore

#4444 feat: don't stop child processes of plugins in dev timeline
  packages/build/src/core/build.js
Labels: type: feature, automerge

#4447 feat: add existing nextjs plugin as a runtime
  packages/build/src/log/messages/compatibility.js
Labels: type: feature, automerge

#4443 feat: use utils.status.show to add no of edge functions to deploy summary
  packages/build/src/plugins_core/edge_functions/index.js
Labels: type: chore, type: feature, echoes/initiative: runtime/edge-handlers

#4452 fix: revert feat: use utils.status.show to add no of edge functions to deploy summary (#4443)
  packages/build/src/plugins_core/edge_functions/index.js
Labels: type: chore, type: bug

#4454 fix: null check
  packages/config/src/env/main.js
Labels: type: bug

#4446 fix: don't create context specific redirects
  packages/build/tests/mutate_save/snapshots/tests.js.md
  packages/build/tests/mutate_save/snapshots/tests.js.snap
  packages/config/src/context.js
Labels: type: bug, automerge

#4459 fix: Update semver logic
  packages/build/src/plugins/compatibility.js
Labels: type: chore, type: bug

#4461 fix: improve prerelease matching in plugin list
  packages/build/src/plugins/compatibility.js
  packages/build/tests/plugins_list/tests.js
Labels: type: bug, automerge

#4464 feat: add reference to runtime when installing missing packages
  packages/build/src/log/messages/compatibility.js
  packages/build/src/log/messages/install.js
  packages/build/src/utils/runtime.js
Labels: type: feature, automerge

#4466 fix: length check for runtimes used
  packages/build/src/log/messages/install.js
Labels: type: bug, automerge
