Repository netlify/build, pull requests merged in 2022-03, with the labels that each got.

#4208 fix: `URL` environment variable in local builds
  packages/config/src/env/main.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/api/tests.js
  packages/config/tests/env/tests.js
Labels: type: bug, automerge

#4209 fix: add deploy-related environment variables to local builds
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/config/src/env/main.js
  packages/config/src/options/main.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/api/tests.js
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/env/tests.js
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/mutate/snapshots/tests.js.md
  packages/config/tests/mutate/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: bug, automerge

#4213 test: fix flaky tests
  packages/build/tests/edge_handlers/tests.js
Labels: type: chore, automerge

#4214 chore: use GitHub forms for issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report_cli.yml
  .github/ISSUE_TEMPLATE/bug_report_ui.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: type: chore, automerge

#4212 chore(ci-tests): split tests across multiple machines
  .github/workflows/workflow.yml
  CONTRIBUTING.md
  ava.config.js
  package-lock.json
  package.json
  tests-metadata.json
  tools/tests_duration.mjs
Labels: type: chore

#4222 feat: add `INTERNAL_EDGE_HANDLERS_SRC` constant
  packages/build/src/core/constants.js
  packages/build/test-d/netlify_plugin_options.ts
  packages/build/tests/constants/fixtures/internal_edge_handlers_src/manifest.yml
  packages/build/tests/constants/fixtures/internal_edge_handlers_src/netlify.toml
  packages/build/tests/constants/fixtures/internal_edge_handlers_src/plugin.js
  packages/build/tests/constants/snapshots/tests.js.md
  packages/build/tests/constants/snapshots/tests.js.snap
  packages/build/tests/constants/tests.js
  packages/build/types/netlify_plugin_constants.d.ts
Labels: type: feature

#4234 fix: non-writable `error.message` inside plugins
  packages/build/src/plugins/error.js
Labels: type: bug, automerge

#4230 chore: document `@netlify/config`
  packages/config/docs/file_paths.md
  packages/config/docs/main.md
Labels: type: chore, automerge

#4229 chore: add documentation about error handling and monitoring
  packages/build/docs/errors.md
Labels: type: chore, automerge

#4240 chore: add documentation about Build plugins
  packages/build/docs/plugins.md
Labels: type: chore, automerge

#4236 chore: document Netlify Build main flow and steps
  packages/build/docs/flow.md
Labels: type: chore
