Repository netlify/build, pull requests merged in 2022-07, with the labels that each got.

#4376 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: type: chore, automerge

#4386 feat: Add a way to pass extra data to the show util
  packages/build/src/plugins/child/status.js
  packages/build/src/status/report.js
  packages/build/tests/status/fixtures/print/five.js
  packages/build/tests/status/fixtures/print/netlify.toml
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/status/tests.js
Labels: type: feature

#4319 feat: validate Edge Functions manifest
  package-lock.json
  packages/build/package.json
  packages/build/src/plugins_core/edge_functions/index.js
  packages/build/src/plugins_core/edge_functions/validate_manifest/validate_edge_functions_manifest.js
  packages/build/tests/unit/validate_edge_manifest/test.js
  packages/build/tests/unit/validate_edge_manifest/unit_fixtures/invalid_manifest_extra_property/manifest.json
  packages/build/tests/unit/validate_edge_manifest/unit_fixtures/invalid_manifest_missing_property/manifest.json
  packages/build/tests/unit/validate_edge_manifest/unit_fixtures/invalid_manifest_wrong_route_pattern/manifest.json
  packages/build/tests/unit/validate_edge_manifest/unit_fixtures/valid_manifest/manifest.json
  packages/build/tests/unit/validate_edge_manifest/util.js
Labels: type: feature

#4392 feat: pass build directory to edge functions bundling
  packages/build/src/plugins_core/edge_functions/index.js
Labels: type: feature, automerge

#4393 fix: fix error message for edge function bundling errors
  packages/build/src/error/parse/location.js
  packages/build/src/error/type.js
  packages/build/src/plugins_core/edge_functions/index.js
  packages/build/src/plugins_core/edge_functions/lib/error.js
  packages/build/tests/edge_functions/snapshots/tests.js.md
  packages/build/tests/edge_functions/snapshots/tests.js.snap
  packages/build/tests/edge_functions/tests.js
  packages/build/tests/helpers/normalize.js
Labels: type: bug, automerge

#4394 feat: add support for custom hashing group in errors
  packages/build/src/error/monitor/report.js
  packages/build/tests/monitor/fixtures/function_bundling_error/netlify/functions/trouble.ts
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/build/tests/monitor/tests.js
Labels: type: feature

#4396 feat: improve error normalisation logic
  packages/build/src/error/monitor/normalize.js
  packages/build/tests/monitor/tests.js
Labels: type: feature

#4398 fix: group function bundling errors
  packages/build/src/error/monitor/normalize.js
  packages/build/src/error/type.js
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/build/tests/monitor/tests.js
Labels: type: bug
