Repository netlify/build, pull requests merged in 2022-10, with the labels that each got.

#4552 feat: optional extra info to error utils
  packages/build/src/error/parse/parse.js
  packages/build/src/error/parse/serialize_status.js
  packages/build/src/plugins/error.js
  packages/build/tests/status/fixtures/error_extra_info/manifest.yml
  packages/build/tests/status/fixtures/error_extra_info/netlify.toml
  packages/build/tests/status/fixtures/error_extra_info/plugin.js
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/status/tests.js
Labels: type: feature

#4549 feat: allow edge function schema to have a display name
  packages/build/src/plugins_core/edge_functions/validate_manifest/validate_edge_functions_manifest.js
Labels: type: feature, automerge

#4543 chore: move tests from build to the new testing library
  .eslintignore
  ava.base.js
  package-lock.json
  packages/build/tests/README.md
  packages/build/tests/constants/tests.js
  packages/build/tests/core/tests.js
  packages/build/tests/deploy/tests.js
  packages/build/tests/edge_functions/tests.js
  packages/build/tests/env/tests.js
  packages/build/tests/error/tests.js
  packages/build/tests/functions/tests.js
  packages/build/tests/helpers/common.js
  packages/build/tests/helpers/config.js
  packages/build/tests/helpers/dir.js
  packages/build/tests/helpers/main.js
  packages/build/tests/helpers/normalize.js
  packages/build/tests/helpers/server.js
  packages/build/tests/helpers/temp.js
  packages/build/tests/install/tests.js
  packages/build/tests/log/tests.js
  packages/build/tests/manifest/tests.js
  packages/build/tests/monitor/tests.js
  packages/build/tests/mutate/tests.js
  packages/build/tests/mutate_headers_redirects/tests.js
  packages/build/tests/mutate_save/tests.js
  packages/build/tests/plugins/tests.js
  packages/build/tests/plugins_events/tests.js
  packages/build/tests/plugins_list/tests.js
  packages/build/tests/stack/tests.js
  packages/build/tests/status/tests.js
  packages/build/tests/steps/tests.js
  packages/build/tests/telemetry/tests.js
  packages/build/tests/time/tests.js
  packages/build/tests/unit/logger/tests.js
  packages/build/tests/unit/validate_edge_manifest/test.js
  packages/build/tests/utils_build/tests.js
  packages/config/tests/api/tests.js
  packages/config/tests/cli/tests.js
  packages/config/tests/cwd/tests.js
  packages/config/tests/env/tests.js
  packages/config/tests/load/tests.js
  packages/config/tests/log/tests.js
  packages/testing/package.json
  packages/testing/src/fixture.ts
  packages/testing/src/index.ts
  packages/testing/src/normalize.ts
  packages/testing/src/server.ts
  packages/testing/src/tcp_server.ts
Labels: type: chore, automerge

#4569 chore: do automatic publishing based on the dependency graph with lerna
  .circleci/config.yml
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
  .prettierignore
  package.json
  packages/build/package.json
  packages/cache-utils/package.json
  packages/config/package.json
  packages/functions-utils/package.json
  packages/git-utils/package.json
  packages/run-utils/package.json
Labels: type: chore, automerge

#4571 fix: migrate run-utils
  packages/run-utils/package.json
  packages/run-utils/src/main.ts
  packages/run-utils/tsconfig.json
Labels: type: bug

#4575 chore: create github release on publish
  .circleci/config.yml
Labels: type: chore, automerge

#4577 chore: remove pr labeler
  .github/workflows/labeler.yml
Labels: automerge

#4578 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/git-utils/CHANGELOG.md
  packages/git-utils/package.json
Labels: autorelease: pending

#4583 chore: make test running independent from netlify build
  .github/workflows/workflow.yml
  .prettierignore
  ava.base.js
  nx.json
  package-lock.json
  package.json
  packages/build/package.json
  packages/build/tests-metadata.json
  packages/cache-utils/package.json
  packages/config/package.json
  packages/functions-utils/package.json
  packages/git-utils/package.json
  packages/run-utils/package.json
  tests-metadata.json
  tools/package.json
  tools/tests-duration.js
Labels: automerge

#4580 chore: release main
  .release-please-manifest.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#4565 chore: migrate build package to Typescript
  .gitignore
  package-lock.json
  packages/build/package.json
  packages/build/src/core/main.ts
  packages/build/tests/plugins/fixtures/tsconfig.json
  packages/build/tsconfig.json
Labels: type: chore

#4594 fix(headers-parser): move headers-parser to monorepo and add types
  .release-please-manifest.json
  package-lock.json
  packages/git-utils/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/LICENSE
  packages/headers-parser/README.md
  packages/headers-parser/ava.config.js
  packages/headers-parser/package.json
  packages/headers-parser/src/all.js
  packages/headers-parser/src/for_regexp.js
  packages/headers-parser/src/index.js
  packages/headers-parser/src/line_parser.js
  packages/headers-parser/src/merge.js
  packages/headers-parser/src/netlify_config_parser.js
  packages/headers-parser/src/normalize.js
  packages/headers-parser/src/results.js
  packages/headers-parser/tests/all.js
  packages/headers-parser/tests/fixtures/headers_file/comment
  packages/headers-parser/tests/fixtures/headers_file/duplicate
  packages/headers-parser/tests/fixtures/headers_file/empty
  packages/headers-parser/tests/fixtures/headers_file/empty_line
  packages/headers-parser/tests/fixtures/headers_file/invalid_dir/.gitkeep
  packages/headers-parser/tests/fixtures/headers_file/invalid_for_order
  packages/headers-parser/tests/fixtures/headers_file/invalid_value_name
  packages/headers-parser/tests/fixtures/headers_file/invalid_value_string
  packages/headers-parser/tests/fixtures/headers_file/multiple_values
  packages/headers-parser/tests/fixtures/headers_file/no_colon
  packages/headers-parser/tests/fixtures/headers_file/success
  packages/headers-parser/tests/fixtures/headers_file/success_two
  packages/headers-parser/tests/fixtures/headers_file/trim_line_path
  packages/headers-parser/tests/fixtures/headers_file/trim_line_values
  packages/headers-parser/tests/fixtures/headers_file/trim_name
  packages/headers-parser/tests/fixtures/headers_file/trim_value
  packages/headers-parser/tests/fixtures/netlify_config/duplicate.toml
  packages/headers-parser/tests/fixtures/netlify_config/empty.toml
  packages/headers-parser/tests/fixtures/netlify_config/for_path_no_slash.toml
  packages/headers-parser/tests/fixtures/netlify_config/invalid_array.toml
  packages/headers-parser/tests/fixtures/netlify_config/invalid_for_string.toml
  packages/headers-parser/tests/fixtures/netlify_config/invalid_for_undefined.toml
  packages/headers-parser/tests/fixtures/netlify_config/invalid_object.toml
  packages/headers-parser/tests/fixtures/netlify_config/invalid_toml.toml
  packages/headers-parser/tests/fixtures/netlify_config/invalid_value_array.toml
  packages/headers-parser/tests/fixtures/netlify_config/invalid_value_name.toml
  packages/headers-parser/tests/fixtures/netlify_config/invalid_value_string.toml
  packages/headers-parser/tests/fixtures/netlify_config/invalid_values_object.toml
  packages/headers-parser/tests/fixtures/netlify_config/multiple_values.toml
  packages/headers-parser/tests/fixtures/netlify_config/success.toml
  packages/headers-parser/tests/fixtures/netlify_config/trim_name.toml
  packages/headers-parser/tests/fixtures/netlify_config/trim_path.toml
  packages/headers-parser/tests/fixtures/netlify_config/trim_value.toml
  packages/headers-parser/tests/fixtures/netlify_config/trim_value_array.toml
  packages/headers-parser/tests/fixtures/netlify_config/value_array.toml
  packages/headers-parser/tests/fixtures/netlify_config/values_undefined.toml
  packages/headers-parser/tests/for_regexp.js
  packages/headers-parser/tests/helpers/main.js
  packages/headers-parser/tests/line_parser.js
  packages/headers-parser/tests/merge.js
  packages/headers-parser/tests/netlify_config_parser.js
  packages/headers-parser/tsconfig.json
  release-please-config.json
Labels: automerge

#4591 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/git-utils/CHANGELOG.md
  packages/git-utils/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
Labels: autorelease: pending

#4596 fix!: migrate to ESModules and add types + adapt minimum node version
  .release-please-manifest.json
  package-lock.json
  packages/nock-udp/CHANGELOG.md
  packages/nock-udp/LICENSE
  packages/nock-udp/README.md
  packages/nock-udp/ava.config.js
  packages/nock-udp/package.json
  packages/nock-udp/src/main.js
  packages/nock-udp/test/helpers/udp_server.js
  packages/nock-udp/test/main.js
  packages/nock-udp/tsconfig.json
  release-please-config.json
Labels: automerge

#4597 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/nock-udp/CHANGELOG.md
  packages/nock-udp/package.json
Labels: autorelease: pending

#4599 fix!: drop node 12 support as it already reached EOL
  .github/workflows/workflow.yml
  README.md
  package-lock.json
  package.json
  packages/build-info/package.json
  packages/build/package.json
  packages/build/tests/install/tests.js
  packages/build/tests/plugins/fixtures/engines/package.json
  packages/build/tests/plugins/fixtures/version_greater_than_minimum/package.json
  packages/build/tests/plugins/tests.js
  packages/cache-utils/package.json
  packages/config/package.json
  packages/functions-utils/package.json
  packages/git-utils/package.json
  packages/headers-parser/package.json
  packages/js-client/package.json
  packages/nock-udp/package.json
  packages/redirect-parser/package.json
  packages/run-utils/package.json
  packages/testing/package.json
  packages/testing/src/server.ts
  tools/package.json
Labels: automerge

#4604 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/git-utils/CHANGELOG.md
  packages/git-utils/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/nock-udp/CHANGELOG.md
  packages/nock-udp/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
  packages/run-utils/CHANGELOG.md
  packages/run-utils/package.json
  packages/testing/package.json
Labels: autorelease: pending

#4603 ci: add stalebot to autoclose old issues
  .github/workflows/stalebot.yml
Labels: automerge

#4598 chore(run-utils): make tests execution with typescript
  nx.json
  package-lock.json
  packages/run-utils/ava.config.js
  packages/run-utils/package.json
  packages/run-utils/src/main.ts
  packages/run-utils/tests/main.ts
Labels: automerge

#4616 chore: move git utils test to typescript + vitest
  package-lock.json
  packages/git-utils/ava.config.js
  packages/git-utils/package.json
  packages/git-utils/src/commits.ts
  packages/git-utils/src/diff.ts
  packages/git-utils/src/exec.ts
  packages/git-utils/src/main.ts
  packages/git-utils/src/match.ts
  packages/git-utils/src/refs.ts
  packages/git-utils/tests/main.js
  packages/git-utils/tests/main.test.ts
  packages/git-utils/vitest.config.ts
Labels: automerge

#4632 test: fix tests that timeouts due to ts-node
  packages/build-info/test/__snapshots__/bin.test.ts.snap
  packages/build-info/test/bin.test.ts
  packages/build-info/vitest.config.ts
Labels: automerge

#4605 chore: release main
  .release-please-manifest.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/git-utils/CHANGELOG.md
  packages/git-utils/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/run-utils/CHANGELOG.md
  packages/run-utils/package.json
Labels: autorelease: pending, automerge

#4638 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#4642 chore: release main
  .release-please-manifest.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#4646 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4649 fix(build): add post_cache_routes to edge validation schema
  package-lock.json
  packages/build/src/plugins_core/edge_functions/validate_manifest/validate_edge_functions_manifest.js
  packages/build/tests/edge_functions/snapshots/tests.js.md
  packages/build/tests/edge_functions/snapshots/tests.js.snap
  packages/build/tests/edge_functions/tests.js
  packages/build/tests/unit/validate_edge_manifest/snapshots/tests.js.md
  packages/build/tests/unit/validate_edge_manifest/snapshots/tests.js.snap
  packages/build/tests/unit/validate_edge_manifest/tests.js
  packages/build/tests/unit/validate_edge_manifest/util.js
Labels: automerge

#4640 chore: Nudge contributors to convert JavaScript to TypeScript
  .github/workflows/typescript-nudge.yml
Labels: automerge

#4654 chore: migrate redirect-parser to vitest
  package-lock.json
  packages/redirect-parser/ava.config.js
  packages/redirect-parser/package.json
  packages/redirect-parser/tests/all.test.ts
  packages/redirect-parser/tests/all.ts
  packages/redirect-parser/tests/helpers/main.ts
  packages/redirect-parser/tests/line-parser.test.ts
  packages/redirect-parser/tests/line_parser.ts
  packages/redirect-parser/tests/merge.test.ts
  packages/redirect-parser/tests/merge.ts
  packages/redirect-parser/tests/netlify-config-parser.test.ts
  packages/redirect-parser/tests/netlify_config_parser.ts
  packages/redirect-parser/vitest.config.ts
Labels: automerge

#4655 feat: add `mode` property to edge functions config
  packages/config/src/edge_functions_config.ts
  packages/config/src/validate/validations.js
  packages/config/tests/validate/fixtures/edge_functions_mode_allowed/netlify.toml
  packages/config/tests/validate/fixtures/edge_functions_mode_disallowed/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: feature, Adds or modifies js files

#4657 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#4643 feat!: add packageManger information + make jsWorkspace packagePaths relative
  package-lock.json
  packages/build-info/package.json
  packages/build-info/src/bin.ts
  packages/build-info/src/context.ts
  packages/build-info/src/core.ts
  packages/build-info/src/detect-package-manager.ts
  packages/build-info/src/detect-package-mangaer.test.ts
  packages/build-info/src/get-build-info.ts
  packages/build-info/src/index.ts
  packages/build-info/src/main.ts
  packages/build-info/src/workspaces.ts
  packages/build-info/tests/__snapshots__/bin.test.ts.snap
  packages/build-info/tests/bin.test.ts
  packages/build-info/tests/context.test.ts
  packages/build-info/tests/fixtures/js-workspaces/not-in-workspace/package.json
  packages/build-info/tests/fixtures/js-workspaces/package.json
  packages/build-info/tests/fixtures/js-workspaces/packages/gatsby-site/gatsby-config.js
  packages/build-info/tests/fixtures/js-workspaces/packages/gatsby-site/package.json
  packages/build-info/tests/fixtures/js-workspaces/packages/package-2/package.json
  packages/build-info/tests/fixtures/pnpm-workspace/package.json
  packages/build-info/tests/fixtures/pnpm-workspace/packages/blog/package.json
  packages/build-info/tests/fixtures/pnpm-workspace/packages/website/package.json
  packages/build-info/tests/fixtures/pnpm-workspace/pnpm-lock.yaml
  packages/build-info/tests/fixtures/pnpm-workspace/pnpm-workspace.yaml
  packages/build-info/tests/fixtures/pnpm-workspace/tooling/package.json
  packages/build-info/tests/fixtures/simple-package-json/package.json
  packages/build-info/tests/fixtures/yarn-berry-workspace/.yarn/releases/yarn-3.2.4.cjs
  packages/build-info/tests/fixtures/yarn-berry-workspace/.yarnrc.yml
  packages/build-info/tests/fixtures/yarn-berry-workspace/package.json
  packages/build-info/tests/fixtures/yarn-berry-workspace/packages/blog/package.json
  packages/build-info/tests/fixtures/yarn-berry-workspace/packages/website/package.json
  packages/build-info/tests/fixtures/yarn-berry-workspace/tooling/package.json
  packages/build-info/tests/fixtures/yarn-berry-workspace/yarn.lock
  packages/build-info/tests/get-build-info.test.ts
  packages/build-info/tests/helpers.ts
  packages/build-info/tests/mock-file-system.ts
  packages/build-info/tests/pnpm.test.ts
  packages/build-info/tests/test-setup.ts
  packages/build-info/tests/yarn.test.ts
  packages/build-info/tsconfig.json
  packages/build-info/vitest.config.ts
Labels: Adds or modifies js files

#4653 fix(headers-parser): optimize merge of large headers files
  packages/headers-parser/package.json
  packages/headers-parser/src/all.ts
  packages/headers-parser/src/index.ts
  packages/headers-parser/src/line_parser.ts
  packages/headers-parser/src/merge.ts
  packages/headers-parser/src/netlify_config_parser.ts
  packages/headers-parser/src/normalize.ts
  packages/headers-parser/src/results.js
  packages/headers-parser/src/results.ts
  packages/headers-parser/src/types.ts
  packages/headers-parser/tests/fixtures/headers_file/large_headers_file
  packages/headers-parser/tests/merge.bench.ts
Labels: automerge
