Repository netlify/build, pull requests merged in 2022-12, with the labels that each got.

#4735 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4748 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4749 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#4752 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4753 fix: clear edge functions dist directory before build
  packages/build/src/plugins_core/edge_functions/index.js
  packages/build/tests/edge_functions/tests.js
Labels: type: feature, Adds or modifies js files

#4754 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4761 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#4764 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/git-utils/CHANGELOG.md
  packages/git-utils/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/nock-udp/CHANGELOG.md
  packages/nock-udp/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
  packages/run-utils/CHANGELOG.md
  packages/run-utils/package.json
Labels: autorelease: pending

#4767 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4769 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#4773 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#4775 chore: migrate from deprecated set-output command
  .github/workflows/pre-release.yml
  .github/workflows/workflow.yml
Labels: automerge

#4776 chore: remove plugins_break_builds_with_unsupported_plugin_versions feature flag
  CONTRIBUTING.md
  packages/build/src/core/feature_flags.js
  packages/build/src/log/messages/compatibility.ts
  packages/build/src/plugins/spawn.ts
  packages/build/tests/functions/fixtures/functions_package_json_invalid/package.json
  packages/build/tests/plugins_list/fixtures/plugins_unsupported_version_package_json/netlify.toml
  packages/build/tests/plugins_list/fixtures/plugins_unsupported_version_package_json/node_modules/@netlify/plugin-nextjs/index.js
  packages/build/tests/plugins_list/fixtures/plugins_unsupported_version_package_json/node_modules/@netlify/plugin-nextjs/manifest.yml
  packages/build/tests/plugins_list/fixtures/plugins_unsupported_version_package_json/node_modules/@netlify/plugin-nextjs/package.json
  packages/build/tests/plugins_list/fixtures/plugins_unsupported_version_package_json/package.json
  packages/build/tests/plugins_list/snapshots/tests.js.md
  packages/build/tests/plugins_list/tests.js
Labels: type: chore, automerge, Adds or modifies js files

#4779 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4774 feat: add `build.edge_functions_import_map` config property
  packages/config/src/validate/validations.js
  packages/config/tests/validate/fixtures/build_edge_functions_import_map/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: type: feature, Adds or modifies js files

#4785 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4787 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4789 chore: retry failed CI runs
  .github/workflows/workflow.yml
Labels: type: chore

#4788 feat: add `quiet` flag
  packages/build/src/core/build.ts
  packages/build/src/core/config.js
  packages/build/src/core/normalize_flags.ts
  packages/build/src/core/types.ts
  packages/build/src/plugins/spawn.ts
  packages/build/src/steps/return.js
  packages/build/src/steps/run_step.ts
  packages/build/src/steps/run_steps.js
  packages/build/tests/plugins_events/fixtures/dev_with_error/manifest.yml
  packages/build/tests/plugins_events/fixtures/dev_with_error/netlify.toml
  packages/build/tests/plugins_events/fixtures/dev_with_error/plugin.js
  packages/build/tests/plugins_events/snapshots/tests.js.md
  packages/build/tests/plugins_events/snapshots/tests.js.snap
  packages/build/tests/plugins_events/tests.js
Labels: type: feature, automerge, Adds or modifies js files

#4791 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending
