Repository netlify/build, pull requests merged in 2022-09, with the labels that each got.

#4484 test: fix tests to pass on m1 mac
  packages/build/tests/core/tests.js
Labels: type: chore

#4449 feat: activate deployment configuration API
  packages/build/src/plugins_core/functions/index.js
  packages/build/src/plugins_core/functions/zisi.js
  packages/build/tests/core/fixtures/functions_config_json/.netlify/functions-internal/function_two.js
  packages/build/tests/core/fixtures/functions_config_json/.netlify/functions-internal/function_two.json
  packages/build/tests/core/fixtures/functions_config_json/netlify/functions/function_one.js
  packages/build/tests/core/fixtures/functions_config_json/netlify/functions/function_one.json
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: type: feature

#4481 fix: rename edge functions constants types
  packages/build/test-d/config/netlify_config.ts
  packages/build/test-d/netlify_plugin_options.ts
  packages/build/types/config/netlify_config.d.ts
  packages/build/types/netlify_plugin_constants.d.ts
Labels: type: bug, automerge

#4508 feat: add support for edge functions import maps with ESZIP
  .gitignore
  package-lock.json
  packages/build/package.json
  packages/build/src/plugins_core/edge_functions/index.js
  packages/build/src/plugins_core/edge_functions/lib/internal_manifest.js
  packages/build/tests/edge_functions/fixtures/functions_internal/.netlify/edge-functions/function-1.ts
  packages/build/tests/edge_functions/fixtures/functions_internal/.netlify/edge-functions/manifest.json
  packages/build/tests/edge_functions/fixtures/functions_internal/import-map.json
  packages/build/tests/edge_functions/fixtures/functions_internal/util.ts
  packages/build/tests/edge_functions/tests.js
Labels: type: feature

#4524 fix: build packages with lerna
  .github/workflows/pre-release.yml
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
  .gitignore
  lerna.json
  nx.json
  package-lock.json
  package.json
  packages/build/package.json
  packages/build/src/error/parse/clean_stack.js
  packages/build/tests/core/tests.js
  packages/build/tests/edge_functions/tests.js
  packages/build/tests/helpers/main.js
  packages/build/tests/monitor/tests.js
  packages/build/tests/plugins_list/tests.js
  packages/build/tests/unit/logger/tests.js
  packages/build/tests/unit/validate_edge_manifest/test.js
  packages/cache-utils/package.json
  packages/cache-utils/tests/digests.js
  packages/cache-utils/tests/dir.js
  packages/cache-utils/tests/has.js
  packages/cache-utils/tests/list.js
  packages/cache-utils/tests/move.js
  packages/cache-utils/tests/path.js
  packages/cache-utils/tests/remove.js
  packages/cache-utils/tests/save_restore.js
  packages/cache-utils/tests/ttl.js
  packages/config/package.json
  packages/config/tests/load/tests.js
  packages/config/tests/mutate/tests.js
  packages/functions-utils/package.json
  packages/functions-utils/tests/main.js
  packages/git-utils/package.json
  packages/git-utils/tests/main.js
  packages/run-utils/package.json
  packages/run-utils/tests/fixtures/run.js
  packages/run-utils/tests/main.js
Labels: type: chore, type: bug

#4533 fix: lerna caching
  .github/workflows/release-please.yml
  package.json
  packages/build/package.json
  packages/cache-utils/package.json
  packages/config/package.json
  packages/functions-utils/package.json
  packages/git-utils/package.json
  packages/run-utils/package.json
Labels: type: bug

#4540 fix: nx caching and depends on config
  nx.json
  package-lock.json
  package.json
Labels: type: bug

#4538 ci: fix running build after install
  .github/workflows/workflow.yml
  package-lock.json
  packages/build/bin.js
  packages/build/package.json
  packages/config/bin.js
  packages/config/package.json
Labels: type: chore, automerge

#4544 refactor: migrate @netlify/config to typescript
  .eslintrc.cjs
  packages/config/package.json
  packages/config/src/error.ts
  packages/config/tsconfig.json
Labels: type: chore, automerge

#4546 chore: rename fake package in tests to avoid security warning
  packages/build/tests/plugins_list/fixtures/plugins_compat_site_dependencies_range/node_modules/@netlify/dependency-with-range/package.json
  packages/build/tests/plugins_list/fixtures/plugins_compat_site_dependencies_range/package.json
  packages/build/tests/plugins_list/tests.js
Labels: type: chore

#4555 fix: install then build workspaces
  .github/workflows/pre-release.yml
  .github/workflows/release-please.yml
  ava.base.js
Labels: type: chore, type: bug
