Repository netlify/build, pull requests merged in 2022-06, with the labels that each got.

#4320 chore: Fix tests
  package-lock.json
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/edge_functions/snapshots/tests.js.snap
  packages/build/tests/install/tests.js
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/build/tests/mutate/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.snap
Labels: type: chore

#4318 chore(release): add node-workspace plugin to release-please
  release-please-config.json
Labels: type: chore, automerge

#4253 chore(ci): Add informational Codecov status checks
  codecov.yml
Labels: type: chore, automerge

#4325 refactor: cleanup `buildbot_build_go_functions, `zisi_parse_isc` and `buildbot_nft_transpile_esm` feature flags
  package-lock.json
  packages/build/package.json
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins_core/functions/error.js
  packages/build/src/plugins_core/functions/feature_flags.js
  packages/build/tests/core/tests.js
  packages/build/tests/functions/snapshots/tests.js.md
  packages/build/tests/functions/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/functions-utils/package.json
  packages/functions-utils/tests/main.js
Labels: type: chore

#4329 feat: pull environment variables from envelope if a site has opted in
  packages/config/src/api/site_info.js
  packages/config/src/env/envelope.js
  packages/config/src/env/main.js
  packages/config/src/log/messages.js
  packages/config/src/main.js
  packages/config/tests/env/tests.js
Labels: type: feature, automerge

#4354 fix: return an empty object rather than throwing swallowed error in envelope fetch
  packages/config/src/env/envelope.js
Labels: type: bug, automerge
