Repository netlify/build, pull requests merged in 2022-11, with the labels that each got.

#4664 fix: pin framework-info package to 9.4.0
  package-lock.json
  packages/build-info/package.json
Labels: type: bug, automerge

#4663 chore: release main
  .release-please-manifest.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
Labels: autorelease: pending, automerge

#4666 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4672 fix: fail builds if the Next.js Runtime version is >= 4.0.0 && < 4.26.0
  packages/build/src/core/build.ts
  packages/build/src/core/feature_flags.js
  packages/build/src/error/type.js
  packages/build/src/log/messages/compatibility.ts
  packages/build/src/plugins/spawn.js
  packages/build/tests/plugins_list/fixtures/plugins_unsupported_version_package_json/netlify.toml
  packages/build/tests/plugins_list/fixtures/plugins_unsupported_version_package_json/node_modules/@netlify/plugin-nextjs/index.js
  packages/build/tests/plugins_list/fixtures/plugins_unsupported_version_package_json/node_modules/@netlify/plugin-nextjs/manifest.yml
  packages/build/tests/plugins_list/fixtures/plugins_unsupported_version_package_json/node_modules/@netlify/plugin-nextjs/package.json
  packages/build/tests/plugins_list/fixtures/plugins_unsupported_version_package_json/package.json
  packages/build/tests/plugins_list/snapshots/tests.js.md
  packages/build/tests/plugins_list/snapshots/tests.js.snap
  packages/build/tests/plugins_list/tests.js
Labels: Adds or modifies js files

#4667 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#4675 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4680 chore: release main
  .release-please-manifest.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4681 Revert "fix(deps): update dependency @netlify/zip-it-and-ship-it to v…
  package-lock.json
  packages/build/package.json
  packages/functions-utils/package.json
Labels: automerge

#4683 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#4661 fix: per build step system logging
  packages/build/src/core/main.ts
  packages/build/src/log/messages/core.ts
  packages/build/src/steps/return.js
  packages/build/src/steps/run_step.ts
  packages/build/tests/constants/snapshots/tests.js.md
  packages/build/tests/constants/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/deploy/snapshots/tests.js.md
  packages/build/tests/deploy/snapshots/tests.js.snap
  packages/build/tests/edge_functions/snapshots/tests.js.md
  packages/build/tests/edge_functions/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/functions/snapshots/tests.js.md
  packages/build/tests/functions/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/build/tests/mutate/snapshots/tests.js.md
  packages/build/tests/mutate/snapshots/tests.js.snap
  packages/build/tests/mutate_headers_redirects/snapshots/tests.js.md
  packages/build/tests/mutate_headers_redirects/snapshots/tests.js.snap
  packages/build/tests/mutate_save/snapshots/tests.js.md
  packages/build/tests/mutate_save/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins_events/snapshots/tests.js.md
  packages/build/tests/plugins_events/snapshots/tests.js.snap
  packages/build/tests/plugins_list/snapshots/tests.js.md
  packages/build/tests/plugins_list/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/steps/snapshots/tests.js.md
  packages/build/tests/steps/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/utils_build/snapshots/tests.js.md
  packages/build/tests/utils_build/snapshots/tests.js.snap
Labels: Adds or modifies js files

#4686 feat!: add `cache` config property to edge functions
  packages/config/src/edge_functions.ts
  packages/config/src/edge_functions_config.ts
  packages/config/src/validate/validations.js
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/validate/fixtures/edge_functions_mode_allowed/netlify.toml
  packages/config/tests/validate/fixtures/edge_functions_mode_disallowed/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: type: feature, Adds or modifies js files

#4688 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#4693 fix: update edge-bundler
  package-lock.json
  packages/build/package.json
  packages/testing/package.json
Labels: type: chore, automerge

#4694 Release please branches main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4697 fix: pin down edge bundler to release
  package-lock.json
  packages/build/package.json
Labels: type: bug

#4691 chore: update lock file after release-please
  .circleci/config.yml
Labels: automerge

#4698 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4699 chore(ci): make the update lockfile step for releases its own workflow
  .circleci/config.yml
Labels: automerge

#4701 feat: add support for edge function layers
  package-lock.json
  packages/build/package.json
  packages/build/src/plugins_core/edge_functions/index.js
  packages/build/src/plugins_core/edge_functions/lib/internal_manifest.js
  packages/build/src/plugins_core/edge_functions/validate_manifest/validate_edge_functions_manifest.js
  packages/build/tests/edge_functions/snapshots/tests.js.md
  packages/build/tests/edge_functions/snapshots/tests.js.snap
Labels: type: feature, automerge, Adds or modifies js files

#4702 chore: release main
  .circleci/config.yml
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/git-utils/CHANGELOG.md
  packages/git-utils/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/nock-udp/CHANGELOG.md
  packages/nock-udp/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
  packages/run-utils/CHANGELOG.md
  packages/run-utils/package.json
Labels: autorelease: pending

#4709 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#4712 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#4710 feat: move EF validation logic to edge-bundler
  package-lock.json
  packages/build/package.json
  packages/build/src/plugins_core/edge_functions/validate_manifest/validate_edge_functions_manifest.js
  packages/build/src/plugins_core/edge_functions/validate_manifest/validate_edge_functions_manifest.ts
  packages/build/tests/edge_functions/snapshots/tests.js.snap
  packages/build/tests/unit/validate_edge_manifest/snapshots/tests.js.md
  packages/build/tests/unit/validate_edge_manifest/snapshots/tests.js.snap
  packages/build/tests/unit/validate_edge_manifest/tests.js
  packages/build/tests/unit/validate_edge_manifest/unit_fixtures/empty_manifest/manifest.json
  packages/build/tests/unit/validate_edge_manifest/unit_fixtures/invalid_manifest/manifest.json
  packages/build/tests/unit/validate_edge_manifest/unit_fixtures/invalid_manifest_extra_property/manifest.json
  packages/build/tests/unit/validate_edge_manifest/unit_fixtures/invalid_manifest_missing_property/manifest.json
  packages/build/tests/unit/validate_edge_manifest/unit_fixtures/invalid_manifest_wrong_route_pattern/manifest.json
Labels: automerge, Adds or modifies js files

#4714 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4700 fix(deps): add 'fast-safe-stringify' to headers-parser
  package-lock.json
  packages/headers-parser/package.json
Labels: automerge

#4716 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
Labels: autorelease: pending

#4719 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4721 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4723 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4726 fix: node18 support for netlify/build
  packages/build/src/plugins/spawn.ts
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: Adds or modifies js files

#4727 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4728 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4732 chore: clean up tests
  packages/build/package.json
  packages/build/tests/edge_functions/tests.js
  packages/build/tests/monitor/tests.js
  packages/testing/src/normalize.ts
Labels: type: chore, automerge, Adds or modifies js files

#4731 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending, automerge
