Repository netlify/build, pull requests merged in 2022-02, with the labels that each got.

#4088 chore: use ESM-specific Renovate config
  renovate.json5
Labels: type: chore, automerge

#4133 fix: pin `ts-node` version
  package-lock.json
  packages/build/package.json
  renovate.json5
Labels: type: bug, automerge

#4172 fix: truncate long headers and redirects in build logs
  packages/build/tests/log/fixtures/truncate_headers/manifest.yml
  packages/build/tests/log/fixtures/truncate_headers/netlify.toml
  packages/build/tests/log/fixtures/truncate_headers/plugin.js
  packages/build/tests/log/fixtures/truncate_redirects/manifest.yml
  packages/build/tests/log/fixtures/truncate_redirects/netlify.toml
  packages/build/tests/log/fixtures/truncate_redirects/plugin.js
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/log/tests.js
  packages/config/src/simplify.js
Labels: type: bug

#4176 Revert "fix: truncate long headers and redirects in build logs (#4172)"
  package-lock.json
  packages/build/tests/log/fixtures/truncate_headers/manifest.yml
  packages/build/tests/log/fixtures/truncate_headers/netlify.toml
  packages/build/tests/log/fixtures/truncate_headers/plugin.js
  packages/build/tests/log/fixtures/truncate_redirects/manifest.yml
  packages/build/tests/log/fixtures/truncate_redirects/netlify.toml
  packages/build/tests/log/fixtures/truncate_redirects/plugin.js
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/log/tests.js
  packages/config/package.json
  packages/config/src/simplify.js
Labels: type: bug, automerge

#4178 fix(config-redirects): revert 216213fc2f6f5ff9b61c3bb3a71afac7d7099ebf
  packages/config/package.json
Labels: type: bug, automerge

#4182 chore: add regression tests for sites with many redirects or headers
  packages/build/tests/helpers/tcp_server.js
  packages/build/tests/log/fixtures/truncate_headers/manifest.yml
  packages/build/tests/log/fixtures/truncate_headers/netlify.toml
  packages/build/tests/log/fixtures/truncate_headers/plugin.js
  packages/build/tests/log/fixtures/truncate_redirects/manifest.yml
  packages/build/tests/log/fixtures/truncate_redirects/netlify.toml
  packages/build/tests/log/fixtures/truncate_redirects/plugin.js
  packages/build/tests/log/tests.js
  packages/build/tests/mutate_save/fixtures/many_headers/manifest.yml
  packages/build/tests/mutate_save/fixtures/many_headers/netlify.toml
  packages/build/tests/mutate_save/fixtures/many_headers/plugin.js
  packages/build/tests/mutate_save/fixtures/many_redirects/manifest.yml
  packages/build/tests/mutate_save/fixtures/many_redirects/netlify.toml
  packages/build/tests/mutate_save/fixtures/many_redirects/plugin.js
  packages/build/tests/mutate_save/tests.js
Labels: type: chore, automerge

#4183 fix: truncate headers/redirects in logs
  packages/build/tests/log/tests.js
  packages/config/src/log/cleanup.js
Labels: type: bug

#4184 fix: pass feature flags to `netlify-redirect-parser` and `netlify-headers-parser`
  packages/build/src/core/config.js
  packages/build/src/plugins_core/deploy/index.js
  packages/config/src/headers.js
  packages/config/src/main.js
  packages/config/src/mutations/update.js
  packages/config/src/redirects.js
Labels: type: chore, type: bug

#4185 fix: remove manifest feat flag check
  packages/build/src/core/feature_flags.js
  packages/build/src/plugins_core/functions/zisi.js
  packages/build/tests/core/tests.js
  packages/build/tests/functions/tests.js
Labels: type: bug, automerge

#4190 fix: remove feature flag `redirects_parser_normalize_status`
  packages/build/src/core/feature_flags.js
Labels: type: chore, type: bug, automerge
