Repository netlify/build, pull requests merged in 2023-06, with the labels that each got.

#5039 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5037 fix(config): ignores an empty config file path
  package-lock.json
  packages/build/tests/core/fixtures/toml/apps/nested/netlify.toml
  packages/build/tests/core/fixtures/toml/netlify.toml
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/config/src/main.js
  packages/config/src/path.ts
  packages/config/tests/cli/fixtures/toml/apps/nested/netlify.toml
  packages/config/tests/cli/fixtures/toml/netlify.toml
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/cli/tests.js
Labels: Adds or modifies js files

#5044 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#5045 feat: expose system logger to zip-it-and-ship-it
  packages/build/src/core/feature_flags.ts
  packages/build/src/plugins_core/functions/index.ts
  packages/build/src/plugins_core/functions/zisi.ts
  packages/build/tests/plugins/tests.js
Labels: automerge, Adds or modifies js files

#5048 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5058 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
Labels: autorelease: pending, automerge

#5069 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#5075 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5076 feat: pass through siteFeatureFlagPrefix to API
  packages/config/src/api/site_info.js
  packages/config/src/main.js
Labels: automerge, Adds or modifies js files

#5077 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#5079 fix: fix typo
  packages/config/src/api/site_info.js
Labels: automerge, Adds or modifies js files

#5080 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending, automerge

#5082 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5091 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5094 feat: Passthrough explicitSecretKeys field
  packages/build/src/core/build.ts
  packages/build/src/core/flags.js
  packages/build/src/log/messages/config.js
  packages/build/src/steps/core_step.ts
  packages/build/src/steps/run_step.ts
  packages/build/src/steps/run_steps.js
  packages/build/tests-metadata.json
Labels: automerge, Adds or modifies js files

#5095 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#5083 feat: setup open telemetry tracing
  package-lock.json
  packages/build/package.json
  packages/build/src/core/build.ts
  packages/build/src/core/flags.js
  packages/build/src/core/main.ts
  packages/build/src/core/normalize_flags.ts
  packages/build/src/core/types.ts
  packages/build/src/error/report.ts
  packages/build/src/steps/error.js
  packages/build/src/steps/run_step.ts
  packages/build/src/tracing/main.ts
  packages/build/tests/tracing/tests.js
Labels: automerge, Adds or modifies js files

#5096 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#5100 fix(tracing): handle buildbot tracing integration problems
  package-lock.json
  packages/build/package.json
  packages/build/src/core/build.ts
  packages/build/src/core/normalize_flags.ts
  packages/build/src/log/messages/config.js
  packages/build/src/tracing/main.ts
Labels: automerge, Adds or modifies js files

#5101 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending, automerge

#5104 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5108 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5109 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5097 feat: Support Secrets Scanning
  .gitignore
  package-lock.json
  packages/build/docs/flow.md
  packages/build/package.json
  packages/build/src/error/type.js
  packages/build/src/log/messages/core_steps.js
  packages/build/src/plugins_core/secrets_scanning/index.ts
  packages/build/src/plugins_core/secrets_scanning/utils.ts
  packages/build/src/steps/get.js
  packages/build/tests/secrets_scanning/fixtures/src_default/manifest.yml
  packages/build/tests/secrets_scanning/fixtures/src_default/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_default/plugin.js
  packages/build/tests/secrets_scanning/fixtures/src_scanning_disabled/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_no_matches/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_no_matches/src/some-file.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_no_matches/src/static-files/static-a.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_set_empty/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_set_empty/src/file.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_set_non_empty/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_set_non_empty/src/some-file.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_set_non_empty/src/static-files/static-a.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_set_non_empty/src/static-files/static-b.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_set_non_empty/src/static-files/static-c.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_set_non_empty/src/static-files/static-d.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_set_non_empty/src/static-files/static-e.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_all_keys/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_all_paths/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_all_paths/src/some-file.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_all_paths/src/static-files/static-a.txt
  packages/build/tests/secrets_scanning/snapshots/tests.js.md
  packages/build/tests/secrets_scanning/snapshots/tests.js.snap
  packages/build/tests/secrets_scanning/tests.js
Labels: automerge, Adds or modifies js files

#5110 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge
