Repository netlify/build, pull requests merged in 2023-10, with the labels that each got.

#5298 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5313 fix: stop using snapshot for checking invalid package json
  .github/workflows/workflow.yml
  packages/build/tests-metadata.json
  packages/build/tests/deploy/snapshots/tests.js.md
  packages/build/tests/deploy/snapshots/tests.js.snap
  packages/build/tests/deploy/tests.js
  packages/build/tests/functions/snapshots/tests.js.md
  packages/build/tests/functions/snapshots/tests.js.snap
  packages/build/tests/functions/tests.js
  packages/build/tests/mutate/fixtures/functions_no_log_debug/plugin.js
  packages/build/tests/mutate/snapshots/tests.js.md
  packages/build/tests/mutate/snapshots/tests.js.snap
  packages/build/tests/mutate/tests.js
  packages/build/tests/mutate_save/snapshots/tests.js.md
  packages/build/tests/mutate_save/snapshots/tests.js.snap
  packages/build/tests/mutate_save/tests.js
  packages/build/tests/secrets_scanning/snapshots/tests.js.md
  packages/build/tests/secrets_scanning/snapshots/tests.js.snap
  packages/build/tests/secrets_scanning/tests.js
Labels: Adds or modifies js files

#5312 CT-41: add netlifyConfig to dynamic plugin metadata
  packages/build/src/core/build.ts
  packages/build/src/plugins/child/load.ts
  packages/build/src/plugins/child/logic.js
  packages/build/src/plugins/load.js
  packages/build/tests/plugins/fixtures/dynamic_plugin/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
Labels: Adds or modifies js files

#5314 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5306 feat: detect bun as package manager
  packages/build-info/src/package-managers/detect-package-manager.test.ts
  packages/build-info/src/package-managers/detect-package-manager.ts
Labels: automerge

#5315 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#5318 fix: --version should print version
  packages/build/src/core/bin.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
Labels: Adds or modifies js files

#5319 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5321 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending, automerge

#5327 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5329 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5336 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5338 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5340 fix(tracing): add `framework` data
  packages/build/src/core/main.ts
  packages/build/src/tracing/main.ts
Labels: automerge

#5341 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5350 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5352 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5344 fix: error on scheduled/event-triggered functions with custom route
  packages/build/src/plugins_core/functions/index.ts
  packages/build/tests/functions/fixtures/custom_path_event_triggered/netlify/functions/deploy-succeeded.mjs
  packages/build/tests/functions/fixtures/custom_path_scheduled/netlify/functions/daily.mjs
  packages/build/tests/functions/tests.js
Labels: Adds or modifies js files

#5343 feat: Add support for loading a tracing baggage dump in WC3 Baggage format
  package-lock.json
  packages/build/package.json
  packages/build/src/core/flags.js
  packages/build/src/core/normalize_flags.ts
  packages/build/src/core/types.ts
  packages/build/src/tracing/main.ts
  packages/build/tests/tracing/tests.js
Labels: Adds or modifies js files

#5353 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5354 fix(secret-scanning): secret detection should produce an user error
  packages/build/src/error/type.js
  packages/build/tests/secrets_scanning/tests.js
Labels: automerge, Adds or modifies js files

#5355 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5361 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending
