Repository netlify/build, pull requests merged in 2023-12, with the labels that each got.

#5423 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5421 feat: cleanup internal functions onPreDev
  packages/build/src/plugins_core/pre_dev_cleanup/index.ts
  packages/build/src/steps/get.js
  packages/build/tests/functions/fixtures/internal_functions/.netlify/edge-functions/server.mjs
  packages/build/tests/functions/fixtures/internal_functions/.netlify/functions-internal/server.mjs
  packages/build/tests/functions/tests.js
Labels: Adds or modifies js files

#5431 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5435 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5437 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5436 feat(otel-utils): create opentelemetry utils package
  package-lock.json
  packages/opentelemetry-utils/README.md
  packages/opentelemetry-utils/package.json
  packages/opentelemetry-utils/src/index.ts
  packages/opentelemetry-utils/tests/main.test.ts
  packages/opentelemetry-utils/tsconfig.json
  packages/opentelemetry-utils/vitest.config.ts
  release-please-config.json
Labels: automerge

#5438 chore: release main
  .release-please-manifest.json
  packages/opentelemetry-utils/CHANGELOG.md
Labels: autorelease: pending

#5443 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5451 fix: warn about upcoming system version update
  packages/build/src/plugins/node_version.ts
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: Adds or modifies js files

#5450 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5452 Revert "fix: warn about upcoming system version update"
  packages/build/src/plugins/node_version.ts
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: Adds or modifies js files

#5453 fix: test version selection for ui plugin
  packages/build/src/plugins/expected_version.js
  packages/build/tests/plugins/fixtures/ui_auto_install/.netlify/plugins/node_modules/netlify-plugin-test/index.js
  packages/build/tests/plugins/fixtures/ui_auto_install/.netlify/plugins/node_modules/netlify-plugin-test/manifest.yml
  packages/build/tests/plugins/fixtures/ui_auto_install/.netlify/plugins/node_modules/netlify-plugin-test/package.json
  packages/build/tests/plugins/tests.js
Labels: Adds or modifies js files
