Repository netlify/build, pull requests merged in 2023-01, with the labels that each got.

#4792 feat: add `--outputConfigPath` flag
  packages/build/src/core/build.ts
  packages/build/src/core/config.js
  packages/build/src/core/flags.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/src/plugins_core/save_artifacts/index.js
  packages/build/src/steps/core_step.ts
  packages/build/src/steps/get.js
  packages/build/src/steps/run_step.ts
  packages/build/src/steps/run_steps.js
  packages/build/tests/mutate_save/snapshots/tests.js.md
  packages/build/tests/mutate_save/snapshots/tests.js.snap
  packages/build/tests/mutate_save/tests.js
  packages/config/src/mutations/update.js
Labels: type: feature, Adds or modifies js files

#4794 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#4797 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#4805 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
Labels: autorelease: pending, automerge

#4806 fix: replace statsd-client with hot-shots
  package-lock.json
  packages/build/package.json
  packages/build/src/core/main.ts
  packages/build/src/error/report.ts
  packages/build/src/report/statsd.ts
  packages/build/src/time/report.ts
  packages/build/tests/error_reporting/tests.js
  packages/build/tests/time/tests.js
Labels: Adds or modifies js files

#4815 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#4817 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#4821 feat: Pass internalSrcFolder and name to zisi
  packages/build/src/plugins_core/functions/zisi.js
  packages/build/tests/core/fixtures/functions_display_name/.netlify/functions-internal/function_one.js
  packages/build/tests/core/fixtures/functions_display_name/.netlify/functions-internal/function_one.json
  packages/build/tests/core/fixtures/functions_display_name/.netlify/functions-internal/function_two.js
  packages/build/tests/core/fixtures/functions_internal_src_folder/.netlify/functions-internal/function_two.js
  packages/build/tests/core/fixtures/functions_internal_src_folder/.netlify/functions-internal/function_two.json
  packages/build/tests/core/fixtures/functions_internal_src_folder/netlify/functions/function_one.js
  packages/build/tests/core/fixtures/functions_internal_src_folder/netlify/functions/function_one.json
  packages/build/tests/core/tests.js
Labels: Adds or modifies js files

#4812 feat: install framework runtime
  packages/build/src/core/build.ts
  packages/build/src/core/main.ts
  packages/framework-info/src/main.js
Labels: Adds or modifies js files

#4822 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
Labels: autorelease: pending

#4828 fix: Correctly handle missing node_modules in framework-info
  packages/framework-info/src/main.js
  packages/framework-info/test/fixtures/no-version/package.json
  packages/framework-info/test/main.js
  packages/framework-info/test/snapshots/main.js.md
  packages/framework-info/test/snapshots/main.js.snap
Labels: Adds or modifies js files

#4826 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/nock-udp/CHANGELOG.md
  packages/nock-udp/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
Labels: autorelease: pending

#4830 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#4818 feat: add detection for nix build system
  packages/build-info/src/detect-build-system.ts
  packages/build-info/tests/detect-build-systems.test.ts
Labels: Adds or modifies js files
