Repository netlify/build, pull requests merged in 2023-07, with the labels that each got.

#5111 chore: place outside ff
  packages/build-info/src/node/get-build-info.ts
  packages/build-info/tests/bin.test.ts
Labels: automerge

#5117 chore: Update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge

#5119 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending, automerge

#5122 fix: fixes an issue where the wrong dist was used for frameworks with…
  packages/build-info/src/build-systems/package-managers.test.ts
  packages/build-info/src/frameworks/gatsby.test.ts
  packages/build-info/src/node/__snapshots__/get-build-info.test.ts.snap
  packages/build-info/src/settings/get-build-settings.test.ts
  packages/build-info/src/settings/get-build-settings.ts
Labels: automerge

#5124 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5128 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5118 fix(tracing): actually set the tracing options in the root context
  package-lock.json
  packages/build/docs/tracing.md
  packages/build/package.json
  packages/build/src/core/build.ts
  packages/build/src/core/flags.js
  packages/build/src/core/main.ts
  packages/build/src/core/normalize_flags.ts
  packages/build/src/core/types.ts
  packages/build/src/steps/run_step.ts
  packages/build/src/tracing/main.ts
Labels: automerge, Adds or modifies js files

#5129 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending, automerge

#5126 chore(docs): update CONTRIBUTING.md with updated test and Buildbot release notes
  CONTRIBUTING.md
Labels: automerge

#5127 chore(build): remove pretest script
  packages/build/package.json
Labels: automerge

#5135 fix: support edge_functions `excludedPath`
  packages/config/src/edge_functions.ts
  packages/config/tests/validate/fixtures/edge_functions_excluded_path_invalid/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: Adds or modifies js files

#5134 fix: fixes an issue where package paths where not correctly resolved
  packages/build-info/src/build-systems/build-system.test.ts
  packages/build-info/src/build-systems/nrwl.ts
  packages/build-info/src/file-system.ts
  packages/build-info/src/index.ts
  packages/build-info/src/logger.test.ts
  packages/build-info/src/logger.ts
  packages/build-info/src/node/get-build-info.ts
  packages/build-info/src/project.ts
  packages/build-info/src/settings/get-build-settings.ts
Labels: automerge

#5136 fix: add support for `pattern` and `excludedPattern`
  packages/config/src/edge_functions.ts
  packages/config/tests/validate/fixtures/edge_functions_pattern_path_exclusive/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: Adds or modifies js files

#5137 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#5139 chore: add merge queue support
  .github/workflows/workflow.yml
Labels: automerge

#5140 fix: export PollingStrategies and getSettings as part of the public api
  packages/build-info/src/frameworks/index.ts
  packages/build-info/src/settings/get-build-settings.ts
Labels: automerge

#5132 Feat: Improvements to secrets scanning perf and observability
  packages/build/src/log/messages/core_steps.js
  packages/build/src/plugins_core/secrets_scanning/index.ts
  packages/build/src/plugins_core/secrets_scanning/utils.ts
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_set_non_empty/.gitignore
  packages/build/tests/secrets_scanning/snapshots/tests.js.md
  packages/build/tests/secrets_scanning/snapshots/tests.js.snap
Labels: automerge, Adds or modifies js files

#5141 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5143 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5146 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5147 fix: downgrade dot-prop to support Node.js 14
  package-lock.json
  packages/build-info/package.json
Labels: automerge

#5145 fix: fix return type of get framework to return the class
  packages/build-info/src/get-framework.ts
Labels: automerge

#5158 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5116 feat: install integrations alongside plugins
  packages/build/src/core/build.ts
  packages/build/src/core/config.js
  packages/build/src/install/missing.js
  packages/build/src/log/messages/compatibility.ts
  packages/build/src/log/messages/install.js
  packages/build/src/plugins/options.ts
  packages/build/src/plugins/resolve.js
  packages/build/src/plugins/spawn.ts
  packages/config/package.json
  packages/config/src/api/site_info.js
  packages/config/src/main.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
Labels: automerge, Adds or modifies js files

#5163 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5164 fix: references to token in fetch integrations and include some tests
  packages/config/src/api/site_info.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/api/tests.js
Labels: automerge, Adds or modifies js files

#5165 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#5142 fix: do not allow excluded path and pattern together in toml
  packages/config/src/edge_functions.ts
  packages/config/tests/validate/fixtures/edge_functions_excluded_pattern_path_exclusive/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: Adds or modifies js files

#5170 fix: omit the git path even if no other omit paths provided
  packages/build/src/plugins_core/secrets_scanning/utils.ts
Labels: automerge

#5167 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending, automerge

#5168 fix: pull integrations in buildy botty mode
  packages/build/src/core/build.ts
  packages/build/src/core/config.js
  packages/build/src/plugins/resolve.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/config/src/api/site_info.js
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/base/snapshots/tests.js.md
  packages/config/tests/base/snapshots/tests.js.snap
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tests/context/snapshots/tests.js.md
  packages/config/tests/context/snapshots/tests.js.snap
  packages/config/tests/cwd/snapshots/tests.js.md
  packages/config/tests/cwd/snapshots/tests.js.snap
  packages/config/tests/load/snapshots/tests.js.md
  packages/config/tests/load/snapshots/tests.js.snap
  packages/config/tests/log/snapshots/tests.js.md
  packages/config/tests/log/snapshots/tests.js.snap
  packages/config/tests/mutate/snapshots/tests.js.md
  packages/config/tests/mutate/snapshots/tests.js.snap
  packages/config/tests/normalize/snapshots/tests.js.md
  packages/config/tests/normalize/snapshots/tests.js.snap
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: automerge, Adds or modifies js files

#5182 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#5181 fix: detection of workspace file and correct dev port
  packages/build-info/src/build-systems/build-system.ts
  packages/build-info/src/build-systems/nx.test.ts
  packages/build-info/src/build-systems/nx.ts
  packages/build-info/src/frameworks/next.test.ts
  packages/build-info/src/settings/get-build-settings.test.ts
  packages/build-info/src/settings/get-build-settings.ts
  packages/build-info/tests/fixtures/nx-integrated-old/apps/astro-e2e/cypress.config.ts
  packages/build-info/tests/fixtures/nx-integrated-old/apps/astro/astro.config.mjs
  packages/build-info/tests/fixtures/nx-integrated-old/apps/website/next.config.js
  packages/build-info/tests/fixtures/nx-integrated-old/libs/components/index.ts
  packages/build-info/tests/fixtures/nx-integrated-old/nx.json
  packages/build-info/tests/fixtures/nx-integrated-old/package.json
  packages/build-info/tests/fixtures/nx-integrated-old/workspace.json
Labels: Adds or modifies js files

#5184 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5183 feat: update pnpm build command for workspaces to build dependents
  packages/build-info/src/build-systems/package-managers.test.ts
  packages/build-info/src/build-systems/package-managers.ts
  packages/build-info/src/node/__snapshots__/get-build-info.test.ts.snap
  packages/build-info/src/settings/get-build-settings.test.ts
Labels: automerge

#5186 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5189 fix: fix nx-integrated detection via forced framework
  packages/build-info/src/build-systems/nx.test.ts
  packages/build-info/src/build-systems/nx.ts
  packages/build-info/src/frameworks/framework.ts
  packages/build-info/src/get-framework.ts
  packages/build-info/src/project.test.ts
  packages/build-info/src/project.ts
  packages/build-info/src/settings/get-build-settings.test.ts
  packages/build-info/src/workspaces/detect-workspace.ts
  packages/build-info/tests/fixtures/nx-integrated-old/workspace.json
Labels: automerge

#5192 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5190 fix: add correct 11ty logos for light and dark
  packages/build-info/assets/logos/eleventy/dark.svg
  packages/build-info/assets/logos/eleventy/light.svg
  packages/build-info/src/frameworks/eleventy.ts
Labels: automerge

#5188 fix: mark go version errors as user errors
  .github/workflows/workflow.yml
  packages/build/src/plugins_core/functions/error.js
  packages/build/tests/monitor/fixtures/go_missing_dependency/netlify/functions/missing_dependency/go.mod
  packages/build/tests/monitor/fixtures/go_missing_dependency/netlify/functions/missing_dependency/go.sum
  packages/build/tests/monitor/fixtures/go_missing_dependency/netlify/functions/missing_dependency/main.go
  packages/build/tests/monitor/fixtures/go_version_error/netlify/functions/wrong_version/go.mod
  packages/build/tests/monitor/fixtures/go_version_error/netlify/functions/wrong_version/go.sum
  packages/build/tests/monitor/fixtures/go_version_error/netlify/functions/wrong_version/main.go
  packages/build/tests/monitor/tests.js
Labels: automerge, Adds or modifies js files

#5194 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5150 feat(tracing): add sample rate tracing parameter
  packages/build/src/core/flags.js
  packages/build/src/core/normalize_flags.ts
  packages/build/src/core/types.ts
  packages/build/src/tracing/main.ts
  packages/build/tests/tracing/tests.js
Labels: automerge, Adds or modifies js files

#5195 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#5193 fix: correctly reference env from testOpts to install integrations
  packages/build/tests/constants/snapshots/tests.js.md
  packages/build/tests/constants/snapshots/tests.js.snap
  packages/build/tests/constants/tests.js
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/build/tests/monitor/tests.js
  packages/build/tests/utils_build/snapshots/tests.js.md
  packages/build/tests/utils_build/snapshots/tests.js.snap
  packages/build/tests/utils_build/tests.js
  packages/config/src/api/site_info.js
  packages/config/tests/api/tests.js
Labels: automerge, Adds or modifies js files

#5196 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending, automerge

#5197 feat: make getBuildSettings accept an optional package parameter
  packages/build-info/src/project.ts
  packages/build-info/src/settings/get-build-settings.test.ts
  packages/build-info/src/settings/get-build-settings.ts
Labels: automerge

#5198 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5200 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#4990 fix: change nuxt detection dist for v3
  packages/build-info/src/frameworks/nuxt.test.ts
  packages/build-info/src/frameworks/nuxt.ts
  packages/build-info/src/settings/get-build-settings.test.ts
Labels: automerge

#5205 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5208 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5210 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending
