Repository netlify/build, pull requests merged in 2023-03, with the labels that each got.

#4897 feat: add feature flagging possibility to build-info
  packages/build-info/src/node/bin.ts
  packages/build-info/src/node/get-build-info.ts
  packages/build-info/tests/__snapshots__/bin.test.ts.snap
  packages/build-info/tests/get-build-info.test.ts
  packages/build-info/tests/pnpm.test.ts
  packages/build-info/tests/yarn.test.ts
Labels: automerge

#4898 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
Labels: autorelease: pending, automerge

#4884 feat: remove ff project_deploy_configuration_api_use_per_function_configuration_files + update zisi to 8.8.0
  package-lock.json
  packages/build/package.json
  packages/build/tests/core/tests.js
  packages/functions-utils/package.json
Labels: type: chore, Adds or modifies js files

#4900 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#4903 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4904 chore: cleanup ff buildbot_es_modules_esbuild
  package-lock.json
  packages/build/package.json
  packages/build/src/core/feature_flags.ts
  packages/build/src/plugins_core/functions/feature_flags.js
  packages/build/src/plugins_core/functions/feature_flags.ts
  packages/build/tests/core/fixtures/functions_es_modules/functions/function_with_es_module.js
  packages/build/tests/core/fixtures/functions_es_modules/helper.js
  packages/build/tests/core/fixtures/functions_es_modules/netlify.toml
  packages/build/tests/core/tests.js
Labels: automerge, Adds or modifies js files

#4878 docs: fix link to contribution doc
  .github/pull_request_template.md
Labels: automerge

#4909 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4912 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#4855 refactor: cleanup rolled out feature flag
  packages/build/src/plugins/spawn.ts
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/build/tests/plugins_events/snapshots/tests.js.md
  packages/build/tests/plugins_events/snapshots/tests.js.snap
Labels: automerge, Adds or modifies js files

#4917 fix: fix deployment of framework-info icons
  packages/framework-info/netlify.toml
  packages/framework-info/vite.config.js
Labels: automerge, Adds or modifies js files

#4918 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
Labels: autorelease: pending

#4919 feat: use dev cycle feature flagging
  package-lock.json
  packages/build-info/package.json
  packages/build-info/src/node/bin.ts
  packages/build-info/src/node/feature-flags.ts
  packages/build-info/tests/__snapshots__/bin.test.ts.snap
Labels: automerge

#4920 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending, automerge

#4921 chore: update logo in readme
  build.png
  static/logo.png
Labels: automerge

#4925 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#4932 fix: expose apply mutation to API surface
  packages/config/package.json
  packages/config/src/index.ts
  packages/config/src/main.js
  packages/config/src/mutations/config_prop_name.js
  packages/config/src/mutations/config_prop_name.ts
  packages/config/tests/mutate/tests.js
Labels: Adds or modifies js files

#4933 Revert "feat: use dev cycle feature flagging"
  package-lock.json
  packages/build-info/package.json
  packages/build-info/src/node/bin.ts
  packages/build-info/src/node/feature-flags.ts
  packages/build-info/tests/__snapshots__/bin.test.ts.snap
Labels: automerge

#4922 fix: improve grammar and typos in comments
  packages/build-info/src/browser/file-system.ts
  packages/build-info/src/build-systems/build-system.ts
  packages/build-info/src/file-system.ts
  packages/build-info/src/package-managers/detect-package-manager.ts
  packages/build-info/src/project.ts
  packages/build/src/core/config.js
  packages/build/src/core/flags.js
  packages/build/src/core/lingering.js
  packages/build/src/core/missing_side_file.js
  packages/build/src/core/normalize_flags.ts
  packages/build/src/env/metadata.js
  packages/build/src/error/build.js
  packages/build/src/error/handle.ts
  packages/cache-utils/src/hash.ts
  packages/config/src/bin/flags.js
  packages/config/src/build_dir.js
  packages/config/src/context.js
  packages/config/src/default.js
  packages/config/src/files.js
  packages/config/src/log/logger.js
  packages/config/src/merge.js
  packages/config/src/mutations/update.js
  packages/config/src/normalize.js
  packages/config/src/options/base.js
  packages/config/src/utils/toml.js
  packages/functions-utils/src/main.ts
  packages/git-utils/src/exec.ts
  packages/headers-parser/src/merge.ts
  packages/headers-parser/src/netlify_config_parser.ts
  packages/headers-parser/src/normalize.ts
  packages/headers-parser/src/results.ts
  packages/redirect-parser/src/all.ts
  packages/redirect-parser/src/netlify_config_parser.js
  packages/redirect-parser/src/results.js
Labels: automerge

#4939 fix: pass internalSrcFolder to zisi
  packages/build/src/plugins_core/functions/zisi.js
  packages/build/tests/core/tests.js
Labels: type: bug, automerge, Adds or modifies js files

#4935 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/git-utils/CHANGELOG.md
  packages/git-utils/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
Labels: autorelease: pending, automerge

#4941 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4943 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#4947 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4948 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4953 fix: correctly tag edge function validation errors as user error
  packages/build/src/plugins_core/edge_functions/validate_manifest/validate_edge_functions_manifest.ts
  packages/build/tests/edge_functions/fixtures/functions_validation_failed/netlify/edge-functions/functions-1.ts
  packages/build/tests/edge_functions/snapshots/tests.js.md
  packages/build/tests/edge_functions/snapshots/tests.js.snap
  packages/build/tests/edge_functions/tests.js
Labels: Adds or modifies js files

#4952 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4958 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#4961 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#4963 feat: log number of user and generated functions for lambda to datadog
  packages/build/src/plugins_core/functions/index.ts
  packages/build/src/steps/run_steps.js
  packages/build/tests/time/snapshots/tests.js.md
  packages/build/tests/time/snapshots/tests.js.snap
Labels: type: feature, automerge, Adds or modifies js files

#4965 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4962 fix: entrypoint for node with correct types
  packages/build-info/bin.js
  packages/build-info/package.json
  packages/build-info/tsconfig.build.json
Labels: Adds or modifies js files
