Repository netlify/build, pull requests merged in 2023-08, with the labels that each got.

#5211 feat: remove tokens related to integrations, improve typings
  packages/config/src/api/site_info.ts
  packages/config/src/main.js
  packages/config/src/types/api.ts
  packages/config/src/types/options.ts
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/api/tests.js
Labels: automerge, Adds or modifies js files

#5214 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending, automerge

#5217 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5223 feat: add packagePath property for config
  packages/config/src/base.js
  packages/config/src/base.ts
  packages/config/src/bin/flags.ts
  packages/config/src/build_dir.js
  packages/config/src/build_dir.ts
  packages/config/src/context.ts
  packages/config/src/files.js
  packages/config/src/files.ts
  packages/config/src/main.ts
  packages/config/src/merge_normalize.ts
  packages/config/src/normalize.ts
  packages/config/src/path.ts
  packages/config/src/redirects.ts
  packages/config/src/utils/remove_falsy.js
  packages/config/src/utils/remove_falsy.ts
  packages/config/tests/base/fixtures/monorepo/apps/app-1/_redirects
  packages/config/tests/base/fixtures/monorepo/apps/app-2/_headers
  packages/config/tests/base/fixtures/monorepo/apps/app-3/netlify.toml
  packages/config/tests/base/fixtures/monorepo/apps/app-3/netlify/functions/hello-world/hello-world.js
  packages/config/tests/base/fixtures/monorepo/apps/app-4/netlify.toml
  packages/config/tests/base/fixtures/monorepo/apps/app-4/netlify/edge-functions/hello/hello.ts
  packages/config/tests/base/fixtures/monorepo/apps/app-5/custom-dir/hello.ts
  packages/config/tests/base/fixtures/monorepo/apps/app-5/netlify.toml
  packages/config/tests/base/fixtures/monorepo/apps/app-6/custom-dir/hello.ts
  packages/config/tests/base/fixtures/monorepo/apps/app-6/netlify.toml
  packages/config/tests/base/fixtures/monorepo/package.json
  packages/config/tests/base/tests.js
  packages/config/tests/cli/snapshots/tests.js.md
  packages/config/tests/cli/snapshots/tests.js.snap
  packages/config/tsconfig.json
  packages/config/tsfixme.d.ts
  packages/redirect-parser/src/all.ts
Labels: automerge, Adds or modifies js files

#5222 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
Labels: autorelease: pending

#5224 test: update monorepo tests
  packages/config/src/path.ts
  packages/config/tests/base/fixtures/monorepo-with-root-files/apps/app-1/dist/_redirects
  packages/config/tests/base/fixtures/monorepo-with-root-files/apps/app-1/netlify.toml
  packages/config/tests/base/fixtures/monorepo-with-root-files/apps/app-2/_redirects
  packages/config/tests/base/fixtures/monorepo-with-root-files/apps/app-2/package.json
  packages/config/tests/base/fixtures/monorepo-with-root-files/netlify.toml
  packages/config/tests/base/fixtures/monorepo/apps/app-7/build-plugin/index.js
  packages/config/tests/base/fixtures/monorepo/apps/app-7/build-plugin/mainfest.yaml
  packages/config/tests/base/fixtures/monorepo/apps/app-7/netlify.toml
  packages/config/tests/base/tests.js
Labels: Adds or modifies js files

#5225 feat: add package path to build as well
  packages/build/src/core/build.ts
  packages/build/src/core/config.js
  packages/build/src/core/constants.js
  packages/build/src/core/flags.js
  packages/build/src/plugins/options.ts
  packages/build/src/plugins/resolve.js
  packages/build/src/plugins_core/deploy/index.js
  packages/build/src/plugins_core/edge_functions/index.ts
  packages/build/src/plugins_core/functions/index.ts
  packages/build/src/plugins_core/save_artifacts/index.js
  packages/build/src/steps/core_step.ts
  packages/build/src/steps/plugin.js
  packages/build/src/steps/run_core_steps.ts
  packages/build/src/steps/run_step.ts
  packages/build/src/steps/run_steps.js
  packages/build/src/time/main.ts
  packages/build/src/tracing/main.ts
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
Labels: automerge, Adds or modifies js files

#5228 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5221 feat: allow injecting bootstrapURL from CLI
  packages/build/src/core/build.ts
  packages/build/src/plugins_core/edge_functions/index.ts
  packages/build/src/steps/core_step.ts
  packages/build/src/steps/run_step.ts
  packages/build/src/steps/run_steps.js
  packages/build/tests/edge_functions/tests.js
Labels: Adds or modifies js files

#5229 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5231 fix: forward edgeFunctionsBootstrapURL via run_core_steps
  packages/build/src/steps/run_core_steps.ts
Labels: automerge

#5234 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5237 fix: update the constants with the correct internal functions path
  packages/build/src/core/constants.js
  packages/build/types/netlify_plugin_constants.d.ts
Labels: Adds or modifies js files

#5241 fix: hide edgeFunctionsBootstrapURL
  packages/build/src/log/messages/config.js
Labels: Adds or modifies js files

#5244 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5254 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5259 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5261 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5263 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5264 fix: prevent addExact running when no integrations supplied
  packages/build/src/install/main.js
  packages/build/src/install/missing.js
  packages/build/src/plugins/resolve.js
Labels: automerge, Adds or modifies js files

#5266 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#5267 feat: udpate astro ports for 3.x.x
  packages/build-info/src/frameworks/astro.test.ts
  packages/build-info/src/frameworks/astro.ts
Labels: automerge

#5270 fix: add ef-method field
  packages/config/src/edge_functions.ts
  packages/config/tests/validate/fixtures/edge_functions_method_disallowed/netlify.toml
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
  packages/config/tests/validate/tests.js
Labels: Adds or modifies js files
