Repository netlify/build, pull requests merged in 2023-02, with the labels that each got.

#4839 refactor: remove path-exists dependency and replace with node native fs.existsSync
  package-lock.json
  packages/config/package.json
  packages/config/src/error.ts
  packages/config/src/files.js
  packages/config/src/main.js
  packages/config/src/mutations/update.js
  packages/config/src/options/base.js
  packages/config/src/parse.ts
  packages/config/src/path.ts
  packages/config/tests/mutate/tests.js
Labels: Adds or modifies js files

#4836 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#4843 fix: fixes an issue where the cache could not save .dot directories
  packages/build/src/core/constants.js
  packages/build/tests/plugins/fixtures/cache_utils/.gitignore
  packages/build/tests/plugins/fixtures/cache_utils/build.mjs
  packages/build/tests/plugins/fixtures/cache_utils/netlify-plugin-cache/index.js
  packages/build/tests/plugins/fixtures/cache_utils/netlify-plugin-cache/manifest.yaml
  packages/build/tests/plugins/fixtures/cache_utils/netlify.toml
  packages/build/tests/plugins/fixtures/cache_utils/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/cache-utils/src/fs.ts
  packages/cache-utils/tests/digests.test.ts
  packages/cache-utils/tests/dir.test.ts
  packages/testing/src/dir.ts
Labels: automerge, Adds or modifies js files

#4846 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
Labels: autorelease: pending, automerge

#4832 added hugo.toml as config file for Hugo
  packages/framework-info/src/frameworks/hugo.json
Labels: automerge

#4852 feat: export getFrameworkById
  packages/framework-info/README.md
  packages/framework-info/src/core.ts
Labels: automerge

#4856 fix: remove update-notifier as unhelpful
  package-lock.json
  packages/build/package.json
  packages/build/src/core/normalize_flags.ts
  packages/build/src/core/types.ts
  packages/build/src/error/handle.ts
  packages/build/src/log/messages/core.ts
  packages/build/src/log/old_version.js
  packages/build/src/utils/json.ts
  packages/build/tests/log/tests.js
Labels: Adds or modifies js files

#4847 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/nock-udp/CHANGELOG.md
  packages/nock-udp/package.json
Labels: autorelease: pending, automerge

#4858 fix: respect manual order of frameworks
  packages/framework-info/package.json
  packages/framework-info/scripts/frameworks.js
  packages/framework-info/scripts/transform_json.js
  packages/framework-info/src/core.ts
  packages/framework-info/src/main.ts
  packages/framework-info/src/types.ts
  packages/framework-info/tests/__snapshots__/main.test.ts.snap
  packages/framework-info/tests/frameworks.test.ts
Labels: Adds or modifies js files

#4859 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
Labels: autorelease: pending

#4864 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#4866 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending, automerge

#4867 fix: Updated logos to correct file name
  packages/framework-info/assets/logos/nextjs/dark.svg
  packages/framework-info/assets/logos/nextjs/light.svg
  packages/framework-info/assets/logos/nuxt/dark.svg
  packages/framework-info/assets/logos/nuxt/default.svg
  packages/framework-info/assets/logos/nuxt/light.svg
Labels: automerge

#4857 fix: add test for generator field and remove internalSrcFolder usage
  package-lock.json
  packages/build/package.json
  packages/build/src/plugins_core/functions/zisi.js
  packages/build/tests/core/fixtures/functions_config_json/.netlify/functions-internal/function_two.json
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/core/tests.js
  packages/functions-utils/package.json
Labels: type: feature, Adds or modifies js files

#4873 fix(framework-info): add missing types in package.json
  packages/framework-info/package.json
Labels: automerge

#4891 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
Labels: autorelease: pending
