Repository netlify/build, pull requests merged in 2023-11, with the labels that each got.

#5362 feat: allow build event handlers to be passed programatically to the build execution
  packages/build/src/core/build.ts
  packages/build/src/core/main.ts
  packages/build/src/core/types.ts
  packages/build/src/log/messages/config.js
  packages/build/src/steps/get.js
  packages/build/tests/core/tests.js
Labels: automerge, Adds or modifies js files

#5364 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#5365 feat: leverage errors types for tracing
  packages/build/src/steps/error.js
  packages/build/src/tracing/main.ts
  packages/build/tests/tracing/tests.js
Labels: Adds or modifies js files

#5370 chore: release main
  .release-please-manifest.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5375 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5377 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5374 chore(build): add types to errors in build
  packages/build/src/error/info.ts
  packages/build/src/error/parse/location.ts
  packages/build/src/error/parse/parse.ts
  packages/build/src/error/parse/plugin.ts
  packages/build/src/error/parse/serialize_log.ts
  packages/build/src/error/type.js
  packages/build/src/error/types.ts
Labels: automerge

#5378 fix: link to secrets scanning docs
  packages/build/src/log/messages/core_steps.js
  packages/build/tests/secrets_scanning/snapshots/tests.js.md
  packages/build/tests/secrets_scanning/snapshots/tests.js.snap
Labels: Adds or modifies js files

#5381 fix(tracing): namespace attributes in build error events and add further data
  packages/build/src/error/types.ts
  packages/build/src/tracing/main.ts
  packages/build/tests/error/tests.js
  packages/build/tests/tracing/tests.js
Labels: automerge, Adds or modifies js files

#5379 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5385 fix(build-error): add core step id to the build error type and traces
  packages/build/src/error/types.ts
Labels: automerge

#5384 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#5390 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5386 fix: skip scanning .cache for secrets
  packages/build/src/plugins_core/secrets_scanning/utils.ts
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_cache_path/.cache/some-cache/data.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_cache_path/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_cache_path/src/some-file.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_cache_path/src/static-files/static-a.txt
  packages/build/tests/secrets_scanning/tests.js
Labels: Adds or modifies js files

#5391 feat: supply system log to trusted plugins via FD
  packages/build/src/core/build.ts
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/child/systemLog.js
  packages/build/src/plugins/spawn.ts
  packages/build/src/steps/plugin.js
  packages/build/tests/plugins/fixtures/feature_flags/plugin.js
  packages/build/tests/plugins/fixtures/feature_flags_untrusted/plugin.js
  packages/build/tests/plugins/tests.js
  packages/build/types/netlify_plugin_options.d.ts
Labels: Adds or modifies js files

#5392 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5388 feat: create opentelemetry sdk package
  package-lock.json
  packages/opentelemetry-sdk-setup/README.md
  packages/opentelemetry-sdk-setup/bin.js
  packages/opentelemetry-sdk-setup/package.json
  packages/opentelemetry-sdk-setup/src/bin.ts
  packages/opentelemetry-sdk-setup/src/sdk-setup.ts
  packages/opentelemetry-sdk-setup/src/util.ts
  packages/opentelemetry-sdk-setup/tests/fixtures/monorepo/package.json
  packages/opentelemetry-sdk-setup/tests/fixtures/monorepo/packages/some-package/js-exec.js
  packages/opentelemetry-sdk-setup/tests/fixtures/monorepo/packages/some-package/package.json
  packages/opentelemetry-sdk-setup/tests/fixtures/package-with-symlink/.bin/js-exec.js
  packages/opentelemetry-sdk-setup/tests/fixtures/package-with-symlink/package/js-exec.js
  packages/opentelemetry-sdk-setup/tests/fixtures/package-with-symlink/package/package.json
  packages/opentelemetry-sdk-setup/tests/main.test.ts
  packages/opentelemetry-sdk-setup/tsconfig.json
  packages/opentelemetry-sdk-setup/vitest.config.ts
Labels: automerge, Adds or modifies js files

#5400 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
Labels: autorelease: pending, automerge

#5402 fix(build): add otel sdk setup as an optional peer dependency
  package-lock.json
  packages/build/package.json
Labels: automerge

#5407 fix(build): add support for ntl otel sdk setup on preloading
  packages/build/src/core/flags.js
  packages/build/src/core/normalize_flags.ts
  packages/build/src/core/types.ts
  packages/build/src/plugins/spawn.ts
  packages/build/src/tracing/main.ts
  packages/build/tests/tracing/tests.js
Labels: automerge, Adds or modifies js files

#5403 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
  packages/opentelemetry-sdk-setup/package.json
Labels: autorelease: pending

#5408 fix(build): add trusted plugin error type
  packages/build/src/error/parse/serialize_status.ts
  packages/build/src/error/types.ts
  packages/build/src/plugins/spawn.ts
  packages/build/src/steps/error.ts
  packages/build/src/steps/plugin.js
  packages/build/tests/error/fixtures/trusted_plugin/netlify.toml
  packages/build/tests/error/fixtures/trusted_plugin/node_modules/@netlify/netlify-plugin-test/index.js
  packages/build/tests/error/fixtures/trusted_plugin/node_modules/@netlify/netlify-plugin-test/manifest.yml
  packages/build/tests/error/fixtures/trusted_plugin/node_modules/@netlify/netlify-plugin-test/package.json
  packages/build/tests/error/fixtures/trusted_plugin/package.json
  packages/build/tests/error/fixtures/trusted_plugin_uncaught/netlify.toml
  packages/build/tests/error/fixtures/trusted_plugin_uncaught/node_modules/@netlify/netlify-plugin-test/index.js
  packages/build/tests/error/fixtures/trusted_plugin_uncaught/node_modules/@netlify/netlify-plugin-test/manifest.yml
  packages/build/tests/error/fixtures/trusted_plugin_uncaught/node_modules/@netlify/netlify-plugin-test/package.json
  packages/build/tests/error/fixtures/trusted_plugin_uncaught/package.json
  packages/build/tests/error/tests.js
Labels: automerge, Adds or modifies js files

#5410 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5404 feat(build): Add step to upload blobs from file based output
  .gitignore
  package-lock.json
  packages/build/package.json
  packages/build/src/core/types.ts
  packages/build/src/plugins_core/blobs_upload/index.ts
  packages/build/src/plugins_core/blobs_upload/utils.ts
  packages/build/src/plugins_core/build_command.js
  packages/build/src/steps/core_step.ts
  packages/build/src/steps/get.js
  packages/build/src/steps/run_core_steps.ts
  packages/build/src/steps/run_step.ts
  packages/build/src/utils/blobs.ts
  packages/build/tests/blobs_upload/fixtures/src_empty/netlify.toml
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/dist/.netlify/blobs/deploy/$with-metadata.txt.json
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/dist/.netlify/blobs/deploy/nested/$file.txt.json
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/dist/.netlify/blobs/deploy/nested/file.txt
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/dist/.netlify/blobs/deploy/something.txt
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/dist/.netlify/blobs/deploy/with-metadata.txt
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/netlify.toml
  packages/build/tests/blobs_upload/fixtures/src_with_malformed_blobs_metadata/dist/.netlify/blobs/deploy/$with-metadata.txt.json
  packages/build/tests/blobs_upload/fixtures/src_with_malformed_blobs_metadata/dist/.netlify/blobs/deploy/with-metadata.txt
  packages/build/tests/blobs_upload/fixtures/src_with_malformed_blobs_metadata/netlify.toml
  packages/build/tests/blobs_upload/tests.js
  packages/build/tests/steps/fixtures/with_preexisting_blobs/netlify.toml
  packages/build/tests/steps/fixtures/with_preexisting_blobs/out/.netlify/blobs/deploy/foo.txt
  packages/build/tests/steps/tests.js
Labels: Adds or modifies js files

#5414 fix(build): cleanup buildbot client and add further error segmentation
  packages/build/src/error/parse/location.ts
  packages/build/src/error/types.ts
  packages/build/src/plugins/events.ts
  packages/build/src/plugins_core/deploy/buildbot_client.js
  packages/build/src/plugins_core/deploy/buildbot_client.ts
  packages/build/src/utils/errors.js
  packages/build/src/utils/errors.ts
  packages/build/tests/deploy/tests.js
Labels: automerge, Adds or modifies js files

#5413 feat: cleanup any existing blobs from previous builds as a pre-build command
  .gitignore
  packages/build/src/plugins_core/blobs_upload/index.ts
  packages/build/src/plugins_core/blobs_upload/utils.ts
  packages/build/src/plugins_core/build_command.js
  packages/build/src/plugins_core/pre_cleanup/index.ts
  packages/build/src/steps/get.js
  packages/build/src/utils/blobs.ts
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/build.mjs
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/dist/.netlify/blobs/deploy/$with-metadata.txt.json
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/dist/.netlify/blobs/deploy/nested/$file.txt.json
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/dist/.netlify/blobs/deploy/nested/file.txt
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/dist/.netlify/blobs/deploy/something.txt
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/dist/.netlify/blobs/deploy/with-metadata.txt
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/netlify.toml
  packages/build/tests/blobs_upload/fixtures/src_with_malformed_blobs_metadata/build.mjs
  packages/build/tests/blobs_upload/fixtures/src_with_malformed_blobs_metadata/dist/.netlify/blobs/deploy/$with-metadata.txt.json
  packages/build/tests/blobs_upload/fixtures/src_with_malformed_blobs_metadata/dist/.netlify/blobs/deploy/with-metadata.txt
  packages/build/tests/blobs_upload/fixtures/src_with_malformed_blobs_metadata/netlify.toml
  packages/build/tests/blobs_upload/tests.js
  packages/build/tests/pre_cleanup/fixtures/src_empty/netlify.toml
  packages/build/tests/pre_cleanup/fixtures/with_preexisting_blobs/netlify.toml
  packages/build/tests/pre_cleanup/fixtures/with_preexisting_blobs/out/.netlify/blobs/deploy/foo.txt
  packages/build/tests/pre_cleanup/tests.js
  packages/build/tests/steps/tests.js
Labels: Adds or modifies js files

#5416 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5417 fix(build): add plugin version to tracing errors
  packages/build/src/error/types.ts
  packages/build/tests/error/tests.js
Labels: Adds or modifies js files

#5420 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending
