Repository netlify/build, pull requests merged in 2023-05, with the labels that each got.

#4993 fix: remove left padding and numbers from header
  package-lock.json
  packages/build/src/log/header.ts
  packages/build/src/log/messages/steps.js
  packages/build/src/steps/run_step.ts
  packages/build/tests/constants/snapshots/tests.js.md
  packages/build/tests/constants/snapshots/tests.js.snap
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/deploy/snapshots/tests.js.md
  packages/build/tests/deploy/snapshots/tests.js.snap
  packages/build/tests/edge_functions/snapshots/tests.js.md
  packages/build/tests/edge_functions/snapshots/tests.js.snap
  packages/build/tests/env/snapshots/tests.js.md
  packages/build/tests/env/snapshots/tests.js.snap
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/functions/snapshots/tests.js.md
  packages/build/tests/functions/snapshots/tests.js.snap
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/build/tests/manifest/snapshots/tests.js.md
  packages/build/tests/manifest/snapshots/tests.js.snap
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/build/tests/mutate/snapshots/tests.js.md
  packages/build/tests/mutate/snapshots/tests.js.snap
  packages/build/tests/mutate_headers_redirects/snapshots/tests.js.md
  packages/build/tests/mutate_headers_redirects/snapshots/tests.js.snap
  packages/build/tests/mutate_save/snapshots/tests.js.md
  packages/build/tests/mutate_save/snapshots/tests.js.snap
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins_events/snapshots/tests.js.md
  packages/build/tests/plugins_events/snapshots/tests.js.snap
  packages/build/tests/plugins_list/snapshots/tests.js.md
  packages/build/tests/plugins_list/snapshots/tests.js.snap
  packages/build/tests/stack/snapshots/tests.js.md
  packages/build/tests/stack/snapshots/tests.js.snap
  packages/build/tests/status/snapshots/tests.js.md
  packages/build/tests/status/snapshots/tests.js.snap
  packages/build/tests/steps/snapshots/tests.js.md
  packages/build/tests/steps/snapshots/tests.js.snap
  packages/build/tests/telemetry/snapshots/tests.js.md
  packages/build/tests/telemetry/snapshots/tests.js.snap
  packages/build/tests/utils_build/snapshots/tests.js.md
  packages/build/tests/utils_build/snapshots/tests.js.snap
Labels: Adds or modifies js files

#4995 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#4996 fix: fixes an issue where it could not retrieve the settings for the same root as projectdir
  packages/build-info/src/node/__snapshots__/get-build-info.test.ts.snap
  packages/build-info/src/node/get-build-info.test.ts
  packages/build-info/src/project.test.ts
  packages/build-info/src/project.ts
Labels: automerge

#5006 fix: remove `del` package
  package-lock.json
  packages/build/package.json
  packages/build/tests/functions/tests.js
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/build/tests/monitor/tests.js
  packages/build/tests/mutate_headers_redirects/tests.js
  packages/build/tests/mutate_save/tests.js
  packages/cache-utils/package.json
  packages/cache-utils/src/main.ts
  packages/cache-utils/src/manifest.ts
  packages/cache-utils/tests/helpers/main.ts
  packages/config/package.json
  packages/config/tests/cli/tests.js
  packages/config/tests/mutate/tests.js
  packages/framework-info/package.json
  packages/framework-info/tests/package.test.ts
  packages/testing/package.json
  packages/testing/src/dir.ts
Labels: automerge, Adds or modifies js files, Ecosystem: Dev Foundations

#5008 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#5012 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5019 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#5028 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5029 fix(framework-info): remove unnecessary dependency on node-url
  package-lock.json
  packages/framework-info/package.json
Labels: automerge
