Repository netlify/build, pull requests merged in 2024-09, with the labels that each got.

#5815 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5830 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5805 ci: add e2e testing pipeline to the reopsitory
  .circleci/config.yml
Labels: Adds or modifies js files

#5831 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5839 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5836 fix(zip-it-and-ship-it): create missing symlinks when archiveFormat=none
  packages/zip-it-and-ship-it/src/runtimes/node/utils/zip.ts
  packages/zip-it-and-ship-it/tests/fixtures-esm/symlinked-deps/function.mjs
  packages/zip-it-and-ship-it/tests/fixtures-esm/symlinked-deps/node_modules/.pnpm/is-even-or-odd@1.0.0/node_modules/is-even
  packages/zip-it-and-ship-it/tests/fixtures-esm/symlinked-deps/node_modules/.pnpm/is-even-or-odd@1.0.0/node_modules/is-even-or-odd/index.js
  packages/zip-it-and-ship-it/tests/fixtures-esm/symlinked-deps/node_modules/.pnpm/is-even-or-odd@1.0.0/node_modules/is-even-or-odd/package.json
  packages/zip-it-and-ship-it/tests/fixtures-esm/symlinked-deps/node_modules/.pnpm/is-even-or-odd@1.0.0/node_modules/is-odd
  packages/zip-it-and-ship-it/tests/fixtures-esm/symlinked-deps/node_modules/.pnpm/is-even@1.0.0/node_modules/is-even/index.js
  packages/zip-it-and-ship-it/tests/fixtures-esm/symlinked-deps/node_modules/.pnpm/is-even@1.0.0/node_modules/is-even/package.json
  packages/zip-it-and-ship-it/tests/fixtures-esm/symlinked-deps/node_modules/.pnpm/is-even@1.0.0/node_modules/is-odd
  packages/zip-it-and-ship-it/tests/fixtures-esm/symlinked-deps/node_modules/.pnpm/is-odd@1.0.0/node_modules/is-odd/index.js
  packages/zip-it-and-ship-it/tests/fixtures-esm/symlinked-deps/node_modules/.pnpm/is-odd@1.0.0/node_modules/is-odd/package.json
  packages/zip-it-and-ship-it/tests/fixtures-esm/symlinked-deps/node_modules/is-even-or-odd
  packages/zip-it-and-ship-it/tests/symlinked_included_files.test.ts
Labels: Adds or modifies js files

#5841 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5842 fix: set default nodejs version for redwoodjs
  packages/build-info/src/frameworks/redwood.test.ts
  packages/build-info/src/frameworks/redwoodjs.ts
Labels: automerge

#5844 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5848 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5855 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending
