Repository netlify/build, pull requests merged in 2024-12, with the labels that each got.

#5926 chore: remove released feature flag for extensions/ future state
  packages/config/src/api/site_info.ts
  packages/config/src/case.ts
  packages/config/tests/api/tests.js
Labels: Adds or modifies js files

#5911 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/git-utils/CHANGELOG.md
  packages/git-utils/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/nock-udp/CHANGELOG.md
  packages/nock-udp/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
  packages/opentelemetry-sdk-setup/package.json
  packages/opentelemetry-utils/CHANGELOG.md
  packages/opentelemetry-utils/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
  packages/run-utils/CHANGELOG.md
  packages/run-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5914 feat(build): Add trace attribute to track builds failing from Netlify maintained extensions
  packages/build/src/error/types.ts
  packages/build/src/plugins/load.js
  packages/build/src/steps/plugin.js
  packages/build/src/steps/run_step.ts
  packages/build/src/steps/run_steps.js
  packages/build/tests/error/tests.js
  packages/config/src/types/integrations.ts
Labels: automerge, Adds or modifies js files

#5915 fix: fail build when extension failed to be retrieved
  packages/config/src/api/site_info.ts
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/api/tests.js
Labels: Adds or modifies js files

#5943 feat: rename unscoped NPM packages
  package-lock.json
  packages/config/docs/main.md
  packages/config/package.json
  packages/config/src/headers.js
  packages/config/src/redirects.ts
  packages/headers-parser/package.json
  packages/redirect-parser/package.json
Labels: Adds or modifies js files

#5947 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5951 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5954 Revert "fix: fail build when extension failed to be retrieved"
  packages/config/src/api/site_info.ts
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/api/tests.js
Labels: Adds or modifies js files

#5957 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending
