Repository netlify/build, pull requests merged in 2024-07, with the labels that each got.

#5746 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5752 fix: revert config mutation passing
  packages/build/src/core/config.js
Labels: automerge, Adds or modifies js files

#5753 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5758 fix: bump serverless-functions-api version with the fix
  package-lock.json
  packages/zip-it-and-ship-it/package.json
Labels: automerge

#5754 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5764 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
Labels: autorelease: pending

#5761 feat: pass default config for resolveUpdatedConfig instead of cached config
  packages/build/src/core/build.ts
  packages/build/src/core/config.js
  packages/build/src/steps/core_step.ts
  packages/build/src/steps/plugin.js
  packages/build/src/steps/run_core_steps.ts
  packages/build/src/steps/run_step.ts
  packages/build/src/steps/run_steps.js
  packages/build/src/steps/update_config.js
  packages/config/src/main.ts
  packages/config/tests/mutate/tests.js
Labels: automerge, Adds or modifies js files

#5765 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#5766 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5768 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5770 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#5775 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5785 fix: handle non node: prefixed Node.js builtins when no npm specifiers were found
  packages/build/src/error/monitor/normalize.js
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/edge-bundler/node/bundler.test.ts
  packages/edge-bundler/node/npm_dependencies.ts
  packages/edge-bundler/test/fixtures/imports_node_builtin/netlify/edge-functions/func1.ts
  packages/testing/src/normalize.ts
Labels: Adds or modifies js files
