Repository netlify/build, pull requests merged in 2024-08, with the labels that each got.

#5787 feat: change meta endpoint to pass siteid as a url parameter
  packages/config/src/api/site_info.ts
  packages/config/tests/api/tests.js
Labels: Adds or modifies js files

#5794 feat: pass accountId to runBuild and resolve config
  packages/build/src/core/build.ts
  packages/build/src/core/config.js
Labels: Adds or modifies js files

#5795 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5797 feat: add accountId flags const
  packages/build/src/core/flags.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
Labels: automerge, Adds or modifies js files

#5798 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending, automerge

#5793 fix: don't overwrite plugin origin if it exists
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/config/src/origin.js
  packages/config/tests/validate/snapshots/tests.js.md
  packages/config/tests/validate/snapshots/tests.js.snap
Labels: Adds or modifies js files

#5810 feat(config): return account id from config in offline mode
  packages/config/src/api/site_info.ts
  packages/config/tests/api/tests.js
Labels: Adds or modifies js files

#5800 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5811 feat(build): add account id constant to plugins
  packages/build/src/core/constants.ts
  packages/build/tests/constants/fixtures/account_id/manifest.yml
  packages/build/tests/constants/fixtures/account_id/netlify.toml
  packages/build/tests/constants/fixtures/account_id/plugin.js
  packages/build/tests/constants/snapshots/tests.js.md
  packages/build/tests/constants/snapshots/tests.js.snap
  packages/build/tests/constants/tests.js
  packages/zip-it-and-ship-it/src/runtimes/node/parser/index.ts
Labels: Adds or modifies js files

#5812 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending
