Repository netlify/build, pull requests merged in 2024-03, with the labels that each got.

#5538 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
  packages/opentelemetry-sdk-setup/package.json
Labels: autorelease: pending

#5543 fix: support deploy config API in monorepos
  packages/build/src/plugins_core/deploy_config/index.ts
  packages/build/tests/deploy_config/fixtures/monorepo/apps/app-1/build.mjs
  packages/build/tests/deploy_config/fixtures/monorepo/apps/app-1/netlify.toml
  packages/build/tests/deploy_config/fixtures/monorepo/apps/app-1/package.json
  packages/build/tests/deploy_config/fixtures/monorepo/apps/app-2/build.mjs
  packages/build/tests/deploy_config/fixtures/monorepo/apps/app-2/netlify.toml
  packages/build/tests/deploy_config/fixtures/monorepo/apps/app-2/package.json
  packages/build/tests/deploy_config/fixtures/monorepo/package.json
  packages/build/tests/deploy_config/fixtures/monorepo/pnpm-workspace.yaml
  packages/build/tests/deploy_config/tests.js
Labels: Adds or modifies js files

#5544 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5548 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
  packages/opentelemetry-sdk-setup/package.json
  packages/opentelemetry-utils/CHANGELOG.md
  packages/opentelemetry-utils/package.json
Labels: autorelease: pending

#5550 chore: disable test in Node 14
  packages/build/tests/deploy_config/tests.js
Labels: Adds or modifies js files

#5455 fix(metrics): add validation/formatting before sending errors to BugSnag
  packages/build-info/src/metrics.test.ts
  packages/build-info/src/metrics.ts
Labels: automerge

#5551 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5554 fix: stop pinning plugins with prerelease versions
  packages/build/src/plugins/pinned_version.js
  packages/build/src/utils/semver.js
  packages/build/tests/plugins_list/fixtures/pin_prerelease/.netlify/plugins/node_modules/netlify-plugin-contextual-env/index.js
  packages/build/tests/plugins_list/fixtures/pin_prerelease/.netlify/plugins/node_modules/netlify-plugin-contextual-env/manifest.yml
  packages/build/tests/plugins_list/fixtures/pin_prerelease/.netlify/plugins/node_modules/netlify-plugin-contextual-env/package.json
  packages/build/tests/plugins_list/fixtures/pin_prerelease/.netlify/plugins/package.json
  packages/build/tests/plugins_list/fixtures/pin_prerelease/package.json
  packages/build/tests/plugins_list/snapshots/tests.js.md
  packages/build/tests/plugins_list/snapshots/tests.js.snap
  packages/build/tests/plugins_list/tests.js
  packages/build/tests/unit/validate_edge_manifest/snapshots/tests.js.md
  packages/build/tests/unit/validate_edge_manifest/snapshots/tests.js.snap
  packages/build/tests/unit/validate_edge_manifest/tests.js
Labels: Adds or modifies js files

#5555 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5560 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
Labels: autorelease: pending

#5556 feat: instrument child process with open telemetry
  package-lock.json
  packages/build/package.json
  packages/build/src/core/build.ts
  packages/build/src/plugins/child/main.js
  packages/build/src/plugins/child/run.js
  packages/build/src/plugins/node_version.ts
  packages/build/src/plugins/spawn.ts
  packages/build/src/plugins_core/build_command.js
  packages/build/src/steps/plugin.js
  packages/build/src/steps/run_step.ts
  packages/build/tests/log/snapshots/tests.js.md
  packages/build/tests/log/snapshots/tests.js.snap
  packages/opentelemetry-sdk-setup/package.json
  packages/opentelemetry-sdk-setup/src/index.ts
  packages/opentelemetry-sdk-setup/src/sdk-setup.ts
  packages/opentelemetry-sdk-setup/tests/main.test.ts
  packages/opentelemetry-utils/package.json
  packages/opentelemetry-utils/tests/main.test.ts
Labels: Adds or modifies js files

#5562 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5564 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending
