Repository netlify/build, pull requests merged in 2024-05, with the labels that each got.

#5622 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#5623 feat: parse custom rate limit info from redirects
  packages/redirect-parser/src/normalize.js
  packages/redirect-parser/tests/fixtures/netlify_config/with_ratelimit.toml
  packages/redirect-parser/tests/netlify-config-parser.test.ts
Labels: type: feature, Adds or modifies js files

#5627 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
  packages/opentelemetry-sdk-setup/package.json
  packages/opentelemetry-utils/CHANGELOG.md
  packages/opentelemetry-utils/package.json
Labels: autorelease: pending

#5645 chore: adapt zisi repo
  .eslintrc.cjs
  .github/codeql/codeql-config.yml
  .github/workflows/benchmark.yml
  .github/workflows/workflow.yml
  .prettierignore
  .release-please-manifest.json
  package-lock.json
  packages/config/src/bin/flags.ts
  packages/zip-it-and-ship-it/.editorconfig
  packages/zip-it-and-ship-it/.eslintrc.cjs
  packages/zip-it-and-ship-it/.gitattributes
  packages/zip-it-and-ship-it/.github/.kodiak.toml
  packages/zip-it-and-ship-it/.github/CODEOWNERS
  packages/zip-it-and-ship-it/.github/ISSUE_TEMPLATE.md
  packages/zip-it-and-ship-it/.github/PULL_REQUEST_TEMPLATE.md
  packages/zip-it-and-ship-it/.github/codeql/codeql-config.yml
  packages/zip-it-and-ship-it/.github/workflows/codeql-analysis.yml
  packages/zip-it-and-ship-it/.github/workflows/fossa.yml
  packages/zip-it-and-ship-it/.github/workflows/pre-release.yml
  packages/zip-it-and-ship-it/.github/workflows/release-please.yml
  packages/zip-it-and-ship-it/.github/workflows/workflow.yml
  packages/zip-it-and-ship-it/.gitignore
  packages/zip-it-and-ship-it/.prettierignore
  packages/zip-it-and-ship-it/.prettierrc.json
  packages/zip-it-and-ship-it/CODE_OF_CONDUCT.md
  packages/zip-it-and-ship-it/CONTRIBUTING.md
  packages/zip-it-and-ship-it/LICENSE
  packages/zip-it-and-ship-it/benchmarks/helpers/main.js
  packages/zip-it-and-ship-it/bin.js
  packages/zip-it-and-ship-it/codecov.yml
  packages/zip-it-and-ship-it/commitlint.config.cjs
  packages/zip-it-and-ship-it/package-lock.json
  packages/zip-it-and-ship-it/package.json
  packages/zip-it-and-ship-it/src/bin.ts
  packages/zip-it-and-ship-it/src/config.ts
  packages/zip-it-and-ship-it/src/runtimes/node/bundlers/esbuild/plugin_native_modules.ts
  packages/zip-it-and-ship-it/src/runtimes/node/bundlers/zisi/resolve.ts
  packages/zip-it-and-ship-it/src/runtimes/node/parser/exports.ts
  packages/zip-it-and-ship-it/src/utils/fs.ts
  packages/zip-it-and-ship-it/src/utils/remove_undefined.ts
  packages/zip-it-and-ship-it/src/utils/urlpattern.ts
  packages/zip-it-and-ship-it/tests/esbuild.test.ts
  packages/zip-it-and-ship-it/tests/fixtures-esm/v2-api-cjs-ts-aliases/function.ts
  packages/zip-it-and-ship-it/tests/fixtures-esm/v2-api-esm-ts-aliases/function.ts
  packages/zip-it-and-ship-it/tests/fixtures/node-module-missing-conditional/function.js
  packages/zip-it-and-ship-it/tests/helpers/main.ts
  packages/zip-it-and-ship-it/tests/helpers/test_many.ts
  packages/zip-it-and-ship-it/tests/list_functions_files.test.ts
  packages/zip-it-and-ship-it/tests/main.test.ts
  packages/zip-it-and-ship-it/tsconfig.json
  release-please-config.json
Labels: Adds or modifies js files

#5652 fix: flush output from "Deploy site" step
  packages/build/src/plugins_core/deploy/index.js
Labels: Adds or modifies js files

#5654 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5658 fix: update config logger
  packages/config/src/log/logger.js
Labels: Adds or modifies js files

#5657 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#5659 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5664 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5673 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
  packages/opentelemetry-sdk-setup/package.json
Labels: autorelease: pending

#5676 fix: stop changing `logs` if flusher is not set
  packages/build/src/log/logger.ts
  packages/build/src/steps/core_step.ts
  packages/build/src/steps/plugin.js
Labels: Adds or modifies js files

#5674 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5677 feat: pass output flusher to `callChild`
  packages/build/src/log/output_flusher.ts
  packages/build/src/log/stream.js
  packages/build/src/log/stream.ts
  packages/build/src/plugins/spawn.ts
  packages/build/src/steps/plugin.js
Labels: Adds or modifies js files

#5678 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5679 feat: emit system log when plugin has failed to load
  packages/build/src/core/build.ts
  packages/build/src/core/feature_flags.ts
  packages/build/src/plugins/load.js
  packages/build/tests/plugins/fixtures/syntax_error/manifest.yml
  packages/build/tests/plugins/fixtures/syntax_error/netlify.toml
  packages/build/tests/plugins/fixtures/syntax_error/plugin.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: Adds or modifies js files

#5682 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5683 feat: add `timeout` config prop for functions
  packages/zip-it-and-ship-it/src/config.ts
  packages/zip-it-and-ship-it/src/main.ts
  packages/zip-it-and-ship-it/src/manifest.ts
  packages/zip-it-and-ship-it/src/runtimes/node/in_source_config/index.ts
  packages/zip-it-and-ship-it/src/runtimes/node/index.ts
  packages/zip-it-and-ship-it/src/runtimes/runtime.ts
  packages/zip-it-and-ship-it/tests/__snapshots__/list_function.test.ts.snap
  packages/zip-it-and-ship-it/tests/__snapshots__/list_functions.test.ts.snap
  packages/zip-it-and-ship-it/tests/__snapshots__/list_functions_files.test.ts.snap
  packages/zip-it-and-ship-it/tests/fixtures-esm/v2-api-name-generator/.netlify/functions-internal/server.json
  packages/zip-it-and-ship-it/tests/fixtures-esm/v2-api-name-generator/.netlify/functions-internal/server.mjs
  packages/zip-it-and-ship-it/tests/unit/runtimes/node/in_source_config.test.ts
  packages/zip-it-and-ship-it/tests/v2api.test.ts
Labels: automerge, Adds or modifies js files

#5647 feat: retrieve integration meta data from new endpoint
  packages/config/src/api/site_info.ts
  packages/config/src/error.ts
  packages/config/src/main.ts
  packages/config/tests/api/tests.js
Labels: automerge, Adds or modifies js files

#5685 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#5687 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#5689 fix: revert b8899e06a31f5615ef41d8a4ab251bcc96717837
  packages/config/src/api/site_info.ts
  packages/config/src/error.ts
  packages/config/src/main.ts
  packages/config/tests/api/tests.js
Labels: Adds or modifies js files

#5690 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending
