Repository netlify/build, pull requests merged in 2024-04, with the labels that each got.

#5565 feat: support deploy config API with Blobs
  packages/build/src/plugins_core/blobs_upload/index.ts
  packages/build/src/plugins_core/pre_cleanup/index.ts
  packages/build/src/utils/blobs.ts
  packages/build/tests/blobs_upload/fixtures/src_with_blobs/build.mjs
  packages/build/tests/blobs_upload/fixtures/src_with_blobs_legacy/build.mjs
  packages/build/tests/blobs_upload/fixtures/src_with_blobs_legacy/netlify.toml
  packages/build/tests/blobs_upload/tests.js
Labels: Adds or modifies js files

#5569 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5575 fix: update logic for plugin selection fallback
  packages/build/src/core/feature_flags.ts
  packages/build/src/plugins/compatibility.test.ts
  packages/build/src/plugins/compatibility.ts
  packages/build/src/plugins/expected_version.ts
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/tests.js
Labels: Adds or modifies js files

#5573 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5589 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5593 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5594 feat(secrets scanning): support globs
  package-lock.json
  packages/build/package.json
  packages/build/src/plugins_core/secrets_scanning/utils.ts
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_glob_path/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_glob_path/src/some-file.txt
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_glob_path/src/static-files/notsafefile.js
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_glob_path/src/static-files/safefile.js
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_glob_path/src/static-files/static-a.txt
  packages/build/tests/secrets_scanning/snapshots/tests.js.md
  packages/build/tests/secrets_scanning/snapshots/tests.js.snap
  packages/build/tests/secrets_scanning/tests.js
Labels: Adds or modifies js files

#5595 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5426 fix: when fetching env from envelope, pass context
  packages/config/src/api/site_info.ts
  packages/config/src/env/envelope.ts
  packages/config/src/env/main.ts
  packages/config/src/main.ts
  packages/config/tests/env/tests.js
Labels: stale, Adds or modifies js files

#5599 chore: adapt edge-bundler repo
  .circleci/config.yml
  .eslintrc.cjs
  .github/workflows/workflow.yml
  .prettierignore
  .release-please-manifest.json
  package-lock.json
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/edge-bundler/.editorconfig
  packages/edge-bundler/.eslintrc.cjs
  packages/edge-bundler/.gitattributes
  packages/edge-bundler/.github/.kodiak.toml
  packages/edge-bundler/.github/CODEOWNERS
  packages/edge-bundler/.github/ISSUE_TEMPLATE/bug_report.md
  packages/edge-bundler/.github/ISSUE_TEMPLATE/feature_request.md
  packages/edge-bundler/.github/pull_request_template.md
  packages/edge-bundler/.github/workflows/fossa.yml
  packages/edge-bundler/.github/workflows/github-packages-releaser.yml
  packages/edge-bundler/.github/workflows/integration.yml
  packages/edge-bundler/.github/workflows/workflow.yml
  packages/edge-bundler/.prettierrc.json
  packages/edge-bundler/CODE_OF_CONDUCT.md
  packages/edge-bundler/CONTRIBUTING.md
  packages/edge-bundler/LICENSE
  packages/edge-bundler/commitlint.config.cjs
  packages/edge-bundler/node/bridge.ts
  packages/edge-bundler/node/bundle_error.ts
  packages/edge-bundler/node/declaration.ts
  packages/edge-bundler/node/downloader.test.ts
  packages/edge-bundler/node/finder.ts
  packages/edge-bundler/node/manifest.test.ts
  packages/edge-bundler/node/manifest.ts
  packages/edge-bundler/node/npm_dependencies.ts
  packages/edge-bundler/node/server/util.ts
  packages/edge-bundler/node/types.ts
  packages/edge-bundler/node/utils/error.ts
  packages/edge-bundler/node/validation/manifest/index.test.ts
  packages/edge-bundler/node/validation/manifest/index.ts
  packages/edge-bundler/package-lock.json
  packages/edge-bundler/package.json
  packages/edge-bundler/renovate.json5
  packages/edge-bundler/test/integration/test.js
  packages/edge-bundler/vitest.config.ts
  release-please-config.json
Labels: Adds or modifies js files

#5597 chore: release main
  .github/workflows/workflow.yml
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
  packages/opentelemetry-sdk-setup/package.json
  packages/opentelemetry-utils/CHANGELOG.md
  packages/opentelemetry-utils/package.json
Labels: autorelease: pending, Adds or modifies js files

#5600 fix: clean up blob directories in pre-dev
  .gitignore
  packages/build/src/plugins_core/pre_dev_cleanup/index.ts
  packages/build/src/utils/blobs.ts
  packages/build/tests/pre_dev_cleanup/fixtures/monorepo/apps/with-blobs/.netlify/deploy/v1/blobs/deploy/foo.txt
  packages/build/tests/pre_dev_cleanup/fixtures/monorepo/apps/with-blobs/netlify.toml
  packages/build/tests/pre_dev_cleanup/fixtures/monorepo/apps/with-blobs/package.json
  packages/build/tests/pre_dev_cleanup/fixtures/monorepo/apps/with-leftover-functions/.netlify/edge-functions/leftover.mjs
  packages/build/tests/pre_dev_cleanup/fixtures/monorepo/apps/with-leftover-functions/.netlify/functions-internal/leftover.mjs
  packages/build/tests/pre_dev_cleanup/fixtures/monorepo/apps/with-leftover-functions/netlify.toml
  packages/build/tests/pre_dev_cleanup/fixtures/monorepo/apps/with-leftover-functions/package.json
  packages/build/tests/pre_dev_cleanup/fixtures/monorepo/apps/with-legacy-blobs/.netlify/blobs/deploy/foo.txt
  packages/build/tests/pre_dev_cleanup/fixtures/monorepo/apps/with-legacy-blobs/netlify.toml
  packages/build/tests/pre_dev_cleanup/fixtures/monorepo/apps/with-legacy-blobs/package.json
  packages/build/tests/pre_dev_cleanup/fixtures/monorepo/package.json
  packages/build/tests/pre_dev_cleanup/fixtures/monorepo/pnpm-workspace.yaml
  packages/build/tests/pre_dev_cleanup/fixtures/with-blobs/.netlify/deploy/v1/blobs/deploy/foo.txt
  packages/build/tests/pre_dev_cleanup/fixtures/with-blobs/netlify.toml
  packages/build/tests/pre_dev_cleanup/fixtures/with-leftover-functions/.netlify/edge-functions/leftover.mjs
  packages/build/tests/pre_dev_cleanup/fixtures/with-leftover-functions/.netlify/functions-internal/leftover.mjs
  packages/build/tests/pre_dev_cleanup/fixtures/with-leftover-functions/netlify.toml
  packages/build/tests/pre_dev_cleanup/fixtures/with-legacy-blobs/.netlify/blobs/deploy/foo.txt
  packages/build/tests/pre_dev_cleanup/fixtures/with-legacy-blobs/netlify.toml
  packages/build/tests/pre_dev_cleanup/tests.js
Labels: Adds or modifies js files

#5607 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#5609 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending
