Repository netlify/build, pull requests merged in 2024-02, with the labels that each got.

#5464 feat: allow mutating images field in NetlifyConfig
  packages/config/src/mutations/apply.js
Labels: Adds or modifies js files

#5497 fix: check version range of node 20 upgrade
  packages/build/src/core/build.ts
  packages/build/src/plugins/node_version.ts
  packages/build/src/plugins/options.ts
  packages/build/src/plugins/resolve.js
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
Labels: Adds or modifies js files

#5500 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#5506 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5508 fix: switch to @iarna/toml
  package-lock.json
  packages/build-info/package.json
  packages/build-info/src/settings/get-toml-settings.ts
  packages/build/tests/error/snapshots/tests.js.md
  packages/build/tests/error/snapshots/tests.js.snap
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/config/package.json
  packages/config/src/utils/toml.js
  packages/config/tests/parse/snapshots/tests.js.md
  packages/config/tests/parse/snapshots/tests.js.snap
  packages/headers-parser/package.json
  packages/headers-parser/src/netlify_config_parser.ts
  packages/redirect-parser/package.json
  packages/redirect-parser/src/netlify_config_parser.js
Labels: automerge, Adds or modifies js files

#5510 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
Labels: autorelease: pending, automerge

#5509 feat: initial support for Deploy Configuration API
  .gitignore
  package-lock.json
  packages/build/src/core/dry.js
  packages/build/src/plugins_core/deploy_config/index.ts
  packages/build/src/plugins_core/deploy_config/util.ts
  packages/build/src/plugins_core/types.ts
  packages/build/src/steps/get.ts
  packages/build/src/steps/run_core_steps.ts
  packages/build/src/steps/run_step.ts
  packages/build/src/steps/run_steps.js
  packages/build/tests/deploy_config/fixtures/deploy_config/.netlify/deploy/v1/config.json
  packages/build/tests/deploy_config/fixtures/deploy_config/manifest.yml
  packages/build/tests/deploy_config/fixtures/deploy_config/netlify.toml
  packages/build/tests/deploy_config/fixtures/deploy_config/plugin.js
  packages/build/tests/deploy_config/fixtures/from_build_command/.netlify/deploy/v1/config.json
  packages/build/tests/deploy_config/fixtures/from_build_command/manifest.yml
  packages/build/tests/deploy_config/fixtures/from_build_command/netlify.toml
  packages/build/tests/deploy_config/fixtures/from_build_command/plugin.js
  packages/build/tests/deploy_config/fixtures/from_build_command/seed.json
  packages/build/tests/deploy_config/fixtures/from_build_command/write_config.mjs
  packages/build/tests/deploy_config/fixtures/malformed_config/.netlify/deploy/v1/config.json
  packages/build/tests/deploy_config/fixtures/malformed_config/manifest.yml
  packages/build/tests/deploy_config/fixtures/malformed_config/netlify.toml
  packages/build/tests/deploy_config/fixtures/malformed_config/plugin.js
  packages/build/tests/deploy_config/fixtures/missing_config/manifest.yml
  packages/build/tests/deploy_config/fixtures/missing_config/netlify.toml
  packages/build/tests/deploy_config/fixtures/missing_config/plugin.js
  packages/build/tests/deploy_config/fixtures/readonly_properties/.netlify/deploy/v1/config.json
  packages/build/tests/deploy_config/fixtures/readonly_properties/manifest.yml
  packages/build/tests/deploy_config/fixtures/readonly_properties/netlify.toml
  packages/build/tests/deploy_config/fixtures/readonly_properties/plugin.js
  packages/build/tests/deploy_config/snapshots/tests.js.md
  packages/build/tests/deploy_config/snapshots/tests.js.snap
  packages/build/tests/deploy_config/tests.js
  packages/config/src/index.ts
  packages/config/src/merge.js
  packages/testing/src/normalize.ts
Labels: Adds or modifies js files

#5516 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#5519 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5522 feat: stop logging internal config mutations
  packages/build/src/steps/plugin.js
  packages/build/src/steps/update_config.js
Labels: Adds or modifies js files

#5521 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#5515 fix: pass absolute path to resolvePath for resolveIntegration
  packages/build/src/plugins/resolve.js
Labels: Adds or modifies js files

#5524 fix: don't wipe functions created in `onPreDev`
  packages/build/src/steps/get.ts
  packages/build/tests/functions/fixtures/functions_leftover/.netlify/edge-functions/leftover.mjs
  packages/build/tests/functions/fixtures/functions_leftover/.netlify/functions-internal/leftover.mjs
  packages/build/tests/functions/fixtures/functions_leftover/manifest.yml
  packages/build/tests/functions/fixtures/functions_leftover/netlify.toml
  packages/build/tests/functions/fixtures/functions_leftover/plugin.mjs
  packages/build/tests/functions/tests.js
Labels: Adds or modifies js files

#5523 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
Labels: autorelease: pending

#5527 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending

#5525 feat: emit system log for config mutations
  packages/build/src/log/messages/mutations.js
  packages/build/src/steps/core_step.ts
  packages/build/src/steps/plugin.js
  packages/build/src/steps/run_step.ts
  packages/build/src/steps/update_config.js
  packages/build/tests/deploy_config/tests.js
Labels: Adds or modifies js files

#5530 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
  packages/opentelemetry-sdk-setup/package.json
  packages/opentelemetry-utils/CHANGELOG.md
  packages/opentelemetry-utils/package.json
Labels: autorelease: pending

#5534 fix: remove cli_fetch_integrations and cli_fetch_integrations
  packages/build/src/plugins/resolve.js
  packages/build/tests/install/tests.js
  packages/config/tests/api/tests.js
Labels: Adds or modifies js files

#5533 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending
