Repository netlify/build, pull requests merged in 2025-05, with the labels that each got.

#6227 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6285 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6247 feat: rename API package to `@netlify/api`
  nx.json
  package-lock.json
  packages/config/package.json
  packages/config/src/api/client.js
  packages/config/src/api/site_info.ts
  packages/config/src/env/envelope.ts
  packages/config/src/env/main.ts
  packages/js-client/README.md
  packages/js-client/package.json
Labels: Adds or modifies js files

#6289 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#6230 feat: introduce enhanced secret scanning
  packages/build/docs/flow.md
  packages/build/src/core/build.ts
  packages/build/src/core/flags.js
  packages/build/src/log/messages/config.js
  packages/build/src/log/messages/core_steps.js
  packages/build/src/plugins_core/secrets_scanning/index.ts
  packages/build/src/plugins_core/secrets_scanning/utils.ts
  packages/build/src/plugins_core/types.ts
  packages/build/src/steps/core_step.ts
  packages/build/src/steps/run_step.ts
  packages/build/src/steps/run_steps.js
  packages/build/tests/secrets_scanning/fixtures/src_scanning_env_vars_no_matches/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_likely_enhanced_scan_secrets/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_likely_enhanced_scan_secrets_disabled/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_no_likely_enhanced_scan_secrets/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_all_keys/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_all_paths/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_omit_glob_path/netlify.toml
  packages/build/tests/secrets_scanning/snapshots/tests.js.md
  packages/build/tests/secrets_scanning/snapshots/tests.js.snap
  packages/build/tests/secrets_scanning/tests.js
Labels: Adds or modifies js files

#6223 feat!: end of support for v14 and v16
  .github/workflows/workflow.yml
  package-lock.json
  package.json
  packages/build-info/package.json
  packages/build/package.json
  packages/build/src/plugins/node_version.ts
  packages/build/src/plugins/resolve.js
  packages/build/tests/blobs_upload/tests.js
  packages/build/tests/core/snapshots/tests.js.md
  packages/build/tests/core/snapshots/tests.js.snap
  packages/build/tests/edge_functions/tests.js
  packages/build/tests/frameworks_api/tests.js
  packages/build/tests/functions/tests.js
  packages/build/tests/plugins/fixtures/engines/package.json
  packages/build/tests/plugins/fixtures/version_greater_than_minimum/package.json
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/cache-utils/package.json
  packages/config/package.json
  packages/edge-bundler/package.json
  packages/framework-info/package.json
  packages/functions-utils/package.json
  packages/git-utils/package.json
  packages/headers-parser/package.json
  packages/js-client/package.json
  packages/nock-udp/package.json
  packages/opentelemetry-sdk-setup/package.json
  packages/opentelemetry-utils/package.json
  packages/redirect-parser/package.json
  packages/run-utils/package.json
  packages/testing/package.json
  packages/zip-it-and-ship-it/package.json
Labels: Adds or modifies js files

#6299 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/git-utils/CHANGELOG.md
  packages/git-utils/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/nock-udp/CHANGELOG.md
  packages/nock-udp/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
  packages/opentelemetry-sdk-setup/package.json
  packages/opentelemetry-utils/CHANGELOG.md
  packages/opentelemetry-utils/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
  packages/run-utils/CHANGELOG.md
  packages/run-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6313 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
  packages/opentelemetry-sdk-setup/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6325 chore: cpy-file was renamed to copy-file
  package-lock.json
  packages/zip-it-and-ship-it/package.json
  packages/zip-it-and-ship-it/src/runtimes/go/index.ts
  packages/zip-it-and-ship-it/src/runtimes/node/index.ts
  packages/zip-it-and-ship-it/src/runtimes/node/utils/zip.ts
Labels: automerge

#6322 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6301 fix(deps): upgrade execa to v8
  package-lock.json
  packages/build-info/package.json
  packages/build/package.json
  packages/config/package.json
  packages/edge-bundler/package.json
  packages/git-utils/package.json
  packages/run-utils/package.json
  packages/run-utils/src/main.ts
  packages/testing/package.json
  packages/zip-it-and-ship-it/package.json
Labels: automerge

#6345 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/git-utils/CHANGELOG.md
  packages/git-utils/package.json
  packages/run-utils/CHANGELOG.md
  packages/run-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6348 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6351 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6373 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#6375 feat: safelist common string in react proptypes from secret detection
  packages/build/src/plugins_core/secrets_scanning/secret_prefixes.ts
  packages/build/src/plugins_core/secrets_scanning/utils.ts
  packages/build/tests/utils_secretscanning/tests.js
Labels: Adds or modifies js files

#6377 fix: drop node-fetch from build package
  package-lock.json
  packages/build/package.json
  packages/build/src/plugins_core/blobs_upload/index.ts
  packages/build/src/plugins_core/dev_blobs_upload/index.ts
  packages/build/tests/blobs_upload/tests.js
  packages/build/tests/plugins/fixtures/blobs_read/plugin.js
Labels: Adds or modifies js files

#6374 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#6388 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#6318 feat: allow to scan secrets without buffering whole lines
  packages/build/src/plugins_core/secrets_scanning/index.ts
  packages/build/src/plugins_core/secrets_scanning/utils.ts
  packages/build/tests/secrets_scanning/fixtures/src_scanning_large_binary_file/generate.mjs
  packages/build/tests/secrets_scanning/fixtures/src_scanning_large_binary_file/netlify.toml
  packages/build/tests/secrets_scanning/snapshots/tests.js.md
  packages/build/tests/secrets_scanning/snapshots/tests.js.snap
  packages/build/tests/secrets_scanning/tests.js
  packages/build/tests/utils_secretscanning/tests.js
Labels: Adds or modifies js files

#6376 feat: allow enhanced scan to run without impacting builds
  packages/build/src/log/messages/core_steps.js
  packages/build/src/plugins_core/secrets_scanning/index.ts
  packages/build/tests/secrets_scanning/tests.js
Labels: Adds or modifies js files

#6379 feat: restrict requirements for enhanced secret scan matches
  packages/build/src/plugins_core/secrets_scanning/utils.ts
  packages/build/tests/utils_secretscanning/tests.js
Labels: Adds or modifies js files

#6414 feat: rename enhanced secret scan env vars
  packages/build/src/log/messages/core_steps.js
  packages/build/src/plugins_core/secrets_scanning/index.ts
  packages/build/src/plugins_core/secrets_scanning/utils.ts
  packages/build/tests/secrets_scanning/fixtures/src_scanning_likely_enhanced_scan_secrets_disabled/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_likely_enhanced_scan_secrets_omitted/netlify.toml
  packages/build/tests/secrets_scanning/tests.js
Labels: Adds or modifies js files

#6397 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/cache-utils/CHANGELOG.md
  packages/cache-utils/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/git-utils/CHANGELOG.md
  packages/git-utils/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/nock-udp/CHANGELOG.md
  packages/nock-udp/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
  packages/opentelemetry-sdk-setup/package.json
  packages/opentelemetry-utils/CHANGELOG.md
  packages/opentelemetry-utils/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
  packages/run-utils/CHANGELOG.md
  packages/run-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6418 feat: smart secret detection looks for high entropy level
  packages/build/src/plugins_core/secrets_scanning/utils.ts
  packages/build/tests/secrets_scanning/fixtures/src_scanning_likely_enhanced_scan_secrets/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_likely_enhanced_scan_secrets_disabled/netlify.toml
  packages/build/tests/secrets_scanning/fixtures/src_scanning_likely_enhanced_scan_secrets_omitted/netlify.toml
  packages/build/tests/utils_secretscanning/tests.js
Labels: Adds or modifies js files

#6419 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending
