Repository netlify/build, pull requests merged in 2025-01, with the labels that each got.

#5972 test: rebalance test suite
  .github/workflows/workflow.yml
  CONTRIBUTING.md
  ava.base.js
  package-lock.json
  package.json
  packages/build/ava.config.js
  packages/build/package.json
  packages/build/tests-metadata.json
  tools/package.json
  tools/tests-duration.js
Labels: Adds or modifies js files

#5992 test: resolve a few issues with tests causing inconsistent results
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
  packages/build/tests/install/tests.js
  packages/build/tests/plugins/tests.js
Labels: Adds or modifies js files

#6009 feat(js-client): add type definitions
  packages/js-client/src/index.ts
  packages/js-client/src/types.ts
Labels: automerge

#6012 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6008 fix(config): fail builds if failed to fetch extensions
  packages/config/src/api/site_info.ts
  packages/config/tests/api/snapshots/tests.js.md
  packages/config/tests/api/snapshots/tests.js.snap
  packages/config/tests/api/tests.js
Labels: Adds or modifies js files

#6016 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#6017 fix(js-client): Update method params type to be optional when all param keys are optional
  packages/js-client/src/types.ts
Labels: automerge

#6021 fix(js-client): add type definitions for operation method `opts` argument
  packages/js-client/src/types.ts
Labels: automerge

#6020 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#6023 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending, automerge

#6036 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6045 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending
