Repository netlify/build, pull requests merged in 2025-03, with the labels that each got.

#6117 feat: remove references to removed flag and always produce manfiest
  packages/build/tests/functions/tests.js
  packages/zip-it-and-ship-it/src/feature_flags.ts
  packages/zip-it-and-ship-it/src/runtimes/node/utils/zip.ts
  packages/zip-it-and-ship-it/src/zip.ts
  packages/zip-it-and-ship-it/tests/symlinked_included_files.test.ts
  packages/zip-it-and-ship-it/tests/telemetry.test.ts
  packages/zip-it-and-ship-it/tests/v2api.test.ts
Labels: Adds or modifies js files

#6107 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/headers-parser/CHANGELOG.md
  packages/headers-parser/package.json
  packages/nock-udp/CHANGELOG.md
  packages/nock-udp/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending, automerge

#6124 chore: fix various CI issues
  .github/workflows/workflow.yml
  package-lock.json
  packages/testing/package.json
  packages/testing/src/fixture.ts
Labels: Adds or modifies js files

#6097 fix(deps): remove 2 unused deps and 20 unused dev deps
  package-lock.json
  packages/build-info/package.json
  packages/build/package.json
  packages/edge-bundler/package.json
  packages/framework-info/package.json
  packages/opentelemetry-sdk-setup/package.json
  packages/opentelemetry-utils/package.json
  packages/redirect-parser/package.json
  packages/zip-it-and-ship-it/package.json
Labels: Adds or modifies js files

#6108 chore: remove `.only` from test
  .eslintrc.cjs
  package-lock.json
  package.json
  packages/build/tests/plugins/fixtures/core_override/netlify.toml
  packages/build/tests/plugins/snapshots/tests.js.md
  packages/build/tests/plugins/snapshots/tests.js.snap
  packages/build/tests/plugins/tests.js
  packages/build/tests/secrets_scanning/snapshots/tests.js.md
  packages/build/tests/secrets_scanning/snapshots/tests.js.snap
  packages/build/tests/secrets_scanning/tests.js
Labels: Adds or modifies js files

#6146 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/framework-info/CHANGELOG.md
  packages/framework-info/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/opentelemetry-sdk-setup/CHANGELOG.md
  packages/opentelemetry-sdk-setup/package.json
  packages/opentelemetry-utils/CHANGELOG.md
  packages/opentelemetry-utils/package.json
  packages/redirect-parser/CHANGELOG.md
  packages/redirect-parser/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending, automerge

#6150 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6154 fix: reduce the usage of getSiteInfo if we already have a cachedConfig
  packages/config/src/main.ts
  packages/config/tests/api/fixtures/cached_config/netlify.toml
  packages/config/tests/api/tests.js
Labels: Adds or modifies js files

#6160 fix: add the right vitest linter to the eslint config
  .eslintrc.cjs
Labels: Adds or modifies js files

#6155 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
Labels: autorelease: pending

#6141 test: add test for staging extension api
  packages/config/src/api/site_info.ts
  packages/config/src/integrations.ts
  packages/config/src/main.ts
  packages/config/src/types/options.ts
  packages/config/tests/api/tests.js
Labels: automerge, Adds or modifies js files

#6163 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
Labels: autorelease: pending

#6172 fix: remove problematic `omit.js` dependency
  package-lock.json
  packages/js-client/package.json
  packages/js-client/src/methods/response.js
  packages/js-client/src/omit.test.ts
  packages/js-client/src/omit.ts
  packages/js-client/src/operations.js
Labels: Adds or modifies js files

#6170 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending
