Repository netlify/build, pull requests merged in 2025-04, with the labels that each got.

#6168 fix: ensure extension api is always called with the right host
  packages/config/src/api/site_info.ts
  packages/config/src/integrations.ts
  packages/config/src/main.ts
  packages/config/tests/api/tests.js
Labels: Adds or modifies js files

#6180 fix: changing wording to extensions instead of integrations
  packages/build/src/log/messages/install.js
Labels: Adds or modifies js files

#6186 fix: add extra types for extensionMetaData
  packages/build/src/types/netlify_plugin_options.ts
Labels: automerge

#6144 fix: remove getAvailableIntegrations and start using the other call we already do
  packages/config/src/api/integrations.ts
  packages/config/src/integrations.ts
  packages/config/src/main.ts
  packages/config/tests/api/fixtures/integration/netlify.toml
  packages/config/tests/api/tests.js
Labels: Adds or modifies js files

#6185 fix: changing wording to extensions in more places
  packages/build/src/install/missing.js
  packages/build/src/log/messages/compatibility.ts
  packages/build/tests/install/snapshots/tests.js.md
  packages/build/tests/install/snapshots/tests.js.snap
Labels: Adds or modifies js files

#6167 feat!: support package.json.exports field for npm dependencies used within Netlify Edge Functions
  package-lock.json
  packages/build/tests/monitor/snapshots/tests.js.md
  packages/build/tests/monitor/snapshots/tests.js.snap
  packages/edge-bundler/node/bundler.test.ts
  packages/edge-bundler/node/npm_dependencies.ts
  packages/edge-bundler/node/server/server.test.ts
  packages/edge-bundler/node/server/server.ts
  packages/edge-bundler/package.json
  packages/edge-bundler/test/fixtures/imports_npm_module_exports/functions/func1.ts
  packages/edge-bundler/test/fixtures/imports_npm_module_exports/node_modules/@secret/magic/dist/hello.js
  packages/edge-bundler/test/fixtures/imports_npm_module_exports/node_modules/@secret/magic/package.json
  packages/edge-bundler/test/fixtures/imports_npm_module_exports/package.json
Labels: Adds or modifies js files

#6181 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
Labels: autorelease: pending

#6197 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/edge-bundler/CHANGELOG.md
  packages/edge-bundler/package.json
Labels: autorelease: pending

#6198 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6209 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/functions-utils/CHANGELOG.md
  packages/functions-utils/package.json
  packages/zip-it-and-ship-it/CHANGELOG.md
  packages/zip-it-and-ship-it/package.json
Labels: autorelease: pending

#6205 feat: send deploy validations report on secret scan
  packages/build/src/plugins_core/secrets_scanning/index.ts
  packages/build/src/plugins_core/secrets_scanning/utils.ts
  packages/build/src/plugins_core/types.ts
  packages/build/src/status/validations.ts
  packages/build/src/steps/core_step.ts
  packages/build/src/steps/run_step.ts
  packages/build/tests/secrets_scanning/tests.js
Labels: Adds or modifies js files

#6210 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build/CHANGELOG.md
  packages/build/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/js-client/CHANGELOG.md
  packages/js-client/package.json
Labels: autorelease: pending

#6213 chore: release main
  .release-please-manifest.json
  package-lock.json
  packages/build-info/CHANGELOG.md
  packages/build-info/package.json
Labels: autorelease: pending
